### ISSUE TITLE
Locale based formatting

### ISSUE THREAD

**Issue by mine-cetinkaya-rundel** [rstudio/gt#1]
A few locale based customizations that I can think of are:

- currency symbol at the beginning/end of value
- comma/period for decimals
- % sign at the beginning/end of value
- minus sign/parentheses for negative values

I have not looked for an comprehensive resource on this, but I bet there is one.

**Comment by rich-iannone** [comment]
The locale piece is now pretty solid. We have the `locale` argument that is present in most of the `fmt_*()` functions, allowing for hundreds of locale codes to be used. This allows for automatic use of decimal separator characters, grouping separators, etc.

The percent- and currency-based formatters also have a `locale` argument and ways to override placement of the affixed symbol. 

Finally, all number-based formatters have a `negative_val` argument that accepts either `"signed"` or `"parens"` (giving us the option for a minus sign or parentheses).
