### ISSUE TITLE
Modify `cols_align()` to target column labels and possibly selections of cells

### ISSUE THREAD

**Issue by rich-iannone** [rstudio/gt#100]
Currently, `cols_align()` works on entire columns and there is no way to align the column labels differently than the data cells associated with the targeted columns. It would also be good to align certain cells differently.

All of this might involve incorporating either the `rows` or `locations` argument in order to target cells.

**Comment by rich-iannone** [comment]
It’s sometimes more aesthetically pleasing to have centered headers with (1) columns that contain free-form text (usually these are wider columns), (2) in tables with many columns of mixed alignments, or (3) for column headers under a spanning column header (to center those column labels).

**Comment by jcheng5** [comment]
Great, thanks for the clarification.

**Comment by rich-iannone** [comment]
You’re welcome! I’ve seen some wonderful tables in books that do great stuff with different alignments. Unfortunately these examples are hard to find on the internet, but having to freedom for a few more styling choices like this I feel will go a long way.

**Comment by rich-iannone** [comment]
We can modify the column labels’ alignment easily now with `tab_style()` so this update isn’t really needed now.
