### ISSUE TITLE
Functionality to remove source note

### ISSUE THREAD

**Issue by LukasWallrich** [rstudio/gt#1005]
I am using a package (`modelsummary`) that returns a gt table - but sometimes includes source notes that I don't need. I am trying to remove them in post-processing, but so far it appears that I can only do that by calling `gt:::dt_source_notes_set("")`. That is good enough for interactive use, but I am in the process of moving that function into a package - where I obviously don't want to rely on unexported functions.

Is there already a way to remove/reset source notes that I am overlooking? Otherwise, could that be provided? Maybe an 'overwrite'/`replace` option in `tab_source_note()`? While my use case is admittedly rather specific, it does not seem unlikely that people might want to update source notes in an existing table ...

**Comment by rich-iannone** [comment]
Thanks for filing this issue. This sort of thing is coming up quite a bit as gt objects are being created in other packages and there is the possibility for further customization. I do believe there should be a set of easy-to-use functions that simply reset/remove table parts. I'll get to working on this soon, thanks again for the suggestion!
