### ISSUE TITLE
Missing headers when grouping

### ISSUE THREAD

**Issue by ReneKat** [rstudio/gt#1008]
Hello gt developers & users,

I'm using gt for the first time today and have been really successful following your tutorials. Thank you!

I'm having a tiny snag with my column labels when grouping. How can I get the Sub-basin and Site labels to show up when I call cols_label()?

Here's the code I put together:

```
library(gt)
library(dplyr)
library(tidyverse)


Table1_Sampling_Stations_rev2 %>%
  dplyr::filter(site_description %in% c("Saint Lucie Estuary", "South IRL", "South-Central IRL", "North-Central IRL", "North IRL", "Banana River Lagoon", "Mosquito Lagoon")) %>%
  dplyr::group_by(site_description, site, sample.number) %>%
  gt(rowname_col = "site", groupname_col = "site_description") %>%
  tab_header(title = md("**FCH Sampling Sites**"), subtitle = "August 2018 - May 2020") %>%
  cols_label(site_description = html("Sub-basin"),
             site = html("Site"),
             latitude = html("Latitude"),
             longitude = html("Longitude"),
             IRLON.id = html("IRLON"),
             sample.number = html("Number of<br>Samples")
  ) %>%
  tab_options(row_group.as_column = TRUE)
```

I want all the labels to show as specified by the col_label()   I think it has something to do with the group_by() function. Any ideas, suggestions, or another tutorial to follow? 

Thanks so much for your help,
René

![Table_1](https://user-images.githubusercontent.com/37948733/185017588-4a986d93-8918-4162-aa2d-a81460b6358a.png)

**Comment by rich-iannone** [comment]
Sorry for the delay in responding. Here, you’d need `tab_stubhead()` since now you have a stub (by default the column label is not shown). And, you only get one label so you’d have to combine them in a single phrase.
