### ISSUE TITLE
`fmt_integer()` doesn't work following `fmt_number()`

### ISSUE THREAD

**Issue by francisbarton** [rstudio/gt#1019]
## Prework

* [x] Read and agree to the [code of conduct](https://www.contributor-covenant.org/version/2/0/code_of_conduct/) and [contributing guidelines](https://github.com/rstudio/gt/blob/master/.github/CONTRIBUTING.md).
* [x] If there is [already a relevant issue](https://github.com/rstudio/gt/issues), whether open or closed, comment on the existing thread instead of posting a new issue.
* [x] Post a [minimal reproducible example](https://www.tidyverse.org/help/) so the maintainer can troubleshoot the problems you identify. A reproducible example is:
    * [x] **Runnable**: post enough R code and data so any onlooker can create the error on their own computer.
    * [x] **Minimal**: reduce runtime wherever possible and remove complicated details that are irrelevant to the issue at hand.
    * [x] **Readable**: format your code according to the [tidyverse style guide](https://style.tidyverse.org/).

## Description

If I format all numeric columns to 1dp, then try to format a single one of these columns to an integer, the integer formatting does not override the previous formatting.
(This also applies if I try to re-apply `fmt_number` with `decimals = 0`.)

Example use case: I want all numeric columns formatted to 1dp, except the final column which I need formatted as an integer. But I don't know how many columns my table will have, so I want to do a blanket fmt_number first.

## Reproducible example

``` r
library(dplyr, warn.conflicts = FALSE)
library(gt)

tibble(a = sample(1:1e5, 3) / 1e4, b = sample(1:1e5, 3) / 1e4) |>
  gt() |>
  gt::fmt_number(where(is.numeric), decimals = 1) |>
  gt::fmt_integer(columns = 2)
```

<table class="gt_table">
  
  <thead class="gt_col_headings">
    <tr>
      <th class="gt_col_heading gt_columns_bottom_border gt_right" rowspan="1" colspan="1">a</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_right" rowspan="1" colspan="1">b</th>
    </tr>
  </thead>
  <tbody class="gt_table_body">
    <tr><td class="gt_row gt_right">1.2</td>
<td class="gt_row gt_right">1.3</td></tr>
    <tr><td class="gt_row gt_right">9.2</td>
<td class="gt_row gt_right">5.0</td></tr>
    <tr><td class="gt_row gt_right">2.1</td>
<td class="gt_row gt_right">9.8</td></tr>
  </tbody>
  
  
</table>

<sup>Created on 2022-08-22 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

``` r
library(dplyr, warn.conflicts = FALSE)
library(gt)

tibble(a = sample(1:1e5, 3) / 1e3, b = sample(1:1e5, 3) / 1e3) |>
  gt() |>
  gt::fmt_number(columns = where(is.numeric), decimals = 1) |>
  gt::fmt_number(columns = last_col(), decimals = 0)
```
<table class="gt_table">
  
  <thead class="gt_col_headings">
    <tr>
      <th class="gt_col_heading gt_columns_bottom_border gt_right" rowspan="1" colspan="1">a</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_right" rowspan="1" colspan="1">b</th>
    </tr>
  </thead>
  <tbody class="gt_table_body">
    <tr><td class="gt_row gt_right">53.7</td>
<td class="gt_row gt_right">11.7</td></tr>
    <tr><td class="gt_row gt_right">52.2</td>
<td class="gt_row gt_right">45.2</td></tr>
    <tr><td class="gt_row gt_right">47.3</td>
<td class="gt_row gt_right">30.8</td></tr>
  </tbody>
  
</table>

<sup>Created on 2022-08-22 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

## Expected results

I would expect `fmt_integer` to override `fmt_number` and turn column 2 into a column of integers, using appropriate rounding.

<table class="gt_table">
  
  <thead class="gt_col_headings">
    <tr>
      <th class="gt_col_heading gt_columns_bottom_border gt_right" rowspan="1" colspan="1">a</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_right" rowspan="1" colspan="1">b</th>
    </tr>
  </thead>
  <tbody class="gt_table_body">
    <tr><td class="gt_row gt_right">1.2</td>
<td class="gt_row gt_right">1</td></tr>
    <tr><td class="gt_row gt_right">9.2</td>
<td class="gt_row gt_right">5</td></tr>
    <tr><td class="gt_row gt_right">2.1</td>
<td class="gt_row gt_right">10</td></tr>
  </tbody>
  
  
</table>

I would expect `fmt_number` to override the previous `fmt_number` for the specified column, and turn column 2 into a column of integers, using appropriate rounding.

<table class="gt_table">
  
  <thead class="gt_col_headings">
    <tr>
      <th class="gt_col_heading gt_columns_bottom_border gt_right" rowspan="1" colspan="1">a</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_right" rowspan="1" colspan="1">b</th>
    </tr>
  </thead>
  <tbody class="gt_table_body">
    <tr><td class="gt_row gt_right">53.7</td>
<td class="gt_row gt_right">12</td></tr>
    <tr><td class="gt_row gt_right">52.2</td>
<td class="gt_row gt_right">45</td></tr>
    <tr><td class="gt_row gt_right">47.3</td>
<td class="gt_row gt_right">31</td></tr>
  </tbody>
  
  
</table>

## Session info

<details style="margin-bottom:10px;">
<summary>
Session info
</summary>

``` r
sessionInfo()
#> R version 4.2.1 (2022-06-23 ucrt)
#> Platform: x86_64-w64-mingw32/x64 (64-bit)
#> Running under: Windows 10 x64 (build 19044)
#> 
#> Matrix products: default
#> 
#> locale:
#> [1] LC_COLLATE=English_United Kingdom.utf8 
#> [2] LC_CTYPE=English_United Kingdom.utf8   
#> [3] LC_MONETARY=English_United Kingdom.utf8
#> [4] LC_NUMERIC=C                           
#> [5] LC_TIME=English_United Kingdom.utf8    
#> 
#> attached base packages:
#> [1] stats     graphics  grDevices utils     datasets  methods   base     
#> 
#> other attached packages:
#> [1] gt_0.6.0    dplyr_1.0.9
#> 
#> loaded via a namespace (and not attached):
#>  [1] pillar_1.8.1     compiler_4.2.1   highr_0.9        tools_4.2.1     
#>  [5] digest_0.6.29    checkmate_2.1.0  evaluate_0.16    lifecycle_1.0.1 
#>  [9] tibble_3.1.8     gtable_0.3.0     pkgconfig_2.0.3  rlang_1.0.4     
#> [13] reprex_2.0.2     cli_3.3.0        DBI_1.1.3        rstudioapi_0.13 
#> [17] yaml_2.3.5       xfun_0.32        fastmap_1.1.0    withr_2.5.0     
#> [21] stringr_1.4.1    knitr_1.39       sass_0.4.2.9000  generics_0.1.3  
#> [25] fs_1.5.2         vctrs_0.4.1      grid_4.2.1       tidyselect_1.1.2
#> [29] glue_1.6.2       R6_2.5.1         fansi_1.0.3      rmarkdown_2.15  
#> [33] purrr_0.3.4      ggplot2_3.3.6    magrittr_2.0.3   ellipsis_0.3.2  
#> [37] backports_1.4.1  scales_1.2.1     htmltools_0.5.3  assertthat_0.2.1
#> [41] colorspace_2.0-3 utf8_1.2.2       stringi_1.7.8    munsell_0.5.0   
#> [45] crayon_1.5.1
```

</details>

**Comment by rich-iannone** [comment]
Thanks for reporting this! This is a definite bug and doesn't follow the expectation that later formatters should win out.
