### ISSUE TITLE
Implement `starts_with` column selectors in tab_spanner

### ISSUE THREAD

**Issue by MikeKSmith** [rstudio/gt#102]
It would be good to allow the ability to use the `starts_with` column selectors in the tab_spanner `columns` definition:
   
``` r
library(tidyverse)
library(gt)
myTableData <- tribble(~Variable, ~Value, ~Female_n, ~Female_prop, ~Male_n, ~Male_prop,
"Compliance", "No",            2,      0.0270,      0,     0,    
"Compliance", "Yes",          13,      0.176,      59,     0.797)

# Explicit definition of table spanning columns
myTableData %>%
group_by(Variable) %>%
  gt() %>%
  tab_header(title = "Summary of categorical covariates") %>%
  tab_spanner(label="Female",
              columns=vars("Female_n", "Female_prop")) %>%
  tab_spanner(label="Male",
              columns=vars("Male_n", "Male_prop")) %>%
  cols_label(Female_n = "n",
             Male_n = "n",
             Female_prop = "Percentage",
             Male_prop = "Percentage")
```

<style>html {
  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Fira Sans', 'Droid Sans', 'Helvetica Neue', Arial, sans-serif;
}

#ngwpwvkoag .gt_table {
  display: table;
  border-collapse: collapse;
  margin-left: auto;
  margin-right: auto;
  color: #000000;
  font-size: 16px;
  background-color: #FFFFFF;
  /* table.background.color */
  width: auto;
  /* table.width */
  border-top-style: solid;
  /* table.border.top.style */
  border-top-width: 2px;
  /* table.border.top.width */
  border-top-color: #A8A8A8;
  /* table.border.top.color */
}

#ngwpwvkoag .gt_heading {
  background-color: #FFFFFF;
  /* heading.background.color */
  border-bottom-color: #FFFFFF;
}

#ngwpwvkoag .gt_title {
  color: #000000;
  font-size: 125%;
  /* heading.title.font.size */
  padding-top: 4px;
  /* heading.top.padding */
  padding-bottom: 1px;
  border-bottom-color: #FFFFFF;
  border-bottom-width: 0;
}

#ngwpwvkoag .gt_subtitle {
  color: #000000;
  font-size: 85%;
  /* heading.subtitle.font.size */
  padding-top: 1px;
  padding-bottom: 4px;
  /* heading.bottom.padding */
  border-top-color: #FFFFFF;
  border-top-width: 0;
}

#ngwpwvkoag .gt_bottom_border {
  border-bottom-style: solid;
  /* heading.border.bottom.style */
  border-bottom-width: 2px;
  /* heading.border.bottom.width */
  border-bottom-color: #A8A8A8;
  /* heading.border.bottom.color */
}

#ngwpwvkoag .gt_column_spanner {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #A8A8A8;
  padding-top: 4px;
  padding-bottom: 4px;
}

#ngwpwvkoag .gt_col_heading {
  color: #000000;
  background-color: #FFFFFF;
  /* column_labels.background.color */
  font-size: 16px;
  /* column_labels.font.size */
  font-weight: initial;
  /* column_labels.font.weight */
  vertical-align: middle;
  padding: 10px;
  margin: 10px;
}

#ngwpwvkoag .gt_sep_right {
  border-right: 5px solid #FFFFFF;
}

#ngwpwvkoag .gt_group_heading {
  padding: 8px;
  color: #000000;
  background-color: #FFFFFF;
  /* stub_group.background.color */
  font-size: 16px;
  /* stub_group.font.size */
  font-weight: initial;
  /* stub_group.font.weight */
  border-top-style: solid;
  /* stub_group.border.top.style */
  border-top-width: 2px;
  /* stub_group.border.top.width */
  border-top-color: #A8A8A8;
  /* stub_group.border.top.color */
  border-bottom-style: solid;
  /* stub_group.border.bottom.style */
  border-bottom-width: 2px;
  /* stub_group.border.bottom.width */
  border-bottom-color: #A8A8A8;
  /* stub_group.border.bottom.color */
  vertical-align: middle;
}

#ngwpwvkoag .gt_empty_group_heading {
  padding: 0.5px;
  color: #000000;
  background-color: #FFFFFF;
  /* stub_group.background.color */
  font-size: 16px;
  /* stub_group.font.size */
  font-weight: initial;
  /* stub_group.font.weight */
  border-top-style: solid;
  /* stub_group.border.top.style */
  border-top-width: 2px;
  /* stub_group.border.top.width */
  border-top-color: #A8A8A8;
  /* stub_group.border.top.color */
  border-bottom-style: solid;
  /* stub_group.border.bottom.style */
  border-bottom-width: 2px;
  /* stub_group.border.bottom.width */
  border-bottom-color: #A8A8A8;
  /* stub_group.border.bottom.color */
  vertical-align: middle;
}

#ngwpwvkoag .gt_striped tr:nth-child(even) {
  background-color: #f2f2f2;
}

#ngwpwvkoag .gt_row {
  padding: 10px;
  /* row.padding */
  margin: 10px;
  vertical-align: middle;
}

#ngwpwvkoag .gt_stub {
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #A8A8A8;
  padding-left: 12px;
}

#ngwpwvkoag .gt_stub.gt_row {
  background-color: #FFFFFF;
}

#ngwpwvkoag .gt_summary_row {
  background-color: #FFFFFF;
  /* summary_row.background.color */
  padding: 6px;
  /* summary_row.padding */
  text-transform: inherit;
  /* summary_row.text_transform */
}

#ngwpwvkoag .gt_first_summary_row {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #A8A8A8;
}

#ngwpwvkoag .gt_table_body {
  border-top-style: solid;
  /* field.border.top.style */
  border-top-width: 2px;
  /* field.border.top.width */
  border-top-color: #A8A8A8;
  /* field.border.top.color */
  border-bottom-style: solid;
  /* field.border.bottom.style */
  border-bottom-width: 2px;
  /* field.border.bottom.width */
  border-bottom-color: #A8A8A8;
  /* field.border.bottom.color */
}

#ngwpwvkoag .gt_footnote {
  font-size: 90%;
  /* footnote.font.size */
  padding: 4px;
  /* footnote.padding */
}

#ngwpwvkoag .gt_sourcenote {
  font-size: 90%;
  /* sourcenote.font.size */
  padding: 4px;
  /* sourcenote.padding */
}

#ngwpwvkoag .gt_center {
  text-align: center;
}

#ngwpwvkoag .gt_left {
  text-align: left;
}

#ngwpwvkoag .gt_right {
  text-align: right;
  font-variant-numeric: tabular-nums;
}

#ngwpwvkoag .gt_font_normal {
  font-weight: normal;
}

#ngwpwvkoag .gt_font_bold {
  font-weight: bold;
}

#ngwpwvkoag .gt_font_italic {
  font-style: italic;
}

#ngwpwvkoag .gt_super {
  font-size: 65%;
}

#ngwpwvkoag .gt_footnote_glyph {
  font-style: italic;
  font-size: 65%;
}
</style>

<table class="gt_table">

<thead>

<tr>

<th class="gt_heading gt_title gt_font_normal gt_center" colspan="5">

Summary of categorical covariates

</th>

</tr>

<tr>

<th class="gt_heading gt_subtitle gt_font_normal gt_center gt_bottom_border" colspan="5">

</th>

</tr>

</thead>

<tr>

<th class="gt_col_heading gt_center" rowspan="2" colspan="1">

Value

</th>

<th class="gt_col_heading gt_column_spanner gt_sep_right gt_center" rowspan="1" colspan="2">

Female

</th>

<th class="gt_col_heading gt_column_spanner gt_center" rowspan="1" colspan="2">

Male

</th>

</tr>

<tr>

<th class="gt_col_heading gt_right" rowspan="1" colspan="1">

n

</th>

<th class="gt_col_heading gt_right" rowspan="1" colspan="1">

Percentage

</th>

<th class="gt_col_heading gt_right" rowspan="1" colspan="1">

n

</th>

<th class="gt_col_heading gt_NA" rowspan="1" colspan="1">

Percentage

</th>

</tr>

<tbody class="gt_table_body gt_striped">

<tr class="gt_group_heading_row">

<td colspan="5" class="gt_group_heading">

Compliance

</td>

</tr>

<tr>

<td class="gt_row gt_left">

No

</td>

<td class="gt_row gt_right">

2

</td>

<td class="gt_row gt_right">

0.027

</td>

<td class="gt_row gt_right">

0

</td>

<td class="gt_row gt_right">

0.000

</td>

</tr>

<tr>

<td class="gt_row gt_left">

Yes

</td>

<td class="gt_row gt_right">

13

</td>

<td class="gt_row gt_right">

0.176

</td>

<td class="gt_row gt_right">

59

</td>

<td class="gt_row gt_right">

0.797

</td>

</tr>

</tbody>

</table>

``` r

# Not Working
myTableData %>%
  group_by(Variable) %>%
  gt() %>%
  tab_header(title = "Summary of categorical covariates") %>%
  tab_spanner(label="Female",
              columns=starts_with("Female_")) %>%
  tab_spanner(label="Male",
              columns=starts_with("Male_"))
#> Error: No tidyselect variables were registered
```

<sup>Created on 2018-12-11 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>
<details><summary>Session info</summary>

``` r
devtools::session_info()
#> Session info -------------------------------------------------------------
#>  setting  value                                      
#>  version  R version 3.5.1 Patched (2018-11-18 r75627)
#>  system   x86_64, mingw32                            
#>  ui       RTerm                                      
#>  language (EN)                                       
#>  collate  English_United Kingdom.1252                
#>  tz       Europe/London                              
#>  date     2018-12-11
#> Packages -----------------------------------------------------------------
#>  package    * version    date       source                       
#>  assertthat   0.2.0      2017-04-11 CRAN (R 3.5.1)               
#>  backports    1.1.2      2017-12-13 CRAN (R 3.5.0)               
#>  base       * 3.5.1      2018-11-19 local                        
#>  bindr        0.1.1      2018-03-13 CRAN (R 3.5.1)               
#>  bindrcpp   * 0.2.2      2018-03-29 CRAN (R 3.5.1)               
#>  broom        0.5.0      2018-07-17 CRAN (R 3.5.1)               
#>  cellranger   1.1.0      2016-07-27 CRAN (R 3.5.1)               
#>  checkmate    1.8.5      2017-10-24 CRAN (R 3.5.1)               
#>  cli          1.0.1      2018-09-25 CRAN (R 3.5.1)               
#>  colorspace   1.3-2      2016-12-14 CRAN (R 3.5.1)               
#>  commonmark   1.7        2018-12-01 CRAN (R 3.5.1)               
#>  compiler     3.5.1      2018-11-19 local                        
#>  crayon       1.3.4      2017-09-16 CRAN (R 3.5.1)               
#>  datasets   * 3.5.1      2018-11-19 local                        
#>  devtools     1.13.6     2018-06-27 CRAN (R 3.5.1)               
#>  digest       0.6.18     2018-10-10 CRAN (R 3.5.1)               
#>  dplyr      * 0.7.8      2018-11-10 CRAN (R 3.5.1)               
#>  evaluate     0.11       2018-07-17 CRAN (R 3.5.1)               
#>  forcats    * 0.3.0      2018-02-19 CRAN (R 3.5.1)               
#>  ggplot2    * 3.1.0      2018-10-25 CRAN (R 3.5.1)               
#>  glue         1.3.0      2018-07-17 CRAN (R 3.5.1)               
#>  graphics   * 3.5.1      2018-11-19 local                        
#>  grDevices  * 3.5.1      2018-11-19 local                        
#>  grid         3.5.1      2018-11-19 local                        
#>  gt         * 0.1.0      2018-12-10 Github (rstudio/gt@fe4870f)  
#>  gtable       0.2.0      2016-02-26 CRAN (R 3.5.1)               
#>  haven        1.1.2      2018-06-27 CRAN (R 3.5.1)               
#>  hms          0.4.2      2018-03-10 CRAN (R 3.5.1)               
#>  htmltools    0.3.6      2017-04-28 CRAN (R 3.5.1)               
#>  httr         1.3.1      2017-08-20 CRAN (R 3.5.1)               
#>  jsonlite     1.5        2017-06-01 CRAN (R 3.5.1)               
#>  knitr        1.20       2018-02-20 CRAN (R 3.5.1)               
#>  lattice      0.20-38    2018-11-04 CRAN (R 3.5.1)               
#>  lazyeval     0.2.1      2017-10-29 CRAN (R 3.5.1)               
#>  lubridate    1.7.4      2018-04-11 CRAN (R 3.5.1)               
#>  magrittr     1.5        2014-11-22 CRAN (R 3.5.1)               
#>  memoise      1.1.0      2017-04-21 CRAN (R 3.5.1)               
#>  methods    * 3.5.1      2018-11-19 local                        
#>  modelr       0.1.2      2018-05-11 CRAN (R 3.5.1)               
#>  munsell      0.5.0      2018-06-12 CRAN (R 3.5.1)               
#>  nlme         3.1-137    2018-04-07 CRAN (R 3.5.1)               
#>  pillar       1.3.0      2018-07-14 CRAN (R 3.5.1)               
#>  pkgconfig    2.0.2      2018-08-16 CRAN (R 3.5.1)               
#>  plyr         1.8.4      2016-06-08 CRAN (R 3.5.1)               
#>  purrr      * 0.2.5      2018-05-29 CRAN (R 3.5.1)               
#>  R6           2.2.2      2017-06-17 CRAN (R 3.5.1)               
#>  Rcpp         0.12.19    2018-10-01 CRAN (R 3.5.1)               
#>  readr      * 1.1.1      2017-05-16 CRAN (R 3.5.1)               
#>  readxl       1.1.0      2018-04-20 CRAN (R 3.5.1)               
#>  rlang        0.3.0.1    2018-10-25 CRAN (R 3.5.1)               
#>  rmarkdown    1.10       2018-06-11 CRAN (R 3.5.1)               
#>  rprojroot    1.3-2      2018-01-03 CRAN (R 3.5.1)               
#>  rvest        0.3.2      2016-06-17 CRAN (R 3.5.1)               
#>  sass         0.1.0.9000 2018-12-10 Github (rstudio/sass@c73867d)
#>  scales       1.0.0      2018-08-09 CRAN (R 3.5.1)               
#>  stats      * 3.5.1      2018-11-19 local                        
#>  stringi      1.1.7      2018-03-12 CRAN (R 3.5.0)               
#>  stringr    * 1.3.1      2018-05-10 CRAN (R 3.5.1)               
#>  tibble     * 1.4.2      2018-01-22 CRAN (R 3.5.1)               
#>  tidyr      * 0.8.2      2018-10-28 CRAN (R 3.5.1)               
#>  tidyselect   0.2.5      2018-10-11 CRAN (R 3.5.1)               
#>  tidyverse  * 1.2.1      2017-11-14 CRAN (R 3.5.1)               
#>  tools        3.5.1      2018-11-19 local                        
#>  utils      * 3.5.1      2018-11-19 local                        
#>  withr        2.1.2      2018-03-15 CRAN (R 3.5.1)               
#>  xml2         1.2.0      2018-01-24 CRAN (R 3.5.1)               
#>  yaml         2.2.0      2018-07-25 CRAN (R 3.5.1)
```

</details>

**Comment by rich-iannone** [comment]
This would be a nice improvement, thanks for providing the examples!

**Comment by MikeKSmith** [comment]
No problem. Would it be possible to do something similar with cols_label? i.e. cols_label(ends_with("_n") = "n", ends_with("_prop") = "prop") as in the example above?

**Comment by rich-iannone** [comment]
Both use cases make a lot of sense and they will both be implemented.

**Comment by rich-iannone** [comment]
@MikeKSmith I've moved your second point to a separate issue: #161 .
