### ISSUE TITLE
preserve leading white spaces in word output

### ISSUE THREAD

**Issue by thebioengineer** [rstudio/gt#1020]
## Prework

* [ ] Read and agree to the [code of conduct](https://www.contributor-covenant.org/version/2/0/code_of_conduct/) and [contributing guidelines](https://github.com/rstudio/gt/blob/master/.github/CONTRIBUTING.md).
* [ ] If there is [already a relevant issue](https://github.com/rstudio/gt/issues), whether open or closed, comment on the existing thread instead of posting a new issue.
* [ ] Post a [minimal reproducible example](https://www.tidyverse.org/help/) so the maintainer can troubleshoot the problems you identify. A reproducible example is:
    * [ ] **Runnable**: post enough R code and data so any onlooker can create the error on their own computer.
    * [ ] **Minimal**: reduce runtime wherever possible and remove complicated details that are irrelevant to the issue at hand.
    * [ ] **Readable**: format your code according to the [tidyverse style guide](https://style.tidyverse.org/).

## Description

Describe the bug clearly and concisely. 

not sure about the table body, but in stub header currently the spaces get removed by the xml

## Reproducible example

* [ ] Post a [minimal reproducible example](https://www.tidyverse.org/help/) so the maintainer can troubleshoot the problems you identify. A reproducible example is:
    * [ ] **Runnable**: post enough R code and data so any onlooker can create the error on their own computer.
    * [ ] **Minimal**: reduce runtime wherever possible and remove complicated details that are irrelevant to the issue at hand.
    * [ ] **Readable**: format your code according to the [tidyverse style guide](https://style.tidyverse.org/).

## Expected result

What should have happened? Please be as specific as possible.

## Session info

End the reproducible example with a call to `sessionInfo()` in the same session (e.g. `reprex(session_info = TRUE)`) and include the output.

**Comment by thebioengineer** [comment]
This was resolved in #1131 - however, we currently don't address the new indent feature that was added. Should we look into that @rich-iannone ?

**Comment by thebioengineer** [comment]
Running the code example from tab_stub_indent, this is not incorporated as of yet.

**Comment by rich-iannone** [comment]
I think indenting through `tab_stub_indent()` would be good to get in for this release!

**Comment by rich-iannone** [comment]
The original issue is solved now and let's open up a new issue for `tab_stub_indent()` and close this one down.
