### ISSUE TITLE
finding package for tabu.sty  compilation failed- package installation error LaTeX Error: File `tabu.sty' not found.

### ISSUE THREAD

**Issue by OlexiyPukhov** [rstudio/gt#1024]
When I try to create gt files in pdf, I get  the following error. This only happens after I name the columns a long text, so it has to span multi lines. It then tries to install tabu, but it cannot. I've searched online that tabu is old and I'm pretty sure its not maintained anymore and superseded by something else. This is the code I try to run with it.

registered_by_year_tbl %>% gt(rowname_col = "initial_pharmacist_registration") %>% 
    tab_stubhead(label = "Year") %>% 
    cols_label(
        education_country = ("Location"),
        number_registered_scraped = ("Number Registered - Scraped"),
        number_registered_OCP_AR = ("Number Registered - OCP AR"),
        currently_practicing_scraped = ("Currently Practicing Part A or Part B Registered That Year"),
        ratio_practicing_registered = ("Ratio Currently Practicing / Number Registered OCP AR, round 2")
    ) %>% 
    cols_width(
        education_country ~px(60),
        number_registered_scraped ~px(60),
        number_registered_OCP_AR ~px(60),
        ratio_practicing_registered ~ px(100),
        currently_practicing_scraped ~px(100)
        )

I've tried adjusting the px number and it still doesn't work. This is my YAML
format: pdf
editor: visual
fig-dpi: 400
fig-height: 9
fig-width: 8.5
fontsize: "4"
fig-align: center
theme: litera
execute: 
  warning: false

**Comment by rich-iannone** [comment]
This seems unavoidable for LaTeX so perhaps the only workaround is to use shorter column names.
