### ISSUE TITLE
Feature request: `day_m` option for `date_style` in `fmt_date()`

### ISSUE THREAD

**Issue by mine-cetinkaya-rundel** [rstudio/gt#1028]
## Prework

- [x] Read and abide by **gt**'s [code of conduct](https://www.contributor-covenant.org/version/2/0/code_of_conduct/) and [contributing guidelines](https://github.com/rstudio/gt/blob/master/.github/CONTRIBUTING.md).
- [x] Search for duplicates among the [existing issues](https://github.com/rstudio/gt/issues) (both open and closed).

## Proposal

I'd love a 15th option for `date_style` in `fmt_date()`: `day_m`.

`"day_m"`: `29 Feb`

This will help keep the width of a date column narrower, which I could use in places like [this](https://sta199-f22-1.github.io/).

**Comment by rich-iannone** [comment]
Like the idea and this will be implemented soon!
