### ISSUE TITLE
The html abundant code displays when run gt in the github_document

### ISSUE THREAD

**Issue by JiaxiangBU** [rstudio/gt#104]
[Here](https://github.com/JiaxiangBU/learn_gt/blob/master/gt_rstudio.md) is the display on the md document, like this,

![image](https://user-images.githubusercontent.com/15884785/49950405-b4b4de00-ff32-11e8-88c9-3efaed40967d.png)

And the Rmd document is [here](https://github.com/JiaxiangBU/learn_gt/blob/master/gt_rstudio.Rmd) for reproducing.

**Comment by IyarLin** [comment]
Getting same results. Md file [here](https://github.com/IyarLin/utilityFunctions/blob/master/try.md)
Would really love the option to have this work in github_document!

Thanks for all the great work

**Comment by gongcastro** [comment]
This issue has some time, but in case it's helpful: `gt::as_raw_html()` seems to do the trick it in my local RStudio session. The HTML and CSS code no longer appears on top of the tables when the gihub_document Rmd file is rendered on GitHub.
```r
library(gt)
as_raw_html(gt(mtcars)) 
````
R version 4.0.4 (2021-02-15)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19041)

**Comment by IyarLin** [comment]
@gongcastro 
Thanks! That does seem to do the trick

**Comment by rich-iannone** [comment]
Alright, this looks more or less answered so I'll close this now!
