### ISSUE TITLE
Feature Request: Allow modifying the caption after creating a gt()

### ISSUE THREAD

**Issue by billdenney** [rstudio/gt#1048]
## Prework

- [x] Read and abide by **gt**'s [code of conduct](https://www.contributor-covenant.org/version/2/0/code_of_conduct/) and [contributing guidelines](https://github.com/rstudio/gt/blob/master/.github/CONTRIBUTING.md).
- [x] Search for duplicates among the [existing issues](https://github.com/rstudio/gt/issues) (both open and closed).

## Proposal

`tab_caption(data, caption)` to allow modifying a caption on an already-created gt() object.

```r
data %>%
  gt(caption="old caption") %>%
  tab_caption("my caption here")
```

As an addition, it would be helpful to also be able to extract the caption information.  This may be too flexible, but I would find it helpful to use `tab_caption(my_gt)` to get the current caption.

**Comment by billdenney** [comment]
Related to #328

**Comment by rich-iannone** [comment]
Sounds like a good feature. Thanks for creating this issue!
