### ISSUE TITLE
Does gtsave() now require a Chrome installation?

### ISSUE THREAD

**Issue by rdelrossi** [rstudio/gt#1049]
I’m working with the development version of `gt()` and noticed that `gtsave()` now uses functionality in `webshot2`. 

Does this mean I now have to have Google Chrome installed in order to use `gtsave()`? Have tried to avoid installing Chrome to this point!

**Comment by henrique1008** [comment]
I had problems with this too
Seems webshot2 needs chrome or chromium to work 
At first i received message to needs install chrome in vm ubuntu on azure
But after that, I received other bug, in my local ubuntu it's work nice, but not in cloud ubuntu

bellow the link to my issue
https://github.com/rstudio/gt/issues/1029

bests

**Comment by rdelrossi** [comment]
Appreciate your comment, @henrique1008. 

I've avoided Chrome on my Mac religiously, though I've conceded to Chromium through Vivaldi, which I actually find a very useful tool. 

Still, despite the Vivaldi install, I'm getting errors from gt 0.7.0 about not being able to run the Chrome.app. Perhaps there's a way to configure webshot2 to use what it needs from the Vivaldi installation.

I'm pretty invested in gt(), so will need to figure out something for going forward.

**Comment by henrique1008** [comment]
I'm pretty invested in gt() too, and very interested in this solution
As you can observe in my issue, after install chrome I'm getting erros from gt 0.7 too, this is a bug I think
In my server, I can use webshot2 normally, but not work in gt 0.7

**Comment by rdelrossi** [comment]
Got this to work @henrique1008 without installing Chrome by setting the CHROMOTE_CHROME environment variable to my installation of Vivaldi:

```r
Sys.setenv(CHROMOTE_CHROME = "/Applications/Vivaldi.app/Contents/MacOS/Vivaldi")
```

Now `r ggsave(tbl, "x.png")` generates the table as a PNG file with no difficulty.
