### ISSUE TITLE
consequence of breaking change in htmltools `0.5.3`

### ISSUE THREAD

**Issue by antdurrant** [rstudio/gt#1055]
I see from the release of [0.5.3](https://github.com/rstudio/htmltools/releases/tag/v0.5.3) and issue https://github.com/rstudio/htmltools/issues/305 that there was no expected use-case, so just want to flag this.

Inline printing `gt::gt()` tables (though not `knitr::kable()` tables) leaves the ``{=html} tag in the printed output.

````
# no problem
```{r}
x <-gt::gt(head(mtcars))

x
```
# prefix/afix

`r x`

````

How the tagged output looks -

<img width="500" alt="Screen Shot 2022-09-09 at 14 05 19" src="https://user-images.githubusercontent.com/52227638/189275649-caf66c7c-86e6-4a48-821e-52cec17cb4fc.png">

# Use case example

My frequent use case in reports is rendering tables/graphs _or_ text _or_ nothing, depending on available data and/or other specific conditions. 

````
```{r}
knitr::opts_chunk$set(
	echo = FALSE,
	message = FALSE,
	warning = FALSE
)

output_fun <- function(x){
  if(x <.5){
  "some text"
} else if(x < .8){
  x
} # implied else NULL
}

a <- output_fun(.3)
b <- output_fun(.6)
c <- output_fun(.9)
```


```{r}
a
b
c
```

`r a`

`r b`

`r c`
````

I don't know if this is a "normal" use-case, or whether this matches the expected behaviour on your end, or whether there is a satisfactory work-around. Seeing that there didn't seem to be an expected use-case made me think it would be reasonable to bring it to your attention.

For the time-being, I'm just going to roll-back to 0.5.2.

Many thanks for continuing to provide such excellent tools!

**Comment by rich-iannone** [comment]
Agree this is something that can be fixed in gt. I moved this issue to https://github.com/rstudio/gt/issues/1055 so I am closing it here.

**Comment by antdurrant** [comment]
many thanks, all!
