### ISSUE TITLE
Double line style

### ISSUE THREAD

**Issue by nipnipj** [rstudio/gt#1069]
How can I change the style of a border (`column_labels.border.bottom.style`) from one line to double line like the ones used by `tab_row_group` but for only one side (and black maybe)?

**Comment by rich-iannone** [comment]
You can use the following code (works in the *in-development* version of gt):

```r
library(gt)

exibble |>
  gt() |>
  tab_options(
    column_labels.border.bottom.style = "double",
    column_labels.border.bottom.color = "black",
    column_labels.border.bottom.width = px(3)
  )
```

<img width="784" alt="column-labels-double-border" src="https://user-images.githubusercontent.com/5612024/228564937-cd7241ed-3d05-4fc3-b76c-47911dd957b6.png">
