### ISSUE TITLE
Request for additional functionality for cols_align_decimal

### ISSUE THREAD

**Issue by steveputman** [rstudio/gt#1076]
Accidentally commented on merged PR . . .probably makes sense as separate issue.

This is great, @rich-iannone! 

It's fairly common, when using `accounting = TRUE`, that numbers are rounded (so `decimals = 0`). That combination of options (unless `drop_trailing_dec_mark = FALSE` is also used) doesn't align properly, which obviously makes sense given that there are no decimals for `cols_align_decimal()` to attack. 

Do you think there's any way to address that combination of options (for example by (a) faking the decimal by imputing the `drop_trailing_dec_mark = FALSE` option, running `align_to_char()`, then stripping out the decimal or (b) applying the original approach of inserting an invisible parenthesis after nonnegative numbers)? Happy to take a stab but not sure of the best approach.

Thanks!

``` r
library(gt)

dplyr::tibble(
  char = LETTERS[1:8],
  num = c(1.2, -33.52, 9023.2, -283.527, 0.401, -123.1, NA, 41)) |> 
  gt() |> 
  tab_header("fmt_currency / accounting = TRUE / decimals = 0") |> 
  fmt_currency(num, accounting = TRUE, decimals = 0) |> 
  cols_align_decimal()
```

<div id="cgxvxxiaoe" style="overflow-x:auto;overflow-y:auto;width:auto;height:auto;">

<table class="gt_table">
  <thead class="gt_header">
    <tr>
      <td colspan="2" class="gt_heading gt_title gt_font_normal gt_bottom_border" style>fmt_currency / accounting = TRUE / decimals = 0</td>
    </tr>
    
  </thead>
  <thead class="gt_col_headings">
    <tr>
      <th class="gt_col_heading gt_columns_bottom_border gt_left" rowspan="1" colspan="1" scope="col" id="char">char</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_right" rowspan="1" colspan="1" scope="col" id="num">num</th>
    </tr>
  </thead>
  <tbody class="gt_table_body">
    <tr><td headers="char" class="gt_row gt_left">A</td>
<td headers="num" class="gt_row gt_right">    $1 </td></tr>
    <tr><td headers="char" class="gt_row gt_left">B</td>
<td headers="num" class="gt_row gt_right"> ($34 ) </td></tr>
    <tr><td headers="char" class="gt_row gt_left">C</td>
<td headers="num" class="gt_row gt_right">$9,023 </td></tr>
    <tr><td headers="char" class="gt_row gt_left">D</td>
<td headers="num" class="gt_row gt_right">($284 ) </td></tr>
    <tr><td headers="char" class="gt_row gt_left">E</td>
<td headers="num" class="gt_row gt_right">    $0 </td></tr>
    <tr><td headers="char" class="gt_row gt_left">F</td>
<td headers="num" class="gt_row gt_right">($123 ) </td></tr>
    <tr><td headers="char" class="gt_row gt_left">G</td>
<td headers="num" class="gt_row gt_right">NA</td></tr>
    <tr><td headers="char" class="gt_row gt_left">H</td>
<td headers="num" class="gt_row gt_right">   $41 </td></tr>
  </tbody>
  
  
</table>
</div>

<sup>Created on 2022-10-13 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

_Originally posted by @steveputman in https://github.com/rstudio/gt/issues/1058#issuecomment-1278397424_

**Comment by rich-iannone** [comment]
Thanks so much @steveputman for submitting the PR for this! It looks great so I'll review it shortly (and then merge right after that).
