### ISSUE TITLE
gt_save to png does not work on shinyapps.io

### ISSUE THREAD

**Issue by JZauner** [rstudio/gt#1082]
## Description

The gtsave function (save to png) does not work on shinyapps.io. With `gt 0.6.0`, this could be fixed by including the `webshot`library and including
```
if (!webshot::is_phantomjs_installed())
webshot::install_phantomjs()
```
in the appscript. 

Since `gt 0.7.0` changed to `webshot2` and `chromote`, this fix - obviously - does not work anymore (I have tried by including both libraries in my script).

BTW. `gt` is the best otherwise :)

**Comment by rdelrossi** [comment]
[This](https://github.com/rstudio/gt/issues/1049) may be of some help, @JZauner.

**Comment by JZauner** [comment]
Thanks @rdelrossi. Based on your suggestion I have searched a bit and it might work if shinyapps.io had a browser installed that the `chromote` package could talk to (which does not seem to be the case at present). 
Also, my problem might not be considered a bug but rather a current limitation in a niche case where people using shinyapps.io want to use `gt` with png save functionality?

**Comment by schloerke** [comment]
There is an open PR for shinyapps.io to install chrome for chromote. 

Until that PR is merged (and implemented), you'll need to `library(pagedown)` to get chrome installed on shinyapps.io

**Comment by JZauner** [comment]
Adding `pagedown` worked like a charm - Thanks a lot, @schloerke!
