### ISSUE TITLE
Quarto Word output is always left aligned

### ISSUE THREAD

**Issue by ddsjoberg** [rstudio/gt#1089]
Hey hey! I ❤️ {gt} !!

I noticed that with Word output, the column alignment does not yet respect the column alignment assigned in `gt::cols_align()`. You probably already know this, but wanted to make an issue just in case. The output below was created using the current dev version of gt. The columns should be center aligned, but they are all left aligned.

🍁 🍁 

````
---
title: "Quarto+Word+Alignment"
format: docx
---

## Quarto

Quarto enables you to weave together content and executable code into a finished document. To learn more about Quarto see <https://quarto.org>.

```{r}
packageVersion("gt")
mtcars[1:4, 1:4] |> 
  gt::gt() |> 
  gt::cols_align("center") |> 
  gt::cols_label(mpg = "A very very long header",
                 cyl = "Another long header")
```
````

![image](https://user-images.githubusercontent.com/26774684/198415178-8e3df427-cdd2-4098-86e6-0e07ce939af7.png)

**Comment by rich-iannone** [comment]
Thanks for posting this issue, I think @thebioengineer has a fix in the works.

**Comment by thebioengineer** [comment]
This feature has been added in #1131 - @rich-iannone, I think we can close this issue out

**Comment by ddsjoberg** [comment]
🥳 🍾 🥳 🍾 🥳 🍾 ❤️
