### ISSUE TITLE
garbaged hebrew text using gt & gtsummary

### ISSUE THREAD

**Issue by yatirbe** [rstudio/gt#1100]
I am using gtsummary version 1.5.2
and gt version 0.4.0

I cant figure out why I am getting garbaged hebrew text lables even though the encoding is UTF-8 and all looks fine in the data frame.
see image below.
I cannot upgrade packages version on the server.
Any ideas ?
(the gtsummary package author suggested posting here)

![image](https://user-images.githubusercontent.com/72144652/199254301-7b87bb00-15d4-4c98-a10f-ec343ba8e172.png)

**Comment by rich-iannone** [comment]
Sorry about the difficulty encountered here. I'll check to see that this is less of a problem for the dev version, otherwise this is something on the roadmap (see https://github.com/rstudio/gt/issues/697).
