### ISSUE TITLE
Some css styles cannot be isolated from Quarto's default settings

### ISSUE THREAD

**Issue by AlbertRapp** [rstudio/gt#1120]
## Description

As discussed in #1113 some css styles are not isolated from Quarto's defaults even when using `as_raw_html()`. I think this mainly relates to styles that are inherited from `body`. Some styles can be isolated from Quarto's defaults by wrapping the code chunk in a `div` with `style="all:initial;"`.

## Reproducible example

Multiple examples documented at https://guileless-mousse-1c0b8b.netlify.app/ (in a Quarto book to see effects).

**Comment by rich-iannone** [comment]
Thanks for filing this issue! Will work with the Quarto team to improve this aspect of gt.
