### ISSUE TITLE
table title doesn't span all columns when exported to html

### ISSUE THREAD

**Issue by yiqinfu** [rstudio/gt#113]
Using the example from the documentation, we save the table to an html file:

```
start_date <- "2010-06-07"
end_date <- "2010-06-14"

plot = sp500 %>%
  dplyr::filter(date >= start_date & date <= end_date) %>%
  dplyr::select(-adj_close) %>%
  dplyr::mutate(date = as.character(date)) %>%
  gt() %>%
  tab_header(
    title = "S&P 500",
    subtitle = glue::glue("{start_date} to {end_date}")
  ) %>%
  tab_style(cells_styles(text_font = "Optima",
                         text_align = "center",
                         text_weight = "bolder"),
            locations = cells_title(groups = title)
  ) %>%
  fmt_date(
    columns = vars(date),
    date_style = 3
  ) %>%
  fmt_currency(
    columns = vars(open, high, low, close),
    currency = "USD"
  ) %>%
  fmt_number(
    columns = vars(volume),
    scale_by = 1 / 1E9,
    pattern = "{x}B"
  ) %>%
  as_raw_html(inline_css = T)
write_file(plot, "plot.html")
```

If we open the html file, we see this:

![screen shot 2018-12-16 at 9 43 55 pm](https://user-images.githubusercontent.com/23423360/50063735-bde4bb80-017b-11e9-9bf2-4b6a962b453a.png)

The title doesn't span all columns.

Edit: The title *does* span all columns when no style is added. If we add any style to it, it doesn't display properly.

**Comment by rich-iannone** [comment]
I see the issue. Internally, the `gt:::inline_html_styles()` function will see CSS `class` and `style` attributes and, during inlining, merge generated style rules into the existing set. The problem is that the `colspan` attr (included in both `<th>`'s of the title and subtitle) is wiped out because of its positioning between `class` and `style` (which is added to the end of the end of the tag). The solution is to put the `colspan` attribute before `class`.

**Comment by yiqinfu** [comment]
> I see the issue. Internally, the `gt:::inline_html_styles()` function will see CSS `class` and `style` attributes and, during inlining, merge generated style rules into the existing set. The problem is that the `colspan` attr (included in both `<th>`'s of the title and subtitle) is wiped out because of its positioning between `class` and `style` (which is added to the end of the end of the tag). The solution is to put the `colspan` attribute before `class`.

Thank you! Looking forward to the update.

**Comment by rich-iannone** [comment]
@yiqinfu You're welcome! Thanks for filing the issue.
