### ISSUE TITLE
Error in rlang::eval_tidy(expr = var_expr, data = data_tbl, env = emptyenv()) :    object 'factor_name' not found Called from: rlang::eval_tidy(expr = var_expr, data = data_tbl, env = emptyenv())

### ISSUE THREAD

**Issue by kmatosli** [rstudio/gt#1139]
I have a gt table below that has started returning this error of an object not found.  The column exists in the data table.  Has something changed in the gt package  that may be causing this issue? If I switch to the latest version, it forces me to get webshot2 adding additional issues.  Currently it can't find columns that exists.  If it is not one factor name it switches to mtd.  Not really sure how to trouble shoot this.

acwiimiexustopplotmtd = gt(acwiimiexustopmtdpivot)%>%
  tab_header(title= md("**Index**"), subtitle = md("Top 38 Sorted by Month to Date")) %>%
  tab_options(table.width = pct(50)) %>% 
  tab_options(
    heading.background.color = wbColorList$BlairBlue,
    column_labels.background.color = wbColorList$BlairBlue,
    column_labels.font.weight = "bolder",
    data_row.padding = px(0),
    row_group.padding = px(1))%>%
  tab_style(
    style = cell_text(font = "Roboto Condensed", size = px(14), align = "left"),
    locations = cells_title("title")) %>%
  tab_style(
    style = cell_text(font = "Roboto Condensed", size = px(12), align = "left"),
    locations = cells_title("subtitle")) %>%
  tab_style(
    style = cell_text(font = "Roboto Condensed", size = px(10)),
    locations = cells_column_labels(columns = TRUE)) %>%  # Works up to here.
  tab_style(
    style = cell_text(
    font = "Roboto Condensed",
    size = px(12)),
    locations = cells_body(
    columns = c(factor_name, factor_category, last_month, last_quarter, mtd, qtd, ytd))) %>%
  cols_label(factor_name = "Factor Name", factor_category = "Category",
             last_month = "Last Mo", last_quarter = "Last Qtr", mtd = "MTD",
             qtd = "QTD", ytd = "YTD") %>%
  data_color(
    columns = c(mtd),
    colors = scales::col_numeric(
      palette = c("red", "white", wbColorList$DarkGreen),
      domain=NULL
    ) %>%
fmt_number(
    columns = c(last_month, last_quarter, mtd, qtd, ytd),
    decimals = 2,
    use_seps = FALSE) %>% 
cols_width(
  c(factor_name) ~ px(250),
  c(factor_category) ~ px(75),
  c(last_month) ~ px(50),
  c(last_quarter) ~ px (50),
  c(mtd) ~ px(50),
  c(qtd) ~ px(50),
  c(ytd) ~ px(50)) %>%
cols_move(
  columns = c(last_month, qtd, last_quarter, ytd),
  after = c(mtd)
)%>%
data_color(
    columns = c(mtd),
    colors = scales::col_numeric(
      palette = c("red", "white", wbColorList$DarkGreen),
      domain=NULL
    )
  )
)

**Comment by rich-iannone** [comment]
I cannot reproduce this unfortunately. Could you provide a reproducible example that I can run on my system?
