### ISSUE TITLE
cross-references are broken when output format is docx

### ISSUE THREAD

**Issue by XiangyunHuang** [rstudio/gt#1140]
## Prework

* [x] Read and agree to the [code of conduct](https://www.contributor-covenant.org/version/2/0/code_of_conduct/) and [contributing guidelines](https://github.com/rstudio/gt/blob/master/.github/CONTRIBUTING.md).
* [x] If there is [already a relevant issue](https://github.com/rstudio/gt/issues), whether open or closed, comment on the existing thread instead of posting a new issue.
* [x] Post a [minimal reproducible example](https://www.tidyverse.org/help/) so the maintainer can troubleshoot the problems you identify. A reproducible example is:
    * [x] **Runnable**: post enough R code and data so any onlooker can create the error on their own computer.
    * [x] **Minimal**: reduce runtime wherever possible and remove complicated details that are irrelevant to the issue at hand.
    * [x] **Readable**: format your code according to the [tidyverse style guide](https://style.tidyverse.org/).

## Description

Cross-references was broken when output format is docx.

## Reproducible example

a minimal reproducible example from https://github.com/rstudio/gt/issues/994

````
---
title: "quarto gt"
format: docx
---

## Quarto

A table @tbl-gt.

```{r}
#| label: tbl-gt
#| tbl-cap: A Caption
#| echo: false

library(gt)

mtcars |> 
  head() |>
  gt() |>  
  tab_spanner(
    label = "performance",
    columns = c(
      mpg, cyl, disp
      )
  ) 
```
````

Here is a screenshot from docx.

<img width="1092" src="https://user-images.githubusercontent.com/12031874/202876848-861b3319-5f63-4815-a324-60a3f2dbff12.png">

## Expected result

Cross-references work!

## Session info

End the reproducible example with a call to `sessionInfo()` in the same session (e.g. `reprex(session_info = TRUE)`) and include the output.

```
> sessionInfo("gt")
R version 4.2.2 (2022-10-31)
Platform: x86_64-apple-darwin17.0 (64-bit)
Running under: macOS Ventura 13.0.1

Matrix products: default
LAPACK: /Library/Frameworks/R.framework/Versions/4.2/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
character(0)

other attached packages:
[1] gt_0.8.0

loaded via a namespace (and not attached):
[1] compiler_4.2.2  graphics_4.2.2  tools_4.2.2     utils_4.2.2     grDevices_4.2.2 stats_4.2.2    
[7] datasets_4.2.2  methods_4.2.2   base_4.2.2 
```

I use quarto 1.2.269 and gt 0.8.0

**Comment by stevenbedrick** [comment]
Just to add, the same problem is happening with Knitr, so it's (maybe) not just a Quarto thing.

**Comment by tdemarchin** [comment]
Hi, I have the same issue. Is there any fix planned soon?

**Comment by tdemarchin** [comment]
Hi, this a very blocking issue as I cannot gt in production, do you plan to fix it soon?

**Comment by ldecicco-USGS** [comment]
I wanted to add that example given in this issue shows 2 problems. The cross referencing doesn't work, and the caption doesn't show up. Ideally both would be fixed.

**Comment by XiangyunHuang** [comment]
The issue was solved by Quarto 1.4.376, so I'm gone to close it.

**Comment by anbrav0** [comment]
Hi all 

I apologize if this is already a separate issue or maybe I am mistaken, but gt table outputs seem to break whenever I include a "label" and a "tbl-cap" option in the chunk when trying to render as a .docx format

Please see below my details to reproduce this:

RStudio version: Version 2024.12.0+467 (2024.12.0+467)

Quarto version: 
```
quarto::quarto_version()
‘1.6.39’
```

Reproducible code example: 
```
---
title: "quarto gt"
format: docx
---

## Quarto


```{r}
#| echo: false
#| label: tbl-gt
#| tbl-cap: A Caption

library(gt)

mtcars |> 
  head() |>
  gt() |>  
  tab_spanner(
    label = "performance",
    columns = c(
      mpg, cyl, disp
      )
  ) 
```

Opening the rendered .docx file:


<img width="373" alt="Image" src="https://github.com/user-attachments/assets/01fa5b92-3a9d-4b75-8ad9-dd93a4bb7109" />

When viewing the .docx file:

<img width="1013" alt="Image" src="https://github.com/user-attachments/assets/474e42a6-704a-4ce9-a9b2-5e49a4cdd88e" />


If i were to remove the chunk options "label" and a "tbl-cap" I no longer get the unreadable content warning, and the output looks like so:

<img width="1012" alt="Image" src="https://github.com/user-attachments/assets/ebeccb58-9a54-490e-9ab6-0d722d220d0b" />


session info:
```
─ Session info ───────────────────────────────────────────────────────────
 setting  value
 version  R version 4.4.1 (2024-06-14)
 os       macOS 15.0
 system   aarch64, darwin20
 ui       RStudio
 language (EN)
 collate  en_US.UTF-8
 ctype    en_US.UTF-8
 tz       America/New_York
 date     2025-01-21
 rstudio  2024.12.0+467 Kousa Dogwood (desktop)
 pandoc   3.2 @ /Applications/RStudio.app/Contents/Resources/app/quarto/bin/tools/aarch64/ (via rmarkdown)

─ Packages ───────────────────────────────────────────────────────────────
 package     * version  date (UTC) lib source
 cli           3.6.3    2024-06-21 [1] CRAN (R 4.4.0)
 digest        0.6.37   2024-08-19 [1] CRAN (R 4.4.1)
 dplyr         1.1.4    2023-11-17 [1] CRAN (R 4.4.0)
 evaluate      1.0.1    2024-10-10 [1] CRAN (R 4.4.1)
 fansi         1.0.6    2023-12-08 [1] CRAN (R 4.4.0)
 fastmap       1.2.0    2024-05-15 [1] CRAN (R 4.4.0)
 generics      0.1.3    2022-07-05 [1] CRAN (R 4.4.0)
 glue          1.8.0    2024-09-30 [1] CRAN (R 4.4.1)
 gt          * 0.11.1   2024-10-04 [1] CRAN (R 4.4.1)
 htmltools     0.5.8.1  2024-04-04 [1] CRAN (R 4.4.0)
 jsonlite      1.8.9    2024-09-20 [1] CRAN (R 4.4.1)
 knitr         1.49     2024-11-08 [1] CRAN (R 4.4.1)
 later         1.4.1    2024-11-27 [1] CRAN (R 4.4.1)
 lifecycle     1.0.4    2023-11-07 [1] CRAN (R 4.4.0)
 magrittr      2.0.3    2022-03-30 [1] CRAN (R 4.4.0)
 pillar        1.9.0    2023-03-22 [1] CRAN (R 4.4.0)
 pkgconfig     2.0.3    2019-09-22 [1] CRAN (R 4.4.0)
 processx      3.8.4    2024-03-16 [1] CRAN (R 4.4.0)
 ps            1.8.1    2024-10-28 [1] CRAN (R 4.4.1)
 quarto        1.4.4    2024-07-20 [1] CRAN (R 4.4.0)
 R6            2.5.1    2021-08-19 [1] CRAN (R 4.4.0)
 Rcpp          1.0.13-1 2024-11-02 [1] CRAN (R 4.4.1)
 rlang         1.1.4    2024-06-04 [1] CRAN (R 4.4.0)
 rmarkdown     2.29     2024-11-04 [1] CRAN (R 4.4.1)
 rstudioapi    0.17.1   2024-10-22 [1] CRAN (R 4.4.1)
 sass          0.4.9    2024-03-15 [1] CRAN (R 4.4.0)
 sessioninfo   1.2.2    2021-12-06 [1] CRAN (R 4.4.0)
 tibble        3.2.1    2023-03-20 [1] CRAN (R 4.4.0)
 tidyselect    1.2.1    2024-03-11 [1] CRAN (R 4.4.0)
 utf8          1.2.4    2023-10-22 [1] CRAN (R 4.4.0)
 vctrs         0.6.5    2023-12-01 [1] CRAN (R 4.4.0)
 withr         3.0.2    2024-10-28 [1] CRAN (R 4.4.1)
 xfun          0.49     2024-10-31 [1] CRAN (R 4.4.1)
 xml2          1.3.6    2023-12-04 [1] CRAN (R 4.4.0)
 yaml          2.3.10   2024-07-26 [1] CRAN (R 4.4.0)

 [1] /Library/Frameworks/R.framework/Versions/4.4-arm64/Resources/library
```

**Comment by anbrav0** [comment]
this might already be brought up in here: https://github.com/quarto-dev/quarto-cli/issues/7151
