### ISSUE TITLE
Add `md()` and `html()` features to list argument in `cols_label()`

### ISSUE THREAD

**Issue by alex-lauer** [rstudio/gt#1146]
## Prework

- [ x ] Read and abide by **gt**'s [code of conduct](https://www.contributor-covenant.org/version/2/0/code_of_conduct/) and [contributing guidelines](https://github.com/rstudio/gt/blob/master/.github/CONTRIBUTING.md).
- [ x ] Search for duplicates among the [existing issues](https://github.com/rstudio/gt/issues) (both open and closed).

## Proposal

I really love the feature to add a named list of column labels to `cols_label()`. In most cases this list evolves during my data processing work prior to the table creation. I would like to use `md()` here to add a line break to my column labels. The below code works fine:

```{r}
library(gt)
library(tidyverse)

col_list1 <- list(
  "mfr" = "Manufacturer",
  "model" = "Model",
  "hp_rpm" = md("Horse Power  \n(rpm)")
)

gt::gtcars |> 
  dplyr::filter(mfr == "BMW") |> 
  dplyr::select(mfr, model, hp_rpm) |> 
  gt() |> 
  cols_label(
    .list = col_list1
  )
```
![image](https://user-images.githubusercontent.com/46823209/203966419-b2b495fb-a578-4c6a-8b06-71b8b78d6666.png)

However, these ones don't:

```{r}
library(gt)
library(tidyverse)

col_list2 <- as.list(c("Manufacturer", "Model", md("Horse Power  \n(rpm)"))) |> 
  purrr::set_names(c("mfr", "model", "hp_rpm"))

gt::gtcars |> 
  dplyr::filter(mfr == "BMW") |> 
  dplyr::select(mfr, model, hp_rpm) |> 
  gt() |> 
  cols_label(
    .list = col_list2
  )

col_list3 <- as.list(c("Manufacturer", "Model", "Horse Power  \n(rpm)")) |> 
  purrr::set_names(c("mfr", "model", "hp_rpm"))

gt::gtcars |> 
  dplyr::filter(mfr == "BMW") |> 
  dplyr::select(mfr, model, hp_rpm) |> 
  gt() |> 
  cols_label(
    .list = md(col_list3)
  )
```
![image](https://user-images.githubusercontent.com/46823209/203967045-815f36e6-e5fe-4469-b5fc-8633c9427302.png)

Thanks so much in advance!

**Comment by rich-iannone** [comment]
Thanks for filing this issue! Totally agree that this should work and we’ll make it happen for the upcoming release.

**Comment by rich-iannone** [comment]
@alex-lauer With a new PR in the works (https://github.com/rstudio/gt/pull/1265), you can now supply a function (that will be called on all provided label values) in the optional `.fn` argument. So the last statement from your example will work like this:

```r
gt::gtcars |> 
  dplyr::filter(mfr == "BMW") |> 
  dplyr::select(mfr, model, hp_rpm) |> 
  gt() |> 
  cols_label(
    .list = col_list3,
    .fn = md
  )
```

<img width="491" alt="cols_label_fn_arg" src="https://user-images.githubusercontent.com/5612024/226698402-bd43cf03-4999-4d24-81fc-c0319f6420a0.png">
