### ISSUE TITLE
Add option to define table caption and enable cross-referencing

### ISSUE THREAD

**Issue by larnsce** [rstudio/gt#115]
This is an extremely useful package. Thanks! In all my reporting with .Rmd files, I use the `bookdown` file formats `pdf_document2` and `html_document2`, which allow for cross-referencing of tables and figures in text. See here: https://bookdown.org/yihui/bookdown/tables.html

Is there an option available in the `gt` package that allows for tables to have named captions and numbering, which allows for cross-referencing in text using ` \@ref(tab:tab1)`?

**Comment by rich-iannone** [comment]
There is no option currently for this, but it seems like this would be a worthwhile LaTeX integration feature, similar to #112. Thanks for filing this issue.

**Comment by vincentarelbundock** [comment]
The new changes I pushed in this PR address this issue: https://github.com/rstudio/gt/pull/143

I added a `label` argument to `tab_header` because that seemed to make sense, but I'm not sure if that's the design you had in mind.

Currently, label is only inserted in the LaTeX caption, but it would be trivial to use the `bookdown` html tags.

**Comment by kevinykuo** [comment]
+1 Not being able to cross reference blocks writing books and academic articles (and even technical blog posts in many cases probably).

**Comment by davebraze** [comment]
+1 to this. 

I have been using the subtitle as "caption" in gt tables. Could a caption argument to tab_header() be setup as an alias for subtitle, in a way that would work with bookdown's html_document2 and pdf_document2? It'd be nice to have some formatting pixie dust too.

```
gt(head(mtcars)) %>%
    tab_header(title="", subtitle="Table 1: Mtcars with gt.") %>%
    tab_options(table.width=pct(90),
                    table.border.top.style=0,
                    row.padding=px(4)) %>%
        tab_style(style=cells_styles(
                      text_align='left',
                      text_color='grey'),
                  locations=cells_title(groups="subtitle"))
```

**Comment by dmenne** [comment]
Check kable: Captions and Table numbering including cross-referencing for bookdown included. I don't know of any other package that supports it, but not having these two is a no-go for science.

**Comment by ballengerj** [comment]
I agree. This needs to be a priority fix for the more widespread use of this package for the creation of reports.

**Comment by dmenne** [comment]
Since cross-referencing is documented confusingly (with or without #?), I have created a cheat-gist sample bookdown file, with a function `mcaption`  that can substitute for the missing features in most cases I am interested in.

https://gist.github.com/dmenne/f8eb291c9e71a5de44764d442e8bdefd

**Comment by rsantamariao** [comment]
Thanks dmenne, it works for me.
Any chance to move the caption below the table?

**Comment by njtierney** [comment]
Hi there, just wondering if there is a timeline for this? I love `gt`, but not being able to reference tables means I won't be able to use it for a lot of my work

**Comment by kendavidn** [comment]
Cross referencing in html would make this the undisputed king of table packages!

**Comment by jcheng5** [comment]
Implementation hints:
https://github.com/yihui/knitr/blob/ed9d8bba2eb3603e2bda3d27870535bcc93a83f9/R/table.R#L159
https://github.com/rstudio/bookdown/blob/00987215b7572def2f5cd73a623efc38f4f30ab7/R/html.R#L535

**Comment by jaredlander** [comment]
Tried out the new `caption` argument. That's a big step toward using this in `{bookdown}`. Is it possible to add `caption.short`, similar to `knitr::kable()`?

**Comment by camillebelmin** [comment]
Hi, I'm really glad to hear there is this new argument on the gt function. However, it has not worked for me and I was not able to find an example how to use it. Could someone provide an example how to use caption to cross-reference tables in bookdown, or direct me towards a page providing this? I would be very grateful.

**Comment by dmenne** [comment]
Caption works for me, but there is no `label` argument. Please, rstudio, simply use yihui's kable as a template, it works fine.

**Comment by camillebelmin** [comment]
@dmenne, thanks for your answer. How do you reference your gt table in your text then (i.e. @ref(tab:label))? Do you output your Rmd into PDF or HTML?

**Comment by dmenne** [comment]
I am a bit out of sync how I did it, but one of the tricks in my gist will do. Ugly, though

https://gist.github.com/dmenne/f8eb291c9e71a5de44764d442e8bdefd

**Comment by camillebelmin** [comment]
I think I figured out that cross-referencing gt tables works when knitting with HTML but not to PDF... 
Here is a simple example:  

I am referencing Table \@ref(tab:descri) 

```{r label }
df = data.frame(A = c(1,2,3), B = c(4,5,6))

gt(df, caption = "this is the caption")
```

**Comment by dmenne** [comment]
But where did you define the label "descri"?

**Comment by camillebelmin** [comment]
Oh the label of the code chunk did not appear in the code above. I defined it as follows: 
```{r descri}
df = data.frame(A = c(1,2,3), B = c(4,5,6))
gt(df, caption = "this is the caption")
``` 
 Table \\@ref(tab:descri) resulted in "Table 1"  when the output was bookdown::html_document2. But when the output was bookdown::pdf_document2, it resulted in "Table ??"

**Comment by camillebelmin** [comment]
Oh the label of the code chunk did not appear in the code above. I defined it as follows: 
\```{r descri}
df = data.frame(A = c(1,2,3), B = c(4,5,6))
gt(df, caption = "this is the caption")
\``` 
 Table \\@ref(tab:descri) resulted in "Table 1"  when the output was bookdown::html_document2. But when the output was bookdown::pdf_document2, it resulted in "Table ??"

**Comment by dmenne** [comment]
Thank, the usual way. I will add it to my gist.

**Comment by mxw010** [comment]
> Oh the label of the code chunk did not appear in the code above. I defined it as follows: ```{r descri} df = data.frame(A = c(1,2,3), B = c(4,5,6)) gt(df, caption = "this is the caption") ``` Table \@ref(tab:descri) resulted in "Table 1" when the output was bookdown::html_document2. But when the output was bookdown::pdf_document2, it resulted in "Table ??"

This is not working for me :\

This should be highest priority. Not being able to referencing tables basically makes this package useless for any scientific article.
