### ISSUE TITLE
tab_spanner not working, even with example code

### ISSUE THREAD

**Issue by erdnaxel** [rstudio/gt#1154]
Hello:

I want to use tab_spanner, but it doesn't work. I tried with the example code in the documentation and it fails... (I use many other gt functions and everything works as expected.)

`
library(gt)

gtcars %>%
  dplyr::select(
    -mfr, -trim, bdy_style,
    -drivetrain, -trsmn, -ctry_origin
  ) %>%
  dplyr::slice(1:8) %>%
  gt(rowname_col = "model") %>%
  tab_spanner(
    label = "performance",
    columns = c(
      hp, hp_rpm, trq, trq_rpm,
      mpg_c, mpg_h
    )
  )
`

returns: 

![image](https://user-images.githubusercontent.com/63831549/205338631-8654125f-ded1-4696-9b47-58225c154990.png)

Session info:

![image](https://user-images.githubusercontent.com/63831549/205338803-259dffce-1d74-4365-8dd0-479c9370bfd9.png)

**Comment by denis-or** [comment]
Hello.

I tested it on linux mint 20.4 with R 4.2.1 and gt 0.8.0. It worked here.

``` r
library(gt)

gtcars %>%
  dplyr::select(
    -mfr, -trim, bdy_style,
    -drivetrain, -trsmn, -ctry_origin
  ) %>%
  dplyr::slice(1:8) %>%
  gt(rowname_col = "model") %>%
  tab_spanner(
    label = "performance",
    columns = c(
      hp, hp_rpm, trq, trq_rpm,
      mpg_c, mpg_h
    )
  )
```

<div id="xmiillysvn" style="padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;">

<table class="gt_table">
  
  <thead class="gt_col_headings">
    <tr>
      <th class="gt_col_heading gt_columns_bottom_border gt_left" rowspan="2" colspan="1" scope="col" id=""></th>
      <th class="gt_col_heading gt_columns_bottom_border gt_right" rowspan="2" colspan="1" scope="col" id="year">year</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_left" rowspan="2" colspan="1" scope="col" id="bdy_style">bdy_style</th>
      <th class="gt_center gt_columns_top_border gt_column_spanner_outer" rowspan="1" colspan="6" scope="colgroup" id="performance">
        <span class="gt_column_spanner">performance</span>
      </th>
      <th class="gt_col_heading gt_columns_bottom_border gt_right" rowspan="2" colspan="1" scope="col" id="msrp">msrp</th>
    </tr>
    <tr>
      <th class="gt_col_heading gt_columns_bottom_border gt_right" rowspan="1" colspan="1" scope="col" id="hp">hp</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_right" rowspan="1" colspan="1" scope="col" id="hp_rpm">hp_rpm</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_right" rowspan="1" colspan="1" scope="col" id="trq">trq</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_right" rowspan="1" colspan="1" scope="col" id="trq_rpm">trq_rpm</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_right" rowspan="1" colspan="1" scope="col" id="mpg_c">mpg_c</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_right" rowspan="1" colspan="1" scope="col" id="mpg_h">mpg_h</th>
    </tr>
  </thead>
  <tbody class="gt_table_body">
    <tr><th id="stub_1_1" scope="row" class="gt_row gt_left gt_stub">GT</th>
<td headers="stub_1_1 year" class="gt_row gt_right">2017</td>
<td headers="stub_1_1 bdy_style" class="gt_row gt_left">coupe</td>
<td headers="stub_1_1 hp" class="gt_row gt_right">647</td>
<td headers="stub_1_1 hp_rpm" class="gt_row gt_right">6250</td>
<td headers="stub_1_1 trq" class="gt_row gt_right">550</td>
<td headers="stub_1_1 trq_rpm" class="gt_row gt_right">5900</td>
<td headers="stub_1_1 mpg_c" class="gt_row gt_right">11</td>
<td headers="stub_1_1 mpg_h" class="gt_row gt_right">18</td>
<td headers="stub_1_1 msrp" class="gt_row gt_right">447000</td></tr>
    <tr><th id="stub_1_2" scope="row" class="gt_row gt_left gt_stub">458 Speciale</th>
<td headers="stub_1_2 year" class="gt_row gt_right">2015</td>
<td headers="stub_1_2 bdy_style" class="gt_row gt_left">coupe</td>
<td headers="stub_1_2 hp" class="gt_row gt_right">597</td>
<td headers="stub_1_2 hp_rpm" class="gt_row gt_right">9000</td>
<td headers="stub_1_2 trq" class="gt_row gt_right">398</td>
<td headers="stub_1_2 trq_rpm" class="gt_row gt_right">6000</td>
<td headers="stub_1_2 mpg_c" class="gt_row gt_right">13</td>
<td headers="stub_1_2 mpg_h" class="gt_row gt_right">17</td>
<td headers="stub_1_2 msrp" class="gt_row gt_right">291744</td></tr>
    <tr><th id="stub_1_3" scope="row" class="gt_row gt_left gt_stub">458 Spider</th>
<td headers="stub_1_3 year" class="gt_row gt_right">2015</td>
<td headers="stub_1_3 bdy_style" class="gt_row gt_left">convertible</td>
<td headers="stub_1_3 hp" class="gt_row gt_right">562</td>
<td headers="stub_1_3 hp_rpm" class="gt_row gt_right">9000</td>
<td headers="stub_1_3 trq" class="gt_row gt_right">398</td>
<td headers="stub_1_3 trq_rpm" class="gt_row gt_right">6000</td>
<td headers="stub_1_3 mpg_c" class="gt_row gt_right">13</td>
<td headers="stub_1_3 mpg_h" class="gt_row gt_right">17</td>
<td headers="stub_1_3 msrp" class="gt_row gt_right">263553</td></tr>
    <tr><th id="stub_1_4" scope="row" class="gt_row gt_left gt_stub">458 Italia</th>
<td headers="stub_1_4 year" class="gt_row gt_right">2014</td>
<td headers="stub_1_4 bdy_style" class="gt_row gt_left">coupe</td>
<td headers="stub_1_4 hp" class="gt_row gt_right">562</td>
<td headers="stub_1_4 hp_rpm" class="gt_row gt_right">9000</td>
<td headers="stub_1_4 trq" class="gt_row gt_right">398</td>
<td headers="stub_1_4 trq_rpm" class="gt_row gt_right">6000</td>
<td headers="stub_1_4 mpg_c" class="gt_row gt_right">13</td>
<td headers="stub_1_4 mpg_h" class="gt_row gt_right">17</td>
<td headers="stub_1_4 msrp" class="gt_row gt_right">233509</td></tr>
    <tr><th id="stub_1_5" scope="row" class="gt_row gt_left gt_stub">488 GTB</th>
<td headers="stub_1_5 year" class="gt_row gt_right">2016</td>
<td headers="stub_1_5 bdy_style" class="gt_row gt_left">coupe</td>
<td headers="stub_1_5 hp" class="gt_row gt_right">661</td>
<td headers="stub_1_5 hp_rpm" class="gt_row gt_right">8000</td>
<td headers="stub_1_5 trq" class="gt_row gt_right">561</td>
<td headers="stub_1_5 trq_rpm" class="gt_row gt_right">3000</td>
<td headers="stub_1_5 mpg_c" class="gt_row gt_right">15</td>
<td headers="stub_1_5 mpg_h" class="gt_row gt_right">22</td>
<td headers="stub_1_5 msrp" class="gt_row gt_right">245400</td></tr>
    <tr><th id="stub_1_6" scope="row" class="gt_row gt_left gt_stub">California</th>
<td headers="stub_1_6 year" class="gt_row gt_right">2015</td>
<td headers="stub_1_6 bdy_style" class="gt_row gt_left">convertible</td>
<td headers="stub_1_6 hp" class="gt_row gt_right">553</td>
<td headers="stub_1_6 hp_rpm" class="gt_row gt_right">7500</td>
<td headers="stub_1_6 trq" class="gt_row gt_right">557</td>
<td headers="stub_1_6 trq_rpm" class="gt_row gt_right">4750</td>
<td headers="stub_1_6 mpg_c" class="gt_row gt_right">16</td>
<td headers="stub_1_6 mpg_h" class="gt_row gt_right">23</td>
<td headers="stub_1_6 msrp" class="gt_row gt_right">198973</td></tr>
    <tr><th id="stub_1_7" scope="row" class="gt_row gt_left gt_stub">GTC4Lusso</th>
<td headers="stub_1_7 year" class="gt_row gt_right">2017</td>
<td headers="stub_1_7 bdy_style" class="gt_row gt_left">coupe</td>
<td headers="stub_1_7 hp" class="gt_row gt_right">680</td>
<td headers="stub_1_7 hp_rpm" class="gt_row gt_right">8250</td>
<td headers="stub_1_7 trq" class="gt_row gt_right">514</td>
<td headers="stub_1_7 trq_rpm" class="gt_row gt_right">5750</td>
<td headers="stub_1_7 mpg_c" class="gt_row gt_right">12</td>
<td headers="stub_1_7 mpg_h" class="gt_row gt_right">17</td>
<td headers="stub_1_7 msrp" class="gt_row gt_right">298000</td></tr>
    <tr><th id="stub_1_8" scope="row" class="gt_row gt_left gt_stub">FF</th>
<td headers="stub_1_8 year" class="gt_row gt_right">2015</td>
<td headers="stub_1_8 bdy_style" class="gt_row gt_left">coupe</td>
<td headers="stub_1_8 hp" class="gt_row gt_right">652</td>
<td headers="stub_1_8 hp_rpm" class="gt_row gt_right">8000</td>
<td headers="stub_1_8 trq" class="gt_row gt_right">504</td>
<td headers="stub_1_8 trq_rpm" class="gt_row gt_right">6000</td>
<td headers="stub_1_8 mpg_c" class="gt_row gt_right">11</td>
<td headers="stub_1_8 mpg_h" class="gt_row gt_right">16</td>
<td headers="stub_1_8 msrp" class="gt_row gt_right">295000</td></tr>
  </tbody>
  
  
</table>
</div>

<sup>Created on 2022-12-14 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by rich-iannone** [comment]
@erdnaxel : my suggestion is to update gt to the latest version and try again. The example works on my system as well and within the testing framework. Will close this issue but please re-open if problems persist.

**Comment by erdnaxel** [comment]
@rich-iannone I updated to gt 0.8.0, but the problem persisted.

I kept playing with the function and I found a solution -- "gather" is set to TRUE by default. By changing it to FALSE, the problem went away!

![image](https://user-images.githubusercontent.com/63831549/208569701-d367cc3e-7997-4034-8719-29331eaf32df.png)
