### ISSUE TITLE
Can `data_color` provide a deprecation message through `lifecycle` or `rlang`?

### ISSUE THREAD

**Issue by mrcaseb** [rstudio/gt#1160]
https://github.com/rstudio/gt/blob/e263689c4fdb33e0b6f1cfc8805dbdafee4d80e6/R/data_color.R#L567-L584

gt 0.9.0 deprecates the `colors` argument in data_color and prints the warning on every call. 

Can this be changed to a "once every 8 hours" deprecation warning?

It's possible to do this with either `lifcycle` (which is a reverse dependency through ggplot2) or by passing `.frequency` and `.frequency_id` arguments in the cli_warning like

``` r
cli::cli_warn(
  c(
    "Since gt v0.9.0, the `colors` argument has been deprecated.",
    "*" = "Please use the `palette` argument to define a color palette."
  ), 
  .frequency = "regularly",
  .frequency_id = "data_color_warning"
)
#> Warning: Since gt v0.9.0, the `colors` argument has been deprecated.
#> • Please use the `palette` argument to define a color palette.
#> This warning is displayed once every 8 hours.
```

**Comment by rich-iannone** [comment]
Thank you for this issue! This is an excellent suggestion so I'll apply this frequency level to all deprecation messages in the package.

**Comment by rich-iannone** [comment]
I tried this out and discovered quickly that many tests that check for warnings fail (says they do not actually elicit warnings). Until that’s corrected with some sort of workaround, this cannot be done.

**Comment by mrcaseb** [comment]
> I tried this out and discovered quickly that many tests that check for warnings fail (says they do not actually elicit warnings). Until that’s corrected with some sort of workaround, this cannot be done.

I don't know if this would break anything else but it is possible to set the option
`options("rlib_warning_verbosity" = "verbose")`
in the test environment to make rlang warn every time

**Comment by rich-iannone** [comment]
> > I tried this out and discovered quickly that many tests that check for warnings fail (says they do not actually elicit warnings). Until that’s corrected with some sort of workaround, this cannot be done.
> 
> I don't know if this would break anything else but it is possible to set the option `options("rlib_warning_verbosity" = "verbose")` in the test environment to make rlang warn every time See https://rlang.r-lib.org/reference/abort.html#muffling-and-silencing-conditions

This helped, thank you! I'm now using `local_options("rlib_warning_verbosity" = "verbose")` in selected `test_that({...})` blocks to ensure that `expect_warning()` and `expect_no_warning()` work correctly.
