### ISSUE TITLE
Add tab_spanner before the columns labels

### ISSUE THREAD

**Issue by denis-or** [rstudio/gt#1162]
## Prework

* [ X] Read and agree to the [code of conduct](https://www.contributor-covenant.org/version/2/0/code_of_conduct/) and [contributing guidelines](https://github.com/rstudio/gt/blob/master/.github/CONTRIBUTING.md).
* [X ] If there is [already a relevant issue](https://github.com/rstudio/gt/issues), whether open or closed, comment on the existing thread instead of posting a new issue.
* [X ] For any problems you identify, a [minimal reproducible example](https://www.tidyverse.org/help/) so the maintainer can troubleshoot. A reproducible example is:
    * [X ] **Runnable**: post enough R code and data so any onlooker can create the error on their own computer.
    * [ X] **Minimal**: reduce runtime wherever possible and remove complicated details that are irrelevant to the issue at hand.
    * [X ] **Readable**: format your code according to the [tidyverse style guide](https://style.tidyverse.org/).

## Question

Hello guys.  Look the spanners of the table below. I would like the 1st spanner to stay before the column labels. Is a table like this possible with `gt`?

<img src='https://user-images.githubusercontent.com/49842454/206206338-5a2d283e-3ea4-4210-82de-259fa0a25f6f.png' width='500'>

## Reproducible example

``` r
df_tab_1_2 <-
  tibble::tibble(
    age_group = c("10-19", "20-29", "30-39", "40-49", "50-59", "60-69", "70-79"),
    midpoint = c(15, 25, 35, 45, 55, 65, 75),
    prevalence_1975 = c(17, 14, 12, 10, NA, NA, NA),
    prevalence_1985 = c(28, 23, 19, 18, 15, NA, NA),
    prevalence_1995 = c(NA, 35, 30, 26, 22, 20, NA),
    prevalence_2005 = c(NA, NA, 45, 40, 36, 31, 27)
  )


df_tab_1_2 |>
  gt::gt() |>
  gt::tab_header(
    title = gt::md("**TABLE 1-2** Hypothetical data from a series of cross-sectional studies of prevalence of disease Y in a population, by age and survey date (calendar time), 1975–2005."),
  ) |>
  gt::cols_label(
    age_group = gt::md("**Age group<br>(years)**"),
    midpoint = gt::md("**Midpoint<br>(years)**"),
    prevalence_1975 = gt::md("**1975**"),
    prevalence_1985 = gt::md("**1985**"),
    prevalence_1995 = gt::md("**1995**"),
    prevalence_2005 = gt::md("**2005**")
  ) |>
  gt::cols_align(align = "left",
                 columns = age_group) |>
  gt::cols_align(
    align = "center",
    columns = c(
      midpoint,
      prevalence_1975,
      prevalence_1985,
      prevalence_1995,
      prevalence_2005
    )
  ) |>
  gt::tab_spanner(
    label = "Prevalence (per 1000)",
    columns = prevalence_1975:prevalence_2005
  ) |> 
  gt::tab_spanner(
    label = "Survey date",
    columns = prevalence_1975:prevalence_2005
  )
```

<table class="gt_table">
  <thead class="gt_header">
    <tr>
      <td colspan="6" class="gt_heading gt_title gt_font_normal gt_bottom_border" style><strong>TABLE 1-2</strong> Hypothetical data from a series of cross-sectional studies of prevalence of disease Y in a population, by age and survey date (calendar time), 1975–2005.</td>
    </tr>
    
  </thead>
  <thead class="gt_col_headings">
    <tr>
      <th class="gt_center gt_columns_top_border gt_column_spanner_outer" rowspan="1" colspan="2" scope="colgroup" id></th>
      <th class="gt_center gt_columns_top_border gt_column_spanner_outer" rowspan="1" colspan="4" scope="colgroup" id="Survey date">
        <span class="gt_column_spanner">Survey date</span>
      </th>
    </tr>
    <tr>
      <th class="gt_col_heading gt_columns_bottom_border gt_left" rowspan="2" colspan="1" scope="col" id="&lt;strong&gt;Age group&lt;br&gt;(years)&lt;/strong&gt;"><strong>Age group<br>(years)</strong></th>
      <th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="2" colspan="1" scope="col" id="&lt;strong&gt;Midpoint&lt;br&gt;(years)&lt;/strong&gt;"><strong>Midpoint<br>(years)</strong></th>
      <th class="gt_center gt_columns_top_border gt_column_spanner_outer" rowspan="1" colspan="4" scope="colgroup" id="Prevalence (per 1000)">
        <span class="gt_column_spanner">Prevalence (per 1000)</span>
      </th>
    </tr>
    <tr>
      <th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1" scope="col" id="&lt;strong&gt;1975&lt;/strong&gt;"><strong>1975</strong></th>
      <th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1" scope="col" id="&lt;strong&gt;1985&lt;/strong&gt;"><strong>1985</strong></th>
      <th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1" scope="col" id="&lt;strong&gt;1995&lt;/strong&gt;"><strong>1995</strong></th>
      <th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1" scope="col" id="&lt;strong&gt;2005&lt;/strong&gt;"><strong>2005</strong></th>
    </tr>
  </thead>
  <tbody class="gt_table_body">
    <tr><td headers="age_group" class="gt_row gt_left">10-19</td>
<td headers="midpoint" class="gt_row gt_center">15</td>
<td headers="prevalence_1975" class="gt_row gt_center">17</td>
<td headers="prevalence_1985" class="gt_row gt_center">28</td>
<td headers="prevalence_1995" class="gt_row gt_center">NA</td>
<td headers="prevalence_2005" class="gt_row gt_center">NA</td></tr>
    <tr><td headers="age_group" class="gt_row gt_left">20-29</td>
<td headers="midpoint" class="gt_row gt_center">25</td>
<td headers="prevalence_1975" class="gt_row gt_center">14</td>
<td headers="prevalence_1985" class="gt_row gt_center">23</td>
<td headers="prevalence_1995" class="gt_row gt_center">35</td>
<td headers="prevalence_2005" class="gt_row gt_center">NA</td></tr>
    <tr><td headers="age_group" class="gt_row gt_left">30-39</td>
<td headers="midpoint" class="gt_row gt_center">35</td>
<td headers="prevalence_1975" class="gt_row gt_center">12</td>
<td headers="prevalence_1985" class="gt_row gt_center">19</td>
<td headers="prevalence_1995" class="gt_row gt_center">30</td>
<td headers="prevalence_2005" class="gt_row gt_center">45</td></tr>
    <tr><td headers="age_group" class="gt_row gt_left">40-49</td>
<td headers="midpoint" class="gt_row gt_center">45</td>
<td headers="prevalence_1975" class="gt_row gt_center">10</td>
<td headers="prevalence_1985" class="gt_row gt_center">18</td>
<td headers="prevalence_1995" class="gt_row gt_center">26</td>
<td headers="prevalence_2005" class="gt_row gt_center">40</td></tr>
    <tr><td headers="age_group" class="gt_row gt_left">50-59</td>
<td headers="midpoint" class="gt_row gt_center">55</td>
<td headers="prevalence_1975" class="gt_row gt_center">NA</td>
<td headers="prevalence_1985" class="gt_row gt_center">15</td>
<td headers="prevalence_1995" class="gt_row gt_center">22</td>
<td headers="prevalence_2005" class="gt_row gt_center">36</td></tr>
    <tr><td headers="age_group" class="gt_row gt_left">60-69</td>
<td headers="midpoint" class="gt_row gt_center">65</td>
<td headers="prevalence_1975" class="gt_row gt_center">NA</td>
<td headers="prevalence_1985" class="gt_row gt_center">NA</td>
<td headers="prevalence_1995" class="gt_row gt_center">20</td>
<td headers="prevalence_2005" class="gt_row gt_center">31</td></tr>
    <tr><td headers="age_group" class="gt_row gt_left">70-79</td>
<td headers="midpoint" class="gt_row gt_center">75</td>
<td headers="prevalence_1975" class="gt_row gt_center">NA</td>
<td headers="prevalence_1985" class="gt_row gt_center">NA</td>
<td headers="prevalence_1995" class="gt_row gt_center">NA</td>
<td headers="prevalence_2005" class="gt_row gt_center">27</td></tr>
  </tbody>
  
  
</table>
</div>

<sup>Created on 2022-12-10 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by rich-iannone** [comment]
While you can't have a spanner column label below the column labels, it's possible to get a little creative with `tab_spanner()` and some styling to achieve the desired result. Here's what I came up with:

```r
library(gt)

df_tab_1_2 <-
  tibble::tibble(
    age_group = c("10-19", "20-29", "30-39", "40-49", "50-59", "60-69", "70-79"),
    midpoint = c(15, 25, 35, 45, 55, 65, 75),
    prevalence_1975 = c(17, 14, 12, 10, NA, NA, NA),
    prevalence_1985 = c(28, 23, 19, 18, 15, NA, NA),
    prevalence_1995 = c(NA, 35, 30, 26, 22, 20, NA),
    prevalence_2005 = c(NA, NA, 45, 40, 36, 31, 27)
  )

df_tab_1_2 <-
  df_tab_1_2 |>
  gt::gt() |>
  gt::tab_header(
    title = gt::md("**TABLE 1-2** Hypothetical data from a series of cross-sectional studies of prevalence of disease Y in a population, by age and survey date (calendar time), 1975–2005."),
  ) |>
  gt::cols_label(
    everything() ~ ""
  ) |>
  gt::cols_align(align = "left",
                 columns = age_group) |>
  gt::cols_align(
    align = "center",
    columns = c(
      midpoint,
      prevalence_1975,
      prevalence_1985,
      prevalence_1995,
      prevalence_2005
    )
  )

df_tab_1_2 |>
  gt::tab_spanner(
    label = md("**Prevalence (per 1000)**"),
    columns = prevalence_1975:prevalence_2005
  ) |> 
  gt::tab_spanner(
    label = gt::md("**1975**"),
    columns = prevalence_1975
  ) |>
  gt::tab_spanner(
    label = gt::md("**1985**"),
    columns = prevalence_1985
  ) |>
  gt::tab_spanner(
    label = gt::md("**1995**"),
    columns = prevalence_1995
  ) |>
  gt::tab_spanner(
    label = gt::md("**2005**"),
    columns = prevalence_2005
  ) |>
  gt::tab_spanner(
    label = gt::md("**Survey Date**"),
    columns = prevalence_1975:prevalence_2005
  ) |>
  gt::tab_spanner(
    label = gt::md("**Age group (years)**"),
    columns = age_group
  ) |>
  gt::tab_spanner(
    label = gt::md("**Midpoint (years)**"),
    columns = midpoint
  ) |>
  gt::tab_style(
    style = cell_borders(sides = "top", style = "hidden"),
    locations = cells_body(rows = 1)
  )
```

<img width="957" alt="tab-spanner-use" src="https://user-images.githubusercontent.com/5612024/228569354-21c7743f-3182-4194-8ce1-fa7c2b94b756.png">
