### ISSUE TITLE
Updates to `cols_merge()`

### ISSUE THREAD

**Issue by ddsjoberg** [rstudio/gt#1167]
Proposed updates to `cols_merge()`
- Add `cols_merge(rows=)` argument. Only columns and rows selected will merged. But we will need some sort of mechanism for handle default values
- Add `cols_merge(pattern_missing=)` argument. This would specify what the default value of the cell should be when the cell is not merged with others. A reasonable default value here would be an empty string (like how `<<>>` handles missing cells. We also would like to be able to add something like `cols_merge(pattern = "{1} ({2})", rows = !is.na(ci), pattern_missing="{1}")`

**Comment by rich-iannone** [comment]
Thanks for filing this issue Dan! These proposed update both make a lot of sense and this is all something I could get to working on quickly.
