### ISSUE TITLE
Rendering to html moves groupname_col to the top of the rendered html table

### ISSUE THREAD

**Issue by RicLouRiv** [rstudio/gt#1172]
## Prework

* [x] Read and agree to the [code of conduct](https://www.contributor-covenant.org/version/2/0/code_of_conduct/) and [contributing guidelines](https://github.com/rstudio/gt/blob/master/.github/CONTRIBUTING.md).
* [ ] If there is [already a relevant issue](https://github.com/rstudio/gt/issues), whether open or closed, comment on the existing thread instead of posting a new issue.
* [ ] Post a [minimal reproducible example](https://www.tidyverse.org/help/) so the maintainer can troubleshoot the problems you identify. A reproducible example is:
    * [ ] **Runnable**: post enough R code and data so any onlooker can create the error on their own computer.
    * [ ] **Minimal**: reduce runtime wherever possible and remove complicated details that are irrelevant to the issue at hand.
    * [ ] **Readable**: format your code according to the [tidyverse style guide](https://style.tidyverse.org/).

## Description

I'm trying to take a gt table with groupname and rowname columns set that renders beautifully in R Studio, but when I convert it to html, the groupname_cols vals get moved to the top and get all jammed together, and the other columns get moved to the left.

## Reproducible example

library(tidyverse)
library(gt)

gtcars %>%
  dplyr::select(mfr, model, year, hp, trq) %>%
  gt(
    rowname_col = "model",
    groupname_col = "mfr"
  ) %>%
  tab_options(
    row_group.as_column = TRUE
  ) %>%
  tab_style(
    style = list(
      cell_fill(color = rgb(106, 151, 212, maxColorValue = 255)),
      cell_text(
        color = "white",
        weight = "bold"
      )
    ),
    locations = cells_column_labels()
  ) %>%
  tab_style(
    style = list(
      cell_text(
        weight = "bold"
      )
    ),
    locations = cells_row_groups()
  ) %>%
  tab_style(
    style = list(
      cell_fill(color = rgb(219, 230, 245, maxColorValue = 255))
    ),
    locations = cells_body(
      columns = model
    )
  ) %>%
  as_raw_html() -> html

## Expected result

I'm trying to take a gt table with groupname and rowname columns set that renders beautifully in R Studio, but when I convert it to html, the groupname_cols vals get moved to the top and get all jammed together, and the other columns get moved to the left.

## Session info

End the reproducible example with a call to `sessionInfo()` in the same session (e.g. `reprex(session_info = TRUE)`) and include the output.

**Comment by rich-iannone** [comment]
I just tested this and works fine in my v0.8 version of gt. Could you update and try again? I know it was a problem before v0.8, which is why we worked on integrating {juicyjuice} (my own awesome package) to more correctly produce HTML with inlined styles.

**Comment by RicLouRiv** [comment]
Yes, updating worked!Sent from my iPhoneOn Dec 16, 2022, at 2:14 PM, Richard Iannone ***@***.***> wrote:﻿
I just tested this and works fine in my v0.8 version of gt. Could you update and try again? I know it was a problem before v0.8, which is why we worked on integrating {juicyjuice} (my own awesome package) to more correctly produce HTML with inlined styles.

**Comment by RicLouRiv** [comment]
Updating to v0.8 fixes the issue.
