### ISSUE TITLE
Reconsider choice of CSS inliner with system dependency on V8

### ISSUE THREAD

**Issue by joeroe** [rstudio/gt#1179]
#1114 switched to using the Javascript library [juice](https://github.com/Automattic/juice) (via [juicyjuice](https://github.com/rich-iannone/juicyjuice)) for CSS inlining. But this requires V8 (via [V8](https://github.com/jeroen/v8)), which is a gigantic system dependency for a relatively marginal feature. For example, it took almost an hour to compile it on Arch Linux, (8.0 GiB, i5-6200U × 4). For me this makes gt itself too heavy a dependency for e.g. research compendiums.

Some googling tells me there are a few options for CSS inlining libraries in other languages, e.g. [Python/Rust css-inliner](https://github.com/Stranger6667/css-inline), [Perl CSS::Inliner](). Otherwise, is is feasible to port juice (or the features needed) to R? Or at least make juicyjuice an optional dependency?

**Comment by nanxstats** [comment]
I would also add that V8 seeks to download a static build of libv8 from the internet at installation time, especially when the system libv8 version is lower than expected. Making it a hard dependency poses some challenges when deploying in an enterprise environment.

**Comment by rich-iannone** [comment]
Sorry for the problems this has caused. I agree now that V8 is a heavy dependency; I thought things had recently gotten better installation-wise but that's obviously not the case. The CSS-inlining feature is important for some specific (yet important) use cases but I can make `juicyjuice` an optional installation.

I'll make the necessary changes shortly and the hard dependency will be removed in the next CRAN release.

**Comment by joeroe** [comment]
31bacf23cfa95ab05834fa7613b56245df758c7f moved juicyjuice back to a hard dependency.

**Comment by viv-analytics** [comment]
Any chance that the proclaimed solution for v8 dependency from #1179 and #1229 issues would make it into the next release?

Currently, its a show-stopper on Suse Enterprise distributions.

**Comment by barracuda156** [comment]
Another vote in favor of getting rid of V8 dependency.

**Comment by nipnipj** [comment]
V8 is pain.
