### ISSUE TITLE
possible problem website's css

### ISSUE THREAD

**Issue by wibeasley** [rstudio/gt#118]
The package's website is displaying incorrectly probably?

![image](https://user-images.githubusercontent.com/1372890/50368924-6ff0fe80-0553-11e9-9fe6-6f4fdc69996f.png)

**Comment by rich-iannone** [comment]
The page looks pretty good to me (on all major browsers). Might just be a serving hiccup from gh-pages or a bad connection to the page. Please try it again and, if this persists, reopen the issue. Otherwise closing this now.
