### ISSUE TITLE
Issue with Quarto and table font size

### ISSUE THREAD

**Issue by ddsjoberg** [rstudio/gt#1183]
Hello! 🍁 

I noticed an issue when gt is rendered to HTML with Quarto that the table font size is not changed. I've attached a `*.qmd` and rendered HTML file. Also copied the pseudo qmd doc below with output.

This could be a duplicate of https://github.com/rstudio/gt/issues/1120 . If it is, apologies for the duplicate post!

[gt-example-quarto.zip](https://github.com/rstudio/gt/files/10373973/gt-example-quarto.zip)
````
---
title: "gt+Quarto font size"
format:
  html:
    embed-resources: true
---

## Quarto

Build a base table

```{r}
packageVersion("gt")

tbl <- 
  head(mtcars) |> 
  gt::gt()

tbl
```
````
![image](https://user-images.githubusercontent.com/26774684/211331658-81b44465-1740-4c9b-8d1f-65fc5d1a71b3.png)

Reduce the padding and font size.
But only padding is reduced, not the font size
````
```{r}
tbl |> 
  gt::tab_options(table.font.size = 13, data_row.padding = gt::px(1), 
    summary_row.padding = gt::px(1), grand_summary_row.padding = gt::px(1), 
    footnotes.padding = gt::px(1), source_notes.padding = gt::px(1), 
    row_group.padding = gt::px(1))
```
````
![image](https://user-images.githubusercontent.com/26774684/211331791-f5da2632-0763-480c-be98-d100a9a4f2c7.png)

Now add a call to `cols_width()`, and it all to works! The headers went from bold to not bold...
````
```{r}
tbl |> 
  gt::tab_options(table.font.size = 13, data_row.padding = gt::px(1), 
    summary_row.padding = gt::px(1), grand_summary_row.padding = gt::px(1), 
    footnotes.padding = gt::px(1), source_notes.padding = gt::px(1), 
    row_group.padding = gt::px(1)) |> 
  gt::cols_width(mpg ~ gt::px(50))
```

```` 
![image](https://user-images.githubusercontent.com/26774684/211331977-8678a21f-f20a-4d17-8786-19b2221e45ae.png)

**Comment by rich-iannone** [comment]
Now fixed in dev version!

**Comment by NEinterz** [comment]
Does this apply to .rmd files as well?
