### ISSUE TITLE
Possibility to create an `as_word()` function?

### ISSUE THREAD

**Issue by rich-iannone** [rstudio/gt#121]
Currently, we can only use the `rtf_document` format in R Markdown to generate a Word compatible document with **gt** tables embedded within.

Here is a minimal example:

````
---
output: rtf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(gt)
```

# gt Table in RTF document

```{r}
gtcars %>%
  dplyr::filter(ctry_origin == "Germany") %>%
  dplyr::group_by(mfr) %>%
  dplyr::top_n(2, msrp) %>%
  dplyr::ungroup() %>%
  dplyr::select(mfr, model, drivetrain, msrp) %>%
  gt()
```
````

Which produces this document:

<img width="932" alt="rtf_word_gt" src="https://user-images.githubusercontent.com/5612024/50659053-4bd8e880-0f69-11e9-987b-8e5ef28f99af.png">

The problem is that the `word_document` output format for R Markdown doesn't work in this way. Other packages that create display tables haven't yet solved this problem either. Proposal here is to generate a `as_word()` function to create table output that is compatible with the Word document output that R Markdown generates.

**Comment by rich-iannone** [comment]
The `kableExtra` package recommended (01-2018) that the way to get output tables into a Word document is to copy/paste HTML table output from the Viewer directly into an open Word doc. 

Another option is to just use the `rtf_output` format that opens in Word (as an RTF file, which could then be saved as a .docx file, for instance).

The `knitr::kable()` function is able to produce native table code for Word documents, and, the pander package also has this capability (with more options for table output). Here is a document that describes how: https://rmarkdown.rstudio.com/articles_docx.html.

**Comment by jianli4** [comment]
Hi Richard, thanks for your awesome work. It will be fantastic if as_word() function can come in the near future! I wonder if section break (\sect) or other similar formatting features can be added to the as_rtf/as_word function?

**Comment by ABSOD** [comment]
Hi Richard,
I want to support the development of tools to output gt objects to a word format.  I have a Shiny App that produces tables in a *.docx file so my users can incorporate a table into their documents.  as_rtf doesn't work in my context.  My current Shiny App uses flextable and officer.  However, I need to support three separate table formats (HTML and Latex via kable and Word via flextable) to give my users the capabilities they need.  Using gt has the potential of really simplifying my app.  I need it to be more capable before I can move it into production.

**Comment by elong0527** [comment]
@ABSOD , just my one bullet of think. Did you try pandoc tool to transfer .rtf to .docx ? 

I assume the new AST format should be able to use. 

https://pandoc.org/MANUAL.html

if this works, as_word could be a simple wrap up after of as_rtf with pandoc command.

**Comment by rpodcast** [comment]
I want to mention that I found out (literally a few minutes ago) that our pipelines at work for producing results will be eventually moving to `docx` output files for tables and listings, so I'm certainly hoping that down the road we can get that as a new output format too.

**Comment by JaneWall** [comment]
Any suggestion on how to get the table width to be wider so the rows are not split?  In the example above, Mercedes-Benz and Porsche as well as the numbers run to multiple lines.

**Comment by mzobeck** [comment]
Bumping this. Blown away by the functionality of `gt`, but this is a critical piece of missing functionality that breaks up my workflow.

**Comment by kkmann** [comment]
Any progress towards table-making in word ? x) 

It is really to bad that collaborators tend to love .docx (ok, it has gotten better over the years) and it is still so hard to programmatically create nice word files... What is the main painpoint for making that work with gt?

**Comment by Saadi4469** [comment]
Any update on this?

**Comment by bwiernik** [comment]
Would outputting rtf formatted tables when rendering a Word document be a reasonable stopgap measure until fuller support for Word could be implemented?

**Comment by rich-iannone** [comment]
@bwiernik that seems reasonable. And, as an update, there is a PR now that that is focused on actual Word output (e.g., can be used in the R Markdown `word_output` format). It's pretty far along but won't be included in the release. However, you can definitely try it out by using `devtools::install_github("rstudio/gt@w-tbl-exp")`.

**Comment by jestarr** [comment]
Same here.  I tried the new branch, and it didn't work for me either.

**Comment by andrewbaxter439** [comment]
As a small update on this - it also fails for & in rendering. But replacing <,> and & with `&lt;` `&gt;` and `&amp;` can be a workaround in the meantime.

**Comment by rich-iannone** [comment]
Now done, thanks to @thebioengineer in https://github.com/rstudio/gt/pull/811. There’s an open PR to solve the last problem (thanks again, Ellis!).

**Comment by torfason** [comment]
This is awesome, great!

Just one note, I had a very weird experience when I was checking out the issue reported by @andrewbaxter439. When I tried to render the following document, I do not get an error, but Skype gets launched with a dialog to share the document(!) :

    ---
    title: "Untitled"
    output:
      word_document: default
      html_document:
        df_print: paged
    date: "2022-08-21"
    ---
    
    ```{r}
    library(gt)
    library(tidyverse)
    tibble(`a` = c("<", "b"),
           b = 1:2) %>% 
      gt()
    ```

This implies that arbitrary word code sequences could be injected when rendering markdown into word without escaping control characters. So whatever is done in terms of escaping control character is not only a matter of preventing corrupted documents but about security. So great that a fix is in sight.

(If I replace the `<` in th above example with, for example an `x` the document is correctly rendered, suggesting that this is very specific to the inclusion of `<`)

**Comment by thebioengineer** [comment]
Wow, I did not get that sort of response when I was testing, and it's a surprising find!

 I've added code in the latest PR to escape those sorts of characters through htmlEscape to convert potentially sensitive symbols.

**Comment by wzbillings** [comment]
This works for me for `word_document` output, but not for `bookdown::word_document2` output. However, it does work for me in a quarto doc with `format: docx`.

Are there plans to implement this for bookdown documents or is moving to quarto the best solution if I need some of the bookdown features?
