### ISSUE TITLE
gtsave to accept lists for pagination V1

### ISSUE THREAD

**Issue by thebioengineer** [rstudio/gt#1211]
## Prework

- [x] Read and abide by **gt**'s [code of conduct](https://www.contributor-covenant.org/version/2/0/code_of_conduct/) and [contributing guidelines](https://github.com/rstudio/gt/blob/master/.github/CONTRIBUTING.md).
- [x] Search for duplicates among the [existing issues](https://github.com/rstudio/gt/issues) (both open and closed).

## Proposal

Describe the new feature clearly and concisely. If applicable, write a minimal example in R code or pseudo-code to show input, usage, and desired output.

This is a suggestion to allow gtsave to accept a list of gts (and perhaps some meta information such as entries into tab_options or special titles, etc too?) to created paginated reports of gts. This is mainly useful for the rtf, word, and pdf outputs, but I can see it being useful for all the outputs to be able to generate multiple tables in one go to a single document.

This is to support work going towards pagination & was previously discussed with @rich-iannone 

An example of how this might look code wise is:

```{r}

## tables by car make

library(tidyverse)
library(gt)

gtcars |>
 group_split(mfr) |>
 map(function(x){
  x |>
   select(-mfr) |>
   gt() |>
   tab_caption(paste("Cars by",unique(x$mfr))
 }) |>
 gtsave("tables_by_mfr.pdf")

```

**Comment by rich-iannone** [comment]
I think this part of pagination effort is now considered done (starting from https://github.com/rstudio/gt/pull/1216 and with several refinement PRs).
