### ISSUE TITLE
`sub_small_vals` only replaces non-zero values 

### ISSUE THREAD

**Issue by ajb5d** [rstudio/gt#1228]
## Prework

* [x] Read and agree to the [code of conduct](https://www.contributor-covenant.org/version/2/0/code_of_conduct/) and [contributing guidelines](https://github.com/rstudio/gt/blob/master/.github/CONTRIBUTING.md).
* [x] If there is [already a relevant issue](https://github.com/rstudio/gt/issues), whether open or closed, comment on the existing thread instead of posting a new issue.
* [x] Post a [minimal reproducible example](https://www.tidyverse.org/help/) so the maintainer can troubleshoot the problems you identify. A reproducible example is:
    * [x] **Runnable**: post enough R code and data so any onlooker can create the error on their own computer.
    * [x] **Minimal**: reduce runtime wherever possible and remove complicated details that are irrelevant to the issue at hand.
    * [x] **Readable**: format your code according to the [tidyverse style guide](https://style.tidyverse.org/).

## Description

`sub_small_vals()` replaces values that are smaller than a threshold _but non-zero_. This is depicted in the documentation examples but is not described anywhere else. I use `sub_small_vals()` to format p values an occasionally a very (very, very) small P value is returned as zero. 

I'm happy to supply a PR to either adjust the documentation or add an argument to `sub_small_vals()` to include zero values as small values (i.e. `include_zero=TRUE`)

## Reproducible example

From the `sub_small_vals()` documentation:

``` r
library(gt)

tbl <- dplyr::tibble(num = c(10^(-4:2), 0, NA))

tbl %>%
  gt() %>%
  fmt_number(columns = num) %>%
  sub_small_vals()
```

<table class="gt_table">
  
  <thead class="gt_col_headings">
    <tr>
      <th class="gt_col_heading gt_columns_bottom_border gt_right" rowspan="1" colspan="1" scope="col" id="num">num</th>
    </tr>
  </thead>
  <tbody class="gt_table_body">
    <tr><td headers="num" class="gt_row gt_right">&lt;0.01</td></tr>
    <tr><td headers="num" class="gt_row gt_right">&lt;0.01</td></tr>
    <tr><td headers="num" class="gt_row gt_right">0.01</td></tr>
    <tr><td headers="num" class="gt_row gt_right">0.10</td></tr>
    <tr><td headers="num" class="gt_row gt_right">1.00</td></tr>
    <tr><td headers="num" class="gt_row gt_right">10.00</td></tr>
    <tr><td headers="num" class="gt_row gt_right">100.00</td></tr>
    <tr><td headers="num" class="gt_row gt_right">0.00</td></tr>
    <tr><td headers="num" class="gt_row gt_right">NA</td></tr>
  </tbody>
  
  
</table>
</div>

<sup>Created on 2023-02-27 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

<details style="margin-bottom:10px;">
<summary>
Session info
</summary>

``` r
sessioninfo::session_info()
#> ─ Session info ───────────────────────────────────────────────────────────────
#>  setting  value
#>  version  R version 4.2.2 (2022-10-31)
#>  os       macOS Ventura 13.2.1
#>  system   aarch64, darwin20
#>  ui       X11
#>  language (EN)
#>  collate  en_US.UTF-8
#>  ctype    en_US.UTF-8
#>  tz       America/New_York
#>  date     2023-02-27
#>  pandoc   2.19.2 @ /Applications/RStudio.app/Contents/Resources/app/quarto/bin/tools/ (via rmarkdown)
#> 
#> ─ Packages ───────────────────────────────────────────────────────────────────
#>  package     * version date (UTC) lib source
#>  cli           3.6.0   2023-01-09 [1] CRAN (R 4.2.0)
#>  colorspace    2.1-0   2023-01-23 [1] CRAN (R 4.2.0)
#>  digest        0.6.31  2022-12-11 [1] CRAN (R 4.2.0)
#>  dplyr         1.1.0   2023-01-29 [1] CRAN (R 4.2.0)
#>  evaluate      0.20    2023-01-17 [1] CRAN (R 4.2.0)
#>  fansi         1.0.4   2023-01-22 [1] CRAN (R 4.2.0)
#>  fastmap       1.1.0   2021-01-25 [1] CRAN (R 4.2.0)
#>  fs            1.6.1   2023-02-06 [1] CRAN (R 4.2.0)
#>  generics      0.1.3   2022-07-05 [1] CRAN (R 4.2.0)
#>  ggplot2       3.4.1   2023-02-10 [1] CRAN (R 4.2.0)
#>  glue          1.6.2   2022-02-24 [1] CRAN (R 4.2.0)
#>  gt          * 0.8.0   2022-11-16 [1] CRAN (R 4.2.0)
#>  gtable        0.3.1   2022-09-01 [1] CRAN (R 4.2.0)
#>  htmltools     0.5.4   2022-12-07 [1] CRAN (R 4.2.0)
#>  knitr         1.42    2023-01-25 [1] CRAN (R 4.2.0)
#>  lifecycle     1.0.3   2022-10-07 [1] CRAN (R 4.2.0)
#>  magrittr      2.0.3   2022-03-30 [1] CRAN (R 4.2.0)
#>  munsell       0.5.0   2018-06-12 [1] CRAN (R 4.2.0)
#>  pillar        1.8.1   2022-08-19 [1] CRAN (R 4.2.0)
#>  pkgconfig     2.0.3   2019-09-22 [1] CRAN (R 4.2.0)
#>  purrr         1.0.1   2023-01-10 [1] CRAN (R 4.2.0)
#>  R.cache       0.16.0  2022-07-21 [1] CRAN (R 4.2.0)
#>  R.methodsS3   1.8.2   2022-06-13 [1] CRAN (R 4.2.0)
#>  R.oo          1.25.0  2022-06-12 [1] CRAN (R 4.2.0)
#>  R.utils       2.12.2  2022-11-11 [1] CRAN (R 4.2.0)
#>  R6            2.5.1   2021-08-19 [1] CRAN (R 4.2.0)
#>  reprex        2.0.2   2022-08-17 [1] CRAN (R 4.2.0)
#>  rlang         1.0.6   2022-09-24 [1] CRAN (R 4.2.0)
#>  rmarkdown     2.20    2023-01-19 [1] CRAN (R 4.2.0)
#>  rstudioapi    0.14    2022-08-22 [1] CRAN (R 4.2.0)
#>  sass          0.4.5   2023-01-24 [1] CRAN (R 4.2.0)
#>  scales        1.2.1   2022-08-20 [1] CRAN (R 4.2.0)
#>  sessioninfo   1.2.2   2021-12-06 [1] CRAN (R 4.2.0)
#>  styler        1.9.0   2023-01-15 [1] CRAN (R 4.2.0)
#>  tibble        3.1.8   2022-07-22 [1] CRAN (R 4.2.0)
#>  tidyselect    1.2.0   2022-10-10 [1] CRAN (R 4.2.0)
#>  utf8          1.2.3   2023-01-31 [1] CRAN (R 4.2.0)
#>  vctrs         0.5.2   2023-01-23 [1] CRAN (R 4.2.0)
#>  withr         2.5.0   2022-03-03 [1] CRAN (R 4.2.0)
#>  xfun          0.37    2023-01-31 [1] CRAN (R 4.2.0)
#>  yaml          2.3.7   2023-01-23 [1] CRAN (R 4.2.0)
#> 
#>  [1] /Library/Frameworks/R.framework/Versions/4.2-arm64/Resources/library
#> 
#> ──────────────────────────────────────────────────────────────────────────────
```

</details>

* [x] Post a [minimal reproducible example](https://www.tidyverse.org/help/) so the maintainer can troubleshoot the problems you identify. A reproducible example is:
    * [x] **Runnable**: post enough R code and data so any onlooker can create the error on their own computer.
    * [x] **Minimal**: reduce runtime wherever possible and remove complicated details that are irrelevant to the issue at hand.
    * [x] **Readable**: format your code according to the [tidyverse style guide](https://style.tidyverse.org/).

## Expected result

Zero should also be replaced with <0.01 (or the documentation should be explicit that it only replaces small, non-zero values).

<table class="gt_table">
  
  <thead class="gt_col_headings">
    <tr>
      <th class="gt_col_heading gt_columns_bottom_border gt_right" rowspan="1" colspan="1" scope="col" id="num">num</th>
    </tr>
  </thead>
  <tbody class="gt_table_body">
    <tr><td headers="num" class="gt_row gt_right">&lt;0.01</td></tr>
    <tr><td headers="num" class="gt_row gt_right">&lt;0.01</td></tr>
    <tr><td headers="num" class="gt_row gt_right">0.01</td></tr>
    <tr><td headers="num" class="gt_row gt_right">0.10</td></tr>
    <tr><td headers="num" class="gt_row gt_right">1.00</td></tr>
    <tr><td headers="num" class="gt_row gt_right">10.00</td></tr>
    <tr><td headers="num" class="gt_row gt_right">100.00</td></tr>
    <tr><td headers="num" class="gt_row gt_right">&lt;0.01</td></tr>
    <tr><td headers="num" class="gt_row gt_right">NA</td></tr>
  </tbody>
  
  
</table>
</div>

## Session info

End the reproducible example with a call to `sessionInfo()` in the same session (e.g. `reprex(session_info = TRUE)`) and include the output.

**Comment by rich-iannone** [comment]
Thanks for reporting this! This is definitely on purpose (the avoidance of substituting zero values). I can definitely clarify this in the documentation of this function.

**Comment by rich-iannone** [comment]
I'd like to only fix the documentation to better clarify the interval. Adding an argument of that type will cause some issues and it seems better anyway to have a separation of concerns between `sub_small_vals()` and `sub_zero()`. As a workaround, I think it's possible to wrap both of those functions into a custom function.
