### ISSUE TITLE
Grouping broken?

### ISSUE THREAD

**Issue by garthtarr** [rstudio/gt#124]
Love this package.

I think these should give the same grouping result (and I'm pretty sure they used to, e.g. e6af6440f0fc5a25658b4da678840c632d06e4cf does work) but they no longer do:

```r
 exibble %>%
  gt(
    rowname_col = "row",
    groupname_col = "group"
  )

exibble %>% group_by(group) %>% 
  gt(
    rowname_col = "row"
  )
```

**Comment by rich-iannone** [comment]
Fixed by #125.
