### ISSUE TITLE
Not able to add footnote to row label if using rowname_col option

### ISSUE THREAD

**Issue by szimmer** [rstudio/gt#1259]
## Prework

* [x ] Read and agree to the [code of conduct](https://www.contributor-covenant.org/version/2/1/code_of_conduct.html) and [contributing guidelines](https://github.com/rstudio/gt/blob/master/.github/CONTRIBUTING.md).
* [x ] If there is [already a relevant issue](https://github.com/rstudio/gt/issues), whether open or closed, comment on the existing thread instead of posting a new issue.

## Description

I am trying to add some footnotes to just some row labels but this doesn't work when I use the option rowname_col. Below I show an example with and without this option

## Reproducible example

* [x ] Post a [minimal reproducible example](https://www.tidyverse.org/help/) so the maintainer can troubleshoot the problems you identify. A reproducible example is:
    * [x] **Runnable**: post enough R code and data so any onlooker can create the error on their own computer.
    * [x ] **Minimal**: reduce runtime wherever possible and remove complicated details that are irrelevant to the issue at hand.
    * [x ] **Readable**: format your code according to the [tidyverse style guide](https://style.tidyverse.org/).

``` r
library(gt)
library(tidyverse)

pizzaplace %>%
  filter(type %in% c("chicken", "veggie")) %>%
  group_by(type, name) %>%
  summarise(total_sales = sum(price), .groups="drop_last") %>%
  gt() %>%
  tab_footnote(
    footnote="Cheese is my favorite",
    locations=cells_body(
      columns=name,
      rows= name %in% c("five_cheese", "four_cheese")
    )
  )
```

<table class="gt_table">
  
  <thead class="gt_col_headings">
    <tr>
      <th class="gt_col_heading gt_columns_bottom_border gt_left" rowspan="1" colspan="1" scope="col">name</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_right" rowspan="1" colspan="1" scope="col">total_sales</th>
    </tr>
  </thead>
  <tbody class="gt_table_body">
    <tr class="gt_group_heading_row">
      <td colspan="2" class="gt_group_heading">chicken</td>
    </tr>
    <tr class="gt_row_group_first"><td class="gt_row gt_left">bbq_ckn</td>
<td class="gt_row gt_right">42768.00</td></tr>
    <tr><td class="gt_row gt_left">cali_ckn</td>
<td class="gt_row gt_right">41409.50</td></tr>
    <tr><td class="gt_row gt_left">ckn_alfredo</td>
<td class="gt_row gt_right">16900.25</td></tr>
    <tr><td class="gt_row gt_left">ckn_pesto</td>
<td class="gt_row gt_right">16701.75</td></tr>
    <tr><td class="gt_row gt_left">southw_ckn</td>
<td class="gt_row gt_right">34705.75</td></tr>
    <tr><td class="gt_row gt_left">thai_ckn</td>
<td class="gt_row gt_right">43434.25</td></tr>
    <tr class="gt_group_heading_row">
      <td colspan="2" class="gt_group_heading">veggie</td>
    </tr>
    <tr class="gt_row_group_first"><td class="gt_row gt_left">five_cheese<sup class="gt_footnote_marks">1</sup></td>
<td class="gt_row gt_right">26066.50</td></tr>
    <tr><td class="gt_row gt_left">four_cheese<sup class="gt_footnote_marks">1</sup></td>
<td class="gt_row gt_right">32265.70</td></tr>
    <tr><td class="gt_row gt_left">green_garden</td>
<td class="gt_row gt_right">13955.75</td></tr>
    <tr><td class="gt_row gt_left">ital_veggie</td>
<td class="gt_row gt_right">16019.25</td></tr>
    <tr><td class="gt_row gt_left">mediterraneo</td>
<td class="gt_row gt_right">15360.50</td></tr>
    <tr><td class="gt_row gt_left">mexicana</td>
<td class="gt_row gt_right">26780.75</td></tr>
    <tr><td class="gt_row gt_left">spin_pesto</td>
<td class="gt_row gt_right">15596.00</td></tr>
    <tr><td class="gt_row gt_left">spinach_fet</td>
<td class="gt_row gt_right">23271.25</td></tr>
    <tr><td class="gt_row gt_left">veggie_veg</td>
<td class="gt_row gt_right">24374.75</td></tr>
  </tbody>
  
  <tfoot class="gt_footnotes">
    <tr>
      <td class="gt_footnote" colspan="2"><sup class="gt_footnote_marks">1</sup> Cheese is my favorite</td>
    </tr>
  </tfoot>
</table>
</div>

```r
pizzaplace %>%
  filter(type %in% c("chicken", "veggie")) %>%
  group_by(type, name) %>%
  summarise(total_sales = sum(price), .groups="drop_last") %>%
  gt(rowname_col = "name") %>%
  tab_footnote(
    footnote="Cheese is my favorite",
    locations=cells_body(
      columns=name,
      rows= name %in% c("five_cheese", "four_cheese")
    )
  )
```

<table class="gt_table">
  
  <thead class="gt_col_headings">
    <tr>
      <th class="gt_col_heading gt_columns_bottom_border gt_left" rowspan="1" colspan="1" scope="col"></th>
      <th class="gt_col_heading gt_columns_bottom_border gt_right" rowspan="1" colspan="1" scope="col">total_sales</th>
    </tr>
  </thead>
  <tbody class="gt_table_body">
    <tr class="gt_group_heading_row">
      <td colspan="2" class="gt_group_heading">chicken</td>
    </tr>
    <tr class="gt_row_group_first"><th scope="row" class="gt_row gt_left gt_stub">bbq_ckn</th>
<td class="gt_row gt_right">42768.00</td></tr>
    <tr><th scope="row" class="gt_row gt_left gt_stub">cali_ckn</th>
<td class="gt_row gt_right">41409.50</td></tr>
    <tr><th scope="row" class="gt_row gt_left gt_stub">ckn_alfredo</th>
<td class="gt_row gt_right">16900.25</td></tr>
    <tr><th scope="row" class="gt_row gt_left gt_stub">ckn_pesto</th>
<td class="gt_row gt_right">16701.75</td></tr>
    <tr><th scope="row" class="gt_row gt_left gt_stub">southw_ckn</th>
<td class="gt_row gt_right">34705.75</td></tr>
    <tr><th scope="row" class="gt_row gt_left gt_stub">thai_ckn</th>
<td class="gt_row gt_right">43434.25</td></tr>
    <tr class="gt_group_heading_row">
      <td colspan="2" class="gt_group_heading">veggie</td>
    </tr>
    <tr class="gt_row_group_first"><th scope="row" class="gt_row gt_left gt_stub">five_cheese</th>
<td class="gt_row gt_right">26066.50</td></tr>
    <tr><th scope="row" class="gt_row gt_left gt_stub">four_cheese</th>
<td class="gt_row gt_right">32265.70</td></tr>
    <tr><th scope="row" class="gt_row gt_left gt_stub">green_garden</th>
<td class="gt_row gt_right">13955.75</td></tr>
    <tr><th scope="row" class="gt_row gt_left gt_stub">ital_veggie</th>
<td class="gt_row gt_right">16019.25</td></tr>
    <tr><th scope="row" class="gt_row gt_left gt_stub">mediterraneo</th>
<td class="gt_row gt_right">15360.50</td></tr>
    <tr><th scope="row" class="gt_row gt_left gt_stub">mexicana</th>
<td class="gt_row gt_right">26780.75</td></tr>
    <tr><th scope="row" class="gt_row gt_left gt_stub">spin_pesto</th>
<td class="gt_row gt_right">15596.00</td></tr>
    <tr><th scope="row" class="gt_row gt_left gt_stub">spinach_fet</th>
<td class="gt_row gt_right">23271.25</td></tr>
    <tr><th scope="row" class="gt_row gt_left gt_stub">veggie_veg</th>
<td class="gt_row gt_right">24374.75</td></tr>
  </tbody>
  
  
</table>
</div>

<sup>Created on 2023-03-19 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

<details style="margin-bottom:10px;">
<summary>
Session info
</summary>

``` r
sessioninfo::session_info()
#> ─ Session info ───────────────────────────────────────────────────────────────
#>  setting  value
#>  version  R version 4.2.2 (2022-10-31 ucrt)
#>  os       Windows 10 x64 (build 22621)
#>  system   x86_64, mingw32
#>  ui       RTerm
#>  language (EN)
#>  collate  English_United States.utf8
#>  ctype    English_United States.utf8
#>  tz       America/New_York
#>  date     2023-03-19
#>  pandoc   2.19.2 @ C:/Program Files/RStudio/resources/app/bin/quarto/bin/tools/ (via rmarkdown)
#> 
#> ─ Packages ───────────────────────────────────────────────────────────────────
#>  package       * version date (UTC) lib source
#>  assertthat      0.2.1   2019-03-21 [1] CRAN (R 4.2.1)
#>  backports       1.4.1   2021-12-13 [1] CRAN (R 4.2.0)
#>  broom           1.0.2   2022-12-15 [1] CRAN (R 4.2.2)
#>  cellranger      1.1.0   2016-07-27 [1] CRAN (R 4.2.1)
#>  cli             3.4.1   2022-09-23 [1] CRAN (R 4.2.2)
#>  colorspace      2.0-3   2022-02-21 [1] CRAN (R 4.2.1)
#>  crayon          1.5.2   2022-09-29 [1] CRAN (R 4.2.2)
#>  DBI             1.1.3   2022-06-18 [1] CRAN (R 4.2.1)
#>  dbplyr          2.2.1   2022-06-27 [1] CRAN (R 4.2.1)
#>  digest          0.6.29  2021-12-01 [1] CRAN (R 4.2.1)
#>  dplyr         * 1.1.0   2023-01-29 [1] CRAN (R 4.2.2)
#>  ellipsis        0.3.2   2021-04-29 [1] CRAN (R 4.2.1)
#>  evaluate        0.16    2022-08-09 [1] CRAN (R 4.2.1)
#>  fansi           1.0.4   2023-01-22 [1] CRAN (R 4.2.2)
#>  fastmap         1.1.0   2021-01-25 [1] CRAN (R 4.2.1)
#>  forcats       * 0.5.2   2022-08-19 [1] CRAN (R 4.2.1)
#>  fs              1.5.2   2021-12-08 [1] CRAN (R 4.2.1)
#>  gargle          1.2.0   2021-07-02 [1] CRAN (R 4.2.1)
#>  generics        0.1.3   2022-07-05 [1] CRAN (R 4.2.1)
#>  ggplot2       * 3.4.0   2022-11-04 [1] CRAN (R 4.2.2)
#>  glue            1.6.2   2022-02-24 [1] CRAN (R 4.2.1)
#>  googledrive     2.0.0   2021-07-08 [1] CRAN (R 4.2.1)
#>  googlesheets4   1.0.1   2022-08-13 [1] CRAN (R 4.2.1)
#>  gt            * 0.7.0   2022-08-25 [1] CRAN (R 4.2.1)
#>  gtable          0.3.0   2019-03-25 [1] CRAN (R 4.2.1)
#>  haven           2.5.1   2022-08-22 [1] CRAN (R 4.2.1)
#>  highr           0.9     2021-04-16 [1] CRAN (R 4.2.1)
#>  hms             1.1.2   2022-08-19 [1] CRAN (R 4.2.1)
#>  htmltools       0.5.3   2022-07-18 [1] CRAN (R 4.2.1)
#>  httr            1.4.4   2022-08-17 [1] CRAN (R 4.2.1)
#>  jsonlite        1.8.4   2022-12-06 [1] CRAN (R 4.2.2)
#>  knitr           1.40    2022-08-24 [1] CRAN (R 4.2.1)
#>  lifecycle       1.0.3   2022-10-07 [1] CRAN (R 4.2.2)
#>  lubridate       1.9.0   2022-11-06 [1] CRAN (R 4.2.2)
#>  magrittr        2.0.3   2022-03-30 [1] CRAN (R 4.2.1)
#>  modelr          0.1.10  2022-11-11 [1] CRAN (R 4.2.2)
#>  munsell         0.5.0   2018-06-12 [1] CRAN (R 4.2.1)
#>  pillar          1.8.1   2022-08-19 [1] CRAN (R 4.2.1)
#>  pkgconfig       2.0.3   2019-09-22 [1] CRAN (R 4.2.1)
#>  purrr         * 0.3.5   2022-10-06 [1] CRAN (R 4.2.1)
#>  R.cache         0.16.0  2022-07-21 [1] CRAN (R 4.2.1)
#>  R.methodsS3     1.8.2   2022-06-13 [1] CRAN (R 4.2.0)
#>  R.oo            1.25.0  2022-06-12 [1] CRAN (R 4.2.0)
#>  R.utils         2.12.0  2022-06-28 [1] CRAN (R 4.2.1)
#>  R6              2.5.1   2021-08-19 [1] CRAN (R 4.2.1)
#>  readr         * 2.1.4   2023-02-10 [1] CRAN (R 4.2.2)
#>  readxl          1.4.1   2022-08-17 [1] CRAN (R 4.2.1)
#>  reprex          2.0.2   2022-08-17 [1] CRAN (R 4.2.1)
#>  rlang           1.0.6   2022-09-24 [1] CRAN (R 4.2.1)
#>  rmarkdown       2.16    2022-08-24 [1] CRAN (R 4.2.1)
#>  rstudioapi      0.13    2020-11-12 [1] CRAN (R 4.2.1)
#>  rvest           1.0.3   2022-08-19 [1] CRAN (R 4.2.1)
#>  sass            0.4.2   2022-07-16 [1] CRAN (R 4.2.1)
#>  scales          1.2.0   2022-04-13 [1] CRAN (R 4.2.1)
#>  sessioninfo     1.2.2   2021-12-06 [1] CRAN (R 4.2.1)
#>  stringi         1.7.8   2022-07-11 [1] CRAN (R 4.2.1)
#>  stringr       * 1.4.1   2022-08-20 [1] CRAN (R 4.2.1)
#>  styler          1.7.0   2022-03-13 [1] CRAN (R 4.2.1)
#>  tibble        * 3.2.0   2023-03-08 [1] CRAN (R 4.2.2)
#>  tidyr         * 1.2.1   2022-09-08 [1] CRAN (R 4.2.1)
#>  tidyselect      1.2.0   2022-10-10 [1] CRAN (R 4.2.2)
#>  tidyverse     * 1.3.2   2022-07-18 [1] CRAN (R 4.2.1)
#>  timechange      0.1.1   2022-11-04 [1] CRAN (R 4.2.2)
#>  tzdb            0.3.0   2022-03-28 [1] CRAN (R 4.2.1)
#>  utf8            1.2.3   2023-01-31 [1] CRAN (R 4.2.2)
#>  vctrs           0.5.2   2023-01-23 [1] CRAN (R 4.2.2)
#>  withr           2.5.0   2022-03-03 [1] CRAN (R 4.2.1)
#>  xfun            0.32    2022-08-10 [1] CRAN (R 4.2.1)
#>  xml2            1.3.3   2021-11-30 [1] CRAN (R 4.2.1)
#>  yaml            2.3.5   2022-02-21 [1] CRAN (R 4.2.1)
#> 
#>  [1] C:/Users/steph/AppData/Local/R/win-library/4.2
#>  [2] C:/Program Files/R/R-4.2.2/library
#> 
#> ──────────────────────────────────────────────────────────────────────────────
```

</details>

## Expected result

Expect a footnote in second table as well to appear on five_cheese and four_cheese lines.

## Session info

See above

**Comment by rich-iannone** [comment]
Sorry for the trouble here. The solution is to use `cells_stub()` in place of `cells_body()`. Though now I think both should be allowed to work (future improvement!).
