### ISSUE TITLE
Row Group Labels: Should be spanning the entire table (or have an option to enable it)

### ISSUE THREAD

**Issue by r-cheologist** [rstudio/gt#128]
It's customary to have verbose row group labels (as one conceptually has the whole table width to work with in terms of horizontal space).

At least in the context of `mydataframe %>% gt::gt(groupname_col = '<SOMECOLUMN>')` and `bookdown`-mediated output to `LaTeX`/`PDF`, however, this currently does not work and the group labels only occupy the first column, potentially rendering it overly wide.

Consider:

    ---
    title: Bug Report
    subtitle: Non--Spanning Row Group Labels
    date: '`r format(Sys.time(), "%d %B, %Y")`'
    author: r-cheologist
    output:
      bookdown::pdf_document2
    ---
    
    ```{r prerequisites, message = FALSE}
    library(magrittr)
    requireNamespace('gt')
    ```
    
    ```{r table}
    data.frame(
      A      = 1:5,
      B      = rep('Longer than longish group label', times = 5),
      groups = c(
        rep('Longish group label', times = 2),
        rep('Label', times = 3))) %>%
      gt::gt(groupname_col = 'groups')
    ```
which gives rise to ![this](https://user-images.githubusercontent.com/3259333/50851420-107d5600-137d-11e9-9631-262580ad5796.png) ...

**Comment by peterparkerspicklepatch** [comment]
Yup, this is a great feature addition and what I'm looking for! Having a group span the space of the relevant rows provides the same value as spanner column labels.

**Comment by rich-iannone** [comment]
Now addressed in a recent commit. Will be in the CRAN v0.7.0 release of gt soon.

**Comment by peterparkerspicklepatch** [comment]
Is this real life? H-Y-P-E

**Comment by sanjmeh** [comment]
Rich you are doing a fantastic job. The gt() package is so intuitive. Waiting for this and the row spanners to be activated.

**Comment by rich-iannone** [comment]
Thank you @sanjmeh , very nice of you to say!
