### ISSUE TITLE
Request: mark NSE-friendly functions in documentation

### ISSUE THREAD

**Issue by MichaelChirico** [rstudio/gt#1290]
I maintain some metaprogramming tools that need to be NSE-aware to avoid flagging code with spurious "undefined objects" warnings from `codetools::checkUsage()`.

For tidyr and dplyr, I can search the documentation for certain links to get a good head start on which functions are NSE-friendly,

e.g. tidyr might use `<tidy-select>`:

![cols= argument of tidyr::pivot longer is described as "<tidy-select> Columns to pivot into longer format."](https://user-images.githubusercontent.com/7606389/229330894-457c60e3-bfad-4d89-939d-632e60975f09.png)

https://github.com/tidyverse/tidyr/blob/0764e65fad777b71aa2a81ffd5447d04a61f8d5e/R/pivot-long.R#L17-L18

Would it make sense for {gt} to offer similar hints in the documentation about where NSE might show up in its calls?

**Comment by rich-iannone** [comment]
Makes perfect sense! I think it's a good idea and one we'll get to for the next release.

**Comment by rich-iannone** [comment]
We now have something akin to this for every exported function (check out https://gt.rstudio.com/reference/data_color.html for an example). Closing this now.
