### ISSUE TITLE
problem installing gt

### ISSUE THREAD

**Issue by arhall1** [rstudio/gt#1302]
I'm unable to install the package.  Apparently it is dependent on the package "juicyjuice" which is dependent on the package "V8".  I'm unable to install "V8'  because of further dependencies.  I believe I have a standard installation of R for a computer runing Linux Ubuntu, and my version of R is up to date so I'm surprised there is so much that needs to be added to use "gt"..  Would it be possible to provide some guidance showing the set of packages the must be installed in order to install "gt" and some instructions that would help accomplishing that?

**Comment by rich-iannone** [comment]
Sorry for the trouble you're having with this. I found a blog post from ROpenSci that provides two installation suggestions for V8 installation (this includes a section for Linux users): https://ropensci.org/blog/2020/11/12/installing-v8/. Once that's installed, gt will then be successfully installed with `install.packages("gt")`.

**Comment by arhall1** [comment]
Thanks for the quick response.  I installed V8 as described in the post you suggested, and then installed gt with no problems.

**Comment by lanacodes123** [comment]
Hello,

I cannot install "gt". I recieve the following errors: ERROR: dependency ‘juicyjuice’ is not available for package ‘gt’' and 'ERROR: loading failed'', and 'ERROR: dependency ‘V8’ is not available for package ‘juicyjuice’'

V8 and juicyjuice are also unable to be downloaded. My R version is 4.1.1 (2021-08-10)

Full output below:
remotes::install_github("rstudio/gt")
Downloading GitHub repo rstudio/gt@HEAD
Installing 2 packages: V8, juicyjuice
Warning: unable to access index for repository http://cran.rstudio.com/bin/macosx/big-sur-arm64/contrib/4.1:
  cannot open URL 'http://cran.rstudio.com/bin/macosx/big-sur-arm64/contrib/4.1/PACKAGES'
Package which is only available in source form, and may need compilation of C/C++/Fortran: ‘V8’
Do you want to attempt to install these from sources? (Yes/no/cancel) yes
installing the source packages ‘V8’, ‘juicyjuice’

trying URL 'http://cran.rstudio.com/src/contrib/V8_4.3.3.tar.gz'
Content type 'application/x-gzip' length 678153 bytes (662 KB)
==================================================
downloaded 662 KB

trying URL 'http://cran.rstudio.com/src/contrib/juicyjuice_0.1.0.tar.gz'
Content type 'application/x-gzip' length 1121080 bytes (1.1 MB)
==================================================
downloaded 1.1 MB

* installing *source* package ‘V8’ ...
** package ‘V8’ successfully unpacked and MD5 sums checked
** using staged installation
Found C++17 compiler: clang++ -arch arm64
Using autobrew bundle: v8-11.2.214.9-universal.tar.xz
** libs
rm -f V8.so RcppExports.o bindings.o
clang++ -arch arm64 -std=gnu++17 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG -I/private/var/folders/mw/d1ns1mss1jq0_l6lwkd820vr0000gn/T/RtmpkRVooK/R.INSTALL11ffe68e7a20e/V8/.deps/include -DV8_COMPRESS_POINTERS -DV8_ENABLE_SANDBOX -I'/Library/Frameworks/R.framework/Versions/4.1-arm64/Resources/library/Rcpp/include' -I/opt/R/arm64/include   -fPIC  -falign-functions=64 -Wall -g -O2  -c RcppExports.cpp -o RcppExports.o
clang++ -arch arm64 -std=gnu++17 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG -I/private/var/folders/mw/d1ns1mss1jq0_l6lwkd820vr0000gn/T/RtmpkRVooK/R.INSTALL11ffe68e7a20e/V8/.deps/include -DV8_COMPRESS_POINTERS -DV8_ENABLE_SANDBOX -I'/Library/Frameworks/R.framework/Versions/4.1-arm64/Resources/library/Rcpp/include' -I/opt/R/arm64/include   -fPIC  -falign-functions=64 -Wall -g -O2  -c bindings.cpp -o bindings.o
clang++ -arch arm64 -std=gnu++17 -dynamiclib -Wl,-headerpad_max_install_names -undefined dynamic_lookup -single_module -multiply_defined suppress -L/Library/Frameworks/R.framework/Resources/lib -L/opt/R/arm64/lib -o V8.so RcppExports.o bindings.o -L/private/var/folders/mw/d1ns1mss1jq0_l6lwkd820vr0000gn/T/RtmpkRVooK/R.INSTALL11ffe68e7a20e/V8/.deps/lib -lv8_monolith -F/Library/Frameworks/R.framework/.. -framework R -Wl,-framework -Wl,CoreFoundation
ld: warning: -undefined dynamic_lookup may not work with chained fixups
installing to /Library/Frameworks/R.framework/Versions/4.1-arm64/Resources/library/00LOCK-V8/00new/V8/libs
** R
** inst
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
** building package indices
** installing vignettes
** testing if installed package can be loaded from temporary location
sh: line 1: 73969 Trace/BPT trap: 5       R_TESTS= '/Library/Frameworks/R.framework/Resources/bin/R' --no-save --no-restore --no-echo 2>&1 < '/var/folders/mw/d1ns1mss1jq0_l6lwkd820vr0000gn/T//RtmpkRVooK/file11ffe2042d08d'
ERROR: loading failed
* removing ‘/Library/Frameworks/R.framework/Versions/4.1-arm64/Resources/library/V8’
ERROR: dependency ‘V8’ is not available for package ‘juicyjuice’
* removing ‘/Library/Frameworks/R.framework/Versions/4.1-arm64/Resources/library/juicyjuice’

The downloaded source packages are in
	‘/private/var/folders/mw/d1ns1mss1jq0_l6lwkd820vr0000gn/T/RtmpDU9dHj/downloaded_packages’
── R CMD build ───────────────────────────────────────────────────────────────────────────────────────────────
✔  checking for file ‘/private/var/folders/mw/d1ns1mss1jq0_l6lwkd820vr0000gn/T/RtmpDU9dHj/remotes11abd70337155/rstudio-gt-da7d7c8/DESCRIPTION’ ...
─  preparing ‘gt’: (617ms)
✔  checking DESCRIPTION meta-information ...
─  checking for LF line-endings in source and make files and shell scripts
─  checking for empty or unneeded directories
   Removed empty directory ‘gt/man/figures’
─  building ‘gt_0.9.0.9000.tar.gz’
   
ERROR: dependency ‘juicyjuice’ is not available for package ‘gt’
* removing ‘/Library/Frameworks/R.framework/Versions/4.1-arm64/Resources/library/gt’
Warning messages:
1: In i.p(...) : installation of package ‘V8’ had non-zero exit status
2: In i.p(...) :
  installation of package ‘juicyjuice’ had non-zero exit status
3: In i.p(...) :
  installation of package ‘/var/folders/mw/d1ns1mss1jq0_l6lwkd820vr0000gn/T//RtmpDU9dHj/file11abd644ac31c/gt_0.9.0.9000.tar.gz’ had non-zero exit status

**Comment by lanacodes123** [comment]
@rich-iannone Hi there! Was wondering if you could help with this issue.
