### ISSUE TITLE
tab_footnote() in Rmarkdown corrupts word document with special character "<"

### ISSUE THREAD

**Issue by AlexGareau** [rstudio/gt#1303]
## Description

When using `tab_footnote(footnote = "p < .05")` in an Rmardown document producing a word document. The word document get corrupted. 

![image](https://user-images.githubusercontent.com/117753797/231565211-000b29e6-9b05-475d-9e58-dab40d25e60a.png)

I was able to pinpoint the faulty character being "<" in the footnote statement. Taking this character out solve the issue of corruption.

**Comment by MarcellGranat** [comment]
You can use &lt; for word output to write "<", however the inconsistency between the output formats still persists.

**Comment by thebioengineer** [comment]
This has been resolved and merged into main
