### ISSUE TITLE
Warning in `gt::gt(process_md = TRUE)` when `rowname_col` is a factor containing `NA`s

### ISSUE THREAD

**Issue by salim-b** [rstudio/gt#1305]
## Prework

* [x] Read and agree to the [code of conduct](https://www.contributor-covenant.org/version/2/1/code_of_conduct.html) and [contributing guidelines](https://github.com/rstudio/gt/blob/master/.github/CONTRIBUTING.md).
* [x] If there is [already a relevant issue](https://github.com/rstudio/gt/issues), whether open or closed, comment on the existing thread instead of posting a new issue.

## Description

See the warning message in the reprex below.

My guess on the cause of the warning: R "labels" `NA`s in factors as `<NA>` (run `factor(NA)` to see what I mean) and gt wrongly tries to interpret that as a Markdown hyperlink.

## Reproducible example

``` r
gt::exibble |>
    tibble::add_row(fctr = NA) |>
    gt::gt(rowname_col = "fctr",
           process_md = TRUE)
#> Warning in `[<-.factor`(`*tmp*`, !is.na(x), value = c("<div
#> class='gt_from_md'><p>one</p>\n</div>", : invalid factor level, NA generated
```

<div id="hqqwgwnsut" style="padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;">
<table class="gt_table" data-quarto-disable-processing="false" data-quarto-bootstrap="false">
  <thead>
    &#10;    <tr class="gt_col_headings">
      <th class="gt_col_heading gt_columns_bottom_border gt_left" rowspan="1" colspan="1" scope="col" id=""></th>
      <th class="gt_col_heading gt_columns_bottom_border gt_right" rowspan="1" colspan="1" scope="col" id="num">num</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_left" rowspan="1" colspan="1" scope="col" id="char">char</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_right" rowspan="1" colspan="1" scope="col" id="date">date</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_right" rowspan="1" colspan="1" scope="col" id="time">time</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_right" rowspan="1" colspan="1" scope="col" id="datetime">datetime</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_right" rowspan="1" colspan="1" scope="col" id="currency">currency</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_left" rowspan="1" colspan="1" scope="col" id="row">row</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_left" rowspan="1" colspan="1" scope="col" id="group">group</th>
    </tr>
  </thead>
  <tbody class="gt_table_body">
    <tr><th id="stub_1_1" scope="row" class="gt_row gt_center gt_stub">one</th>
<td headers="stub_1_1 num" class="gt_row gt_right">1.111e-01</td>
<td headers="stub_1_1 char" class="gt_row gt_left">apricot</td>
<td headers="stub_1_1 date" class="gt_row gt_right">2015-01-15</td>
<td headers="stub_1_1 time" class="gt_row gt_right">13:35</td>
<td headers="stub_1_1 datetime" class="gt_row gt_right">2018-01-01 02:22</td>
<td headers="stub_1_1 currency" class="gt_row gt_right">49.950</td>
<td headers="stub_1_1 row" class="gt_row gt_left">row_1</td>
<td headers="stub_1_1 group" class="gt_row gt_left">grp_a</td></tr>
    <tr><th id="stub_1_2" scope="row" class="gt_row gt_center gt_stub">two</th>
<td headers="stub_1_2 num" class="gt_row gt_right">2.222e+00</td>
<td headers="stub_1_2 char" class="gt_row gt_left">banana</td>
<td headers="stub_1_2 date" class="gt_row gt_right">2015-02-15</td>
<td headers="stub_1_2 time" class="gt_row gt_right">14:40</td>
<td headers="stub_1_2 datetime" class="gt_row gt_right">2018-02-02 14:33</td>
<td headers="stub_1_2 currency" class="gt_row gt_right">17.950</td>
<td headers="stub_1_2 row" class="gt_row gt_left">row_2</td>
<td headers="stub_1_2 group" class="gt_row gt_left">grp_a</td></tr>
    <tr><th id="stub_1_3" scope="row" class="gt_row gt_center gt_stub">three</th>
<td headers="stub_1_3 num" class="gt_row gt_right">3.333e+01</td>
<td headers="stub_1_3 char" class="gt_row gt_left">coconut</td>
<td headers="stub_1_3 date" class="gt_row gt_right">2015-03-15</td>
<td headers="stub_1_3 time" class="gt_row gt_right">15:45</td>
<td headers="stub_1_3 datetime" class="gt_row gt_right">2018-03-03 03:44</td>
<td headers="stub_1_3 currency" class="gt_row gt_right">1.390</td>
<td headers="stub_1_3 row" class="gt_row gt_left">row_3</td>
<td headers="stub_1_3 group" class="gt_row gt_left">grp_a</td></tr>
    <tr><th id="stub_1_4" scope="row" class="gt_row gt_center gt_stub">four</th>
<td headers="stub_1_4 num" class="gt_row gt_right">4.444e+02</td>
<td headers="stub_1_4 char" class="gt_row gt_left">durian</td>
<td headers="stub_1_4 date" class="gt_row gt_right">2015-04-15</td>
<td headers="stub_1_4 time" class="gt_row gt_right">16:50</td>
<td headers="stub_1_4 datetime" class="gt_row gt_right">2018-04-04 15:55</td>
<td headers="stub_1_4 currency" class="gt_row gt_right">65100.000</td>
<td headers="stub_1_4 row" class="gt_row gt_left">row_4</td>
<td headers="stub_1_4 group" class="gt_row gt_left">grp_a</td></tr>
    <tr><th id="stub_1_5" scope="row" class="gt_row gt_center gt_stub">five</th>
<td headers="stub_1_5 num" class="gt_row gt_right">5.550e+03</td>
<td headers="stub_1_5 char" class="gt_row gt_left">NA</td>
<td headers="stub_1_5 date" class="gt_row gt_right">2015-05-15</td>
<td headers="stub_1_5 time" class="gt_row gt_right">17:55</td>
<td headers="stub_1_5 datetime" class="gt_row gt_right">2018-05-05 04:00</td>
<td headers="stub_1_5 currency" class="gt_row gt_right">1325.810</td>
<td headers="stub_1_5 row" class="gt_row gt_left">row_5</td>
<td headers="stub_1_5 group" class="gt_row gt_left">grp_b</td></tr>
    <tr><th id="stub_1_6" scope="row" class="gt_row gt_center gt_stub">six</th>
<td headers="stub_1_6 num" class="gt_row gt_right">NA</td>
<td headers="stub_1_6 char" class="gt_row gt_left">fig</td>
<td headers="stub_1_6 date" class="gt_row gt_right">2015-06-15</td>
<td headers="stub_1_6 time" class="gt_row gt_right">NA</td>
<td headers="stub_1_6 datetime" class="gt_row gt_right">2018-06-06 16:11</td>
<td headers="stub_1_6 currency" class="gt_row gt_right">13.255</td>
<td headers="stub_1_6 row" class="gt_row gt_left">row_6</td>
<td headers="stub_1_6 group" class="gt_row gt_left">grp_b</td></tr>
    <tr><th id="stub_1_7" scope="row" class="gt_row gt_center gt_stub">seven</th>
<td headers="stub_1_7 num" class="gt_row gt_right">7.770e+05</td>
<td headers="stub_1_7 char" class="gt_row gt_left">grapefruit</td>
<td headers="stub_1_7 date" class="gt_row gt_right">NA</td>
<td headers="stub_1_7 time" class="gt_row gt_right">19:10</td>
<td headers="stub_1_7 datetime" class="gt_row gt_right">2018-07-07 05:22</td>
<td headers="stub_1_7 currency" class="gt_row gt_right">NA</td>
<td headers="stub_1_7 row" class="gt_row gt_left">row_7</td>
<td headers="stub_1_7 group" class="gt_row gt_left">grp_b</td></tr>
    <tr><th id="stub_1_8" scope="row" class="gt_row gt_center gt_stub">eight</th>
<td headers="stub_1_8 num" class="gt_row gt_right">8.880e+06</td>
<td headers="stub_1_8 char" class="gt_row gt_left">honeydew</td>
<td headers="stub_1_8 date" class="gt_row gt_right">2015-08-15</td>
<td headers="stub_1_8 time" class="gt_row gt_right">20:20</td>
<td headers="stub_1_8 datetime" class="gt_row gt_right">NA</td>
<td headers="stub_1_8 currency" class="gt_row gt_right">0.440</td>
<td headers="stub_1_8 row" class="gt_row gt_left">row_8</td>
<td headers="stub_1_8 group" class="gt_row gt_left">grp_b</td></tr>
    <tr><th id="stub_1_9" scope="row" class="gt_row gt_center gt_stub">NA</th>
<td headers="stub_1_9 num" class="gt_row gt_right">NA</td>
<td headers="stub_1_9 char" class="gt_row gt_left">NA</td>
<td headers="stub_1_9 date" class="gt_row gt_right">NA</td>
<td headers="stub_1_9 time" class="gt_row gt_right">NA</td>
<td headers="stub_1_9 datetime" class="gt_row gt_right">NA</td>
<td headers="stub_1_9 currency" class="gt_row gt_right">NA</td>
<td headers="stub_1_9 row" class="gt_row gt_left">NA</td>
<td headers="stub_1_9 group" class="gt_row gt_left">NA</td></tr>
  </tbody>
  &#10;  
</table>
</div>

<sup>Created on 2023-04-14 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

## Expected result

No warning.

## Session info

<details style="margin-bottom:10px;">
<summary>
Session info
</summary>

``` r
sessioninfo::session_info()
#> ─ Session info ───────────────────────────────────────────────────────────────
#>  setting  value
#>  version  R version 4.2.3 (2023-03-15)
#>  os       Ubuntu 22.04.2 LTS
#>  system   x86_64, linux-gnu
#>  ui       X11
#>  language en_US.utf8
#>  collate  en_US.utf8
#>  ctype    en_US.utf8
#>  tz       Europe/Zurich
#>  date     2023-04-14
#>  pandoc   3.1.2 @ /usr/bin/ (via rmarkdown)
#> 
#> ─ Packages ───────────────────────────────────────────────────────────────────
#>  package     * version date (UTC) lib source
#>  cli           3.6.1   2023-03-23 [1] RSPM (R 4.2.0)
#>  commonmark    1.9.0   2023-03-17 [1] RSPM (R 4.2.0)
#>  digest        0.6.31  2022-12-11 [1] RSPM (R 4.2.0)
#>  dplyr         1.1.1   2023-03-22 [1] CRAN (R 4.2.3)
#>  evaluate      0.20    2023-01-17 [1] RSPM (R 4.2.0)
#>  fansi         1.0.4   2023-01-22 [1] RSPM (R 4.2.0)
#>  fastmap       1.1.1   2023-02-24 [1] RSPM (R 4.2.0)
#>  fs            1.6.1   2023-02-06 [1] RSPM (R 4.2.0)
#>  generics      0.1.3   2022-07-05 [1] RSPM (R 4.2.0)
#>  glue          1.6.2   2022-02-24 [1] RSPM (R 4.2.0)
#>  gt            0.9.0   2023-03-31 [1] RSPM (R 4.2.0)
#>  htmltools     0.5.5   2023-03-23 [1] RSPM (R 4.2.0)
#>  knitr         1.42    2023-01-25 [1] RSPM (R 4.2.0)
#>  lifecycle     1.0.3   2022-10-07 [1] RSPM (R 4.2.0)
#>  magrittr      2.0.3   2022-03-30 [1] RSPM (R 4.2.0)
#>  markdown      1.6     2023-04-07 [1] RSPM (R 4.2.0)
#>  pillar        1.9.0   2023-03-22 [1] RSPM (R 4.2.0)
#>  pkgconfig     2.0.3   2019-09-22 [1] RSPM
#>  purrr         1.0.1   2023-01-10 [1] RSPM (R 4.2.0)
#>  R.cache       0.16.0  2022-07-21 [1] RSPM (R 4.2.0)
#>  R.methodsS3   1.8.2   2022-06-13 [1] RSPM (R 4.2.0)
#>  R.oo          1.25.0  2022-06-12 [1] RSPM (R 4.2.0)
#>  R.utils       2.12.2  2022-11-11 [1] RSPM (R 4.2.0)
#>  R6            2.5.1   2021-08-19 [1] RSPM
#>  reprex        2.0.2   2022-08-17 [1] RSPM (R 4.2.0)
#>  rlang         1.1.0   2023-03-14 [1] RSPM (R 4.2.0)
#>  rmarkdown     2.21    2023-03-26 [1] RSPM (R 4.2.0)
#>  rstudioapi    0.14    2022-08-22 [1] RSPM (R 4.2.0)
#>  sass          0.4.5   2023-01-24 [1] RSPM (R 4.2.0)
#>  sessioninfo   1.2.2   2021-12-06 [1] RSPM (R 4.2.0)
#>  styler        1.9.1   2023-03-04 [1] RSPM (R 4.2.0)
#>  tibble        3.2.1   2023-03-20 [1] RSPM (R 4.2.0)
#>  tidyselect    1.2.0   2022-10-10 [1] RSPM (R 4.2.0)
#>  utf8          1.2.3   2023-01-31 [1] RSPM (R 4.2.0)
#>  vctrs         0.6.1   2023-03-22 [1] RSPM (R 4.2.0)
#>  withr         2.5.0   2022-03-03 [1] RSPM
#>  xfun          0.38    2023-03-24 [1] RSPM (R 4.2.0)
#>  xml2          1.3.3   2021-11-30 [1] RSPM (R 4.2.0)
#>  yaml          2.3.7   2023-01-23 [1] RSPM (R 4.2.0)
#> 
#>  [1] /home/salim/.software/managed/r
#>  [2] /usr/local/lib/R/site-library
#>  [3] /usr/lib/R/site-library
#>  [4] /usr/lib/R/library
#> 
#> ──────────────────────────────────────────────────────────────────────────────
```

</details>

**Comment by olivroy** [comment]
This is no longer an issue with gt 0.11.0. Possibly as a result of https://github.com/rstudio/gt/pull/1578.

I also tested with current dev version 0.11.0.9000. both in Quarto and outside Quarto.
