### ISSUE TITLE
opt_interactive() removes styling

### ISSUE THREAD

**Issue by rwaaijman** [rstudio/gt#1307]
Great new option, however some styling disappears.

when running
```
table <- gtcars[1:10,] |>
  gt() |>
  data_color("mfr",colors = "lightgray") |> 
  cols_hide(columns = trim) |>
  opt_table_lines(extent = c("none")) |> 
  tab_options(table.font.size = px(12), table.align = "left")
table
```
this is the output
![without interactive](https://user-images.githubusercontent.com/12223921/232057263-27904f1c-f96c-467c-ac47-3822e14fb808.png)

but when ading opt_interactive() some styling disappears, like fontsize and lines:
```
table |> 
  opt_interactive()
```
![with interactive](https://user-images.githubusercontent.com/12223921/232057320-5598568f-6a63-4856-9828-73a1fbe411f9.png)

Is this a bug, or do I something wrong

**Comment by olivroy** [comment]
A related bug, it removes url! done by `gt::fmt_url()`

**Comment by mcanouil** [comment]
From few testing it appears `.reactable` class takes precedence over `.gt_table`.

**Comment by olivroy** [comment]
`gt::opt_table_lines(extent = "none")` could be implemented with `reactable(borderless = TRUE)`
