### ISSUE TITLE
Error rendering HTML table with multiple higher level spanners and cell styles

### ISSUE THREAD

**Issue by nathanieltwarog** [rstudio/gt#1311]
## Prework

* [x] Read and agree to the [code of conduct](https://www.contributor-covenant.org/version/2/1/code_of_conduct.html) and [contributing guidelines](https://github.com/rstudio/gt/blob/master/.github/CONTRIBUTING.md).
* [x] If there is [already a relevant issue](https://github.com/rstudio/gt/issues), whether open or closed, comment on the existing thread instead of posting a new issue.

## Description

When multiple spanners are placed at level 2 or higher *and* styles are added to a a table, the resulting gt object fails to print and render in html.  The issue appears to be code in the function "create_heading_component_h" in "utils_render_html.R" for processing higher spanner rows.  There is a call to `dplyr::filter` which compares the group names in the style table to the vector `spanner_vars`; I believe this is meant to compare it to a specific *element* of `spanner_vars`

## Reproducible example

When no styles are included, the spanners render successfully:

```
randomData <- tibble(First=c("A","B","C"), 
					 GroupA1=1:3,
					 GroupA2=2:4,
					 GroupB1=c(8,10,12),
					 GroupB2=10+(5:7)/10,
					 Final=c("Red","Green","Blue"))

table1 <- randomData %>% gt() %>%
	tab_spanner(columns=c(1),label="Row",level=1) %>%
	tab_spanner(columns=c(2,3),label="Lower",level=1) %>%
	tab_spanner(columns=c(4,5),label="Higher",level=1) %>%
	tab_spanner(columns=c(6),label="White",level=1) %>%
	tab_spanner(columns=c(2,3),label="Group A",level=2) %>%
	tab_spanner(columns=c(4,5),label="Group B",level=2) %>%
	tab_spanner(columns=c(6),label="Color",level=2)

print(table1)
```

But when styles are added to two of the cells, the render fails:

```
table2 <- randomData %>% gt() %>%
	data_color(columns=6,rows=1,palette="red",apply_to="fill") %>%
	tab_spanner(columns=c(1),label="Row",level=1) %>%
	tab_spanner(columns=c(2,3),label="Lower",level=1) %>%
	tab_spanner(columns=c(4,5),label="Higher",level=1) %>%
	tab_spanner(columns=c(6),label="White",level=1) %>%
	tab_spanner(columns=c(2,3),label="Group A",level=2) %>%
	tab_spanner(columns=c(4,5),label="Group B",level=2) %>%
	tab_spanner(columns=c(6),label="Color",level=2)

print(table2)
```

## Expected result

This second table should have formatted a single cell (the sixth cell in the first row) with a red fill (and white text).  However, it instead gives the following error:

```
Error in `dplyr::filter()`:
i In argument: `grpname == spanners_vars`.
Caused by error:
! `..2` must be of size 1, not size 3.
```

**Comment by nathanieltwarog** [comment]
Apologies, the error appears to be in the function `create_columns_component_h`, not in `create_headings_component_h`

**Comment by olivroy** [comment]
This is no longer an issue with gt 0.11
