### ISSUE TITLE
Feature: log-transformation (or any other) of color scale

### ISSUE THREAD

**Issue by DSLituiev** [rstudio/gt#1313]
## Proposal

It would be quite useful to be able to provide a transformation function to the `data_color`.
I need to colorize two columns on log-scale.
I could go with quantiles if it were one, but as I need to align same colors, this does not seem to work well with `domain` specs.

```R
data_color(
    columns = c(n_before,	n_after),
    method = log,
)
```

**Comment by DSLituiev** [comment]
Maybe something to the effect of modifying here:

https://github.com/rstudio/gt/blob/master/R/data_color.R#L824


```R
>>>
# now
data_vals <- dplyr::select(data_tbl, dplyr::all_of(resolved_columns))
---
# with a transform
data_vals <- dplyr::select(data_tbl, dplyr::all_of(resolved_columns))
if (!is.null(transform)) {
     data_vals <- data_vals |> 
                   dplyr::mutate(across(dplyr::all_of(resolved_columns), transform) )
 }
>>>
```

**Comment by rich-iannone** [comment]
You can provide your own colorizing function to `data_color()`. Use the `fn` argument for that: https://gt.rstudio.com/reference/data_color.html
