### ISSUE TITLE
Why only a LIST can be successfully converted to the markdown format?

### ISSUE THREAD

**Issue by mickeyang** [rstudio/gt#1318]
Dear GT team,

Can you please help me understand the below "issue"?

I tried to convert a web link to the Markdown (MD) format by using your helper function ```gt::md```. I attempted three approaches by versioning them as ```file_path_transform_md_v1```, ```file_path_transform_md_v2```, and ```file_path_transform_md_v3```.

```file_path_transform_md_v1``` was converted with the help of `purrr::map`.

```file_path_transform_md_v2``` was transformed by changing the data type to the LIST.

```file_path_transform_md_v3``` was generated purely by the ```gt::md``` function.

It turned out that only the ```file_path_transform_md_v1``` and ```file_path_transform_md_v2``` were successfully converted to clickable hyperlinks, but the ```file_path_transform_md_v3``` failed although all of them were the same data type `from_markdown`. 

I would like to learn the WHY of the above outcomes. I look forward to hearing from you.

Thanks for your help in advance.

The below is created on 2023-04-24 by the [reprex package](https://reprex.tidyverse.org/) (v2.0.1)
```
rm(list = ls())
library(dplyr)
library(gt)

final_table <- tibble(url = "https://www.google.com") |>
  mutate(url_transform = stringr::str_glue("[link]({url})")) |>
  mutate(file_path_transform_md_v1 = purrr::map(url_transform, gt::md)) |>
  mutate(file_path_transform_md_v2 = list(md(url_transform))) |>
  mutate(file_path_transform_md_v3 = md(url_transform))

final_table |> gt()

str(final_table)
#> tibble [1 × 5] (S3: tbl_df/tbl/data.frame)
#>  $ url                      : chr "https://www.google.com"
#>  $ url_transform            : 'glue' chr "[link](https://www.google.com)"
#>  $ file_path_transform_md_v1:List of 1
#>   ..$ : 'from_markdown' chr "[link](https://www.google.com)"
#>  $ file_path_transform_md_v2:List of 1
#>   ..$ : 'from_markdown' chr "[link](https://www.google.com)"
#>  $ file_path_transform_md_v3: 'from_markdown' chr "[link](https://www.google.com)"
```

**Comment by rich-iannone** [comment]
We can get a glue as to why it doesn't work from the tibble print out:

```
> final_table
# A tibble: 1 × 5
  url                    url_transform                  file_path_transform_md_v1 file_path_transform_md_v2 file_path_transform_md_v3     
  <chr>                  <glue>                         <list>                    <list>                    <frm_mrkd>                    
1 https://www.google.com [link](https://www.google.com) <frm_mrkd [1]>            <frm_mrkd [1]>            [link](https://www.google.com)
```

The third variation doesn't work because it's not a list. The `md()` function is meant for use inside of the gt API. Using it outside is fine but it's undocumented and untested.
