### ISSUE TITLE
pptx and word docx output to office verse

### ISSUE THREAD

**Issue by higgi13425** [rstudio/gt#132]
---

one of the especially nice features of the flextable package is the direct export to pptx and docx.
are there nice features of flextable that you can borrow?

```r
ft <- regulartable(head(mtcars))
ft <- theme_booktabs(ft)
ft <- autofit(ft)

ppt <- read_pptx()
ppt <- add_slide(ppt, layout = "Title and Content", master = "Office Theme")
ppt <- ph_with_flextable(ppt, value = ft, type = "body") 

print(ppt, target = "assets/pptx/example.pptx")
```

**Comment by rich-iannone** [comment]
Maybe. These are entirely different output formats but understandably pretty valuable ones. It would take work to port over the different table features to these output types. This is definitely not happening in the short-term unfortunately.

**Comment by higgi13425** [comment]
Do you think that David Gohel could help? He is clearly invested in the office verse for his work.

**Comment by bwiernik** [comment]
Just tagging @davidgohel in the event he might have thoughts on hooks that `gt` might be able to incorporate.
