### ISSUE TITLE
arsenal::tableby() objects?

### ISSUE THREAD

**Issue by higgi13425** [rstudio/gt#133]
It is common to use arsenal::tableby() to produce table 1 in reports of clinical trials.
Can these objects be handled/formatted with gt?

```r
library(arsenal)
tab1 <- tableby(arm ~ sex + age, data=mockstudy)
```

**Comment by rich-iannone** [comment]
@higgi13425 I just experimented with this a bit. The end result is not too bad but I think that a function to do some handling for `tableby` object would make this better. Still, the very basic statements below create a reasonable output table:

```r
library(arsenal)
library(tidyverse)
library(gt)

tableby(arm ~ sex + age, data = mockstudy) %>%
  as.data.frame() %>%
  gt(
    groupname_col = "variable",
    rowname_col = "term"
  )
```

<img width="1066" alt="tableby" src="https://user-images.githubusercontent.com/5612024/51209926-0efce200-18d7-11e9-8fe8-e5f1db15d1b8.png">

This could be much better with some systematic formatting. I'd like to look at more of these table 1 reports to see what can be done to improve to layout and formatting.

**Comment by eheinzen** [comment]
Author/maintainer of arsenal here.   I'd consider a hack using `as.data.frame(summary(.))` instead (see, e.g., eheinzen/arsenal#60).  Something like this should do the trick:

````
library(arsenal)
library(tidyverse)
library(gt)

tab <- tableby(arm ~ sex + age, data = mockstudy) %>%
  summary(term.name = "term", text = NULL)

format_for_gt <- function(df)
{
  df$variable <- df$label[1]
  df[-1, ]
}

tab$object[[1]] <- tab$object[[1]] %>% 
  group_by(variable) %>% 
  do(format_for_gt(.)) %>%
  ungroup()

tab %>% 
  as.data.frame() %>% 
  mutate(variable = tab$object[[1]]$variable) %>% 
  gt(
    rowname_col = "term",
    groupname_col = "variable"
  )
````

This should give you something like this:
![image](https://user-images.githubusercontent.com/30500972/51452458-0c97ef00-1d00-11e9-827b-cdad12920c38.png)

As a side note, we're definitely aware of gt (I found this issue by complete accident), and I was super excited to see it at rstudio::conf, too.  I'd very seriously consider using it to format our tables once it's on CRAN.

cc @bethatkinson @sinnweja

**Comment by dnvaughan** [comment]
Thanks to the tableby authors.  I found the code above from @eheinzen very helpful indeed.
Here is a small modification, to preserve the order of groups ...

```
tableby_to_gt <- function( tablebyObject ) 
{
    format_for_gt <- function(df)
    {
        df$variable <- df$label[1]
        df[-1, ]
    }
    
    tab <- tablebyObject %>%  summary(term.name = "term", text = NULL)
    
    tab$object[[1]] <- tab$object[[1]] %>% 
        mutate( variable = fct_inorder(as.factor(variable)) ) %>%  # preserve order of groups
        group_by(variable) %>% 
        do(format_for_gt(.)) %>%
        ungroup()
    
    gtObject <- tab %>% 
        as.data.frame() %>% 
        mutate(variable = tab$object[[1]]$variable) %>% 
        gt(
            rowname_col = "term",
            groupname_col = "variable"
        ) 
    
    return(gtObject)
}
```
