### ISSUE TITLE
Flag for Europe in fmt_flag ?

### ISSUE THREAD

**Issue by Francois-Geerolf** [rstudio/gt#1333]
## Proposal

Would it be possible to add a flag in fmt_flag for Europe, or euro area ? (and potentially other country groupings)
thanks for a great package !

**Comment by rich-iannone** [comment]
Thanks for submitting the issue and, yes, this could definitely be done. I'm hoping to expand on the `fmt_flag()` by having:

- more flags (e.g., country groups, subdivisions for some countries, historic countries)
- more ways to access (in addition to two-letter country codes also allow three-letter codes, keywords, and common names) 
- aliases for overseas departments and protectorates

**Comment by rich-iannone** [comment]
The EU flag will be available (through `"eu"`) when https://github.com/rstudio/gt/pull/1336 is merged.

**Comment by Francois-Geerolf** [comment]
Amazing ! Thanks a lot !
