### ISSUE TITLE
Coloring NA values

### ISSUE THREAD

**Issue by kwakuduahc1** [rstudio/gt#1349]
I have been trying to color only NA values without coloring other variables with the `data_color` function but without success.

There appears to be an inconsistency in the behavior of the row parameter:

```
library(tidyverse)
library(gt)

dset <- tibble(
               temperature = c(1, 2, NA),
               pulse = c(NA, 1, 1.2)
        )
```

This does not work

```
dset %>%
  gt() %>%
  data_color(rows = is.na(everything()))
```

``` 
Error in `get_contrast_ratio()`:
! At least one color defined for each of `color_1` and `color_2`.~
```

... but this does

```
dset %>%
  gt() %>%
  data_color(rows = is.numeric(everything()))
```

`is.na` and `is.numeric` in my knowledge evaluates to the same logical value(s)

```
dset %>%
  gt() %>%
  data_color(rows = where( ~ is.na(.)))
```

I want to color only the `NA` values without coloring any other value

![image](https://github.com/rstudio/gt/assets/11381582/e469baf3-c289-498c-b3de-be9378adfbf6)

Thanks.

**Comment by rich-iannone** [comment]
Thanks for posting this issue. I can definitely fix this. Another way to move past this for now is to use `tab_style_body()`:

```r
library(gt)
library(tidyverse)

dplyr::tibble(
  temperature = c(1, 2, NA),
  pulse = c(NA, 1, 1.2)
) |>
  gt() |>
  tab_style_body(
    fn = function(x) is.na(x),
    style = cell_fill(color = "lightblue")
  )
```

Which gives us this table:

<img width="343" alt="tab-style-body-na" src="https://github.com/rstudio/gt/assets/5612024/55a3c663-b755-459c-9ca8-d589779e07f9">

**Comment by kwakuduahc1** [comment]
Thank you. Your fix is excellent.

**Comment by rich-iannone** [comment]
I added a clarifying example on how to do this in https://github.com/rstudio/gt/pull/1383. So, I'll close this issue now.

**Comment by kwakuduahc1** [comment]
Thanks.
