### ISSUE TITLE
Allow Commonwealth spelling of "centre"

### ISSUE THREAD

**Issue by jdonland** [rstudio/gt#1353]
The general tidyverse convention seems to be allow both US and Commonwealth spellings of words like "colour"/"color", etc. Therefore "centre" should work in gt for things like column alignment.

**Comment by rich-iannone** [comment]
Thanks for the issue but I really don’t want to do this (for reasons of consistency). And ggplot uses `"center"` (check out this reference page: https://ggplot2.tidyverse.org/reference/geom_text.html#alignment).
