### ISSUE TITLE
Ability to save `gt_group` objects to additional file formats

### ISSUE THREAD

**Issue by bzkrouse** [rstudio/gt#1354]
## Prework

- [x] Read and abide by **gt**'s [code of conduct](https://www.contributor-covenant.org/version/2/1/code_of_conduct.html) and [contributing guidelines](https://github.com/rstudio/gt/blob/master/.github/CONTRIBUTING.md).
- [x] Search for duplicates among the [existing issues](https://github.com/rstudio/gt/issues) (both open and closed).

## Proposal

Thanks for the new features associated with `gt_group`! I was able to successfully export multiple {gt} objects into a single file as docx/rtf. It would be great to also have this expanded to additional formats (pdf, html, png, etc.)

**Comment by rich-iannone** [comment]
Thanks for using these new functions and for the valuable feedback! I can definitely provide more exporting functionality for a group of tables (plus add missing documentation examples).
