### ISSUE TITLE
Background of gt.rstudio.com

### ISSUE THREAD

**Issue by theobroekman** [rstudio/gt#1358]
## Prework

* [ ] Read and agree to the [code of conduct](https://www.contributor-covenant.org/version/2/1/code_of_conduct.html) and [contributing guidelines](https://github.com/rstudio/gt/blob/master/.github/CONTRIBUTING.md).
* [ ] If there is [already a relevant issue](https://github.com/rstudio/gt/issues), whether open or closed, comment on the existing thread instead of posting a new issue.
* [ ] For any problems you identify, a [minimal reproducible example](https://www.tidyverse.org/help/) so the maintainer can troubleshoot. A reproducible example is:
    * [ ] **Runnable**: post enough R code and data so any onlooker can create the error on their own computer.
    * [ ] **Minimal**: reduce runtime wherever possible and remove complicated details that are irrelevant to the issue at hand.
    * [ ] **Readable**: format your code according to the [tidyverse style guide](https://style.tidyverse.org/).

## Question

What would you like to know?
The Background of gt.rstudio.com is now black instead of my default white background, This is in chrome as well as in Edge. Hard to read for me. I would appreciate it very much if this could be changed to how it was before.

**Comment by rich-iannone** [comment]
Thanks for the feedback. I totally agree and now it’s back to having a white background!
