### ISSUE TITLE
Using gt tables in PDF via Quarto

### ISSUE THREAD

**Issue by HaroldDMiller** [rstudio/gt#1363]
Is there any way to include a gt table in a PDF generated by Quarto that preserves the inline css formatting?  The gt tables display beautifully when rendered as an HTML file, but when rendering to PDF, I get a LaTeX compilation error about "Misplaced \noalign" for \midrule.  If I output the gt table as raw html, it will display in the PDF without any errors but it also loses the css formatting of the lines, the text bolding and colors, etc.  I have tried turning on and off various Quarto options, deleting the tables.tex file, changing knitr options, etc, but nothing fixes the problem.  I have had to resort to saving the gt table as an image and then displaying the image as a figure, but that prevents long tables from printing across multiple pages.  (If I output the gt table as raw html, the LaTeX code uses \longtable and that works, but then the table formatting that is stored as css is gone.)  I have looked for other discussions about this and I've seen references to gt not working well in pdfs, but I can't tell if there is a solution somewhere that I could use.

**Comment by cderv** [comment]
FYI @rich-iannone related thread in Quarto repo: 

* https://github.com/quarto-dev/quarto-cli/issues/6084
* https://github.com/quarto-dev/quarto-cli/discussions/6074
* https://github.com/quarto-dev/quarto-cli/discussions/6095
* https://github.com/quarto-dev/quarto-cli/discussions/6102

**Comment by rich-iannone** [comment]
@HaroldDMiller thanks for the question. LaTeX/PDF tables still have some catching up to do in comparison with HTML tables. Some recent work now allows you to change text and background cell colors with `tab_style()` but there is still much work to be done.

You cannot use CSS is LaTeX tables. The strategy of using table images in LaTeX is pretty good, so long as the table isn’t too long as you’ve mentioned. 

Work is being done to add even more styling features to LaTeX tables; I expect this will happen over the next 3-4 months.

**Comment by HaroldDMiller** [comment]
Thanks for the response.  Initially, I didn´t know if I was doing something wrong or if there was a technique for making it work that I wasn´t aware of.  So it´s good to know that "it isn't just me" and that a fix is in the queue.  Having struggled for many hours myself learning how to make LaTeX output do what I want, I have some sense of the challenges you face in adding this functionality to gt.  By the way, thank you for all of the work that you've done with gt -- it works beautifully in html.  I spent a fair amount of time a while back comparing the different table generation packages, and gt has so much better functionality than the others that having to create a workaround for using it with LaTeX is still worth it.

**Comment by rich-iannone** [comment]
@HaroldDMiller @cderv  I agree that the documentation should be improved with regard to features that work in the various output formats (a full article along with statements within the man pages should all be done). Yes, LaTeX is a hard nut to crack with regard to safely implementing styling features. HTML does make it easy thanks to CSS and its broad/uniform support across browsers whereas LaTeX often requires the use of extra CTAN packages which may or may not play well with each other (along with other potential problems, leading the brittleness).

So, if I move too quickly with LaTeX development there may be regressions introduced that could result in the LaTeX table not rendering at all. It is quite the minefield, but I'm making some slow-and-steady development and doing as much manual testing as possible. For instance a recent PR (https://github.com/rstudio/gt/pull/1352) adds support for styling cell background colour, cell text color, and allows for bold/italicized cell text. Try it out if you like by installing gt with `devtools::install_github("rstudio/gt")`. Thanks for your patience with all this, we'll eventually have something really good when it comes to LaTeX tables!

**Comment by HaroldDMiller** [comment]
Thanks for the tip.  I'll try that version.  It may well do what I need in many circumstances.

By the way, I got a LaTeX error with one fairly complex table when I set gt to output in LaTeX format, but I didn't go back to try and figure out exactly what was causing the error because it seemed clear that it wasn't going to do what I needed even with simpler tables that didn't throw an error.

**Comment by baptiste** [comment]
FWIW, the image workaround can be automated relatively well, i.e. the same document would compile in HTML or LaTeX without any modifications, and the table can look the same (though obviously static and no page breaks). The table size can be set to match the text, etc.

The feature gap in LaTeX vs HTML illustrated below (and given the difficulties in closing it) might justify a temporary knitr option `gt_html_to_pdf` that would take care of these steps.

![Screenshot 2023-07-05 at 08 40 09](https://github.com/rstudio/gt/assets/18970/7edd9cd8-5c83-4f44-8ce5-c29c6bf97c12)

https://gist.github.com/baptiste/23efe856d4c4795db3be6eafc543d0ff

@rich-iannone I wonder if you've had a chance to play with tabularray? https://github.com/rstudio/gt/issues/1149 
In my experiments, it seemed the most promising LaTeX package going forward, in terms of feature set (unfortunately, it is also very bleeding edge).

A pragmatic solution, I think, might be eventually to let the user choose between letting R produce the tables via R graphics (https://github.com/rstudio/gt/pull/1015), regardless of output format (but typically when it does not support all formatting features), or in the native format (which can be more bare-bones if not all features are/can be implemented).

**Comment by HaroldDMiller** [comment]
I have a standard little set of code that I currently use to create an image from the gt table using gtsave and use the image if it's going to pdf but use the standard r object if it's going to html (using Quarto's nice "visible when" div class).  The problem I've had is that gtsave creates an image that is the same size regardless of the actual size of the table (if there's a way around that, let me know!!) so when the image displays in the pdf, the font is stretched larger in a smaller table than it is in a larger table.  So I then have to go in and manually adjust the width of the image for every table to try and get a similar size font appearance.  The image also gets cut off on the right side in some tables; that seems to only happen if there is a column spanner in the table; it's not consistently because the table itself is wide.
