### ISSUE TITLE
Replacing spanner doesn't work and instead adds a second spanner

### ISSUE THREAD

**Issue by szimmer** [rstudio/gt#1369]
## Prework

* [ x] Read and agree to the [code of conduct](https://www.contributor-covenant.org/version/2/1/code_of_conduct.html) and [contributing guidelines](https://github.com/rstudio/gt/blob/master/.github/CONTRIBUTING.md).
* [x ] If there is [already a relevant issue](https://github.com/rstudio/gt/issues), whether open or closed, comment on the existing thread instead of posting a new issue.

## Description

I was working with a gt and trying to change the spanner. When trying this, instead I just got a second spanner.

## Reproducible example

* [x ] Post a [minimal reproducible example](https://www.tidyverse.org/help/) so the maintainer can troubleshoot the problems you identify. A reproducible example is:
    * [x ] **Runnable**: post enough R code and data so any onlooker can create the error on their own computer.
    * [x ] **Minimal**: reduce runtime wherever possible and remove complicated details that are irrelevant to the issue at hand.
    * [x ] **Readable**: format your code according to the [tidyverse style guide](https://style.tidyverse.org/).

``` r
library(gt)

gtcar_df <- gtcars |>
  dplyr::select(
    -mfr, -trim, bdy_style,
    -drivetrain, -trsmn, -ctry_origin
  ) |>
  dplyr::slice(1:8)

try1 <- gtcar_df |>
  gt(rowname_col = "model") |>
  tab_spanner(
    label = "performance",
    columns = c(
      hp, hp_rpm, trq, trq_rpm,
      mpg_c, mpg_h
    )
  )

# Replacing spanner 
try1 %>%
  tab_spanner(
    label = "performance v2",
    columns = c(
      hp, hp_rpm, trq, trq_rpm,
      mpg_c, mpg_h
    ),
    replace = TRUE
  )
```

<table class="gt_table" data-quarto-disable-processing="false" data-quarto-bootstrap="false">
  <thead>
    &#10;    <tr class="gt_col_headings gt_spanner_row">
      <th rowspan="1" colspan="1" scope="col"></th>
      <th class="gt_center gt_columns_top_border gt_column_spanner_outer" rowspan="1" colspan="2" scope="colgroup" id></th>
      <th class="gt_center gt_columns_top_border gt_column_spanner_outer" rowspan="1" colspan="6" scope="colgroup" id="performance v2">
        <span class="gt_column_spanner">performance v2</span>
      </th>
      <th class="gt_center gt_columns_top_border gt_column_spanner_outer" rowspan="1" colspan="1" scope="col" id></th>
    </tr>
    <tr class="gt_col_headings gt_spanner_row">
      <th class="gt_col_heading gt_columns_bottom_border gt_left" rowspan="2" colspan="1" scope="col" id=""></th>
      <th class="gt_col_heading gt_columns_bottom_border gt_right" rowspan="2" colspan="1" scope="col" id="year">year</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_left" rowspan="2" colspan="1" scope="col" id="bdy_style">bdy_style</th>
      <th class="gt_center gt_columns_top_border gt_column_spanner_outer" rowspan="1" colspan="6" scope="colgroup" id="performance">
        <span class="gt_column_spanner">performance</span>
      </th>
      <th class="gt_col_heading gt_columns_bottom_border gt_right" rowspan="2" colspan="1" scope="col" id="msrp">msrp</th>
    </tr>
    <tr class="gt_col_headings">
      <th class="gt_col_heading gt_columns_bottom_border gt_right" rowspan="1" colspan="1" scope="col" id="hp">hp</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_right" rowspan="1" colspan="1" scope="col" id="hp_rpm">hp_rpm</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_right" rowspan="1" colspan="1" scope="col" id="trq">trq</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_right" rowspan="1" colspan="1" scope="col" id="trq_rpm">trq_rpm</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_right" rowspan="1" colspan="1" scope="col" id="mpg_c">mpg_c</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_right" rowspan="1" colspan="1" scope="col" id="mpg_h">mpg_h</th>
    </tr>
  </thead>
  <tbody class="gt_table_body">
    <tr><th id="stub_1_1" scope="row" class="gt_row gt_left gt_stub">GT</th>
<td headers="stub_1_1 year" class="gt_row gt_right">2017</td>
<td headers="stub_1_1 bdy_style" class="gt_row gt_left">coupe</td>
<td headers="stub_1_1 hp" class="gt_row gt_right">647</td>
<td headers="stub_1_1 hp_rpm" class="gt_row gt_right">6250</td>
<td headers="stub_1_1 trq" class="gt_row gt_right">550</td>
<td headers="stub_1_1 trq_rpm" class="gt_row gt_right">5900</td>
<td headers="stub_1_1 mpg_c" class="gt_row gt_right">11</td>
<td headers="stub_1_1 mpg_h" class="gt_row gt_right">18</td>
<td headers="stub_1_1 msrp" class="gt_row gt_right">447000</td></tr>
    <tr><th id="stub_1_2" scope="row" class="gt_row gt_left gt_stub">458 Speciale</th>
<td headers="stub_1_2 year" class="gt_row gt_right">2015</td>
<td headers="stub_1_2 bdy_style" class="gt_row gt_left">coupe</td>
<td headers="stub_1_2 hp" class="gt_row gt_right">597</td>
<td headers="stub_1_2 hp_rpm" class="gt_row gt_right">9000</td>
<td headers="stub_1_2 trq" class="gt_row gt_right">398</td>
<td headers="stub_1_2 trq_rpm" class="gt_row gt_right">6000</td>
<td headers="stub_1_2 mpg_c" class="gt_row gt_right">13</td>
<td headers="stub_1_2 mpg_h" class="gt_row gt_right">17</td>
<td headers="stub_1_2 msrp" class="gt_row gt_right">291744</td></tr>
    <tr><th id="stub_1_3" scope="row" class="gt_row gt_left gt_stub">458 Spider</th>
<td headers="stub_1_3 year" class="gt_row gt_right">2015</td>
<td headers="stub_1_3 bdy_style" class="gt_row gt_left">convertible</td>
<td headers="stub_1_3 hp" class="gt_row gt_right">562</td>
<td headers="stub_1_3 hp_rpm" class="gt_row gt_right">9000</td>
<td headers="stub_1_3 trq" class="gt_row gt_right">398</td>
<td headers="stub_1_3 trq_rpm" class="gt_row gt_right">6000</td>
<td headers="stub_1_3 mpg_c" class="gt_row gt_right">13</td>
<td headers="stub_1_3 mpg_h" class="gt_row gt_right">17</td>
<td headers="stub_1_3 msrp" class="gt_row gt_right">263553</td></tr>
    <tr><th id="stub_1_4" scope="row" class="gt_row gt_left gt_stub">458 Italia</th>
<td headers="stub_1_4 year" class="gt_row gt_right">2014</td>
<td headers="stub_1_4 bdy_style" class="gt_row gt_left">coupe</td>
<td headers="stub_1_4 hp" class="gt_row gt_right">562</td>
<td headers="stub_1_4 hp_rpm" class="gt_row gt_right">9000</td>
<td headers="stub_1_4 trq" class="gt_row gt_right">398</td>
<td headers="stub_1_4 trq_rpm" class="gt_row gt_right">6000</td>
<td headers="stub_1_4 mpg_c" class="gt_row gt_right">13</td>
<td headers="stub_1_4 mpg_h" class="gt_row gt_right">17</td>
<td headers="stub_1_4 msrp" class="gt_row gt_right">233509</td></tr>
    <tr><th id="stub_1_5" scope="row" class="gt_row gt_left gt_stub">488 GTB</th>
<td headers="stub_1_5 year" class="gt_row gt_right">2016</td>
<td headers="stub_1_5 bdy_style" class="gt_row gt_left">coupe</td>
<td headers="stub_1_5 hp" class="gt_row gt_right">661</td>
<td headers="stub_1_5 hp_rpm" class="gt_row gt_right">8000</td>
<td headers="stub_1_5 trq" class="gt_row gt_right">561</td>
<td headers="stub_1_5 trq_rpm" class="gt_row gt_right">3000</td>
<td headers="stub_1_5 mpg_c" class="gt_row gt_right">15</td>
<td headers="stub_1_5 mpg_h" class="gt_row gt_right">22</td>
<td headers="stub_1_5 msrp" class="gt_row gt_right">245400</td></tr>
    <tr><th id="stub_1_6" scope="row" class="gt_row gt_left gt_stub">California</th>
<td headers="stub_1_6 year" class="gt_row gt_right">2015</td>
<td headers="stub_1_6 bdy_style" class="gt_row gt_left">convertible</td>
<td headers="stub_1_6 hp" class="gt_row gt_right">553</td>
<td headers="stub_1_6 hp_rpm" class="gt_row gt_right">7500</td>
<td headers="stub_1_6 trq" class="gt_row gt_right">557</td>
<td headers="stub_1_6 trq_rpm" class="gt_row gt_right">4750</td>
<td headers="stub_1_6 mpg_c" class="gt_row gt_right">16</td>
<td headers="stub_1_6 mpg_h" class="gt_row gt_right">23</td>
<td headers="stub_1_6 msrp" class="gt_row gt_right">198973</td></tr>
    <tr><th id="stub_1_7" scope="row" class="gt_row gt_left gt_stub">GTC4Lusso</th>
<td headers="stub_1_7 year" class="gt_row gt_right">2017</td>
<td headers="stub_1_7 bdy_style" class="gt_row gt_left">coupe</td>
<td headers="stub_1_7 hp" class="gt_row gt_right">680</td>
<td headers="stub_1_7 hp_rpm" class="gt_row gt_right">8250</td>
<td headers="stub_1_7 trq" class="gt_row gt_right">514</td>
<td headers="stub_1_7 trq_rpm" class="gt_row gt_right">5750</td>
<td headers="stub_1_7 mpg_c" class="gt_row gt_right">12</td>
<td headers="stub_1_7 mpg_h" class="gt_row gt_right">17</td>
<td headers="stub_1_7 msrp" class="gt_row gt_right">298000</td></tr>
    <tr><th id="stub_1_8" scope="row" class="gt_row gt_left gt_stub">FF</th>
<td headers="stub_1_8 year" class="gt_row gt_right">2015</td>
<td headers="stub_1_8 bdy_style" class="gt_row gt_left">coupe</td>
<td headers="stub_1_8 hp" class="gt_row gt_right">652</td>
<td headers="stub_1_8 hp_rpm" class="gt_row gt_right">8000</td>
<td headers="stub_1_8 trq" class="gt_row gt_right">504</td>
<td headers="stub_1_8 trq_rpm" class="gt_row gt_right">6000</td>
<td headers="stub_1_8 mpg_c" class="gt_row gt_right">11</td>
<td headers="stub_1_8 mpg_h" class="gt_row gt_right">16</td>
<td headers="stub_1_8 msrp" class="gt_row gt_right">295000</td></tr>
  </tbody>
  &#10;  
</table>
</div>

``` r

# Expected result
gtcar_df |>
  gt(rowname_col = "model") |>
  tab_spanner(
    label = "performance v2",
    columns = c(
      hp, hp_rpm, trq, trq_rpm,
      mpg_c, mpg_h
    )
  )
```

<table class="gt_table" data-quarto-disable-processing="false" data-quarto-bootstrap="false">
  <thead>
    &#10;    <tr class="gt_col_headings gt_spanner_row">
      <th class="gt_col_heading gt_columns_bottom_border gt_left" rowspan="2" colspan="1" scope="col" id=""></th>
      <th class="gt_col_heading gt_columns_bottom_border gt_right" rowspan="2" colspan="1" scope="col" id="year">year</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_left" rowspan="2" colspan="1" scope="col" id="bdy_style">bdy_style</th>
      <th class="gt_center gt_columns_top_border gt_column_spanner_outer" rowspan="1" colspan="6" scope="colgroup" id="performance v2">
        <span class="gt_column_spanner">performance v2</span>
      </th>
      <th class="gt_col_heading gt_columns_bottom_border gt_right" rowspan="2" colspan="1" scope="col" id="msrp">msrp</th>
    </tr>
    <tr class="gt_col_headings">
      <th class="gt_col_heading gt_columns_bottom_border gt_right" rowspan="1" colspan="1" scope="col" id="hp">hp</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_right" rowspan="1" colspan="1" scope="col" id="hp_rpm">hp_rpm</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_right" rowspan="1" colspan="1" scope="col" id="trq">trq</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_right" rowspan="1" colspan="1" scope="col" id="trq_rpm">trq_rpm</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_right" rowspan="1" colspan="1" scope="col" id="mpg_c">mpg_c</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_right" rowspan="1" colspan="1" scope="col" id="mpg_h">mpg_h</th>
    </tr>
  </thead>
  <tbody class="gt_table_body">
    <tr><th id="stub_1_1" scope="row" class="gt_row gt_left gt_stub">GT</th>
<td headers="stub_1_1 year" class="gt_row gt_right">2017</td>
<td headers="stub_1_1 bdy_style" class="gt_row gt_left">coupe</td>
<td headers="stub_1_1 hp" class="gt_row gt_right">647</td>
<td headers="stub_1_1 hp_rpm" class="gt_row gt_right">6250</td>
<td headers="stub_1_1 trq" class="gt_row gt_right">550</td>
<td headers="stub_1_1 trq_rpm" class="gt_row gt_right">5900</td>
<td headers="stub_1_1 mpg_c" class="gt_row gt_right">11</td>
<td headers="stub_1_1 mpg_h" class="gt_row gt_right">18</td>
<td headers="stub_1_1 msrp" class="gt_row gt_right">447000</td></tr>
    <tr><th id="stub_1_2" scope="row" class="gt_row gt_left gt_stub">458 Speciale</th>
<td headers="stub_1_2 year" class="gt_row gt_right">2015</td>
<td headers="stub_1_2 bdy_style" class="gt_row gt_left">coupe</td>
<td headers="stub_1_2 hp" class="gt_row gt_right">597</td>
<td headers="stub_1_2 hp_rpm" class="gt_row gt_right">9000</td>
<td headers="stub_1_2 trq" class="gt_row gt_right">398</td>
<td headers="stub_1_2 trq_rpm" class="gt_row gt_right">6000</td>
<td headers="stub_1_2 mpg_c" class="gt_row gt_right">13</td>
<td headers="stub_1_2 mpg_h" class="gt_row gt_right">17</td>
<td headers="stub_1_2 msrp" class="gt_row gt_right">291744</td></tr>
    <tr><th id="stub_1_3" scope="row" class="gt_row gt_left gt_stub">458 Spider</th>
<td headers="stub_1_3 year" class="gt_row gt_right">2015</td>
<td headers="stub_1_3 bdy_style" class="gt_row gt_left">convertible</td>
<td headers="stub_1_3 hp" class="gt_row gt_right">562</td>
<td headers="stub_1_3 hp_rpm" class="gt_row gt_right">9000</td>
<td headers="stub_1_3 trq" class="gt_row gt_right">398</td>
<td headers="stub_1_3 trq_rpm" class="gt_row gt_right">6000</td>
<td headers="stub_1_3 mpg_c" class="gt_row gt_right">13</td>
<td headers="stub_1_3 mpg_h" class="gt_row gt_right">17</td>
<td headers="stub_1_3 msrp" class="gt_row gt_right">263553</td></tr>
    <tr><th id="stub_1_4" scope="row" class="gt_row gt_left gt_stub">458 Italia</th>
<td headers="stub_1_4 year" class="gt_row gt_right">2014</td>
<td headers="stub_1_4 bdy_style" class="gt_row gt_left">coupe</td>
<td headers="stub_1_4 hp" class="gt_row gt_right">562</td>
<td headers="stub_1_4 hp_rpm" class="gt_row gt_right">9000</td>
<td headers="stub_1_4 trq" class="gt_row gt_right">398</td>
<td headers="stub_1_4 trq_rpm" class="gt_row gt_right">6000</td>
<td headers="stub_1_4 mpg_c" class="gt_row gt_right">13</td>
<td headers="stub_1_4 mpg_h" class="gt_row gt_right">17</td>
<td headers="stub_1_4 msrp" class="gt_row gt_right">233509</td></tr>
    <tr><th id="stub_1_5" scope="row" class="gt_row gt_left gt_stub">488 GTB</th>
<td headers="stub_1_5 year" class="gt_row gt_right">2016</td>
<td headers="stub_1_5 bdy_style" class="gt_row gt_left">coupe</td>
<td headers="stub_1_5 hp" class="gt_row gt_right">661</td>
<td headers="stub_1_5 hp_rpm" class="gt_row gt_right">8000</td>
<td headers="stub_1_5 trq" class="gt_row gt_right">561</td>
<td headers="stub_1_5 trq_rpm" class="gt_row gt_right">3000</td>
<td headers="stub_1_5 mpg_c" class="gt_row gt_right">15</td>
<td headers="stub_1_5 mpg_h" class="gt_row gt_right">22</td>
<td headers="stub_1_5 msrp" class="gt_row gt_right">245400</td></tr>
    <tr><th id="stub_1_6" scope="row" class="gt_row gt_left gt_stub">California</th>
<td headers="stub_1_6 year" class="gt_row gt_right">2015</td>
<td headers="stub_1_6 bdy_style" class="gt_row gt_left">convertible</td>
<td headers="stub_1_6 hp" class="gt_row gt_right">553</td>
<td headers="stub_1_6 hp_rpm" class="gt_row gt_right">7500</td>
<td headers="stub_1_6 trq" class="gt_row gt_right">557</td>
<td headers="stub_1_6 trq_rpm" class="gt_row gt_right">4750</td>
<td headers="stub_1_6 mpg_c" class="gt_row gt_right">16</td>
<td headers="stub_1_6 mpg_h" class="gt_row gt_right">23</td>
<td headers="stub_1_6 msrp" class="gt_row gt_right">198973</td></tr>
    <tr><th id="stub_1_7" scope="row" class="gt_row gt_left gt_stub">GTC4Lusso</th>
<td headers="stub_1_7 year" class="gt_row gt_right">2017</td>
<td headers="stub_1_7 bdy_style" class="gt_row gt_left">coupe</td>
<td headers="stub_1_7 hp" class="gt_row gt_right">680</td>
<td headers="stub_1_7 hp_rpm" class="gt_row gt_right">8250</td>
<td headers="stub_1_7 trq" class="gt_row gt_right">514</td>
<td headers="stub_1_7 trq_rpm" class="gt_row gt_right">5750</td>
<td headers="stub_1_7 mpg_c" class="gt_row gt_right">12</td>
<td headers="stub_1_7 mpg_h" class="gt_row gt_right">17</td>
<td headers="stub_1_7 msrp" class="gt_row gt_right">298000</td></tr>
    <tr><th id="stub_1_8" scope="row" class="gt_row gt_left gt_stub">FF</th>
<td headers="stub_1_8 year" class="gt_row gt_right">2015</td>
<td headers="stub_1_8 bdy_style" class="gt_row gt_left">coupe</td>
<td headers="stub_1_8 hp" class="gt_row gt_right">652</td>
<td headers="stub_1_8 hp_rpm" class="gt_row gt_right">8000</td>
<td headers="stub_1_8 trq" class="gt_row gt_right">504</td>
<td headers="stub_1_8 trq_rpm" class="gt_row gt_right">6000</td>
<td headers="stub_1_8 mpg_c" class="gt_row gt_right">11</td>
<td headers="stub_1_8 mpg_h" class="gt_row gt_right">16</td>
<td headers="stub_1_8 msrp" class="gt_row gt_right">295000</td></tr>
  </tbody>
  &#10;  
</table>
</div>

``` r
sessionInfo()
#> R version 4.3.1 (2023-06-16 ucrt)
#> Platform: x86_64-w64-mingw32/x64 (64-bit)
#> Running under: Windows 11 x64 (build 22621)
#> 
#> Matrix products: default
#> 
#> 
#> locale:
#> [1] LC_COLLATE=English_United States.utf8 
#> [2] LC_CTYPE=English_United States.utf8   
#> [3] LC_MONETARY=English_United States.utf8
#> [4] LC_NUMERIC=C                          
#> [5] LC_TIME=English_United States.utf8    
#> 
#> time zone: America/New_York
#> tzcode source: internal
#> 
#> attached base packages:
#> [1] stats     graphics  grDevices utils     datasets  methods   base     
#> 
#> other attached packages:
#> [1] gt_0.9.0
#> 
#> loaded via a namespace (and not attached):
#>  [1] vctrs_0.6.3      cli_3.6.1        knitr_1.43       rlang_1.1.1     
#>  [5] xfun_0.39        generics_0.1.3   glue_1.6.2       htmltools_0.5.5 
#>  [9] fansi_1.0.4      rmarkdown_2.22   evaluate_0.21    tibble_3.2.1    
#> [13] fastmap_1.1.1    yaml_2.3.7       lifecycle_1.0.3  compiler_4.3.1  
#> [17] dplyr_1.1.2      fs_1.6.2         pkgconfig_2.0.3  rstudioapi_0.14 
#> [21] digest_0.6.31    R6_2.5.1         reprex_2.0.2     tidyselect_1.2.0
#> [25] utf8_1.2.3       pillar_1.9.0     magrittr_2.0.3   tools_4.3.1     
#> [29] withr_2.5.0      xml2_1.3.4
```
## Expected result

Spanner should be replaced instead of adding a second one.

## Session info

End the reproducible example with a call to `sessionInfo()` in the same session (e.g. `reprex(session_info = TRUE)`) and include the output.

**Comment by rich-iannone** [comment]
To fully replace that spanner we need to specify the `level`, so the last statement should instead be:

```r
# Replacing spanner 
try1 %>%
  tab_spanner(
    label = "performance v2",
    columns = c(
      hp, hp_rpm, trq, trq_rpm,
      mpg_c, mpg_h
    ),
    level = 1,
    replace = TRUE
  )
```

Even with `replace = TRUE`, the standard behavior of stacking new spanners on top of existing will happen. We really need to specify an explicit `level` and also ensure that `replace = TRUE` (without the latter, you'll get an error and message about an already-existing spanner at the location specified). I looked at the documentation for `tab_spanner()` and none of this is clearly stated at all, so I will add an example on how to do this.

**Comment by szimmer** [comment]
Thanks! I think clarity in documentation would be great. In my mind, a replace argument would **replace** the value.

**Comment by rich-iannone** [comment]
Added the relevant documentation to clarify this in https://github.com/rstudio/gt/commit/23bd57c638264a08b075d4568b3cd23ea518a8bd, so, closing this now.
