### ISSUE TITLE
data_color() to include column name in error message

### ISSUE THREAD

**Issue by sanjmeh** [rstudio/gt#1373]
data_color() is great, however a little error message improvement is desired.

## Existing error
```
Error in scales::col_numeric: Wasn't able to determine range of domain
  118: stop
  117: scales::col_numeric
  116: data_color
   97: render_gt [/home/.../server.R#2631]
   96: func
   83: renderFunc
   82: output$pilfer_gt_tab
    1: runApp
```

## Proposal
The column name should also be provided (column that failed in the `scales::col_numeric` call). It would avoid manually testing each column. This is especially painful when we use data_color() from server.R for a large number of columns.

**Comment by rich-iannone** [comment]
I can try to make this better by getting ahead of a potential scales error. Could you provide some example code where this error might occur?
