### ISSUE TITLE
Multiple `tab_style` calls lead to error for interactive tables

### ISSUE THREAD

**Issue by morrisLuke** [rstudio/gt#1377]
Multiple calls of `tab_style()` leads to an error when attempting to turn a table interactive

Table will work fine static, but add the opt_interactive() and `Error in tmp_rownum[1] <- which(rownum_final == styles$tbl$rown[i] : replacement has zero length`

```
library(tidyverse)
library(gt)
towny |>
  gt() |>
  tab_header(
    title = md("**Dummy Dashboard Name**")
  ) |>tab_row_group(label = "GRP",
                    id = "grp",
                    rows = 101) |>
  tab_row_group(label = "SOME GROUPING",
                id = "gcc",
                rows = c(96:100)) |>
  tab_row_group(label = "ANOTHER GROUPING",
                id = "g1",
                rows = c(90:95)) |>
  tab_row_group(label = "MORE GROUPING",
                id = "g2",
                rows = c(87:89)) |>
  tab_row_group(label = "YET ANOTHER GROUPING",
                id = "g3",
                rows = c(80:86)) |>
  tab_row_group(label = "AGAIN, GROUPING",
                id = "g4",
                rows = c(73:79)) |>
  tab_row_group(label = "ING, GROUP",
                id = "g5",
                rows = c(68:72)) |>
  tab_row_group(label = "EVEN MORE GROUPING",
                id = "g6",
                rows = c(53:67)) |>
  tab_row_group(label = "GROUPS AND GROUPS AND GROUPS",
                id = "g7",
                rows = c(45:52)) |>
  tab_row_group(label = "OH HEY MORE GROUPING",
                id = "g8",
                rows = c(26:44)) |>
  tab_row_group(label = "GROUPAGE",
                id = "g9",
                rows = c(1:25)) |>
  fmt_percent(ends_with("pct"), decimals = 1) |>
  cols_hide(c(1,3:14)) |>
  cols_align(
    align = "center",
    columns = c(15:25)
  ) |>
  tab_style(
    style = cell_borders(sides = "all", color = "#c8c8c8", style = "solid", weight = px(1)),
    locations = cells_body(everything())
  ) |>
  tab_style(
    style = list(
    cell_fill(color = "#3bedc466"),
    cell_text(weight = "bolder")
    ),
    locations = cells_row_groups(everything())
  ) |>
  tab_style(
    style = list(
    cell_text(weight = "bold"),
    cell_borders(sides = "all", color = "#c8c8c8", style = "solid", weight = px(1))
    ),
    locations = cells_column_labels(everything())
  ) |>
  opt_interactive()
```
Again, static version worked fine. Then I got the same error when adding `opt_interactive` to the chain

**Comment by ArthurAndrews** [comment]
This bug can occur in simpler circumstances than this.  I find I can't bold the column titles.  

``` r
library(gt)

mtcars |> 
  gt() |> 
  tab_style(cell_text(weight = "bold"), cells_column_labels()) |> 
  opt_interactive()
#> Error in tmp_rownum[i] <- which(rownum_final == styles_tbl$rownum[i]): replacement has length zero
```

<sup>Created on 2023-10-11 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by lgnbhl** [comment]
Here a workaround to make all the column titles of the table bold (but doesn't fix more advanced styling, such filling cell with a specific color):

``` r
library(gt)

mtcars |>
  gt() |>
  cols_label_with(
    fn = function(x) {
      gt::html(paste0("<span style ='font-weight:bold'>", x, "</span>"))
    }
  ) |>
  opt_interactive()
```

**Comment by lgnbhl** [comment]
> Here a workaround to make all the column titles of the table bold (but doesn't fix more advanced styling, such filling cell with a specific color):
> 
> ```r
> library(gt)
> 
> mtcars |>
>   gt() |>
>   cols_label_with(
>     fn = function(x) {
>       gt::html(paste0("<span style ='font-weight:bold'>", x, "</span>"))
>     }
>   ) |>
>   opt_interactive()
> ```
> 
> Is there a workaround for styling the column background color? @rich-iannone

A possible workaround can be found here: https://gt.albert-rapp.de/styling

**Comment by markjrieke** [comment]
I was able to do additional styling by passing more html styles to the span. Note that for the text_transform block, I had to use glue syntax rather than paste // the inverse doesn't work:

```r
library(gt)

mtcars |>
  gt() |>
  cols_label_with(
    fn = function(x) {
      gt::html(paste0("<span style ='font-weight:bold;font-family:IBM Plex Sans;font-size:6px'>", x, "</span>"))
    }
  ) |>
  text_transform(
    fn = function(x) {
      glue::glue("<span style='font-family:IBM Plex Sans;font-size:14px;color:blue;'>{x}</span>")
    },
    locations = cells_body()
  ) |> 
  opt_interactive()
```

**Comment by olivroy** [comment]
Note that the original code no longer errors with gt 0.11.0. Please open a new issue for the styling problems (with a minimal reproducible example).  Support was added for spanners in interactive

The table looks like this with gt 0.11 with the code provided in https://github.com/rstudio/gt/issues/1377#issue-1805726319

![image](https://github.com/rstudio/gt/assets/52606734/3830cfe5-6d41-4a62-bbd1-7cf3cb2f4190)
