### ISSUE TITLE
gt outputs differ between Rstudio and quarto pdf

### ISSUE THREAD

**Issue by shriv** [rstudio/gt#1382]
## Prework

* [x] Read and agree to the [code of conduct](https://www.contributor-covenant.org/version/2/1/code_of_conduct.html) and [contributing guidelines](https://github.com/rstudio/gt/blob/master/.github/CONTRIBUTING.md).
* [x] If there is [already a relevant issue](https://github.com/rstudio/gt/issues), whether open or closed, comment on the existing thread instead of posting a new issue.

## Description

`gt` doesn't seem to produce the same output in Quarto pdf as it does within Rstudio. My quarto yml is very simple (just the default with `format = pdf`) so I haven't included it in the reprex. I'm not sure if this a user error so any help would be appreciated :-)

## Reproducible example
```r
library(gt)
library(dplyr)

structure(
  list(
    cargo_full = c(
      "Import",
      "Export",
      "",
      "Domestic",
      "Export transhipment",
      "Re-export",
      "Import transhipment"
    ),
    "FALSE" = c(1214L,
                583L, 5228L, 12488L, 4549L, 190L, 523L),
    "TRUE" = c(249456L,
               238755L, 111688L, 99142L, 29998L, 19798L, 12969L),
    proportion_true = c(
      0.317139620712934,
      0.303535173109953,
      0.141991733845592,
      0.126041691828305,
      0.0381372039243257,
      0.0251696900891326,
      0.0164878124439822
    ),
    proportion_false = c(
      0.00154338841136514,
      0.00074118240842329,
      0.00664648650297935,
      0.0158763051739109,
      0.00578325690551895,
      0.000241551728302616,
      0.000664902915275096
    ),
    cumulative_true = c(
      0.317139620712934,
      0.620674793822887,
      0.762666527668479,
      0.888708219496784,
      0.92684542342111,
      0.952015113510242,
      0.968502925954225
    ),
    cumulative_false = c(
      0.00154338841136514,
      0.00228457081978843,
      0.00893105732276778,
      0.0248073624966787,
      0.0305906194021976,
      0.0308321711305002,
      0.0314970740457753
    )
  ),
  row.names = c(NA,-7L),
  class = c("tbl_df", "tbl", "data.frame")
) |>
  select(-cumulative_false) |>
  mutate(cargo_full = if_else(cargo_full == "", "Unclassified", cargo_full)) |>
  rename(correct = `TRUE`,
         incorrect = `FALSE`) |>
  gt::gt() |>
  fmt_percent(columns = ends_with("true"), decimals = 1) |>
  fmt_percent(columns = ends_with("false"), decimals = 1) |>
  cols_label(
    .list = c(
      "cargo_full" = "Movement",
      "proportion_true" = "% correct",
      "proportion_false" = "% incorrect",
      "cumulative_true" = "% cumulative correct"
    )
  ) |>
  cols_align(align = "center") |>
  tab_header(title = "Movement classification in SAS vs. R",
             subtitle = "Metrics compare R classification against SAS classification (ground truth)") |>
  tab_options(table.width = pct(70)) 
```

## Expected result
Expecting centre aligned headers and column names over multiple lines as rendered in Rstudio. 
![image](https://github.com/rstudio/gt/assets/3827179/25facc6c-1e83-465e-86d1-9339bbbb1ee0)

The pdf generated by quarto has misaligned headers and single line column names. 
![image](https://github.com/rstudio/gt/assets/3827179/34f20f34-27c4-41e7-ab61-c2fd4d9d0668)

## Session info

End the reproducible example with a call to `sessionInfo()` in the same session (e.g. `reprex(session_info = TRUE)`) and include the output.

**Comment by rich-iannone** [comment]
The LaTeX output in the PDF is correct and as expected. Whereas HTML tables will automatically insert line breaks to fit content, LaTeX does not do that (see: https://tex.stackexchange.com/questions/248053/a-header-in-a-table-with-two-lines). There isn't yet a clean method for introducing manual line breaks in LaTeX column labels but *it is* being investigated.
