### ISSUE TITLE
opt_interactive doesn't appear to work with gt_fa_column

### ISSUE THREAD

**Issue by joekeane7** [rstudio/gt#1400]
## Prework

* [x] Read and agree to the [code of conduct](https://www.contributor-covenant.org/version/2/1/code_of_conduct.html) and [contributing guidelines](https://github.com/rstudio/gt/blob/master/.github/CONTRIBUTING.md).
* [ ] If there is [already a relevant issue](https://github.com/rstudio/gt/issues), whether open or closed, comment on the existing thread instead of posting a new issue.

## Description

The opt_interactive addition is fantastic, I'm using it in my shiny reports and it is making life a lot easier in this regard.

However I have noticed on top of the tab_style issue that I have seen has already been logged, the function doesn't seem to recognise gt_fa_column. I use this sometimes for easy display of font awesome icons in gt.

## Reproducible example

library(gt)
library(tibble)

data <- tribble(
  ~Column_Name, ~imp_icon,
  "metric1", "chevron-right",
  "metric2", "chevron-right",
  "metric3", "chevron-right",
  "metric4", "chevron-right",
  "metric5", "chevron-up",
  "metric6", "chevron-up"
)

##Works as expected##
data %>%
  gt()  %>%
  gt_fa_column(column = imp_icon,
            palette = "black",
            align = "center"
  )

##Only displays the SVG text##

data %>%
  gt()  %>%
  opt_interactive() %>%
  gt_fa_column(column = imp_icon,
            palette = "black",
            align = "center"
  )

## Expected result

What should have happened? Please be as specific as possible.

## Session info

End the reproducible example with a call to `sessionInfo()` in the same session (e.g. `reprex(session_info = TRUE)`) and include the output.

**Comment by rich-iannone** [comment]
The `gt_fa_column()` function is from `gtExtras` and unfortunately yes, it doesn't work and I need to communicate with the maintainer to help fix the problem. However, there is a nice workaround that *does* work (and you can use it now, so long as you don't mind using the dev version of `gt`, and, the CRAN build of the `fontawesome` package). That workaround involves using the new `fmt_icon()` function. Here is the code:

```r
library(gt)
library(tibble)

data <- tribble(
  ~Column_Name, ~imp_icon,
  "metric1", "chevron-right",
  "metric2", "chevron-right",
  "metric3", "chevron-right",
  "metric4", "chevron-right",
  "metric5", "chevron-up",
  "metric6", "chevron-up"
)

data %>%
  gt() %>%
  opt_interactive() %>%
  fmt_icon(column = imp_icon, fill_color = "black") %>%
  cols_align(align = "center", columns = imp_icon)
```

<img width="1024" alt="fmt_icon_interactive" src="https://github.com/rstudio/gt/assets/5612024/cbbd6220-d477-4d10-a9ab-0ef06a81b8bf">

This works quite well with both static and interactive HTML tables. I hope this solves the issue (so closing it for now); if not, then please re-open.
