### ISSUE TITLE
Disable random div id generation?

### ISSUE THREAD

**Issue by andrewheiss** [rstudio/gt#141]
Right now, [print.R generates a random name](https://github.com/rstudio/gt/blob/0df27115d1453c5c100c98aaeb189c5a34d522a4/R/print.R#L47) for the wrapping div for gt tables (e.g. `<div id="joisdfjkdf">`). This is nice for uniqueness in HTML, but it causes issues with version control, since the table ID changes often (forcing new changes in git). 

Right now, my solution is to use `set.seed()` before any `gt()` stuff, and that's working, but it might be nice to have an argument to `gt()` or something that disables the random id generation and allows users to supply their own.

**Comment by rich-iannone** [comment]
This sounds like a good idea. Thanks for suggesting it!
