### ISSUE TITLE
fmt_flag assign wrong flag and ISO code to the Netherlands

### ISSUE THREAD

**Issue by jamysiak** [rstudio/gt#1432]
## Prework

* [x] Read and agree to the [code of conduct](https://www.contributor-covenant.org/version/2/1/code_of_conduct.html) and [contributing guidelines](https://github.com/rstudio/gt/blob/master/.github/CONTRIBUTING.md).
* [x] If there is [already a relevant issue](https://github.com/rstudio/gt/issues), whether open or closed, comment on the existing thread instead of posting a new issue.

## Description

Describe the bug clearly and concisely. 
Hi there. Thank you for the gt() which is brilliant and useful. 
I noticed an issue with the **fmt_flag** function that generates flag icons for countries using their ISO2 country codes. Specifically, there seems to be a bug when it comes to the **Netherlands** (with the correct ISO2 code "**NL**"). The function doesn't display the flag correctly. In an example from April on your [blog post](https://posit.co/blog/new-formatting-functions-in-gt-0-9-0/), the function associates the ISO2 code "NU" with the Netherlands. However, "NU" is actually the code for **Niue**, a self-governing territory of New Zealand. This same error is present in the countrypops dataset, where the Netherlands is associated with the incorrect ISO2 code "NU". As a result, the flag displayed for the Netherlands using **fmt_flag** appears to be the flag of Niue.

## Reproducible example
data.frame(ISO2 =c("NU", "NL", "DE", "IT")) %>%  gt() %>%
  fmt_flag(columns = ISO2)

* [x] Post a [minimal reproducible example](https://www.tidyverse.org/help/) so the maintainer can troubleshoot the problems you identify. A reproducible example is:
    * [x] **Runnable**: post enough R code and data so any onlooker can create the error on their own computer.
    * [x] **Minimal**: reduce runtime wherever possible and remove complicated details that are irrelevant to the issue at hand.
    * [x] **Readable**: format your code according to the [tidyverse style guide](https://style.tidyverse.org/).

## Expected result

What should have happened? Please be as specific as possible.

## Session info

End the reproducible example with a call to `sessionInfo()` in the same session (e.g. `reprex(session_info = TRUE)`) and include the output.

**Comment by rich-iannone** [comment]
This was fixed in https://github.com/rstudio/gt/pull/1319. For the time being (until the next release of gt) you'll need to install the development version of the package with `devtools::install_github("rstudio/gt")`.
