### ISSUE TITLE
Feature request: "fmt_accounting()"

### ISSUE THREAD

**Issue by steveputman** [rstudio/gt#144]
This was referred to in passing in #1, but it would be wonderful to be able to format negative numbers with parentheses. The `formattable` package had this (though I note that there are some annoyances with alignment, more so in pdf than in html).

Thanks again for the great package!

**Comment by rich-iannone** [comment]
You’re in luck because we already have this functionality. I think it’s probably badly named though: the argument `negative_val` can be set to `parens` in `fmt_number()` and some other functions as well.

**Comment by steveputman** [comment]
Ha! Awesome--sorry I didn't failed to track that down on my own (read *all* the code, Steve).

**Comment by steveputman** [comment]
I made some changes on my fork to deal with the alignment issues when using parentheses (typically you want the last digit of the positive number to line up with the last digit of the negative number rather than the parenthesis). The modification appends `hphantom{(}` in LaTeX or a hidden `<span>` with a parenthesis in HTML to all non-negative numbers to make the alignment work in `fmt_number()`, `fmt_percent()`, and `fmt_currency()`. 

Not the prettiest solution, but it seems to work. Happy to prepare PR if interested.

**Comment by rich-iannone** [comment]
@steveputman I'm looking for alignment solutions in general, so this is great! I'll reopen this issue (where you could show the API usage and outputs) and please do start a PR (and we can discuss the implementation more in there). Thanks!

**Comment by steveputman** [comment]
Great. The idea was to honor whatever was passed in `cols_align`, so no API changes (unless for some reason, one needed the option of aligning the paren with the digit). 

With this code in an R Markdown file (varying the output parameter):
````
---
title: "parens_alignment"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(gt)

df <- tribble(
  ~chars, ~dates, ~curr, ~num, ~pct,
  "rowA", "2018-01-01", 1000.25, 0, .353,
  "rowB", "2018-01-02", -24.37, 10000.823, 0,
  "rowC", "2018-01-03", 0, -.7209, 0.234,
  "rowD", "2018-01-04", -24385.1, 288.21, -1.399
  ) 

rightalign <- df %>%
  gt() %>%
  tab_header(
    title = "Default alignment",
    subtitle = "-"
  ) %>%
  fmt_currency(
    columns = vars(curr),
    negative_val = "parens"
  ) %>%
  fmt_number(
    columns = vars(num),
    negative_val = "parens"
  ) %>%
  fmt_percent(
    columns = vars(pct),
    negative_val = "parens"
  ) 

leftalign <- rightalign %>%
  tab_header(
    title = "Left alignment",
    subtitle = "-"
  ) %>%
  cols_align(
    align = "left"
  )

centeralign <- rightalign %>%
  tab_header(
    title = "Center alignment",
    subtitle = "-"
  ) %>%
  cols_align(
    align = "center"
  )
```
`r rightalign`

`r leftalign`

`r centeralign`
````
You get this output in pdf: 
[parens_alignment.pdf](https://github.com/rstudio/gt/files/2788747/parens_alignment.pdf)
![image](https://user-images.githubusercontent.com/4965916/51630288-67ebfc00-1f0f-11e9-970a-7644c5a208c5.png)


And this in html:

![image](https://user-images.githubusercontent.com/4965916/51630224-3b37e480-1f0f-11e9-8e5c-ec0da8f9e2f6.png)
