### ISSUE TITLE
Compatibility R version

### ISSUE THREAD

**Issue by Son-of-Sevenless** [rstudio/gt#147]
Warning in install.packages :
  package ‘https://github.com/rstudio/gt.git’ is not available (for R version 3.5.1)

Is there a workaround?

**Comment by rich-iannone** [comment]
Hello, this package is not yet available on CRAN so you would need to install it directly from GitHub. For that, ensure you have **devtools** installed and run these statements:

```r
install.packages("devtools")
remotes::install_github("rstudio/gt")
```
