### ISSUE TITLE
[quarto] disable_processing options should opt-out `fmt_markdown` specific output for quarto

### ISSUE THREAD

**Issue by cderv** [rstudio/gt#1488]
````markdown
---
title: "Test"
format: html
keep-md: true
---

```{r}
library(gt)
data.frame(A = "Text", B = '<em class="special">Text</em>') |> 
  gt() |> 
  tab_options(quarto.disable_processing = TRUE) |> 
  fmt_markdown(B)
```
````

![image](https://github.com/rstudio/gt/assets/6791940/5a812521-57ba-46d9-b659-2b20ad90c493)

You can see the weird output in the column. This is related to 
* #1487 

and found while looking at 
* https://github.com/quarto-dev/quarto-cli/discussions/7493

Content produced is still quarto specific
```html
<div data-qmd="<em class="special">Text</em>">
```

but disabling quarto processing should have prevented inserting the `data-qmd` attributes. 

There are other way to achieve that, but still I believe `data-qmd` insertion is tied to quarto table processing. So deactivating it when option is present seems better. 

## What works 

`fmt_passthrough()` works though. 

````markdown
```{r}
library(gt)
data.frame(A = "Text", B = '<em class="special">Text</em>') |> 
  gt() |> 
  tab_options(quarto.disable_processing = TRUE) |> 
  fmt_passthrough(B, escape = FALSE)
```
````

**Comment by rich-iannone** [comment]
This should be solved by fixing https://github.com/rstudio/gt/issues/1487.
