### ISSUE TITLE
Pivot_wide of a formatted gt() table?

### ISSUE THREAD

**Issue by blaidd4drwg** [rstudio/gt#1489]
## Prework

* [x] Read and agree to the [code of conduct](https://www.contributor-covenant.org/version/2/1/code_of_conduct.html) and [contributing guidelines](https://github.com/rstudio/gt/blob/master/.github/CONTRIBUTING.md).
* [x] If there is [already a relevant issue](https://github.com/rstudio/gt/issues), whether open or closed, comment on the existing thread instead of posting a new issue.
* [x] For any problems you identify, a [minimal reproducible example](https://www.tidyverse.org/help/) so the maintainer can troubleshoot. A reproducible example is:
    * [x] **Runnable**: post enough R code and data so any onlooker can create the error on their own computer.
    * [x] **Minimal**: reduce runtime wherever possible and remove complicated details that are irrelevant to the issue at hand.
    * [x] **Readable**: format your code according to the [tidyverse style guide](https://style.tidyverse.org/).

## Question

Given is a dataframe in long format with different years ("Jahr"), different chemical parameters ("Parameter"; not previously known which ones), associated value ("Wert") and the assessment of this value ("Klasse"; given as text - assessment is done outside of R). I would like to conditionally style the "Wert" column (resp. the cell background) according to the value in "Klasse" – and *then* pivot/reshape to a wide form table. The result should look similar to this (done with kableExtra - for multiple reasons we would like to use gt() instead).

### R code for dataframe in long form
`
structure(list(Jahr = c("2002", "2003", "2002", "2003", "2002", 
"2003", "2002", "2003", "2002", "2003"), Parameter = c("Ammonium-Stickstoff", 
"Ammonium-Stickstoff", "DOC", "DOC", "Gesamtphosphor (filtriert)", 
"Gesamtphosphor (filtriert)", "Nitrat-Stickstoff", "Nitrat-Stickstoff", 
"Nitrit-Stickstoff", "Nitrit-Stickstoff"), Wert = c(0.74, 0.98, 
2300, 2580, 29.6, 36.9, 1176, 1264, 2.69, 2.09), Klasse = structure(c(4L, 
4L, 4L, 4L, 4L, 4L, 5L, 5L, 1L, 1L), levels = c("schlecht", "unbefr.", 
"mässig", "gut", "sehr gut"), class = "factor")), row.names = c(NA, 
-10L), class = c("tbl_df", "tbl", "data.frame"))
`

### Picture of dataframe in long form

<img width="383" alt="grafik" src="https://github.com/rstudio/gt/assets/18100143/64522a2b-07f9-4db0-8147-c4f15c44f1f0">

### Picture of expected result

<img width="618" alt="grafik" src="https://github.com/rstudio/gt/assets/18100143/3f6d46d7-4032-4c32-9e73-36c1778cc0a6">

Is there a way to do this in gt()? Or maybe a solution I have not found yet? If I pivot_wide before using gt(), I'm unable to easily conditionally format the table, as it will lack the "Klasse" information.

**Comment by obsaditelnost** [comment]
You could style the data already before passing it to a gt-call:

```
create_badge <- function(text, color_index, color_label) {
  paste0(
    "<span title='", color_label, "' class='badge' style='background-color: ",
    paletteer::paletteer_c("ggthemes::Red-Green-Gold Diverging", 5)[color_index], ";'>", text, "</span>"
  )
}

tbl <- structure(
  list(
    Jahr = c("2002", "2003", "2002", "2003", "2002", "2003", "2002", "2003", "2002", "2003"),
    Parameter = c(
      "Ammonium-Stickstoff", "Ammonium-Stickstoff", "DOC", "DOC", "Gesamtphosphor (filtriert)",
      "Gesamtphosphor (filtriert)", "Nitrat-Stickstoff", "Nitrat-Stickstoff",
      "Nitrit-Stickstoff", "Nitrit-Stickstoff"
    ),
    Wert = c(0.74, 0.98, 2300, 2580, 29.6, 36.9, 1176, 1264, 2.69, 2.09),
    Klasse = structure(c(4L, 4L, 4L, 4L, 4L, 4L, 5L, 5L, 1L, 1L),
      levels = c("schlecht", "unbefr.", "mässig", "gut", "sehr gut"), class = "factor"
    )
  ),
  row.names = c(NA, -10L),
  class = c("tbl_df", "tbl", "data.frame")
)

tbl |>
  dplyr::mutate(
    Wert = create_badge(text = Wert, color_index = as.integer(Klasse), color_label = Klasse)
  ) |>
  tidyr::pivot_wider(id_cols = c(Jahr), names_from = Parameter, values_from = Wert) |>
  gt() |>
  gt::fmt_markdown(columns = everything()) |>
  opt_row_striping() |>
  opt_css("span.badge {color: black; padding: 4px 8px; text-align: center; border-radius: 5px;}")
```

![image](https://github.com/rstudio/gt/assets/107487654/8a817137-8c96-4215-a1c5-610aef81c4ac)

**Comment by rich-iannone** [comment]
Given there's a solution provided (and we don't want to have pivoting in the API), I am going to close this issue.
