### ISSUE TITLE
compatibility issue

### ISSUE THREAD

**Issue by Son-of-Sevenless** [rstudio/gt#151]
I understand that this package needs to be downloaded from github. I tried:
- install.packages("https://github.com/rstudio/gt.git", lib="C:/Programs/R-3.5.1/library")
  This gave the error that there is no compatible version
- remotes::install_github("rstudio/gt", lib="C:/Programs/R-3.5.1/library")
  Here I get the option to update my packages. This is obviously not something I want.

Downloading GitHub repo rstudio/gt@master
These packages have more recent versions available.
Which would you like to update?

 1:   BH         (1.66.0-1 -> 1.69.0-1) [CRAN]
 2:   colorspace (1.3-2    -> 1.4-0   ) [CRAN]
 3:   dplyr      (0.7.7    -> 0.7.8   ) [CRAN]
 4:   pillar     (1.3.0    -> 1.3.1   ) [CRAN]
 5:   Rcpp       (0.12.19  -> 1.0.0   ) [CRAN]
 6:   rlang      (0.3.0.1  -> 0.3.1   ) [CRAN]
 7:   tibble     (1.4.2    -> 2.0.1   ) [CRAN]
 8:   CRAN packages only
 9:   All
10:   None

What am I doing wrong? Could you advise?

**Comment by rich-iannone** [comment]
Could you try option 10 and see if that installs the package?

**Comment by Son-of-Sevenless** [comment]
I tried but did not work.

I also tried to install it in my R console instead of via R studio without succes☹️

**Comment by Son-of-Sevenless** [comment]
I have now installed the latest versions of all packages but R cant find back gt when I use library(gt) after executing your code.

**Comment by rich-iannone** [comment]
Did you try using `remotes::install_github("rstudio/gt", lib="C:/Programs/R-3.5.1/library")` once more after updating the packages?

**Comment by Son-of-Sevenless** [comment]
Yes but no success 😢. Would you have a zipfile which I could use for installing?

**Comment by rich-iannone** [comment]
You can download a zip file directly from GitHub. Navigate to the main project page for **gt**. Press the large green button that says **Clone or Download**. Choose the option that says **Download ZIP**. 

I’m going to close this issue now. If you have any more questions about installing R packages, please direct them to the RStudio Community site or StackOverflow.
