### ISSUE TITLE
New `data_area_fill_color` parameter for `nanoplot_options`

### ISSUE THREAD

**Issue by JoeSydlowski** [rstudio/gt#1521]
## Prework

- [X] Read and abide by **gt**'s [code of conduct](https://www.contributor-covenant.org/version/2/1/code_of_conduct.html) and [contributing guidelines](https://github.com/rstudio/gt/blob/master/.github/CONTRIBUTING.md).
- [X] Search for duplicates among the [existing issues](https://github.com/rstudio/gt/issues) (both open and closed).

## Proposal

A parameter for `data_area_fill_color` along the lines of `reference_area_fill_color` under `nanoplot_options` would be nice to have! The data area here doesn't look quite right, but I don't want to hide it with `show_data_area` if I could change the color instead.
![image](https://github.com/rstudio/gt/assets/47405249/13ffda9e-64a7-4f2c-b2a7-27b043c93a2d)

**Comment by rich-iannone** [comment]
Hey @JoeSydlowski , I followed your suggestion and added the option. Try it out! And let me know if there's anything else that could be done.
