### ISSUE TITLE
Suggested Performance Improvement - choose markdown engine once (DRAFT)

### ISSUE THREAD

**Issue by slodge** [rstudio/gt#1524]
## Prework

* [x] Read and agree to the [code of conduct](https://www.contributor-covenant.org/version/2/1/code_of_conduct.html) and [contributing guidelines](https://github.com/rstudio/gt/blob/master/.github/CONTRIBUTING.md).
* [x] If there is [already a relevant issue](https://github.com/rstudio/gt/issues), whether open or closed, comment on the existing thread instead of posting a new issue.

## Description

We've got one app in test where we were seeing very slow interactive gt rendering times.

I believe the majority of this slowness came from markdown cell rendering - and when I've tried simpler reproduction projects I've generated some profvis outputs that demonstrated this:
![image](https://github.com/rstudio/gt/assets/533662/0bf6eb45-3a0c-40e5-8f29-ff461dbe1fd6)

However... in my real project, profvis is pointing to `utils::packageVersion` as being a significant performance issue - e.g. see:
![image](https://github.com/rstudio/gt/assets/533662/ee40b2a7-d49a-42ad-b425-1507af1614e3)

... but I haven't yet gotten similar results in my test repro projects (yet). I'm not sure why this is - but I'll see if I can work out why "soon" - e.g. perhaps something to do with renv (used in my real project but not in my test repro one)

I'm pausing investigating this for a moment now - but thought I'd open this draft issue/PR now - is this change something gt would be interested in?

## Reproducible example

* [ ] Post a [minimal reproducible example](https://www.tidyverse.org/help/) so the maintainer can troubleshoot the problems you identify. A reproducible example is:
    * [ ] **Runnable**: post enough R code and data so any onlooker can create the error on their own computer.
    * [ ] **Minimal**: reduce runtime wherever possible and remove complicated details that are irrelevant to the issue at hand.
    * [ ] **Readable**: format your code according to the [tidyverse style guide](https://style.tidyverse.org/).

## Expected result

* [ ] Todo - once I get a nice repro

## Session info

* [ ] Todo - once I get a nice repro

**Comment by rich-iannone** [comment]
Many have noted that interactive tables (tables using {reactable} as the backend) are substantially slower. Did you find that standard interactive tables are also a bit slow? If so, this whole thing should probably be given much more time and attention.

**Comment by slodge** [comment]
> Many have noted that interactive tables (tables using {reactable} as the backend) are substantially slower than static tables. Do you find that standard interactive tables (i.e., no formatting or styling) are also a bit slow? If so, this whole thing should probably be given much more time and attention.

The tables I've been looking at this work were slow in non-interactive and really slow in interactive. 

As one of those perf traces shows, some of this slowness was in `utils::packageVersion` calls.

Beyond that, a lot of slowness was in some `map`-based engineering where our authors had written md/html/passthrough content using `md` or using `htmltools` tags - e.g. the sort of code suggested in https://community.rstudio.com/t/create-interactive-links-in-gt-table-in-rmarkdown/70266/2

Some of the markdown columns were particularly slow... let me rejig my test script....

**Comment by slodge** [comment]
Discussion moved to #1528

| fmt_markdown | md |
| ----------- | ---- |
| ![image](https://github.com/rstudio/gt/assets/533662/9b563838-3d34-410f-9b06-fd5ae9e6fd2c) | ![image](https://github.com/rstudio/gt/assets/533662/1b93b763-5aa6-40f2-9bd5-33143895808f) |

(Just leaving these images here as I'm not sure how github cleans things up)
