### ISSUE TITLE
Exporting to rtf with column spanner

### ISSUE THREAD

**Issue by moleps** [rstudio/gt#153]
I tried exporting one of the examples to rtf, but the column spanner is lost somewhere in the process. 

---

<brief description of the problem>

```r
library(gt)

airquality_m <- 
  airquality %>%
  mutate(Year = 1973L) %>%
  slice(1:10)

gt_tbl <- 
  gt(data = airquality_m) %>%
  tab_header(
    title = "New York Air Quality Measurements",
    subtitle = "Daily measurements in New York City (May 1-10, 1973)"
  ) %>%
  tab_spanner(
    label = "Time",
    columns = vars(Year, Month, Day)
  ) %>%
  tab_spanner(
    label = "Measurement",
    columns = vars(Ozone, Solar.R, Wind, Temp)
  )

writeLines(as_rtf(gt_tbl),"t1.rtf")
```
Now - when I open t1.rtf I get:

<img width="649" alt="skjermbilde 2019-01-30 22 18 43" src="https://user-images.githubusercontent.com/16063024/52013364-234afc80-24dd-11e9-9802-fd2d74c07819.png">

Am I missing something here or is this feature not implemented in the rtf output?

**Comment by rich-iannone** [comment]
Column spanner labels are supposed to work with RTF. I will take a look at this and implement a fix.

**Comment by rich-iannone** [comment]
Sorry this took well over a year but a fix is now in place (https://github.com/rstudio/gt/pull/638) in the development version of gt. I tried the code again and opened the RTF in Word. Here is a screenshot.

<img width="1167" alt="air_quality_rtf" src="https://user-images.githubusercontent.com/5612024/95249455-b0804180-07e6-11eb-9921-d7f12e890913.png">
