### ISSUE TITLE
Can tab_spanner() set cols_label() for alternative names?

### ISSUE THREAD

**Issue by yutannihilation** [rstudio/gt#154]
since it might be convenient if subcolumns can have the same names. Suppose the case I want to let the both spanner columns have "value1" and "value2":

``` r
library(gt)
library(tibble)

d <- tibble(id = 1:3, type1_value1 = 2:4, type1_value2 = 3:5, type2_value1 = 4:6, type2_value2 = 5:7)
gt(d) %>%
  cols_label(
    type1_value1 = "value1", type1_value2 = "value2",
    type2_value1 = "value1", type2_value2 = "value2",
  ) %>%
  tab_spanner("type1", c("type1_value1", "type1_value2")) %>%
  tab_spanner("type2", c("type2_value1", "type2_value2"))
```

<table class="gt_table">

<tr>

<th class="gt_col_heading gt_center" rowspan="2" colspan="1">

id

</th>

<th class="gt_col_heading gt_column_spanner gt_sep_right gt_center" rowspan="1" colspan="2">

type1

</th>

<th class="gt_col_heading gt_column_spanner gt_center" rowspan="1" colspan="2">

type2

</th>

</tr>

<tr>

<th class="gt_col_heading gt_right" rowspan="1" colspan="1">

value1

</th>

<th class="gt_col_heading gt_right" rowspan="1" colspan="1">

value2

</th>

<th class="gt_col_heading gt_right" rowspan="1" colspan="1">

value1

</th>

<th class="gt_col_heading gt_NA" rowspan="1" colspan="1">

value2

</th>

</tr>

<tbody class="gt_table_body gt_striped">

<tr>

<td class="gt_row gt_right">

1

</td>

<td class="gt_row gt_right">

2

</td>

<td class="gt_row gt_right">

3

</td>

<td class="gt_row gt_right">

4

</td>

<td class="gt_row gt_right">

5

</td>

</tr>

<tr>

<td class="gt_row gt_right">

2

</td>

<td class="gt_row gt_right">

3

</td>

<td class="gt_row gt_right">

4

</td>

<td class="gt_row gt_right">

5

</td>

<td class="gt_row gt_right">

6

</td>

</tr>

<tr>

<td class="gt_row gt_right">

3

</td>

<td class="gt_row gt_right">

4

</td>

<td class="gt_row gt_right">

5

</td>

<td class="gt_row gt_right">

6

</td>

<td class="gt_row gt_right">

7

</td>

</tr>

</tbody>

</table>

</div>

<sup>Created on 2019-01-31 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1.9000)</sup>

I want to write the above as something like:

``` r
gt(d) %>%
  tab_spanner("type1", c(value1 = "type1_value1", value2 = "type1_value2")) %>%
  tab_spanner("type2", c(value1 = "type2_value1", value2 = "type2_value2"))
```

**Comment by rich-iannone** [comment]
Thanks for filing this issue! I like your idea of setting column labels while mapping those column names to a spanner column label (eliminating the need for using `cols_label()` for those mapped columns).

I think my only (small) issue with your proposed example is that the <column name> and the <label> switch positions compared to `cols_label()`.

**Comment by rich-iannone** [comment]
@yutannihilation Sorry I forgot to mention before that your variable naming fits in nicely with what the `cols_split_delim()` function does:

```r
library(gt)
library(tidyverse)

dplyr::tibble(
  id = 1:3,
  type1_value1 = 2:4,
  type1_value2 = 3:5,
  type2_value1 = 4:6,
  type2_value2 = 5:7
) %>%
  gt() %>%
  cols_split_delim(delim = "_") %>%
  tab_header(title = "A gt Table")
```

<img width="750" alt="cols_split_delim_ftw" src="https://user-images.githubusercontent.com/5612024/53135139-1ce1fa80-3548-11e9-863e-5a10cba05290.png">

**Comment by yutannihilation** [comment]
@rich-iannone Wow, thanks! I didn't notice that nice function, sorry. Then I think my problem is already solved. Should I close this issue? I still feel setting names would be a nice feature, but I'm not sure my example here is enough to consider the use cases.

**Comment by rich-iannone** [comment]
Let’s keep this open so we could explore the idea a bit more. I see both positives and negatives to setting column label names in `tab_spanner()`. So, we should continue to discuss.

**Comment by yutannihilation** [comment]
Sure.

**Comment by MattCowgill** [comment]
How would this be achieved now `cols_split_delim()` has been removed?

**Comment by MattCowgill** [comment]
For anyone like me who finds their way to this issue through some random Googling... `cols_split_delim()` is now `tab_spanner_delim()`, so this is the working version of the code above: 


``` r
library(gt)
library(tidyverse)

dplyr::tibble(
  id = 1:3,
  type1_value1 = 2:4,
  type1_value2 = 3:5,
  type2_value1 = 4:6,
  type2_value2 = 5:7
) %>%
  gt() %>%
  tab_spanner_delim(delim = "_") %>%
  tab_header(title = "A gt Table")
```

<div id="iryzeythso" style="overflow-x:auto;overflow-y:auto;width:auto;height:auto;">
<style>html {
  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Helvetica Neue', 'Fira Sans', 'Droid Sans', Arial, sans-serif;
}

#iryzeythso .gt_table {
  display: table;
  border-collapse: collapse;
  margin-left: auto;
  margin-right: auto;
  color: #333333;
  font-size: 16px;
  font-weight: normal;
  font-style: normal;
  background-color: #FFFFFF;
  width: auto;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #A8A8A8;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #A8A8A8;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
}

#iryzeythso .gt_heading {
  background-color: #FFFFFF;
  text-align: center;
  border-bottom-color: #FFFFFF;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#iryzeythso .gt_title {
  color: #333333;
  font-size: 125%;
  font-weight: initial;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-color: #FFFFFF;
  border-bottom-width: 0;
}

#iryzeythso .gt_subtitle {
  color: #333333;
  font-size: 85%;
  font-weight: initial;
  padding-top: 0;
  padding-bottom: 6px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-color: #FFFFFF;
  border-top-width: 0;
}

#iryzeythso .gt_bottom_border {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#iryzeythso .gt_col_headings {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#iryzeythso .gt_col_heading {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 6px;
  padding-left: 5px;
  padding-right: 5px;
  overflow-x: hidden;
}

#iryzeythso .gt_column_spanner_outer {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  padding-top: 0;
  padding-bottom: 0;
  padding-left: 4px;
  padding-right: 4px;
}

#iryzeythso .gt_column_spanner_outer:first-child {
  padding-left: 0;
}

#iryzeythso .gt_column_spanner_outer:last-child {
  padding-right: 0;
}

#iryzeythso .gt_column_spanner {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 5px;
  overflow-x: hidden;
  display: inline-block;
  width: 100%;
}

#iryzeythso .gt_group_heading {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
}

#iryzeythso .gt_empty_group_heading {
  padding: 0.5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: middle;
}

#iryzeythso .gt_from_md > :first-child {
  margin-top: 0;
}

#iryzeythso .gt_from_md > :last-child {
  margin-bottom: 0;
}

#iryzeythso .gt_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  margin: 10px;
  border-top-style: solid;
  border-top-width: 1px;
  border-top-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  overflow-x: hidden;
}

#iryzeythso .gt_stub {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
}

#iryzeythso .gt_stub_row_group {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
  vertical-align: top;
}

#iryzeythso .gt_row_group_first td {
  border-top-width: 2px;
}

#iryzeythso .gt_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#iryzeythso .gt_first_summary_row {
  border-top-style: solid;
  border-top-color: #D3D3D3;
}

#iryzeythso .gt_first_summary_row.thick {
  border-top-width: 2px;
}

#iryzeythso .gt_last_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#iryzeythso .gt_grand_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#iryzeythso .gt_first_grand_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-style: double;
  border-top-width: 6px;
  border-top-color: #D3D3D3;
}

#iryzeythso .gt_striped {
  background-color: rgba(128, 128, 128, 0.05);
}

#iryzeythso .gt_table_body {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#iryzeythso .gt_footnotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#iryzeythso .gt_footnote {
  margin: 0px;
  font-size: 90%;
  padding-left: 4px;
  padding-right: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

#iryzeythso .gt_sourcenotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#iryzeythso .gt_sourcenote {
  font-size: 90%;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

#iryzeythso .gt_left {
  text-align: left;
}

#iryzeythso .gt_center {
  text-align: center;
}

#iryzeythso .gt_right {
  text-align: right;
  font-variant-numeric: tabular-nums;
}

#iryzeythso .gt_font_normal {
  font-weight: normal;
}

#iryzeythso .gt_font_bold {
  font-weight: bold;
}

#iryzeythso .gt_font_italic {
  font-style: italic;
}

#iryzeythso .gt_super {
  font-size: 65%;
}

#iryzeythso .gt_footnote_marks {
  font-style: italic;
  font-weight: normal;
  font-size: 75%;
  vertical-align: 0.4em;
}

#iryzeythso .gt_asterisk {
  font-size: 100%;
  vertical-align: 0;
}

#iryzeythso .gt_slash_mark {
  font-size: 0.7em;
  line-height: 0.7em;
  vertical-align: 0.15em;
}

#iryzeythso .gt_fraction_numerator {
  font-size: 0.6em;
  line-height: 0.6em;
  vertical-align: 0.45em;
}

#iryzeythso .gt_fraction_denominator {
  font-size: 0.6em;
  line-height: 0.6em;
  vertical-align: -0.05em;
}
</style>
<table class="gt_table">
  <thead class="gt_header">
    <tr>
      <th colspan="5" class="gt_heading gt_title gt_font_normal gt_bottom_border" style>A gt Table</th>
    </tr>
    
  </thead>
  <thead class="gt_col_headings">
    <tr>
      <th class="gt_col_heading gt_columns_bottom_border gt_right" rowspan="2" colspan="1">id</th>
      <th class="gt_center gt_columns_top_border gt_column_spanner_outer" rowspan="1" colspan="2">
        <span class="gt_column_spanner">type1</span>
      </th>
      <th class="gt_center gt_columns_top_border gt_column_spanner_outer" rowspan="1" colspan="2">
        <span class="gt_column_spanner">type2</span>
      </th>
    </tr>
    <tr>
      <th class="gt_col_heading gt_columns_bottom_border gt_right" rowspan="1" colspan="1">value1</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_right" rowspan="1" colspan="1">value2</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_right" rowspan="1" colspan="1">value1</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_right" rowspan="1" colspan="1">value2</th>
    </tr>
  </thead>
  <tbody class="gt_table_body">
    <tr><td class="gt_row gt_right">1</td>
<td class="gt_row gt_right">2</td>
<td class="gt_row gt_right">3</td>
<td class="gt_row gt_right">4</td>
<td class="gt_row gt_right">5</td></tr>
    <tr><td class="gt_row gt_right">2</td>
<td class="gt_row gt_right">3</td>
<td class="gt_row gt_right">4</td>
<td class="gt_row gt_right">5</td>
<td class="gt_row gt_right">6</td></tr>
    <tr><td class="gt_row gt_right">3</td>
<td class="gt_row gt_right">4</td>
<td class="gt_row gt_right">5</td>
<td class="gt_row gt_right">6</td>
<td class="gt_row gt_right">7</td></tr>
  </tbody>
  
  
</table>
</div>

<sup>Created on 2022-04-29 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>
