### ISSUE TITLE
Footnote symbols to cells with variables in fmt_markdown appear in a new line in HTML output

### ISSUE THREAD

**Issue by mdgrant** [rstudio/gt#1541]
## Description
Footnote symbols to cells with variables included in fmt_markdown() are placed in a new line in the HTML output. This did not occur with version 0.9.0.

### Code chunk
```{r}
library(tidyverse)
library(gt)
sza |>
  slice(7:10) |>
  select(-month) |>
  gt() |>
  fmt_markdown(sza) |>
  cols_width(
    latitude ~ px(100),
    tst ~ px(100),
    sza ~ px(100),
  ) |>
  tab_footnote(
    footnote = "With fmt_markdown()",
    locations = cells_body(columns = sza), placement = "right"
  ) |> 
  tab_footnote(
    footnote = "Without fmt_markdown()",
    locations = cells_body(columns = latitude), placement = "right"
  )
```

## Expected result
<img width="252" alt="Screenshot 2024-01-18 at 3 31 42 PM" src="https://github.com/rstudio/gt/assets/10179515/f8a3dd6c-2175-48c6-8668-2e81cba24367">

## Actual result
<img width="250" alt="Screenshot 2024-01-18 at 3 34 24 PM" src="https://github.com/rstudio/gt/assets/10179515/699cfed9-07fa-4a30-badf-44d563bfa6d8">

## Session Info
#> ─ Session info ───────────────────────────────────────────────────────────────
#>  setting  value
#>  version  R version 4.3.2 (2023-10-31)
#>  os       macOS Sonoma 14.2.1
#>  system   aarch64, darwin20
#>  ui       X11
#>  language (EN)
#>  collate  en_US.UTF-8
#>  ctype    en_US.UTF-8
#>  tz       America/Chicago
#>  date     2024-01-18
#>  pandoc   3.1.1 @ /Applications/RStudio.app/Contents/Resources/app/quarto/bin/tools/ (via rmarkdown)
#> 
#> ─ Packages ───────────────────────────────────────────────────────────────────
#>  package     * version date (UTC) lib source
#>  cli           3.6.2   2023-12-11 [1] CRAN (R 4.3.1)
#>  digest        0.6.34  2024-01-11 [1] CRAN (R 4.3.1)
#>  evaluate      0.23    2023-11-01 [1] CRAN (R 4.3.1)
#>  fastmap       1.1.1   2023-02-24 [1] CRAN (R 4.3.0)
#>  fs            1.6.3   2023-07-20 [1] CRAN (R 4.3.0)
#>  glue          1.7.0   2024-01-09 [1] CRAN (R 4.3.1)
#>  htmltools     0.5.7   2023-11-03 [1] CRAN (R 4.3.1)
#>  knitr         1.45    2023-10-30 [1] CRAN (R 4.3.1)
#>  lifecycle     1.0.4   2023-11-07 [1] CRAN (R 4.3.1)
#>  magrittr      2.0.3   2022-03-30 [1] CRAN (R 4.3.0)
#>  purrr         1.0.2   2023-08-10 [1] CRAN (R 4.3.0)
#>  R.cache       0.16.0  2022-07-21 [1] CRAN (R 4.3.0)
#>  R.methodsS3   1.8.2   2022-06-13 [1] CRAN (R 4.3.0)
#>  R.oo          1.25.0  2022-06-12 [1] CRAN (R 4.3.0)
#>  R.utils       2.12.3  2023-11-18 [1] CRAN (R 4.3.1)
#>  reprex        2.1.0   2024-01-11 [1] CRAN (R 4.3.1)
#>  rlang         1.1.3   2024-01-10 [1] CRAN (R 4.3.1)
#>  rmarkdown     2.25    2023-09-18 [1] CRAN (R 4.3.1)
#>  rstudioapi    0.15.0  2023-07-07 [1] CRAN (R 4.3.0)
#>  sessioninfo   1.2.2   2021-12-06 [1] CRAN (R 4.3.0)
#>  styler        1.10.2  2023-08-29 [1] CRAN (R 4.3.0)
#>  vctrs         0.6.5   2023-12-01 [1] CRAN (R 4.3.1)
#>  withr         3.0.0   2024-01-16 [1] CRAN (R 4.3.1)
#>  xfun          0.41    2023-11-01 [1] CRAN (R 4.3.1)
#>  yaml          2.3.8   2023-12-11 [1] CRAN (R 4.3.1)
#> 
#>  [1] /Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library
#> 
#> ──────────────────────────────────────────────────────────────────────────────

**Comment by olivroy** [comment]
This is no longer an issue as of v0.11.0 Possibly fixed as part of https://github.com/rstudio/gt/pull/1644.
