### ISSUE TITLE
Interactive - remove pagination display completely

### ISSUE THREAD

**Issue by slodge** [rstudio/gt#1542]
## Prework

* [x] Read and agree to the [code of conduct](https://www.contributor-covenant.org/version/2/1/code_of_conduct.html) and [contributing guidelines](https://github.com/rstudio/gt/blob/master/.github/CONTRIBUTING.md).
* [x] If there is [already a relevant issue](https://github.com/rstudio/gt/issues), whether open or closed, comment on the existing thread instead of posting a new issue.

## Description

When viewing an interactive page without pagination or pagination info we still see the 1 page number

I suspect this is `showPagination = TRUE` https://github.com/rstudio/gt/blob/3213ec43ee71600735629f9162b2f5bdb43af645/R/render_as_i_html.R#L407

## Reproducible example

```
library(tidyverse)
library(gt)

gt(iris) |> 
  opt_interactive(use_pagination = FALSE, use_pagination_info = FALSE)
```

## Expected result

Would be nice to not have any page footer

Currently see:
![image](https://github.com/rstudio/gt/assets/533662/2af941b3-9263-4e7c-919e-b942196983e8)

## Session info

R4.3
gt 0.10.1
reactable 0.4.4

**Comment by aecoaker** [comment]
Does anyone know if there's an estimated date for this version? I really want to use the gt package but I need a clean finish for accessibility reasons!
