### ISSUE TITLE
Add `locations` argument to `fmt_markdown`

### ISSUE THREAD

**Issue by asbates** [rstudio/gt#1551]
## Prework

- [x] Read and abide by **gt**'s [code of conduct](https://www.contributor-covenant.org/version/2/1/code_of_conduct.html) and [contributing guidelines](https://github.com/rstudio/gt/blob/master/.github/CONTRIBUTING.md).
- [x] Search for duplicates among the [existing issues](https://github.com/rstudio/gt/issues) (both open and closed).

## Proposal

It would be helpful if `fmt_markdown` was extended to take a `locations` argument so that areas outside the body can be targeted. Similar to #901 where they needed to target footnotes, I would like to target column spans. 

My use case is I have span headers with `<br>` tags for line breaks. For example:

```r
library(gt)

names(iris) <- c(
  "Sepal<br>under.Length",
  "Sepal<br>under.Width",
  "Petal<br>under.Length",
  "Petal<br>under.Width",
  "Species"
)

gt(iris) |> 
  tab_spanner_delim(delim = ".")
```

which gives the output 
![image](https://github.com/rstudio/gt/assets/36482959/d0e1d879-825f-4545-81cf-8b3aebb8e725)

I would like to be able to add the line `fmt_markdown(locations = cells_column_spanners())` to indicate the column spans should be interpreted as markdown so the `<br>` tag is not escaped. The desired output would be 
![image](https://github.com/rstudio/gt/assets/36482959/e9519164-0fbd-45e6-9b0d-7bddf8070f94)
 where the text 'under' is on a new line because of the `<br>`.

**Comment by rich-iannone** [comment]
Adding `locations` to `fmt_markdown()` doesn't fit the API so I'd rather go with the ideas in: https://github.com/rstudio/gt/issues/1628.
