### ISSUE TITLE
Could the nanoplot arg `missing_vals = "gap"` actually return a gap, instead of a floating red circle? ⭕️

### ISSUE THREAD

**Issue by jimgar** [rstudio/gt#1567]
## Prework

* [x] Read and agree to the [code of conduct](https://www.contributor-covenant.org/version/2/1/code_of_conduct.html) and [contributing guidelines](https://github.com/rstudio/gt/blob/master/.github/CONTRIBUTING.md).
* [x] If there is [already a relevant issue](https://github.com/rstudio/gt/issues), whether open or closed, comment on the existing thread instead of posting a new issue.
* [x] For any problems you identify, a [minimal reproducible example](https://www.tidyverse.org/help/) so the maintainer can troubleshoot. A reproducible example is:
    * [x] **Runnable**: post enough R code and data so any onlooker can create the error on their own computer.
    * [x] **Minimal**: reduce runtime wherever possible and remove complicated details that are irrelevant to the issue at hand.
    * [x] **Readable**: format your code according to the [tidyverse style guide](https://style.tidyverse.org/).

## Question

Hi, I'm really enjoying the nanoplots in the latest release. I spent several hours using them this week at work on real time series data, which contains a lot of missing values interspersed irregularly throughout.

My question is: Could `missing_vals = "gap"` actually return a gap, instead of the floating red circle?

For example, this table. We specify "gap" but don't get gaps, we get symbols.

<img width="175" alt="Screenshot 2024-02-03 at 00 11 24" src="https://github.com/rstudio/gt/assets/90831652/3654d68c-c3a2-4a56-8166-2b7dfcb2cca9">

I'm sure some people would say "Ah, what you really want is to specify 'zero'". But that's not true in my case, where missing data can't be equated to zero values. Plus, I noted some minor confusion when I showed my boss a table that **did** use `missing_vals = "zero"`: Because there is still a pixel or two where the bars are at zero, he made the (reasonable) interpretation that these were similar to some of the actual, but very small, data points in this dataset (e.g. 0.012).

The other option of "remove" will be useful in some contexts I'm sure, but is not appropriate in my case because I don't want the bars to get squashed together - I need to be able to compare time points down columns. I'd just like a pure gap wherever there's an NA.

If the floating red dot is unexpected behaviour I'm happy to provide sessionInfo etc. For now, here's the code for the table above.

```r
library(tibble)
library(gt)

tibble::tibble(
  month = factor(
    c("jan", "feb", "mar", "apr", "may"),
    levels = c("jan", "feb", "mar", "apr", "may")
  ),
  `0530` = rep(NA_real_, 5L),
  `0600` = c(NA, NA, NA, 1.5, 5),
  `0630` = c(NA, 1.0999999999999943, 4.299999999999997, 8.5, NA),
  `0700` = c(
    5.099999999999994, 7.5, 11.2000000000000028, 15.599999999999994,
    0x1.2ccccccccccccp+4
  ),
  `0730` = c(
    11.2999999999999972, 14.2000000000000028, 18, NA,
    25.700000000000003
  ),
  `0800` = c(
    17.299999999999997, 20.400000000000005684, NA,
    29.700000000000003, 32.8
  ),
) |>
  gt(rowname_col = "month") |>
  cols_nanoplot(
    columns = matches("0"),
    plot_type = "bar",
    missing_vals = "gap",
    new_col_name = "saa"
  )
```

**Comment by rich-iannone** [comment]
Thanks for filing this issue! Yeah, we could certainly make this option display a true gap (no bar or point). And I could repurpose the ⭕️ into another option (maybe something like `"marker"`, with *another* option to style the marker a la ggplot). 

Thanks for using the feature! It’s still young and needs a bit of work so feedback like this is valuable.

**Comment by jimgar** [comment]
Thanks, Rich - "true gap"! That's it. 

You're very welcome for the feedback. The nanoplots are super cool.
