### ISSUE TITLE
Could a gt table default to converting all unspecified colnames to `snakecase::to_sentence_case`?

### ISSUE THREAD

**Issue by davidhodge931** [rstudio/gt#1589]
The logic would be that generally column names as is always need to be adjusted.

If there was a default snakecase::to_sentence_case function applied, then some columns would not need to be adjusted - saving some typing and effort. 

Currently it does this 
![image](https://github.com/rstudio/gt/assets/55065152/2227e08d-aebe-4ee9-b673-702f1242c2bd)

I would prefer the same code output this
![image](https://github.com/rstudio/gt/assets/55065152/cc8ceb8b-0aa4-4bd7-9638-6298a5470f56)

**Comment by olivroy** [comment]
Hi! I like the idea. However, this would break too many existing tables.

There are a few things you can do as a workaround however.

```r
# define a function
gt <- function(data, ...) {
   gt(data, ...) |>
     text_transform(
        fn = snakecase::to_sentence_case,
        locations = cells_column_labels()
 }
```

If you are not aware, gt also defaults to using the label attribute of columns (if they are defined). https://github.com/rstudio/gt/issues/656

I have a couple scripts to do this, but simply put, here is an example

```r
mtcars |> labelled::set_variable_labels(.labels = snakecase::to_sentence_case(names(mtcars))) |> gt()
```
