### ISSUE TITLE
opt_css with opt_interactive

### ISSUE THREAD

**Issue by jmhyman-su** [rstudio/gt#1612]
Is there anyway to utilize both opt_css and opt_interactive within a gt table at the same time?

For example, I would like to freeze the first column and first row while also being able to sort the columns based on value. 

This first code snippet freezes the panes:

gtcars |> 
  gt(id = "one", rowname_col = "model") |> 
  opt_css(
    css = "
    #one .gt_stub {
    position: sticky;
    left: 0;
    }
    
    #one .gt_col_heading {
    position: sticky;
    top: 0;
    }

#one .gt_table {
 border-collapse: separate;
 border-spacing: 0;
}
    thead th:first-child {
    left: 0;
    z-index: 2;
    }") 

While this code can allow sorting:
gtcars %>% gt() %>% opt_interactive()

But I cannot figure out if it is possible to do both at the same time. Any help would be appreciated.

**Comment by obsaditelnost** [comment]
Using `opt_interactive()` changes the table-structure to a div-structure. Automatically reorganising custom-css with respect to the new structure won't be easy because some properties are only available for table-elements. Try to change your CSS and adapt to the new div-structure of the interactive tables:

```
gtcars |>
  gt(id = "one", rowname_col = "model") |>
  opt_css(
    css = " 
      #one div.rt-tr > div:first-child   {
      position: sticky !important;
      left: 0;
      background-color: white;
      z-index:2;}") |> 
  opt_interactive()
```

**Comment by jmhyman-su** [comment]
Thank you! Perfect answer and makes sense
