### ISSUE TITLE
Feature request: render SVG cells in `as_gtable()` output

### ISSUE THREAD

**Issue by teunbrand** [rstudio/gt#1652]
Hi Richard and team,

This feature request / offer is a follow-up on #1563 and proposes to render SVG cells in `as_gtable()` output.
Currently, just the text of SVG cells is displayed and it would be nice if these are properly rendered.
This example with country flags just turns out horribly.

``` r
library(gt)

x <- countrypops |>
  dplyr::filter(year == 2021) |>
  dplyr::filter(grepl("^S", country_name)) |>
  dplyr::arrange(country_name) |>
  dplyr::select(-country_code_3, -year) |>
  dplyr::slice_head(n = 10) |>
  gt() |>
  cols_move_to_start(columns = country_code_2) |>
  fmt_flag(columns = country_code_2)
  
grid::grid.newpage()
grid::grid.draw(as_gtable(x))
```

![](https://i.imgur.com/5YTZe3h.png)

<sup>Created on 2024-05-07 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>

As {grid} doesn't natively support SVG input, it would be sensible to render them as rasters and display these cells as such.
I'll happily prepare a PR if welcome.

**Comment by rich-iannone** [comment]
@teunbrand Your contribution would be welcomed and appreciated! Many thanks for doing this work. I also won't release to CRAN until this feature is complete.
