### ISSUE TITLE
Color columns based on another column

### ISSUE THREAD

**Issue by kwakuduahc1** [rstudio/gt#1659]
## Prework

* [*] Read and agree to the [code of conduct](https://www.contributor-covenant.org/version/2/1/code_of_conduct.html) and [contributing guidelines](https://github.com/rstudio/gt/blob/master/.github/CONTRIBUTING.md).
* [*] If there is [already a relevant issue](https://github.com/rstudio/gt/issues), whether open or closed, comment on the existing thread instead of posting a new issue.
* [*] For any problems you identify, a [minimal reproducible example](https://www.tidyverse.org/help/) so the maintainer can troubleshoot. A reproducible example is:
    * [*] **Runnable**: post enough R code and data so any onlooker can create the error on their own computer.
    * [*] **Minimal**: reduce runtime wherever possible and remove complicated details that are irrelevant to the issue at hand.
    * [*] **Readable**: format your code according to the [tidyverse style guide](https://style.tidyverse.org/).

## Question

What would you like to know?

How do I color other columns based on the value of another column? The issue is described in #1119 but I could not find a description of how to do that and I could not find it in the documentation.

Below is a how it should work

```
mtcars  %>% 
  gt() %>% 
  data_color(
  # Help here
   # color **disp and hp** columns where __cyl__ > 4
  )
```
Thank you in advance.

**Comment by olivroy** [comment]
`data_color()` is quite powerful, I recommend you reading the examples in the documentation https://gt.rstudio.com/reference/data_color.html

```r
# To color disp and hp colors, when cyl > 4, based on their respective values
gt::gt(
  mtcars
) |> 
  gt::data_color(
    columns = c(disp, hp), # columns to color
    rows = cyl > 4, # rows to color
  )
```
![image](https://github.com/rstudio/gt/assets/52606734/6f95c987-62cb-4644-83a4-8270f412aa6f)

```r
# To color disp and hp colors, based on the value of column mpg
gt::gt(
  mtcars
) |> 
  gt::data_color(
    columns = c(mpg),  # colored based on mpg
    rows = cyl > 4, # rows to color
    target_columns = c(disp, hp) # columns to color
  )
```
![image](https://github.com/rstudio/gt/assets/52606734/ddd2b0d8-4bab-41bf-9a43-144c4f3ea569)

The function allows for more customization and options too

**Comment by kwakuduahc1** [comment]
Thank you for the prompt response. However, I am looking at the _disp_ and _hp_ value is less than the _cyl_ value. I could not find that in the documentation.

Best.

**Comment by olivroy** [comment]
Well you can construct any type of condition you want to `rows`

I am not sure I see what you mean?

* Which rows do you expect to be colored?

* Which columns do you expect to be colored?

* color should be based on which column?

* Do you expect the full mtcars dataset to appear, or do you need to use `dplyr::filter()` to remove rows?

```r
# To color disp and hp colors, based on the value of column cyl when cyl>4
gt::gt(
  mtcars
) |> 
  gt::data_color(
    columns = c(cyl),  # colored based on cyl
    rows = cyl > 4, # rows to color
    target_columns = c(disp, hp) # columns to color
  )
```
![image](https://github.com/rstudio/gt/assets/52606734/e1b54e2c-2110-4d50-be21-67491b0e761e)

**Comment by kwakuduahc1** [comment]
Sorry for confusing you.

I want the *disp* and *hp* columns to be colored if any of them is less than the *cyl* value.

I was tired and realize my folly.

Thanks.

**Comment by olivroy** [comment]
Well, in this case, none will be colored, disp and hp have values > 60, and cyl ranges between 4, 6, and 8.

But the code would be 


```r
library(gt)
mtcars |> 
  gt::gt() |> 
  data_color(
    columns = c(disp, hp),
    rows = disp < cyl | hp < cyl
  )
```

But that would error, because the condition for `rows` will not match any row.

**Comment by kwakuduahc1** [comment]
```
mtcars |> 
  gt::gt() |> 
  data_color(
    columns = c(disp, hp),
    rows = am == cyl 
  )
```
throws error 

```
Error in `get_contrast_ratio()`:
! At least one color defined for each of
  `color_1` and `color_2`.
```

Thanks.

**Comment by olivroy** [comment]
This is expected because no row will be colored, `data_color()` cannot be used when no rows are colored.

The error message could be improved however.

`mtcars |> dplyr::filter(am == cyl)` will have no row.

**Comment by kwakuduahc1** [comment]
Thank you.

This works

mtcars |> 
  gt::gt() |> 
  data_color(
    columns = c(disp, hp),
    rows = gear == cyl 
  )

![image](https://github.com/rstudio/gt/assets/11381582/671f4001-fc82-477b-9344-ce597bc27d3d)

I should be good from here onwards.
