### ISSUE TITLE
rotate text on labels

### ISSUE THREAD

**Issue by gvwilson** [rstudio/gt#169]
I would like to be able to rotate the text labels on a table. For example, I have a long label I want to put on the Y axis - I would like to be able to rotate the text 90°. I would also like to be able to rotate the text labels on the X axis 90° to make the table more compact.

**Comment by rich-iannone** [comment]
Thanks for the feature request. Seems very sensible to be able to rotate the labels (both column labels and the row group labels). We will explore this a bit and come back with some draft implementations in this issue.

**Comment by rich-iannone** [comment]
Duplicate of #108
