### ISSUE TITLE
Rownames not showing when gt is set to interactive

### ISSUE THREAD

**Issue by 22ermiller** [rstudio/gt#1702]
I would like rownames to appear on my gt table while being able to interactively sort and navigate through pages, but whenever I make the gt object interactive the rownames go away. 

Here is a simple reproducible example:

```
library(tibble)
library(gt)

gt(iris, rownames_to_stub = T)

gt(iris, rownames_to_stub = T) %>% 
  opt_interactive()
```

Is this result intentional or a bug?

**Comment by olivroy** [comment]
Just realized that this still doesn't work. somehow, would have to rename the Sepal.Width column to [`.rownames`](https://glin.github.io/reactable/reference/reactable.html#arguments) for reactable 

```r
library(tibble)
library(gt)

gt(iris, rownames_to_stub = T)

gt(iris, rowname_col = "Sepal.Width") %>% 
  opt_interactive()

```
