### ISSUE TITLE
LaTeX table rendering issue with math + `fmt_markdown()`

### ISSUE THREAD

**Issue by olivroy** [rstudio/gt#1741]
*Invalid*

I am trying to see what the problem is here

The example in https://quarto-gt-examples.netlify.app/gt-fmt_markdown.html doesn't render correctly.

Locally, I see this with latest dev

![image](https://github.com/rstudio/gt/assets/52606734/bc5fdcf1-1d38-49a1-b4b7-bea6f1003dbf)

On gt 0.10.1 (on webR)
![image](https://github.com/rstudio/gt/assets/52606734/c7a5c78d-715a-4b33-8b2e-ea70cec5d6b2)

Locally, I see the warning

```
Avis : LaTeX-incompatible input and strict mode is set to 'warn': In LaTeX, \\ or \newline does nothing in display mode [newLineInDisplayMode]
```

Let me know if you need more information.

In Quarto 1.5

![image](https://github.com/rstudio/gt/assets/52606734/54f6c923-c636-42d2-9110-76a7fefa3831)

**Comment by olivroy** [comment]
Duplicate of #1687

**Comment by rich-iannone** [comment]
This is entirely a problem of not faithfully extracting the examples from the Rd database to the Quarto documents for the site. I made a quick fix here: https://github.com/rstudio/gt/commit/0fb1c96c625253aa296d3783c805dc9658a015f0. And if you copy that equation example into a Quarto doc and render it (or run it in the console), it renders without error.

Here's the zipped Quarto doc for testing:
[formulas.qmd.zip](https://github.com/user-attachments/files/16087771/formulas.qmd.zip)

**Comment by olivroy** [comment]
Sure, I will take a look. Would you mind trying to add a CodeCov token, so that we can track coverage on codecov again. (The test-coverage action has been failing for a few weeks now)  https://github.com/r-lib/actions/issues/834

**Comment by rich-iannone** [comment]
The CodeCov token has been added as `CODECOV_TOKEN`. Thanks for reminding me of that.
