### ISSUE TITLE
Improve error message when user attempts to call purrr-style function in fmt?

### ISSUE THREAD

**Issue by LukasWallrich** [rstudio/gt#1762]
I should know better (#1148) but I just tried to use `fmt()` with purrr-style functions. While I know that they are becoming outdated, it might still be worth generating an error message that is a bit clearer than the below? Apart from maybe making it explicit that this syntax is not supported, it would be even more helpful to know where the error occurs (as this was part of a long pipeline).

``` r
library(gt)
mtcars |> gt() |> fmt(mpg, fns = ~.x+1)
#> Error in fmt$func[[eval_func]](data_tbl[[col]][rows]): attempt to apply non-function
```

<sup>Created on 2024-07-10 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by olivroy** [comment]
Hi @LukasWallrich! Thanks for the report. You are right that the message could be improved. Do you want to create a PR?

Maybe anonymous functions could be supported if they were coerced with `rlang::as_function()`?

```r
f <- rlang::as_function(f)
```


If it is not possible, you could use a check like this to prevent purrr style function to be accepted.

```r
if (!is.function(f) && rlang::is_function(f)) {
  cli::cli_abort("purrr-style formulas are not supported in `fmt()`")
}
```

The idea will be to add a snapshot test to track the error message.

I recommend you running 

```r
# Create test file 
usethis::use_test("fmt")
```

The test could be the following:

```r
test_that("fmt() gives a good error message when providing a purrr formula (#1762)", {
  expect_snapshot(
    error = TRUE,
    mtcars %>% gt() %>% fmt(mpg, fns = ~.x+1)
  )
})
```

We still use magrittr pipe in our tests (for R 4.0 and R 3.6 compatibility).

Or if you are able to actually fix the issue. Something like

```r
test_that("fmt() works when providing a purrr formula (#1762)", {
  expect_equal(
    mtcars %>% gt() %>% fmt(mpg, fns = ~.x+1),
    mtcars %>% gt() %>% fmt(mpg, fns = function(x) x+1)
  )
})
```

Let us know!

Cheers

**Comment by LukasWallrich** [comment]
Thanks for the suggestions ... I will work on it.

As a first step, the following works - so I am optimistic that I can get the `rlang` solution to work.

```r
library(gt)
mtcars |> gt() |> fmt(mpg, fns = rlang::as_function(~.x+1))
```
