### ISSUE TITLE
`gt::md()` fails when applied to a blank string in new version v0.11.0 on Quarto

### ISSUE THREAD

**Issue by ddsjoberg** [rstudio/gt#1769]
## Prework

* [x] Read and agree to the [code of conduct](https://www.contributor-covenant.org/version/2/1/code_of_conduct.html) and [contributing guidelines](https://github.com/rstudio/gt/blob/master/.github/CONTRIBUTING.md).
* [x] If there is [already a relevant issue](https://github.com/rstudio/gt/issues), whether open or closed, comment on the existing thread instead of posting a new issue.

## Description

@remlapmot reported an issue to gtsummary after they updated to gt v0.11.0. By default, our headers in gtsummary are processed with `gt::md()`, and a blank string leads to an error in Quarto. There is no error when run interactively or using R Markdown. I tested in Quarto versions v1.4.549 and v1.5.54 (released a couple of days ago).

For now, I can update gtsummary to remove `gt::md()` when the string is blank.

## Reproducible example

````
---
title: "tbl_cross reprex"
format:
  html:
    embed-resources: true
---

Example 

```{r}
packageVersion("gt")

mtcars[1:3, 1:2] |> 
  gt::gt() |> 
  gt::cols_label(mpg = gt::md(""))
```
````

Thank you!!

**Comment by remlapmot** [comment]
The error message (under Quarto version 1.5.54) in the terminal is as follows

````
==> quarto preview tbl-cross-reprex-md.qmd --to html --no-watch-inputs --no-browse



processing file: tbl-cross-reprex-md.qmd
  |...................................                 |  67% [unnamed-chunk-1]Error in `vapply()`:
! values must be length 1,
 but FUN(X[[1]]) result is length 0
Backtrace:
  1. global .main()
  2. execute(...)
  3. rmarkdown::render(...)
  4. knitr::knit(knit_input, knit_output, envir = envir, quiet = quiet)
  5. knitr:::process_file(text, output)
     ...
 30. gt:::dt_boxhead_build(data = data, context = context)
 31. base::lapply(...)
 32. gt (local) FUN(X[[i]], ...)
 33. gt:::process_text(label, context)
 34. base::vapply(...)
                                                                                                            


Quitting from lines 11-16 [unnamed-chunk-1] (tbl-cross-reprex-md.qmd)

Execution halted
````

There's no error with gt version 0.10.1.

**Comment by olivroy** [comment]
Thanks for the report. The culprit is possibly here https://github.com/rstudio/gt/pull/1578. in utils

**Comment by olivroy** [comment]
Found the issue `charToRaw("")` gives `character(0)`. Base R consistency strikes again! It sucks when the length of something can change without you knowing.

**Comment by olivroy** [comment]
@remlapmot @ddsjoberg I opened #1772 that should solve the issue. Would you mind doing some testing. I don't know if it would preferable to "cancel" `md()` processing for a single empty string.

```r
md <- function(text) {

  # Apply the `from_markdown` class
if (length(x) == 1 && !nzchar(x, keepNA = FALSE)) {
  return(x)
}
  class(text) <- "from_markdown"
  text
}
```

**Comment by ddsjoberg** [comment]
Thanks for the quick fix @olivroy !!! amazing

I tested the example posted above, and the original issue found in gtsummary, and they both appear resovled with the update 🐐 

<img width="1149" alt="image" src="https://github.com/user-attachments/assets/b89a9ef7-37fb-43a4-9c1f-83a68cbe9824">

**Comment by remlapmot** [comment]
Thanks for such a rapid fix.
