### ISSUE TITLE
Footnote marker placement when using `gt::md()` in Quarto in gt v0.11.0

### ISSUE THREAD

**Issue by ddsjoberg** [rstudio/gt#1773]
## Prework

* [x] Read and agree to the [code of conduct](https://www.contributor-covenant.org/version/2/1/code_of_conduct.html) and [contributing guidelines](https://github.com/rstudio/gt/blob/master/.github/CONTRIBUTING.md).
* [x] If there is [already a relevant issue](https://github.com/rstudio/gt/issues), whether open or closed, comment on the existing thread instead of posting a new issue.

## Description

When a footnote is placed next to text that has been processed with `gt::md()`, the footnote marker is placed in a separate row when rendered with Quarto. I spotted this behaviour in both column labels and footnotes (I haven't checked all location types, e.g. table cells, grouped row headers, summary rows, etc FYI). Note this does not occur when running the code interactively in the RStudio IDE. I think this is new behavior in gt 0.11.0.

## Reproducible example

In the example below, I am using `gt::md()` in the column label and in the actual footnote text. In both cases, the use of `gt::md()` drives the footnote marker so its own row.

````
---
title: "Untitled"
format:
  html:
    embed-resources: true
---

## Quarto

gt footnotes without `gt::md()`: no issues.

```{r}
mtcars[1:2, 1:2] |> 
  gt::gt() |> 
  gt::cols_label(mpg = "**MPG**") |> 
  gt::tab_footnote(
    "_Adding footnote_",
    locations = gt::cells_column_labels(columns = gt::everything())
  )
```

gt footnotes **WITH** `gt::md()`: footnote markers appear on their own line.

```{r}
mtcars[1:2, 1:2] |> 
  gt::gt() |> 
  gt::cols_label(mpg = gt::md("**MPG**")) |> 
  gt::tab_footnote(
    gt::md("_Adding footnote_"),
    locations = gt::cells_column_labels(columns = gt::everything())
  )
```
````

<img width="1215" alt="image" src="https://github.com/user-attachments/assets/f9c230b5-3b45-4e24-a822-28fcc6e122e0">

Thank you again!!! 🕺🏼 

PS This issue could be related to https://github.com/rstudio/gt/issues/1541. But that doesn't mention Quarto?

**Comment by olivroy** [comment]
Thanks for the report!

Will have to double check, but  it seems like the issue you mentioned  (#1541) has been fixed. We'll have to check for this one and Quarto rendering. This is probably related to #1769 and base64encoding. We will have to investigate. It is maybe an issue of <span> / <div>. I am not too familiar.

**Comment by ddsjoberg** [comment]
Thanks @olivroy ! Let me know if I can help in any way. The issues that only pop up in quarto sound vvv tricky

**Comment by olivroy** [comment]
I looked for the diff between the html code generated under Quarto 

Here is the (unhelpful) diff 
![image](https://github.com/user-attachments/assets/d837985e-a700-4d7c-80d6-91fca450a7ce)


@ddsjoberg A way I have found to test output is the following.


```r
gt_tbl <- mtcars[1:2, 1:2] |> 
  gt::gt() |> 
  gt::cols_label(mpg = gt::md("**MPG**")) |> 
  gt::tab_footnote(
    gt::md("_Adding footnote_"),
    locations = gt::cells_column_labels(columns = gt::everything())
  )
# inside Quarto
html_code_quarto <- withr::with_envvar(c("QUARTO_BIN_PATH" = "true"), gt:::render_as_html(gt_tbl))
# out of Quarto
html_code <- withr::with_envvar(c("QUARTO_BIN_PATH" = ""), gt:::render_as_html(gt_tbl))

waldo::compare(html_code, html_code_quarto, x_arg = "html", y_arg = "quarto")
```

I am pretty sure the problem occurs in the `md_to_html()` function.

But I really have no idea what the correct html code should be in this context.

**Comment by ddsjoberg** [comment]
> If you know how to fix something, we'd welcome PRs too!

I think this one is beyond me. (I am no HTML 🧙🏼 !) Sorry @olivroy !

**Comment by bzkrouse** [comment]
I've tested a few more locations and the stub columns are affected too:

```
mtcars[1:2, 1:2] |>
  tibble::rownames_to_column(var = "name") |>
  gt::gt(rowname_col = "name", process_md = TRUE) |>  
  gt::tab_footnote(
    gt::md("_Adding footnote_"),
    locations = gt::cells_stub(rows = 1)
  )
```

and

```
mtcars[1:2, 1:2] |>
  tibble::rownames_to_column(var = "name") |>
  gt::gt(groupname_col = "name", process_md = TRUE) |>  
  gt::tab_footnote(
    gt::md("_Adding footnote_"),
    locations = gt::cells_row_groups()
  )
```
 
(Rmarkdown seems fine!)
Thanks!!

**Comment by ddsjoberg** [comment]
Thank you so much for the fix!! 😻
