### ISSUE TITLE
`fmt_scientific()` should have an option to set the number of power

### ISSUE THREAD

**Issue by zenggyu** [rstudio/gt#179]
`fmt_scientific()` should have an option to set the number of power so that the difference in magnitude is more obvious. Consider the following example:

![_6](https://user-images.githubusercontent.com/10095784/52692811-e9c7c600-2f9f-11e9-934b-30a539eb2b09.png)

The column on the left is what the `fmt_scientific()` does now. There are two powers, i.e., 10^4 and 10^5. It is easy to overlook the power and think that the row in red contains the smallest value. A more obvious presentation would be to use a fixed power (i.e., 10^4), as shown in the right column. It is easy to see that the row in red contains the largest value. The number of power to use can be set manually or be determined by the smallest/largest value.

**Comment by rich-iannone** [comment]
Thanks for posting the issue. Having a fixed power for a set of numbers is completely valid and seems reasonable for comparing across numbers, however, this is not scientific notation (where the mantissa, or coefficient, is in [1, 10)) and so it doesn't belong in `fmt_scientific()`.

An alternative is to use `fmt_number()` with scaling and a pattern:

```r
library(gt)
library(tidyverse)

dplyr::tibble(a = c(1000, 5000, 10000, 15000)) %>%
  gt() %>%
  fmt_number(
    columns = vars(a),
    decimals = 2,
    scale_by = 1E-3,
    pattern = "{x} &times; 10<sup>3</sup>"
  )
```

<img width="751" alt="fmt_number_scale_pattern" src="https://user-images.githubusercontent.com/5612024/53134849-c6c08780-3546-11e9-888d-08ddc06c044e.png">
