### ISSUE TITLE
Feature request: combine gt with cowplot or patchwork

### ISSUE THREAD

**Issue by JasonAizkalns** [rstudio/gt#180]
Following #155, it would be fantastic if gt would play nicely with [cowplot](https://github.com/wilkelab/cowplot), [patchwork](https://github.com/thomasp85/patchwork), or similar packages. A few graphics + neatly formatted summary table is a powerful combination for communicating insights effectively!

**Comment by rich-iannone** [comment]
Thanks for the feature request! This is a great idea and I do think we'll get there. I'd love to have the ability for gt to work well with these packages.

**Comment by DataKritter** [comment]
This would be so helpful.  Currently I'm exporting to .jpg and then re-inserting into a markdown document.
