### ISSUE TITLE
row striping options not respected in HTML rendered from Quarto due to table-striped CSS tag

### ISSUE THREAD

**Issue by drleehw** [rstudio/gt#1812]
gt doesn't seem to respect the row_striping options when rendering through Quarto to HTML. 

For example:
`data <- data.frame(
  Name = c("John", "Jane", "Doe"),
  Age = c(28, 34, 45),
  Occupation = c("Engineer", "Doctor", "Artist")
)

# Render the table using gt
gt_table <- gt(data)

gt_table %>% opt_stylize(style = 1, color = "blue", add_row_striping = FALSE)`

Or more directly:
`gt_table %>% opt_row_striping(row_striping = FALSE)`

Both produce tables in HTML that still have row striping. This seems to be because a `table-striped` is being applied regardless and the Quarto Bootswatch css applies formatting to all objects with that tag. Manually removing that tag from the resultant HTML file fixes the issue, but modifying the properties applied to that tag with CSS is complex and beyond the CSS knowledge of many R users. 

<img width="1028" alt="Untitled" src="https://github.com/user-attachments/assets/00550ef0-793d-4e21-8f72-f40df801d43b">

**Comment by olivroy** [comment]
The way to go is with https://quarto.org/docs/authoring/tables.html#disabling-quarto-table-processing (chunk or global option) like we do in some gt documentation.
https://github.com/rstudio/gt/blob/566c70bc4eb2e61162a6b4f5c45011595b44aab6/vignettes/gt-visual.qmd#L1-L11

 or with `tab_options(quarto.disable_processing = T)` . In Quarto 1.5, they added a new class

Further discussion in https://github.com/quarto-dev/quarto-cli/issues/6945 or https://github.com/rstudio/gt/issues/1739

In Quarto 1.5, this does the trick as well.

```r
#| classes: plain
gt(exibble)
```

**Comment by drleehw** [comment]
Superb! Thanks for the quick help, @olivroy. Can confirm it works.
