### ISSUE TITLE
Recommend usage of remotes package for installation from GitHub rather than devtools

### ISSUE THREAD

**Issue by szimmer** [rstudio/gt#1815]
## Prework

- [x] Read and abide by **gt**'s [code of conduct](https://www.contributor-covenant.org/version/2/1/code_of_conduct.html) and [contributing guidelines](https://github.com/rstudio/gt/blob/master/.github/CONTRIBUTING.md).
- [x] Search for duplicates among the [existing issues](https://github.com/rstudio/gt/issues) (both open and closed).

## Proposal

In the README, it is recommended to use devtools to install the development version of the package. I suggest changing to using remotes as this package is lighter weight and if the user is only using it to install from GitHub and not to do package development work, they shouldn't need to install the much larger package of devtools.

Instead of 

```
devtools::install_github("rstudio/gt")
```

Use 

```
remotes::install_github("rstudio/gt")
```

**Comment by olivroy** [comment]
Thanks for raising this! The new "standard" is to recommend using pak for dev install  in the tidyverse / r-lib (that gt usually roughly follows). We may switch to `pak::pak("rstudio/gt")` at some point in the future. See discussion in https://github.com/r-lib/usethis/issues/2013 for more information.
