### ISSUE TITLE
Footnotes do not render in grid output with locations specified

### ISSUE THREAD

**Issue by olivroy** [rstudio/gt#1831]
The following example errors in grid.

```r
library(gt)
gt<- exibble %>%
  gt() %>%
  tab_footnote("xx", cells_column_labels(1))
plot(gt)
#> Error in apply_footnotes_methd[[context]]
```

gt 0.11.0

The problem lies in the fact that a `footnote_mark_to_grid()` should be created.

I just don't know how this should look like.

In z-utils-footnotes_render.R, line 800 ish, the `footnotes_dispatch` should add grid.

Look at https://github.com/rstudio/gt/pull/1268 to understand how the footnote_mark_*() functions work.

Figure out how to specify a superscript in grid (or render html).

There is also an issue with `fmt_units()`

**Comment by olivroy** [comment]
@teunbrand I wonder if you may have some time to look into this! I tried looking into, but I didn't find it obvious at all to figure out the super-scripts problems.

A similar (but different issue also occurs with `fmt_units()`. 

```r
library(gt)
illness |>
    dplyr::slice_head(n = 10) |>
    gt(rowname_col = "test") |>
    tab_header("Partial summary of daily tests performed on YF patient") |>
    fmt_units(columns = units) |>
     as_gtable()
#> Error in units_to_superscript()
#> Object out not found
```

**Comment by teunbrand** [comment]
The default `grid::textGrob()` has no support for superscripts, so unless you're willing to take on a {gridtext} or {marquee} dependency, this is hard to achieve. Probably the solution of least surprise is to just render the text without any markup.

**Comment by teunbrand** [comment]
{marquee} doesn't translate any html, but it can do markdown, so sub- and superscripts are in scope.
Essentially you'd have to invent a browser to properly translate html to grid, which is why no package is doing this.
