### ISSUE TITLE
Spanners appear incorrect when rendering with Quarto

### ISSUE THREAD

**Issue by snhansen** [rstudio/gt#1839]
Table spanners in gt-tables appear above the spanner label and not below as it should when rendering to html.

### Steps to reproduce

	---
	format: html
	---

	```{r}
	mtcars[1:3, 1:4] |> 
	  gt::gt() |> 
	  gt::tab_spanner(label = gt::md("Header"), columns = 2:3)
	```

### Expected behavior

![image](https://github.com/user-attachments/assets/4e4f9ab1-9c5b-4758-9f4d-5e304a954c29)

### Actual behavior

![image](https://github.com/user-attachments/assets/ef285aa9-ca1b-493c-84c2-b5677eb3212a)

I posted the issue on the Quarto repository and was told that the HTML emitted by `gt` doesn't validate in this case (https://github.com/quarto-dev/quarto-cli/issues/10534)

**Comment by olivroy** [comment]
Thanks for the report! We may have identified the source of the problem https://github.com/rstudio/gt/pull/1842#issuecomment-2303117922
