### ISSUE TITLE
Embedded newlines in column labels  

### ISSUE THREAD

**Issue by aetiologicCanada** [rstudio/gt#184]
I would like gt::cols_label to support embedded new lines, e.g. (in an Rmd)

```r
diamonds %>% select(price) -> junk 
     table <-   junk %>% gt()%>%
       cols_label(
          price = "Who\nWould\nEver\nPay\nThat\nMuch?"
  )
print(table)

```
Current output shows no new lines.

**Comment by rich-iannone** [comment]
Here's something that will work for HTML output:

```r
exibble %>%
  gt() %>%
  cols_label(
    datetime = html("This<br>Is<br>the<br>Date<br>and<br>Time")
  )
```

<img width="949" alt="newlines_gt_column_label" src="https://user-images.githubusercontent.com/5612024/52993116-00777e00-33e1-11e9-88e9-082f1fb9e46e.png">


I do think, however, that we need some portable way (i.e., works across HTML, LaTeX, and RTF) to easily signal newlines.

**Comment by andrewnguyen42** [comment]
@rich-iannone I wanted to piggyback off of this question. Are we able to put latex in column labels? I tried various combinations of `md` and `escape_latex` but I wasn't able to get the desired result

```r
exibble %>%
  gt %>%
  cols_label(time = md("$\tau$"))
```

**Comment by kendonB** [comment]
@rich-iannone your code with line breaks doesn't currently work for me on Ubuntu 18.04. Works for me on Windows 10. Any tips?
