### ISSUE TITLE
opt_interactive() breaks web_image() in 0.11

### ISSUE THREAD

**Issue by apsteinmetz** [rstudio/gt#1846]
This image is properly displayed in version 0.10 within a shiny/bslib web dashboard:
```
library(shiny)
library(bslib)
library(gt)

my_table <- data.frame(country = "Ukraine",flag_url="https://flagcdn.com/w40/ua.png")

ui <- bslib::page(gt::gt_output("table"))

server <- function(input, output) {
    output$table <- gt::render_gt({
        my_table |> 
            gt() |> 
            opt_interactive() |>
            text_transform(
                locations = cells_body(columns = flag_url),
                fn = function(x) { web_image(url = x, height = 30) }
            )
    })
}
shinyApp(ui = ui, server = server)

```
but in version 0.11 the `flag_url` column is just renders as the literal url.

**Comment by olivroy** [comment]
Hi! Thanks for the report

This is fixed in the dev version! `pak::pak("rstudio/gt")`

You may want to take a look at the new(ish) `fmt_flag()` function that would potentially simplify your code!

You would have to supply the country name as its code however. For Ukraine, it is `"ua"` for example!

**Comment by olivroy** [comment]
You may want to look also at `fmt_image()`

```r
library(shiny)
library(bslib)
library(gt)

my_table <- data.frame(country = "ua",flag_url="https://flagcdn.com/w40/ua.png")

ui <- bslib::page(gt::gt_output("table"))

server <- function(input, output) {
  output$table <- gt::render_gt({
    my_table |>
      gt() |>
      opt_interactive() |>
      fmt_flag(columns = country) |>
      fmt_image(flag_url)
  })
}
shinyApp(ui = ui, server = server)
```

That shows two ways to include the country flags
![image](https://github.com/user-attachments/assets/dd422956-e930-4ddb-a06e-0efcab66054d)

**Comment by apsteinmetz** [comment]
Well, I'll be darned!  Sorry I didn't see fmt_image() or fmt_flag() earlier. That would have saved some time.  I'm glad I spotted a bug, anyway.  In the end I decided to use fmt_image() with the flag URLs to get a bigger, rectangular image, rather than the itty bitty circles.  You might want to to make flag shape and/or size an option in fmt_flag().  Thanks for the response.

**Comment by olivroy** [comment]
> You might want to to make flag shape and/or size an option in fmt_flag()

Feel fee to open a feature request about that! (new issue!) Although it is implemented on top of `fmt_icons()`, so would require refactoring to work (If I understand correctly)

**Comment by apsteinmetz** [comment]
but wait. There's more.  opt_interactive() does not play nice with deployments to shinyapps.io.  I'll open another bug report to describe but it's the same problem I suspect.
