### ISSUE TITLE
opt_interactive() prevents table render on shinyapps.io

### ISSUE THREAD

**Issue by apsteinmetz** [rstudio/gt#1849]
## Prework

* [ x] Read and agree to the [code of conduct](https://www.contributor-covenant.org/version/2/1/code_of_conduct.html) and [contributing guidelines](https://github.com/rstudio/gt/blob/master/.github/CONTRIBUTING.md).
* [ x] If there is [already a relevant issue](https://github.com/rstudio/gt/issues), whether open or closed, comment on the existing thread instead of posting a new issue.

## Description
The following shiny app renders three tables on my Windows machine but on shinyapps.io (Ubuntu, I believe) the second and third tables that are rendered using opt_interactive() do not appear. You can see the app here: [https://viztoy.shinyapps.io/gt_test/](https://viztoy.shinyapps.io/gt_test/).  I include image cells because at one point I thought that was the problem but apparently not.  This bug also exists with the prior versions of shiny, bslib and gt

```
library(shiny)
library(bslib)
library(gt)

si <- sessionInfo()
pkgs <- paste(names(si$otherPkgs),collapse = ", ")

vers <- sapply(si$otherPkgs, function(pkg) pkg$Version) |> 
    paste(collapse = ", ")

my_table <- data.frame(country = "Ukraine",
                       use_fmt_image ="https://flagcdn.com/w40/ua.png",
                       use_text_transform = "https://flagcdn.com/w40/ua.png")

ui <- bslib::page(
  p("Table with 'opt_interactive()' OFF"),
  gt::gt_output("table1"),
  p("Table with 'opt_interactive()' ON"),
  gt::gt_output("table2"),
  p("Table with 'opt_interactive()' ON but no images"),
  gt::gt_output("table3"),
  p("Packages: "),
  p(pkgs),p(vers)
)

server <- function(input, output) {
  output$table1 <- gt::render_gt({
    my_table |> 
      gt() |> 
      # opt_interactive() |>
      fmt_image(columns = use_fmt_image) |>
      text_transform(
        locations = cells_body(columns = use_text_transform),
        fn = function(x) { web_image(url = x, height = 30) }
      )
  })
  output$table2 <- gt::render_gt({
    my_table |> 
      gt() |> 
      opt_interactive() |>
      fmt_image(columns = use_fmt_image) |>
      text_transform(
        locations = cells_body(columns = use_text_transform),
        fn = function(x) { web_image(url = x, height = 30) }
      )
  })
  output$table3 <- gt::render_gt({
    my_table |> 
      gt() |> 
      opt_interactive()
  })  
  
}
shinyApp(ui = ui, server = server)
```

**Comment by olivroy** [comment]
This may be an error from reactR 0.6.0. https://github.com/react-R/reactR/issues/86#issuecomment-2227664872. It will possibly work if you downgrade version?

**Comment by apsteinmetz** [comment]
Bingo! Since I never explicitly loaded reactR or reactable I never would have found the problem without your help.  Downgrading reactR to 0.5.0 and reactable to 0.4.3 solved the problem.  Still have to use fmt_image() rather than text_tranform(...web_image()), which is the smarter way, anyway.  Thanks!  The actual demo is here: [https://viztoy.shinyapps.io/olympic/](https://viztoy.shinyapps.io/olympic/)

**Comment by olivroy** [comment]
Thanks for sharing!

**Comment by xx02al** [comment]
Thanks for sharing also from my side. I was facing a similar problem and downgrading the {reactR} package from 0.6.0 to 0.5.0 resolved the issues. 
In the case I was facing, there were 8, code-wise and regarding application logic similar, {gt} tables with `opt_interactive()` spread across multiple modules in a R Shiny app, whereby there is no communication between the modules mentioned. Locally (windows machine), everything worked well. While 6 of the {gt} tables got rendered as intended also when deployed on shinapps.io, for two of them there was nothing but the `gt::tab_source_note()`. I don't know how long it would have taken to find the root of the problems without hints like the documentation here. Hopefully the problems with reactR will be fixed soon.

**Comment by olivroy** [comment]
reactR 0.6.1 released. This should be fixed!

**Comment by xx02al** [comment]
Thanks @olivroy. After updating reactR to 0.6.1 and re-deploying on shinyapps.io, I can confirm that the problems I described above, which occurred with reactR 0.6.0, no longer occur. I.e., using reactR 0.6.1 the app works as intended (as it also did with reactR 0.5.0).
