### ISSUE TITLE
gt data_color does not produce color in PDF but does in HTML

### ISSUE THREAD

**Issue by 1186684BC** [rstudio/gt#185]
Two files: one with yaml output option html_document, the other with pdf_document
HTML option generates coloured cells as expected, but not PDF. 
Can anyone confirm? Linux, R3.5.2

[---
title: "color_pdf"
author: "rcj"
date: "18/02/2019"
output: html_document
---

```{r}
library(tidyverse)
library(gt)

```

```{r}
sessionInfo()
```
```{r}
diamonds %>% select(color, price) %>% group_by(color) %>% 
  summarise(meanprice = mean(price)) %>% 
  gt %>% 
   data_color(columns=vars(meanprice),
               color=scales::col_bin(
                 bins=c(2000, 4000, 4500, 5200, 8000),
                 palette = c("green", "yellow", "orange", "red"),
                 domain=c(0,10000))
    )

``````

[diamond_colour_pdf.pdf](https://github.com/rstudio/gt/files/2877066/diamond_colour_pdf.pdf)

**Comment by rich-iannone** [comment]
Thanks for posting this issue. Currently, colored cells are not supported in LaTeX (or RTF). Apologies for not stating this clearly in any documentation. We wanted to get some more parity between LaTeX and HTML, so, this work will be prioritized.

Noted that this is of immediate relevance to https://github.com/bcgov/air-zone-reports/issues/1

**Comment by 1186684BC** [comment]
Many thanks. Short term suggestion is just to add this caveat to the help for data_color.  Great package. Many thanks.
