### ISSUE TITLE
Misleading text in examples for opt_table_font()

### ISSUE THREAD

**Issue by kelliemac** [rstudio/gt#1879]
## Prework

* [X] Read and agree to the [code of conduct](https://www.contributor-covenant.org/version/2/1/code_of_conduct.html) and [contributing guidelines](https://github.com/rstudio/gt/blob/master/.github/CONTRIBUTING.md).
* [X] If there is [already a relevant issue](https://github.com/rstudio/gt/issues), whether open or closed, comment on the existing thread instead of posting a new issue.

## Description

In the examples for `opt_table_font()` it says "Then, set a larger font size for the table..." but this does not appear to be implemented in the example, or even possible with `opt_table_font()`. This phrase should be removed from the example.

As an aside: it would be great to implement changing font size across the whole table with `opt_table_font()`. I was looking for this option which is how I ended up here - scaling the font size for the whole table up or down is something I commonly do, and it's annoying/issue-prone to use `tab_style()` applied to each portion of the table.

## Reproducible example

Not applicable - this is just about documentation.

**Comment by rich-iannone** [comment]
Thanks for providing this issue! I'm going to tackle this one by adding the `size` and `color` arguments to `opt_table_font()` so that these useful properties are available. I'll change the misleading text in the example as well.

**Comment by kelliemac** [comment]
@rich-iannone awesome!! thank you so much! that will be really helpful.
