### ISSUE TITLE
Table renders in interactive R but not inside a Quarto document

### ISSUE THREAD

**Issue by harrelfe** [rstudio/gt#1887]
## Prework

* [ x] Read and agree to the [code of conduct](https://www.contributor-covenant.org/version/2/1/code_of_conduct.html) and [contributing guidelines](https://github.com/rstudio/gt/blob/master/.github/CONTRIBUTING.md).
* [ x] If there is [already a relevant issue](https://github.com/rstudio/gt/issues), whether open or closed, comment on the existing thread instead of posting a new issue.

## Description

I produced a `gt` table containing sparklines successfully with earlier versions of `gt`/R as seen at the [end of this chapter](https://hbiostat.org/rflow/rformat).  The table renders fine from the console but causes an error when rendering a `Quarto` document that renders the table.  I have not included the code that produces the `gt` result because of its complexity.

 
## Reproducible example

I captured the `gt` object at https://htmp.netlify.app/b.rds.   This renders fine from the console except for not showing the sparklines.

```
require(gt)
b <- readRDS('/tmp/b.rds')
b
```

But rendering a `Quarto` document results in these errors:

```
processing file: test.qmd
  |...................................                 |  67% [unnamed-chunk-1]Error in `vapply()`:
! values must be length 1,
 but FUN(X[[1]]) result is length 0
Backtrace:
  1. global .main()
  2. execute(...)
  3. rmarkdown::render(...)
  4. knitr::knit(knit_input, knit_output, envir = envir, quiet = quiet)
  5. knitr:::process_file(text, output)
     ...
 16. base::withRestarts(...)
 17. base (local) withRestartList(expr, restarts)
 18. base (local) withOneRestart(withRestartList(expr, restarts[-nr]), restarts[[nr]])
 19. base (local) docall(restart$handler, restartArgs)
 21. evaluate (local) fun(base::quote(`<smplErrr>`))
```

Here is the `Quarto` script:

```
---
title: "Untitled"
format: html
editor: visual
---

````{r}
require(gt)
require(sparkline)
sparkline(0)
b <- readRDS('/tmp/b.rds')
b
````
```

Any help appreciated.

## Session info

```
R version 4.4.0 (2024-04-24)
Platform: aarch64-apple-darwin20
Running under: macOS Sonoma 14.6.1

Matrix products: default
BLAS:   /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib 
LAPACK: /Library/Frameworks/R.framework/Versions/4.4-arm64/Resources/lib/libRlapack.dylib;  LAPACK version 3.12.0

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

time zone: America/Chicago
tzcode source: internal

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] sparkline_2.0 gt_0.11.0    

loaded via a namespace (and not attached):
 [1] vctrs_0.6.5       cli_3.6.3         knitr_1.48        rlang_1.1.4      
 [5] xfun_0.47         generics_0.1.3    jsonlite_1.8.9    glue_1.7.0       
 [9] markdown_1.13     htmltools_0.5.8.1 sass_0.4.9        fansi_1.0.6      
[13] tibble_3.2.1      fastmap_1.2.0     yaml_2.3.10       lifecycle_1.0.4  
[17] compiler_4.4.0    dplyr_1.1.4       htmlwidgets_1.6.4 pkgconfig_2.0.3  
[21] rstudioapi_0.16.0 digest_0.6.37     R6_2.5.1          tidyselect_1.2.1 
[25] utf8_1.2.4        pillar_1.9.0      commonmark_1.9.1  magrittr_2.0.3   
[29] tools_4.4.0       xml2_1.3.6       
```

**Comment by olivroy** [comment]
The error appears to be fixed in the dev version of gt 0.11.0.9000. (Quarto 1.5.57)

In the book:
![image](https://github.com/user-attachments/assets/a7bf15c0-eaeb-4936-b581-e0e16a3cdab0)

Quarto 1.5.57 + gt 0.11.0.9000 
![image](https://github.com/user-attachments/assets/f3389a1e-5fb7-4d34-a6ab-a5e32f13b014)

I don't really know why the sparklines don't show up though.

gt offers [`cols_nanoplot()`](https://gt.rstudio.com/reference/cols_nanoplot.html). It may be useful to use this instead of sparklines in the meantime?

**Comment by harrelfe** [comment]
Thanks for the quick reply and good news.  The non-appearance of sparklines outside of `Quarto` is an old problem and doesn't worry me very much.    I'l glad to learn of `cols_nanoplot` and will look into it.   Do you have a guess on when the dev version will result in a CRAN submission?

**Comment by harrelfe** [comment]
I realized there is one reason I can’t use `cols_nanoplot`: I need to provide customized per-bar hover text in bar plots.

**Comment by olivroy** [comment]
@harrelfe gt 0.11.1 released! 

> I realized there is one reason I can’t use cols_nanoplot: I need to provide customized per-bar hover text in bar plots.

Feel free to open a new issue / feature request with more details. I agree with you. I wished there was a way to not show any numbers when hovering for example.

Can we close this issue? At heart, it was a duplicate of #1773. But please try the new version and let me know if things work as expected

**Comment by harrelfe** [comment]
The new version fixed it.  Thanks!
