### ISSUE TITLE
Error while installing gt

### ISSUE THREAD

**Issue by SteveVijayan** [rstudio/gt#1913]
I am getting the error below when installing gt. Any suggestions to fix this?

ERROR: compilation failed for package ‘V8’
* removing ‘/home/----/R/x86_64-pc-linux-gnu-library/4.4/V8’
ERROR: dependency ‘V8’ is not available for package ‘juicyjuice’
* removing ‘/home/----/R/x86_64-pc-linux-gnu-library/4.4/juicyjuice’
ERROR: dependency ‘juicyjuice’ is not available for package ‘gt’
* removing ‘/home/----/R/x86_64-pc-linux-gnu-library/4.4/gt’

✔ Package 'gt' successfully installed.
Warning messages:
1: In utils::install.packages("juicyjuice", repos = "https://cran.rstudio.com/") :
  installation of package ‘V8’ had non-zero exit status
2: In utils::install.packages("juicyjuice", repos = "https://cran.rstudio.com/") :
  installation of package ‘juicyjuice’ had non-zero exit status
3: In utils::install.packages("gt", repos = "https://cran.rstudio.com/") :
  installation of package ‘V8’ had non-zero exit status
4: In utils::install.packages("gt", repos = "https://cran.rstudio.com/") :
  installation of package ‘juicyjuice’ had non-zero exit status
5: In utils::install.packages("gt", repos = "https://cran.rstudio.com/") :
  installation of package ‘gt’ had non-zero exit status

**Comment by olivroy** [comment]
Hi! Thanks for the report. This is not a gt issue per say.

You are likely missing a system dependency.

You can try installing gt with [pak](https://pak.r-lib.org)

```r
pak::pak("gt")
```

which should help resolve the system dependencies problems.

#1284 includes more discussion.

You can also set your CRAN miror to use Posit Package Manager to install packages

https://p3m.dev/client/#/repos/cran/setup

See also https://github.com/jeroen/V8 as it may contain useful information on installation./

**Comment by SteveVijayan** [comment]
Thank you. I'll try your suggestions.
