### ISSUE TITLE
as_gtable not respecting cols_width in as_gtable when tab_options(table.width = pct(100))?

### ISSUE THREAD

**Issue by srcm-mark** [rstudio/gt#1923]
## Prework
Seems potentially related to #1907 

## Question
I generally using gt in combination with patchwork to output chart/table combos. The development of as_gtable gave me far more flexibility to craft the output (from the former roundtrip to .png. Thanks!!!). I have used table.width = pct(100) to ensure that that table output spans the width of the container, while using the cols_width to apportion individual columns.

Might there be another manner to achieve the objective of forcing the table to fit the output container while maintaining relative spacing across columns?

Seems as_gtable drops the table.width requirement (without as_gtable, table.width and cols_width both retained):
``` r
library(gt)
library(gtExtras)
library(tidyverse)

start_date <- "2010-06-07"
end_date <- "2010-06-08"

### no as_gtable
#### table.width not assigned
#### works as expected
sp_tab <- 
  sp500 %>%
  select(-c(volume, adj_close)) %>%
  dplyr::filter(date >= start_date & date <= end_date) %>%
  gt() %>%
  cols_width(date ~ pct(50))
gt_reprex_image(sp_tab)
```

<img src="https://i.imgur.com/Jneo6oi.png" width="1062" />

``` r

#### table.width assigned
#### works as expected
sp_tab <- 
  sp500 %>%
  select(-c(volume, adj_close)) %>%
  dplyr::filter(date >= start_date & date <= end_date) %>%
  gt() %>%
  tab_options(table.width = pct(100)) %>%
  cols_width(date ~ pct(50))
gt_reprex_image(sp_tab)
```

<img src="https://i.imgur.com/eK9lBmu.png" width="1972" />

``` r

### w/ as_gtable
#### table.width not assigned
#### works as expected
sp_tab <- 
  sp500 %>%
  select(-c(volume, adj_close)) %>%
  dplyr::filter(date >= start_date & date <= end_date) %>%
  gt() %>%
  cols_width(date ~ pct(50)) %>% 
  as_gtable(plot = TRUE)
```

![](https://i.imgur.com/Uu7jVxV.png)

``` r

#### table.width assigned
#### does not work as expected
sp_tab <- 
  sp500 %>%
  select(-c(volume, adj_close)) %>%
  dplyr::filter(date >= start_date & date <= end_date) %>%
  gt() %>%
  tab_options(table.width = pct(100)) %>%
  cols_width(date ~ pct(50)) %>% 
  as_gtable(plot = TRUE)
```

![](https://i.imgur.com/fKrlUrs.png)

<sup>Created on 2024-11-14 with [reprex v2.1.1](https://reprex.tidyverse.org)</sup>

**Comment by olivroy** [comment]
Hi @teunbrand! I wonder if you had time to look into this

**Comment by teunbrand** [comment]
This wasn't on my radar, but I'll take a look soon!

**Comment by teunbrand** [comment]
Looking back now at the homebrew table width calculations I wrote, it seems like I didn't anticipate percentage-width columns, just fixed-width columns.
I'd have to study https://www.w3.org/TR/CSS21/tables.html#auto-table-layout and try to mirror that with grid-units somehow.
