### ISSUE TITLE
Install

### ISSUE THREAD

**Issue by GSVeirano** [rstudio/gt#196]

**Comment by GSVeirano** [comment]
Problems to install "gt" in 
R version 3.5.2 (2018-12-20) -- "Eggshell Igloo"
Copyright (C) 2018 The R Foundation for Statistical Computing
Platform: x86_64-w64-mingw32/x64 (64-bit)

Message the Error
> library(gt)
Error: package or namespace load failed for ‘gt’ in library.dynam(lib, package, package.lib):
 DLL ‘sass’ not found: maybe not installed for this architecture?

**Comment by shrektan** [comment]
@GSVeirano You are missing [sass](https://github.com/rstudio/sass) package, which is a dependence package and not on CRAN yet.

Execute `remotes::install_github('rstudio/sass')` first and install `gt` again.
