### ISSUE TITLE
[FR] An easier way of disabling the row striping 

### ISSUE THREAD

**Issue by shrektan** [rstudio/gt#199]
Row striping is nice in general I agree. However, in cases that the content has already been cut up by row groups, it's not necessary. After searching all the documentation and examples, I think the disabling row striping feature is missing in `gt`.

Moreover, I cannot find a way to change the background color of the row striping. In my opinion, it's important in some cases as well.

Thanks.

## UPDATE

My current workaround is `gt::tab_style(gt::cells_styles(bkgd_color = '#FFFFFF'), gt::cells_data(gt::everything()))`

**Comment by rich-iannone** [comment]
I agree that there should be a working option to disable row striping. Also, setting an option for the coloring of the striping is important. This was also brought up in https://github.com/rstudio/gt/issues/3 (although there is no `theme_striped()` function anymore).
