### ISSUE TITLE
The meaning of `field` is not clearly documented

### ISSUE THREAD

**Issue by shrektan** [rstudio/gt#200]
Hi,

I love the below picture. It explains every __"jargon"__ of `gt` in an amazingly clear way. 

But, it misses the definition regarding to `field`  (like in `gt::tab_options(field.border.top.style = 'xxxxxx')`) . Looking through the documentations, I still don't know what `field` really means. 

It would be great if `field` can be marked somewhere in the "Parts of the gt Table"!

![image](https://user-images.githubusercontent.com/8368933/53402807-61104780-39ed-11e9-926e-e2b28eb0b58b.png)

**Comment by rich-iannone** [comment]
You're definitely right about it not being defined. In fact, the term 'field' refers to the same thing as 'table body' (we worked toward removing references to `field` and replacing that with `table body` but we missed this).

So, the thing to do here is to replace `field.border.top.style` (and others) with `table_body.border.top.style`.
