### ISSUE TITLE
rtf_document: footnote glyph only shown in table footer, not in corresponding cell

### ISSUE THREAD

**Issue by pagyeman** [rstudio/gt#204]
<Hi, 
Thank you for this awesome package. 
I have stumbled over a problem with footnotes in rtf_document output. The footnote is rendered correctly in the table footer, including the glyph. However, the glyph is not shown in the corresponding cell.>

```r
reprex(
  {
    library(reprex)
    library(gt)
    library(dplyr)
    library(here)
    
    sza %>%
      group_by(month) %>% 
      slice(1) %>% 
      gt() %>% 
      tab_footnote(
        footnote = "the first month of the year",
        locations = cells_group(
          groups = "jan"
        )
      ) %>% 
      gtsave(filename = here("example.rtf"))
  }
)
```

**Comment by rich-iannone** [comment]
This now works (tested it in my dev system) after the changes applied by https://github.com/rstudio/gt/pull/638 (which fixes RTF).
