### ISSUE TITLE
Feature request (shiny): Allow pagination

### ISSUE THREAD

**Issue by daattali** [rstudio/gt#207]
When creating a gt table in an html file (I'm thinking specifically shiny, but this could apply for rmarkdown or just any html output that can include javascript), it would be great to be able to add pagination. This way long tables are not just one massive table that you have to scroll down for.

With the ability to paginate, it'd be nice to be able to specify the page length.

A related feature would be to allow server-side pagination, so that if I have a table with 10000 rows, instead of sending all that data to the browser and making it slow, only eg. 25 rows get sent to the browser

**Comment by daattali** [comment]
Oh, I just ran into an excellent usecase :)

I was trying to run `gt::gt(gt::pizzaplace)` and I legitimately thought that it was broken and I was about to file a bug report. It just took about a full minute to render, and I thought my RStudio froze. 50k rows is a great usecase for pagination!

**Comment by rich-iannone** [comment]
Thanks for articulating this. Pagination is a thing that should be in **gt**. I do think @tareefk wants this feature as well.

**Comment by Analyst-In-The-Wild** [comment]
Has there been any progress on this as would be a really cool feature? - thanks 😺

**Comment by epijim** [comment]
@daattali - in the pharma industry this is requirement for us to write out the tables to go into a CSR for clinical trial submissions, so wondering if we could fold in our needs by removing shiny? (or is shiny pagination a distinct feature over static pagination)?

@rich-iannone - as discussed, sharing some draft requirements. And tagging a few Roche/Genentech engineering team leads to help refine this:  @shajoezhu, @donyunardi + our chief PO @telepath37 and engineer @pawelru

- [ ] Can paginate a table that would carry over multiple pages when printed (A4 + US letter)
- [ ] Pagination can be specified as landscape or portrait
- [ ] Header/titles carried across pages
- [ ] Subgroup titles repeated if split across pages
- [ ] Footnotes can carry across (if relevant) or appear on appropriate page (if cell specific)

**Comment by wvictor14** [comment]
> A related feature would be to allow server-side pagination, so that if I have a table with 10000 rows, instead of sending all that data to the browser and making it slow, only eg. 25 rows get sent to the browser

Does this exist in >0.9.0 ? I believe not since my large tables take appreciable time to render (e.g. 300 row table in shiny takes around 3-4 seconds to render)
