### ISSUE TITLE
Feature request (shiny): Allow a dataframe to be easily rendered by gt_output without explicit conversion to gt object

### ISSUE THREAD

**Issue by daattali** [rstudio/gt#208]
It would be very handy to have the following work:

```
library(shiny)

ui <- fluidPage(
  gt::gt_output("table")
)

server <- function(input, output, session) {
  output$table <- gt::render_gt(
    mtcars
  )
}

shinyApp(ui, server)
```

In this case I would expect the table to just be a plain boring gt object that simply gets created around `mtcars` with no parameters. This is opinion-based so if you disagree, feel free to close. It kind of goes against the philosophy of making the developer be super precise, and is more along the philosophy of trying to be useful in common expected cases.

**Comment by rich-iannone** [comment]
Ah interesting! This would take almost nothing to implement and it does make a lot of sense to keep things succinct.
