### ISSUE TITLE
Suggestion (shiny): rename or add alias from gt_output to GTOutput and render_gt to renderGT

### ISSUE THREAD

**Issue by daattali** [rstudio/gt#209]
In the shiny universe, all the inputs and outputs follow this naming convention. In the tidyverse things have shifted to use underscore, but in shiny even new features still use the shiny naming convention for consistency. I think it would make it easier for shiny developers to not have to switch contexts and use non-shiny naming conventions.

**Comment by rich-iannone** [comment]
We made a deliberate decision on this way back. Was never sure it was the right call. It's worth a discussion on how exactly to proceed but I agree that this is surprising.

**Comment by daattali** [comment]
Who is "we"? If @jcheng5 or @wch or someone else in the shiny team made this decision, then obviously their opinion is worth a toonie compared to my 2 cents :)

**Comment by rich-iannone** [comment]
Yeah, I commonly defer to their judgment with all things Shiny. And hey! your opinion is worth a lot. We care!

**Comment by daattali** [comment]
In that case, I would just like to formally ask for this to be re-considered and given thought for a few seconds. I won't push for this if they still think underscore is the way to go. Within-package naming convention is important too after all.

**Comment by rich-iannone** [comment]
Ah, sorry for the misunderstanding here. It actually wasn't either of @jcheng5 or @wch who were part of the earlier decision to name these as they are. So, this is ripe for review and reconsideration.
