### ISSUE TITLE
Feature request (shiny): Allow basic interactivity with the table

### ISSUE THREAD

**Issue by daattali** [rstudio/gt#211]
Related to #207 

A few basic interactivity controls would make this package a lot more useful for shiny apps. Off the top of my head, extremely common features that people generally want in a table:

- Ability to click on a column to sort by it
- Ability to search
- Ability to click on one/multiple rows and get a shiny callback specifying what rows are chosen

**Comment by cawthm** [comment]
Out of curiosity, has someone (ie one of the usual power-user contributors) articulated a delineation between the use case of GT vs that of DT?  I'm guessing the goal is for GT to be a more intuitive revamp of DT, but with an initial bias toward more static uses, but maybe I'm wrong.

Incidentally, mine is this: I need a customized/ formatted table to receive high freq incoming data, but one with which the user can richly interact.

In any case, thanks for the package.

**Comment by rich-iannone** [comment]
Closing since basic interactive tables are now possible to generate.
