### ISSUE TITLE
Suggestion: use consistent argument names

### ISSUE THREAD

**Issue by daattali** [rstudio/gt#212]
When looking at the function signature of `gt()`, I noticed that 3 of the arguments use underscore naming scheme, and one of the parameters is `stub_group.sep` which has both an underscore and a period. I sort of understand the reason, it looks like `group.sep` is a "property", but IMO this naming convention is awkward and will be very easy to get wrong.

Here's another example: I was scrolling through the `tab_options()` parameters, and it just doesn't look right IMO:

![image](https://user-images.githubusercontent.com/952340/53856518-3f403300-3fa0-11e9-8b15-abb8b9cb3041.png)

**Comment by rich-iannone** [comment]
This is kind of like the options in `ggplot2::theme()`, where the subcategories are separated by dots. The underscore appears (e.g., in `column_labels`) because I couldn't find a (nice) way to make certain categories a single word (so it uses snake case).

**Comment by daattali** [comment]
I understand the dot notation mirrors ggplot2, that part is ok (I *personally* don't like it, but that's completely just a personal choice question :) )
 
The issue I find is with having a single parameter use two different naming conventions within it. It looks... wrong/sloppy, for a lack of better word :grimacing:

**Comment by rich-iannone** [comment]
Would you suggest using snake case to separate the categories and just avoiding multi-word terms?

**Comment by daattali** [comment]
I would go with `column.labels.background.color` - but it you think that doesn't make sense you can close the issue

**Comment by rich-iannone** [comment]
Thought about it a bit and I think we will lose some of the clarity of having two delimiters in this case. But hey, we have autocomplete in RStudio so I think it won't be a problem.
