### ISSUE TITLE
Consider removing sass as a hard requirement *if at all possible*

### ISSUE THREAD

**Issue by daattali** [rstudio/gt#213]
I just installed the latest github version on R 3.5.2 Windows 7

Installing the `sass` package prerequisite took over 11 minutes, the rest of the installation proceeded in less than a minute.

If `sass` is absolutely integrated into the package and required then not much can be done, but if there's any way to make a few changes and to remove that dependency without degrading performance and code quality, it might be worth it to investigate.

**Comment by rich-iannone** [comment]
This will be less terrible when `sass` is on CRAN and available as a precompiled binary (and that's on me to get done). I agree though... it does take a long time to compile. However, it's absolutely essential to this package.

**Comment by daattali** [comment]
Fair enough, I can live with *temporary* pain!
