### ISSUE TITLE
Allow footnotes on row group labels?

### ISSUE THREAD

**Issue by sharlagelfand** [rstudio/gt#215]
I wonder if it'd be possible to allow footnotes on row group labels (I *think* that's what they're called)? I guess when it's grouped that column is ~special but I'd be curious of this is possible. TY!

``` r
library(gt)
library(dplyr)

# Can't put a footnote on a row group label

pizzaplace %>%
  group_by(type, name) %>%
  summarise(total_sales = sum(price)) %>%
  gt() %>%
  tab_footnote(
    footnote = "This is my favourite kind of pizza!",
    locations = cells_data(
      columns = vars(type),
      rows = type == "veggie"
    )
  )
#> Error in .f(.x[[i]], ...): object 'type' not found

# Can't use the row group label to put a footnote on another variable

pizzaplace %>%
  group_by(type, name) %>%
  summarise(total_sales = sum(price)) %>%
  gt() %>%
  tab_footnote(
    footnote = "This is my favourite kind of pizza!",
    locations = cells_data(
      columns = vars(name),
      rows = type == "veggie"
    )
  )
#> Error in rlang::eval_tidy(expr = var_expr, data = data, env = emptyenv()): object 'type' not found

# Works fine if it's not a row group label

pizzaplace %>%
  group_by(type, name) %>%
  summarise(total_sales = sum(price)) %>%
  ungroup() %>%
  gt() %>%
  tab_footnote(
    footnote = "This is my favourite kind of pizza!",
    locations = cells_data(
      columns = vars(type),
      rows = type == "veggie"
    )
  )
```

<div id="plbqfmptyp" style="overflow-x:auto;">

<table class="gt_table">

<tr>

<th class="gt_col_heading gt_left" rowspan="1" colspan="1">

type

</th>

<th class="gt_col_heading gt_left" rowspan="1" colspan="1">

name

</th>

<th class="gt_col_heading gt_right" rowspan="1" colspan="1">

total\_sales

</th>

</tr>

<tbody class="gt_table_body">

<tr>

<td class="gt_row gt_left">

chicken

</td>

<td class="gt_row gt_left">

bbq\_ckn

</td>

<td class="gt_row gt_right">

42768.00

</td>

</tr>

<tr>

<td class="gt_row gt_left gt_striped">

chicken

</td>

<td class="gt_row gt_left gt_striped">

cali\_ckn

</td>

<td class="gt_row gt_right gt_striped">

41409.50

</td>

</tr>

<tr>

<td class="gt_row gt_left">

chicken

</td>

<td class="gt_row gt_left">

ckn\_alfredo

</td>

<td class="gt_row gt_right">

16900.25

</td>

</tr>

<tr>

<td class="gt_row gt_left gt_striped">

chicken

</td>

<td class="gt_row gt_left gt_striped">

ckn\_pesto

</td>

<td class="gt_row gt_right gt_striped">

16701.75

</td>

</tr>

<tr>

<td class="gt_row gt_left">

chicken

</td>

<td class="gt_row gt_left">

southw\_ckn

</td>

<td class="gt_row gt_right">

34705.75

</td>

</tr>

<tr>

<td class="gt_row gt_left gt_striped">

chicken

</td>

<td class="gt_row gt_left gt_striped">

thai\_ckn

</td>

<td class="gt_row gt_right gt_striped">

43434.25

</td>

</tr>

<tr>

<td class="gt_row gt_left">

classic

</td>

<td class="gt_row gt_left">

big\_meat

</td>

<td class="gt_row gt_right">

22968.00

</td>

</tr>

<tr>

<td class="gt_row gt_left gt_striped">

classic

</td>

<td class="gt_row gt_left gt_striped">

classic\_dlx

</td>

<td class="gt_row gt_right gt_striped">

38180.50

</td>

</tr>

<tr>

<td class="gt_row gt_left">

classic

</td>

<td class="gt_row gt_left">

hawaiian

</td>

<td class="gt_row gt_right">

32273.25

</td>

</tr>

<tr>

<td class="gt_row gt_left gt_striped">

classic

</td>

<td class="gt_row gt_left gt_striped">

ital\_cpcllo

</td>

<td class="gt_row gt_right gt_striped">

25094.00

</td>

</tr>

<tr>

<td class="gt_row gt_left">

classic

</td>

<td class="gt_row gt_left">

napolitana

</td>

<td class="gt_row gt_right">

24087.00

</td>

</tr>

<tr>

<td class="gt_row gt_left gt_striped">

classic

</td>

<td class="gt_row gt_left gt_striped">

pep\_msh\_pep

</td>

<td class="gt_row gt_right gt_striped">

18834.50

</td>

</tr>

<tr>

<td class="gt_row gt_left">

classic

</td>

<td class="gt_row gt_left">

pepperoni

</td>

<td class="gt_row gt_right">

30161.75

</td>

</tr>

<tr>

<td class="gt_row gt_left gt_striped">

classic

</td>

<td class="gt_row gt_left gt_striped">

the\_greek

</td>

<td class="gt_row gt_right gt_striped">

28454.10

</td>

</tr>

<tr>

<td class="gt_row gt_left">

supreme

</td>

<td class="gt_row gt_left">

brie\_carre

</td>

<td class="gt_row gt_right">

11588.50

</td>

</tr>

<tr>

<td class="gt_row gt_left gt_striped">

supreme

</td>

<td class="gt_row gt_left gt_striped">

calabrese

</td>

<td class="gt_row gt_right gt_striped">

15934.25

</td>

</tr>

<tr>

<td class="gt_row gt_left">

supreme

</td>

<td class="gt_row gt_left">

ital\_supr

</td>

<td class="gt_row gt_right">

33476.75

</td>

</tr>

<tr>

<td class="gt_row gt_left gt_striped">

supreme

</td>

<td class="gt_row gt_left gt_striped">

peppr\_salami

</td>

<td class="gt_row gt_right gt_striped">

25529.00

</td>

</tr>

<tr>

<td class="gt_row gt_left">

supreme

</td>

<td class="gt_row gt_left">

prsc\_argla

</td>

<td class="gt_row gt_right">

24193.25

</td>

</tr>

<tr>

<td class="gt_row gt_left gt_striped">

supreme

</td>

<td class="gt_row gt_left gt_striped">

sicilian

</td>

<td class="gt_row gt_right gt_striped">

30940.50

</td>

</tr>

<tr>

<td class="gt_row gt_left">

supreme

</td>

<td class="gt_row gt_left">

soppressata

</td>

<td class="gt_row gt_right">

16425.75

</td>

</tr>

<tr>

<td class="gt_row gt_left gt_striped">

supreme

</td>

<td class="gt_row gt_left gt_striped">

spicy\_ital

</td>

<td class="gt_row gt_right gt_striped">

34831.25

</td>

</tr>

<tr>

<td class="gt_row gt_left">

supreme

</td>

<td class="gt_row gt_left">

spinach\_supr

</td>

<td class="gt_row gt_right">

15277.75

</td>

</tr>

<tr>

<td class="gt_row gt_left gt_striped">

veggie<sup class='gt_footnote_glyph'>1</sup>

</td>

<td class="gt_row gt_left gt_striped">

five\_cheese

</td>

<td class="gt_row gt_right gt_striped">

26066.50

</td>

</tr>

<tr>

<td class="gt_row gt_left">

veggie<sup class='gt_footnote_glyph'>1</sup>

</td>

<td class="gt_row gt_left">

four\_cheese

</td>

<td class="gt_row gt_right">

32265.70

</td>

</tr>

<tr>

<td class="gt_row gt_left gt_striped">

veggie<sup class='gt_footnote_glyph'>1</sup>

</td>

<td class="gt_row gt_left gt_striped">

green\_garden

</td>

<td class="gt_row gt_right gt_striped">

13955.75

</td>

</tr>

<tr>

<td class="gt_row gt_left">

veggie<sup class='gt_footnote_glyph'>1</sup>

</td>

<td class="gt_row gt_left">

ital\_veggie

</td>

<td class="gt_row gt_right">

16019.25

</td>

</tr>

<tr>

<td class="gt_row gt_left gt_striped">

veggie<sup class='gt_footnote_glyph'>1</sup>

</td>

<td class="gt_row gt_left gt_striped">

mediterraneo

</td>

<td class="gt_row gt_right gt_striped">

15360.50

</td>

</tr>

<tr>

<td class="gt_row gt_left">

veggie<sup class='gt_footnote_glyph'>1</sup>

</td>

<td class="gt_row gt_left">

mexicana

</td>

<td class="gt_row gt_right">

26780.75

</td>

</tr>

<tr>

<td class="gt_row gt_left gt_striped">

veggie<sup class='gt_footnote_glyph'>1</sup>

</td>

<td class="gt_row gt_left gt_striped">

spin\_pesto

</td>

<td class="gt_row gt_right gt_striped">

15596.00

</td>

</tr>

<tr>

<td class="gt_row gt_left">

veggie<sup class='gt_footnote_glyph'>1</sup>

</td>

<td class="gt_row gt_left">

spinach\_fet

</td>

<td class="gt_row gt_right">

23271.25

</td>

</tr>

<tr>

<td class="gt_row gt_left gt_striped">

veggie<sup class='gt_footnote_glyph'>1</sup>

</td>

<td class="gt_row gt_left gt_striped">

veggie\_veg

</td>

<td class="gt_row gt_right gt_striped">

24374.75

</td>

</tr>

</tbody>

<tfoot>

<tr>

<td colspan="3" class="gt_footnote">

<sup class='gt_footnote_glyph'><em>1</em></sup> This is my favourite kind of pizza\!

</td>

</tr>

</tfoot>

</table>

</div>

<sup>Created on 2019-03-06 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1.9000)</sup>

**Comment by rich-iannone** [comment]
You can! You have to use `cells_group()`.

```r
pizzaplace %>%
  group_by(type, name) %>%
  summarise(total_sales = sum(price)) %>%
  gt() %>%
  tab_footnote(
    footnote = "This is my favourite kind of pizza!",
    locations = cells_group(groups = "chicken")
    )
  )
```

<img width="646" alt="cells_group_example" src="https://user-images.githubusercontent.com/5612024/53922859-08bbf400-4044-11e9-81b9-a3e8dc0eb8de.png">

I think this raises the issue that the location helper function name isn't that descriptive of the location. Maybe this should be called `cells_rows_group()`?

**Comment by sharlagelfand** [comment]
Oh yeesh I probably could have just read more documentation instead of opening this! I'm happy to just close this issue!

**Comment by rich-iannone** [comment]
Closing this issue because https://github.com/rstudio/gt/issues/322 is focused on the remaining problem (renaming `cells_group()`). Thanks, Sharla!
