### ISSUE TITLE
Add option to remove column labels

### ISSUE THREAD

**Issue by rich-iannone** [rstudio/gt#225]
There are some situations where you wouldn't want column labels in a table. This might be text heavy table where headings are implied or this could be a table for arranging content in an email message.

Here is an example of how this might work in practice with a table made from Markdown elements. We could have the argument `hide_column_labels` in `tab_options()` and set it to `TRUE` when we don't want to display the column labels.

```r
# Create a few Markdown-based
# text snippets
text_1a <- "
 ### This is Markdown.

 Markdown’s syntax is comprised entirely of
 punctuation characters, which punctuation
 characters have been carefully chosen so as
 to look like what they mean... assuming
 you’ve ever used email.
 "

text_1b <- "
 Info on Markdown syntax can be found
 [here](https://daringfireball.net/projects/markdown/).
 "

text_1c <- "<img src=\"https://i.imgur.com/3RqWtfL.gif\" width=\"200\">"

text_2a <- "
 The **gt** package has these datasets:

  - `countrypops`
  - `sza`
  - `gtcars`
  - `sp500`
  - `pizzaplace`
  - `exibble`
 "

text_2b <- "
 There's a quick reference [here](https://commonmark.org/help/).
 "

text_2c <- "
 Yes, gifs should work.
 "

# Arrange the text snippets as a tibble
# using the `dplyr::tribble()` function;
# then, create a gt table and format
# all columns with `fmt_markdown()`
dplyr::tribble(
  ~Markdown, ~md,
  text_1a,   text_2a,
  text_1b,   text_2b,
  text_1c,   text_2c,
) %>%
  gt() %>%
  fmt_markdown(columns = TRUE) %>%
  tab_options(
    table.width = px(500),
    hide_column_labels = TRUE
  )
```

<img width="521" alt="no_column_labels" src="https://user-images.githubusercontent.com/5612024/54368624-dfeebc80-464a-11e9-80cc-c90f65811c71.png">

**Comment by rayuto029** [comment]
Hi! Could you tell me if there´s any way to hide row labels as well?

I´ve posted this question in SOF:
https://stackoverflow.com/questions/68137803/hide-grand-summary-rows-labels-in-gt-package

Thanks in advance!

**Comment by mbjohnsonmn** [comment]
FYI, the tab_options() attribute has changed. To suppress column labels, use column_labels.hidden = TRUE. 

See https://gt.rstudio.com/reference/tab_options.html
