### ISSUE TITLE
Bug with text_transform(...) and cells_column_labels(...)

### ISSUE THREAD

**Issue by banbh** [rstudio/gt#231]
When I run the example below I get an error with message `Error in text_transform_at_location.cells_column_labels(loc = transform$resolved,  : unused argument (fn = transform$fn)`. This seems like a bug (and, in particular, `text_transform(locations = cells_data(vars(char)), fn = toupper)` works fine).

```r
library(tidyverse)
library(gt)

exibble %>%
  gt() %>%
  text_transform(locations = cells_column_labels(vars(char)), fn = toupper)
```

**Comment by rich-iannone** [comment]
Thanks for filing this issue. The `text_transform()` function can only accept a `cells_data()` location, making this an incomplete solution.

**Comment by rich-iannone** [comment]
This now works in the development version of {gt} (was fixed in https://github.com/rstudio/gt/pull/699).

Now if you use

```r
library(gt)

exibble %>%
  gt() %>%
  text_transform(
    locations = cells_column_labels(columns = char),
    fn = toupper
  )
```

you'll get

<img width="926" alt="table" src="https://user-images.githubusercontent.com/5612024/116296759-98fbac80-a768-11eb-9b4e-dfc902b62472.png">
