### ISSUE TITLE
Create table themes

### ISSUE THREAD

**Issue by rich-iannone** [rstudio/gt#238]
Create preset table themes and include several additional styling options (e.g., control over horizontal and vertical borders).

**Comment by rich-iannone** [comment]
Here are some ideas/schematics:

<img width="1055" alt="table_theme_schematics" src="https://user-images.githubusercontent.com/5612024/55635094-e07ffc00-578d-11e9-9fcb-8ba58b93b7cb.png">

The chosen colors use a standard set of six. And there is grayscale. The top row (`S`) is used exclusively for striping rows.

<img width="779" alt="standard_hues" src="https://user-images.githubusercontent.com/5612024/55635099-e4ac1980-578d-11e9-8095-51bb2fa0d87e.png">

One thing that is lacking so far is more grayscale themes. Those are forthcoming.

Aside from these mockups for the overall look, the different line segments (e.g., right of stub, summary border top/bottom, etc.) and cell types need to be a bit more rigorously defined, and, named.

**Comment by genepi10** [comment]
These look fantastic! When can we have them?

**Comment by rich-iannone** [comment]
The above preset schematics need to be updated to incorporate the header, row groups, and the grand summary.

**Comment by charlesatkinson2000** [comment]
I fully support having these themes. I feel they would provide an easy way to style a table nicely (which could then be further modified/adjusted with tab_options).

**Comment by charlesatkinson2000** [comment]
Also, nice color choices here. These all look very nice.

**Comment by jennarowe99** [comment]
Any update on whether the themes will be added to the package? I'm very interested in this.
