### ISSUE TITLE
execute html formatted text in spanner column label

### ISSUE THREAD

**Issue by shannonpileggi** [rstudio/gt#247]
The `html()` helper function does not work with `label` in  `tab_spanner()`. 

---

``` r
library(tidyverse)
library(gt)

airquality_m <- 
  airquality %>%
  mutate(Year = 1973L) %>%
  slice(1:10) %>%
  select(Month, Day, Year)
  
# Create a display table using the `airquality`
# dataset; arrange columns into groups
gt_tbl <- 
  gt(data = airquality_m) %>%
  tab_header(
    title = "New York Air Quality Measurements",
    subtitle = "Daily measurements in New York City (May 1-10, 1973)"
  ) %>%
  tab_spanner(
    label = html("Time <br> n = 10"),
    columns = vars(Year, Month, Day)
  )

# Show the gt Table
gt_tbl
```

<style>html {
  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Helvetica Neue', 'Fira Sans', 'Droid Sans', Arial, sans-serif;
}

#yljoxpsmnf .gt_table {
  display: table;
  border-collapse: collapse;
  margin-left: auto;
  margin-right: auto;
  color: #000000;
  font-size: 16px;
  background-color: #FFFFFF;
  /* table.background.color */
  width: auto;
  /* table.width */
  border-top-style: solid;
  /* table.border.top.style */
  border-top-width: 2px;
  /* table.border.top.width */
  border-top-color: #A8A8A8;
  /* table.border.top.color */
}

#yljoxpsmnf .gt_heading {
  background-color: #FFFFFF;
  /* heading.background.color */
  border-bottom-color: #FFFFFF;
}

#yljoxpsmnf .gt_title {
  color: #000000;
  font-size: 125%;
  /* heading.title.font.size */
  padding-top: 4px;
  /* heading.top.padding */
  padding-bottom: 1px;
  border-bottom-color: #FFFFFF;
  border-bottom-width: 0;
}

#yljoxpsmnf .gt_subtitle {
  color: #000000;
  font-size: 85%;
  /* heading.subtitle.font.size */
  padding-top: 1px;
  padding-bottom: 4px;
  /* heading.bottom.padding */
  border-top-color: #FFFFFF;
  border-top-width: 0;
}

#yljoxpsmnf .gt_bottom_border {
  border-bottom-style: solid;
  /* heading.border.bottom.style */
  border-bottom-width: 2px;
  /* heading.border.bottom.width */
  border-bottom-color: #A8A8A8;
  /* heading.border.bottom.color */
}

#yljoxpsmnf .gt_column_spanner {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #A8A8A8;
  padding-top: 4px;
  padding-bottom: 4px;
}

#yljoxpsmnf .gt_col_heading {
  color: #000000;
  background-color: #FFFFFF;
  /* column_labels.background.color */
  font-size: 16px;
  /* column_labels.font.size */
  font-weight: initial;
  /* column_labels.font.weight */
  vertical-align: middle;
  padding: 10px;
  margin: 10px;
}

#yljoxpsmnf .gt_sep_right {
  border-right: 5px solid #FFFFFF;
}

#yljoxpsmnf .gt_group_heading {
  padding: 8px;
  color: #000000;
  background-color: #FFFFFF;
  /* row_group.background.color */
  font-size: 16px;
  /* row_group.font.size */
  font-weight: initial;
  /* row_group.font.weight */
  border-top-style: solid;
  /* row_group.border.top.style */
  border-top-width: 2px;
  /* row_group.border.top.width */
  border-top-color: #A8A8A8;
  /* row_group.border.top.color */
  border-bottom-style: solid;
  /* row_group.border.bottom.style */
  border-bottom-width: 2px;
  /* row_group.border.bottom.width */
  border-bottom-color: #A8A8A8;
  /* row_group.border.bottom.color */
  vertical-align: middle;
}

#yljoxpsmnf .gt_empty_group_heading {
  padding: 0.5px;
  color: #000000;
  background-color: #FFFFFF;
  /* row_group.background.color */
  font-size: 16px;
  /* row_group.font.size */
  font-weight: initial;
  /* row_group.font.weight */
  border-top-style: solid;
  /* row_group.border.top.style */
  border-top-width: 2px;
  /* row_group.border.top.width */
  border-top-color: #A8A8A8;
  /* row_group.border.top.color */
  border-bottom-style: solid;
  /* row_group.border.bottom.style */
  border-bottom-width: 2px;
  /* row_group.border.bottom.width */
  border-bottom-color: #A8A8A8;
  /* row_group.border.bottom.color */
  vertical-align: middle;
}

#yljoxpsmnf .gt_striped {
  background-color: #f2f2f2;
}

#yljoxpsmnf .gt_from_md > :first-child {
  margin-top: 0;
}

#yljoxpsmnf .gt_from_md > :last-child {
  margin-bottom: 0;
}

#yljoxpsmnf .gt_row {
  padding: 10px;
  /* row.padding */
  margin: 10px;
  vertical-align: middle;
}

#yljoxpsmnf .gt_stub {
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #A8A8A8;
  padding-left: 12px;
}

#yljoxpsmnf .gt_stub.gt_row {
  background-color: #FFFFFF;
}

#yljoxpsmnf .gt_summary_row {
  background-color: #FFFFFF;
  /* summary_row.background.color */
  padding: 6px;
  /* summary_row.padding */
  text-transform: inherit;
  /* summary_row.text_transform */
}

#yljoxpsmnf .gt_first_summary_row {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #A8A8A8;
}

#yljoxpsmnf .gt_table_body {
  border-top-style: solid;
  /* table_body.border.top.style */
  border-top-width: 2px;
  /* table_body.border.top.width */
  border-top-color: #A8A8A8;
  /* table_body.border.top.color */
  border-bottom-style: solid;
  /* table_body.border.bottom.style */
  border-bottom-width: 2px;
  /* table_body.border.bottom.width */
  border-bottom-color: #A8A8A8;
  /* table_body.border.bottom.color */
}

#yljoxpsmnf .gt_footnote {
  font-size: 90%;
  /* footnote.font.size */
  padding: 4px;
  /* footnote.padding */
}

#yljoxpsmnf .gt_sourcenote {
  font-size: 90%;
  /* sourcenote.font.size */
  padding: 4px;
  /* sourcenote.padding */
}

#yljoxpsmnf .gt_center {
  text-align: center;
}

#yljoxpsmnf .gt_left {
  text-align: left;
}

#yljoxpsmnf .gt_right {
  text-align: right;
  font-variant-numeric: tabular-nums;
}

#yljoxpsmnf .gt_font_normal {
  font-weight: normal;
}

#yljoxpsmnf .gt_font_bold {
  font-weight: bold;
}

#yljoxpsmnf .gt_font_italic {
  font-style: italic;
}

#yljoxpsmnf .gt_super {
  font-size: 65%;
}

#yljoxpsmnf .gt_footnote_glyph {
  font-style: italic;
  font-size: 65%;
}
</style>

<div id="yljoxpsmnf" style="overflow-x:auto;">

<table class="gt_table">

<thead>

<tr>

<th colspan="3" class="gt_heading gt_title gt_font_normal gt_center">

New York Air Quality Measurements

</th>

</tr>

<tr>

<th colspan="3" class="gt_heading gt_subtitle gt_font_normal gt_center gt_bottom_border">

Daily measurements in New York City (May 1-10, 1973)

</th>

</tr>

</thead>

<tr>

<th class="gt_col_heading gt_column_spanner gt_center" rowspan="1" colspan="3">

Time \<br\> n = 10

</th>

</tr>

<tr>

<th class="gt_col_heading gt_right" rowspan="1" colspan="1">

Month

</th>

<th class="gt_col_heading gt_right" rowspan="1" colspan="1">

Day

</th>

<th class="gt_col_heading gt_NA" rowspan="1" colspan="1">

Year

</th>

</tr>

<tbody class="gt_table_body">

<tr>

<td class="gt_row gt_right">

5

</td>

<td class="gt_row gt_right">

1

</td>

<td class="gt_row gt_right">

1973

</td>

</tr>

<tr>

<td class="gt_row gt_right gt_striped">

5

</td>

<td class="gt_row gt_right gt_striped">

2

</td>

<td class="gt_row gt_right gt_striped">

1973

</td>

</tr>

<tr>

<td class="gt_row gt_right">

5

</td>

<td class="gt_row gt_right">

3

</td>

<td class="gt_row gt_right">

1973

</td>

</tr>

<tr>

<td class="gt_row gt_right gt_striped">

5

</td>

<td class="gt_row gt_right gt_striped">

4

</td>

<td class="gt_row gt_right gt_striped">

1973

</td>

</tr>

<tr>

<td class="gt_row gt_right">

5

</td>

<td class="gt_row gt_right">

5

</td>

<td class="gt_row gt_right">

1973

</td>

</tr>

<tr>

<td class="gt_row gt_right gt_striped">

5

</td>

<td class="gt_row gt_right gt_striped">

6

</td>

<td class="gt_row gt_right gt_striped">

1973

</td>

</tr>

<tr>

<td class="gt_row gt_right">

5

</td>

<td class="gt_row gt_right">

7

</td>

<td class="gt_row gt_right">

1973

</td>

</tr>

<tr>

<td class="gt_row gt_right gt_striped">

5

</td>

<td class="gt_row gt_right gt_striped">

8

</td>

<td class="gt_row gt_right gt_striped">

1973

</td>

</tr>

<tr>

<td class="gt_row gt_right">

5

</td>

<td class="gt_row gt_right">

9

</td>

<td class="gt_row gt_right">

1973

</td>

</tr>

<tr>

<td class="gt_row gt_right gt_striped">

5

</td>

<td class="gt_row gt_right gt_striped">

10

</td>

<td class="gt_row gt_right gt_striped">

1973

</td>

</tr>

</tbody>

</table>

</div>

<sup>Created on 2019-04-05 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by rich-iannone** [comment]
Thanks for reporting this! The `md()` helper function doesn’t work either for this location.
