### ISSUE TITLE
group column with `<=` sign dispaly wrong?

### ISSUE THREAD

**Issue by shizidushu** [rstudio/gt#249]
It display "30<x<=60" as "30" (see the image below). How to make it work?

``` r
library(gt)
data.frame(age = c("0<=x<=30", "30<x<=60"), value = seq(1,10)) %>%
  gt(groupname_col = "age")
```
![result](https://user-images.githubusercontent.com/13694980/55703430-2a761580-5a0c-11e9-9fd1-dd67c00d69f6.png)

Edit:

Replace `<` with `&lt`, then it works.

But I think we need a better solution. The dataset column should be treat as it is, not as html. Something like `escape` argument in `DT::datatable` might be useful.

```r
library(gt)
data.frame(age = c("0<=x<=30", "30<x<=60"), value = seq(1,10)) %>%
  mutate(age = stringr::str_replace(age, "<", "&lt")) %>%
  gt(groupname_col = "age")
```

**Comment by rich-iannone** [comment]
Thanks for reporting this! This is definitely a bug: the row group labels need escaping.
