### ISSUE TITLE
Can't use alpha argument in data_color()?

### ISSUE THREAD

**Issue by mfherman** [rstudio/gt#250]
I'm having trouble adjusting the alpha of background cell colors when using `data_color()` in conjunction with `scales::col_numeric()`. The documentation of `data_color()` says:

>  If using a colorizing helper function for colors then this option is ignored (each of the colorizing helper functions has its own alpha argument).

But when I try to add an alpha argument to either `data_color()` or `col_numeric()` I don't see any transparency change. Reprex below with example table from `data_color()` documentation. (Apologies for not including the output tables with the code, but I guess GH doesn't like the html formatting...)

``` r
library(gt)
library(tidyverse)

# no alpha
countrypops %>%
  filter(country_name == "Mongolia") %>%
  select(-contains("code")) %>%
  tail(10) %>%
  gt() %>%
  data_color(
    columns = vars(population),
    colors = scales::col_numeric(
      palette = c(
        "red", "orange", "green", "blue"),
      domain = c(0.2E7, 0.4E7))
  )

# set alpha in col_numeric()
countrypops %>%
  filter(country_name == "Mongolia") %>%
  select(-contains("code")) %>%
  tail(10) %>%
  gt() %>%
  data_color(
    columns = vars(population),
    colors = scales::col_numeric(
      palette = c(
        "red", "orange", "green", "blue"),
      domain = c(0.2E7, 0.4E7),
      alpha = 0.1)
  )

# set alpha in data_color()
countrypops %>%
  filter(country_name == "Mongolia") %>%
  select(-contains("code")) %>%
  tail(10) %>%
  gt() %>%
  data_color(
    columns = vars(population),
    colors = scales::col_numeric(
      palette = c(
        "red", "orange", "green", "blue"),
      domain = c(0.2E7, 0.4E7)),
    alpha = 0.1
  )
```

**Comment by MadhulikaTanuboddi** [comment]
This does not work well on Edge and IE11 browsers. The population column where the color is applied does not get the color. Check the attached snapshot.
<img width="1704" alt="Issue_Edge_gt_app_alpha_color" src="https://user-images.githubusercontent.com/5369655/66544601-76099900-eaed-11e9-8d6e-3d2742f11130.png">
