### ISSUE TITLE
Use of minus sign in vars() causes error

### ISSUE THREAD

**Issue by dtburk** [rstudio/gt#261]
I believe this error will crop up any time you use the minus sign in a call to `vars()`, but here is one specific example:

``` r
library(dplyr)
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union
library(gt)

tbl <- tribble(
  ~Role, ~Atlanta, ~Houston, ~`Santa Ana`, ~Raleigh,
  "Bike Advocate", 4L, 7L, 5L, 3L,
  "Bureaucrat", 1L, 4L, 3L, 2L,
  "Elected Official or Aide", 3L, 0L, 1L, 1L, 
  "Housing Advocate", 1L, 1L, 0L, 2L
)

tbl_gt <- tbl %>% 
  gt()

# Causes error
tbl_gt %>% 
  tab_footnote("City", cells_column_labels(columns = vars(-Role)))
#> Error in vapply(resolved, quo_get_expr_char, character(1)): values must be length 1,
#>  but FUN(X[[1]]) result is length 2

# Works
tbl_gt %>% 
  tab_footnote(
    "City", 
    cells_column_labels(columns = vars(Atlanta, Houston, `Santa Ana`, Raleigh)))
```

<table class="gt_table">

<tr>

<th class="gt_col_heading gt_left" rowspan="1" colspan="1">

Role

</th>

<th class="gt_col_heading gt_right" rowspan="1" colspan="1">

Atlanta<sup class='gt_footnote_glyph'>1</sup>

</th>

<th class="gt_col_heading gt_right" rowspan="1" colspan="1">

Houston<sup class='gt_footnote_glyph'>1</sup>

</th>

<th class="gt_col_heading gt_right" rowspan="1" colspan="1">

Santa Ana<sup class='gt_footnote_glyph'>1</sup>

</th>

<th class="gt_col_heading gt_right" rowspan="1" colspan="1">

Raleigh<sup class='gt_footnote_glyph'>1</sup>

</th>

</tr>

<tbody class="gt_table_body">

<tr>

<td class="gt_row gt_left">

Bike Advocate

</td>

<td class="gt_row gt_right">

4

</td>

<td class="gt_row gt_right">

7

</td>

<td class="gt_row gt_right">

5

</td>

<td class="gt_row gt_right">

3

</td>

</tr>

<tr>

<td class="gt_row gt_left gt_striped">

Bureaucrat

</td>

<td class="gt_row gt_right gt_striped">

1

</td>

<td class="gt_row gt_right gt_striped">

4

</td>

<td class="gt_row gt_right gt_striped">

3

</td>

<td class="gt_row gt_right gt_striped">

2

</td>

</tr>

<tr>

<td class="gt_row gt_left">

Elected Official or Aide

</td>

<td class="gt_row gt_right">

3

</td>

<td class="gt_row gt_right">

0

</td>

<td class="gt_row gt_right">

1

</td>

<td class="gt_row gt_right">

1

</td>

</tr>

<tr>

<td class="gt_row gt_left gt_striped">

Housing Advocate

</td>

<td class="gt_row gt_right gt_striped">

1

</td>

<td class="gt_row gt_right gt_striped">

1

</td>

<td class="gt_row gt_right gt_striped">

0

</td>

<td class="gt_row gt_right gt_striped">

2

</td>

</tr>

</tbody>

<tfoot>

<tr>

<td colspan="5" class="gt_footnote">

<sup class='gt_footnote_glyph'><em>1</em></sup> City

</td>

</tr>

</tfoot>

</table>

<sup>Created on 2019-04-18 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by rich-iannone** [comment]
Thanks for opening this issue and for the easy to follow code examples! We'll look into this soon.

**Comment by rich-iannone** [comment]
This now works in the dev version of {gt} thanks to a far better {tidyselect} implementation. Now (since `vars()` is gone) we can use:

```r
library(gt)

tbl <- tribble(
  ~Role, ~Atlanta, ~Houston, ~`Santa Ana`, ~Raleigh,
  "Bike Advocate", 4L, 7L, 5L, 3L,
  "Bureaucrat", 1L, 4L, 3L, 2L,
  "Elected Official or Aide", 3L, 0L, 1L, 1L, 
  "Housing Advocate", 1L, 1L, 0L, 2L
)

tbl_gt <- 
  tbl %>% 
  gt() %>% 
  tab_footnote(
    footnote = "City",
    cells_column_labels(columns = -Role)
  )
```

and expect to see:

<img width="617" alt="table" src="https://user-images.githubusercontent.com/5612024/116295510-2b02b580-a767-11eb-9b66-8bcf1dc59bc7.png">

This was fixed in https://github.com/rstudio/gt/pull/718 but unfortunately this issue wasn't linked until now. Will close this issue now; expect to this functionality in the next CRAN release.
