### ISSUE TITLE
webshot should not save in working directory

### ISSUE THREAD

**Issue by vincentarelbundock** [rstudio/gt#277]
The new webshot feature is super neat. Thanks!

This section poses problems:

https://github.com/rstudio/gt/blob/master/R/gtsave.R#L125

```r
library(gt)
library(tidyverse)
data.frame(x = 1:2, y = 2:3) %>%
    gt() %>%
    gtsave('~/Downloads/test.png')
```

This code will create a new folder inside the working directory called `~` with subfolder `Downloads`. The "normal" behavior would be to expand `~` to `$HOME`.

**Comment by rich-iannone** [comment]
Thanks for pointing this out! Will fix this shortly.
