### ISSUE TITLE
cols_split_delim works only with ordered columns?

### ISSUE THREAD

**Issue by EDiLD** [rstudio/gt#296]
`cols_split_delim()` seems to work only if the colums are sorted on toplevel. Is this intended behaviour or a bug?

```r
library(gt)
library(dplyr)
iris %>%
  filter(Species == 'setosa') %>%
  select(-Species) %>%
  dplyr::slice(1:2) %>%
  gt() %>%
  cols_split_delim(delim = ".")
```

![image](https://user-images.githubusercontent.com/849616/58097244-37735080-7bd7-11e9-9f55-421234fdcf61.png)

```r
iris %>%
  filter(Species == 'setosa') %>%
  select(-Species) %>%
  dplyr::slice(1:2) %>%
  select(1, 3, 2, 4) %>%
  gt() %>%
  cols_split_delim(delim = ".")
```

![image](https://user-images.githubusercontent.com/849616/58097293-5540b580-7bd7-11e9-944b-74b1401d0ccf.png)

Fix is easy, just sort by the string before the split:

```r
iris %>%
  filter(Species == 'setosa') %>%
  select(-Species) %>%
  dplyr::slice(1:2) %>%
  select(1, 3, 2, 4) %>%
  select(order(gsub('^(.*)\\..*$', '\\1', names(.)))) %>%
  gt() %>%
  cols_split_delim(delim = ".")
```

**Comment by rich-iannone** [comment]
Thanks for reporting this. Looks like a clear bug to me, and the implementation needs to be changed. I believe that `cols_split_delim()` needs to internally call `tab_spanner()` and incorporate the latter function's `gather` argument (defaulting to `TRUE`).

What will happen is, in the default case, the columns will be gathered into the appropriate spanners (using the current sorting).

When `gather = FALSE` we accept that common spanner column labels may repeat (but there shouldn't be rendering errors as in the last example you provided).

**Comment by rich-iannone** [comment]
With the revised `tab_spanner_delim()`, this is no longer a problem. In the dev version of {gt}, I can now use:

```r
iris %>%
  filter(Species == 'setosa') %>%
  select(-Species) %>%
  dplyr::slice(1:2) %>%
  gt() %>%
  tab_spanner_delim(delim = ".")
```

or

```r
iris %>%
  filter(Species == 'setosa') %>%
  select(-Species) %>%
  dplyr::slice(1:2) %>%
  select(1, 3, 2, 4) %>%
  gt() %>%
  tab_spanner_delim(delim = ".")
```

and in both cases get this table:

<img width="326" alt="table" src="https://user-images.githubusercontent.com/5612024/116294186-aebba280-a765-11eb-8b46-38033cd24d05.png">

This was fixed in https://github.com/rstudio/gt/pull/665 but this issue was mistakenly not linked to the PR at the time of closing.
