### ISSUE TITLE
remove mention of CRAN in README until its on cran?

### ISSUE THREAD

**Issue by gmbecker** [rstudio/gt#301]
The README file (and thus the splashpage for the github repo, clearly  state that gt is on 
 CRAN and should be installed from there, but gt is not (yet?) published on CRAN. It seems that that language shouldn't be in the README until it is accurate, and should be  replaced with a discussion of the fact that this is still a maturing package that hasn't yet been fully published.

**Comment by rich-iannone** [comment]
I think we just have a bad (i.e., misleading) sentence here. The section:

```
 First and foremost, the gt package is used in an R environment, so, if you don’t have an R installation, it can be obtained from the Comprehensive R Archive Network (CRAN). For the best experience in working with R, use the RStudio Desktop IDE.
```

just talks about getting R first (for those people that stumble onto the page and have no experience at all with R), and, the installation of the package (from GitHub) is in the next paragraph.

I do like the idea of having some discussion as to why it's not on CRAN.

**Comment by gmbecker** [comment]
Hmm I guess clearly states was my bad. It did seem to say that to me when I read it, but reading very carefully I can see you're talking about R itself (though that does strike me  as a slightly odd thing to do in R package docs, which is probably why I didn't read it that way initially).

Anyway :+1:

**Comment by rich-iannone** [comment]
Yeah, I admit it's a little oddball. I'm leaving this issue here as a TODO to fix this part of the README. Thanks, Gabe!

**Comment by william3031** [comment]
Something like this? https://github.com/rstudio/gt/pull/376

**Comment by rich-iannone** [comment]
Recently fixed.
