### ISSUE TITLE
Generating the rtf document with common header and footnote all over the document

### ISSUE THREAD

**Issue by vinsans** [rstudio/gt#305]
Generating the rtf document with common header and footnote all over the document. Is there any simple and easy way for it.. Please help me out with this.
 
![image](https://user-images.githubusercontent.com/27669077/59423930-bcc1dd80-8df0-11e9-9a7d-da8f0a2eb1ce.png)

in the sample screenshot i _marked in red box_.. i have to customize the header and footer like that ( multiple column in header and footer) ,and it should be maintained over all over the document each page.I did not see any example or sample code to generate like this.. Is it possible with gt().If means provide the sample .

**Comment by rich-iannone** [comment]
Page header and footer text can now be specified for RTF documents.
