### ISSUE TITLE
`groups` arg. in `cells_group()` doesn't work with multiple values

### ISSUE THREAD

**Issue by strboul** [rstudio/gt#308]
`groups` argument in the `cells_group()` function doesn't work when a character vector with a length of greater than one is supplied.

In the example below, the group names are not displayed as bold. I think this is because I've specified multiple group names as `c("grp_a", "grp_b")`. 

Is this behavior a design choice? It's a bit confusing for me because the argument name implies some plurality as it's called `groups`, not `group`.  But even so this is a tedious process to write down all group names one by one.

This doesn't work:
```{r}
exibble %>%
  gt(rowname_col = "row", groupname_col = "group") %>%
  tab_style(
    locations = cells_group(groups = c("grp_a", "grp_b")),
    style = cells_styles(text_weight = "bold")
  )
```

This works:
```{r}
exibble %>%
  gt(rowname_col = "row", groupname_col = "group") %>%
  tab_style(
    locations = cells_group(groups = "grp_a"),
    style = cells_styles(text_weight = "bold")
  ) %>% 
  tab_style(
    locations = cells_group(groups = "grp_b"),
    style = cells_styles(text_weight = "bold")
  )
```

I'm happy to help if you give some details about where to begin.

**Comment by rich-iannone** [comment]
This is not a design choice but an unfortunate bug. We will get to fixing this. Thanks for reporting this and providing these great examples!

**Comment by rich-iannone** [comment]
This can be fixed for `set_style.cells_group()` and for `set_footnote.cells_group()` by using a resolver:

```r
  row_groups <- attr(data, "arrange_groups")$groups

  # Resolve row groups
  resolved_row_groups_idx <-
    resolve_data_vals_idx(
      var_expr = !!loc$groups,
      data = NULL,
      vals = row_groups
    )

  groups <- row_groups[resolved_row_groups_idx]
```

**Comment by strboul** [comment]
Is this just a workaround? Looks okay to me but doesn't look very aligned with the rest of the API.

**Comment by rich-iannone** [comment]
It has to be added into the codebase. I’ll have a fix available soon that incorporates the above changes.
