### ISSUE TITLE
Feature request: fmt_bytes()

### ISSUE THREAD

**Issue by wlandau** [rstudio/gt#310]
For performance studies like [this one](https://github.com/richfitz/storr/pull/111#issuecomment-504042967), it would be super helpful to pretty print sizes in bytes, with automatic conversion to KB, MB, GB, etc. as needed. Is this within scope?

**Comment by rich-iannone** [comment]
This is definitely within scope (and internally talked about before). Thanks for posting this as an issue, we hope to get to it soon!

**Comment by rich-iannone** [comment]
Use the following, taken from `pryr:::print.bytes()`:

```r
function (x, digits = 3, ...) 
{
    power <- min(floor(log(abs(x), 1000)), 4)
    if (power < 1) {
        unit <- "B"
    }
    else {
        unit <- c("kB", "MB", "GB", "TB")[[power]]
        x <- x/(1000^power)
    }
    formatted <- format(signif(x, digits = digits), big.mark = ",", 
        scientific = FALSE)
    cat(formatted, " ", unit, "\n", sep = "")
}
```
