### ISSUE TITLE
cols_label overrides tab_styles settings

### ISSUE THREAD

**Issue by cfry-propeller** [rstudio/gt#312]
If you use the cols_label function the formatting of the column header cells seems to be overridden by that function such that you can no longer control the formatting with tab_style.

For example, this
```
gt::gtcars %>%
  dplyr::select(mfr, model, year, hp) %>%
  dplyr::top_n(n = 10) %>%
  gt::gt() %>%
  gt::tab_style(
    style = gt::cells_styles(text_size = '30px'),
    locations = gt::cells_column_labels(columns = TRUE)
  )
```
yields this
![Rplot1](https://user-images.githubusercontent.com/46826199/60226012-38367c80-983e-11e9-9b4b-70311cc0102c.png)
Whereas this
```
gt::gtcars %>%
  dplyr::select(mfr, model, year, hp) %>%
  dplyr::top_n(n = 10) %>%
  gt::gt() %>%
  gt::cols_label(hp = 'Horsepower') %>%
  gt::tab_style(
    style = gt::cells_styles(text_size = '30px'),
    locations = gt::cells_column_labels(columns = TRUE)
  )
```
yields this
![Rplot2](https://user-images.githubusercontent.com/46826199/60226068-7469dd00-983e-11e9-9105-0d36c0b86d4f.png)
Ordering of the functions and other ways of trying to select the column header for styling don't seem to make a difference, so this
```
gt::gtcars %>%
  dplyr::select(mfr, model, year, hp) %>%
  dplyr::top_n(n = 10) %>%
  gt::gt() %>%
  gt::tab_style(
    style = gt::cells_styles(text_size = '30px'),
    locations = gt::cells_column_labels(columns = gt::vars(hp))
  )
```
yields this
![Rplot3](https://user-images.githubusercontent.com/46826199/60226159-d4608380-983e-11e9-8a30-72d9bd6be8e0.png)
But this
```
gt::gtcars %>%
  dplyr::select(mfr, model, year, hp) %>%
  dplyr::top_n(n = 10) %>%
  gt::gt() %>%
  gt::tab_style(
    style = gt::cells_styles(text_size = '30px'),
    locations = gt::cells_column_labels(columns = gt::vars(hp))
  ) %>%
  gt::cols_label(hp = 'Horsepower')
```
yields this
![Rplot4](https://user-images.githubusercontent.com/46826199/60226180-eb06da80-983e-11e9-8a12-dd706937d459.png)
I know you can include markup in the cols_label function, so I'm possibly just using these functions incorrectly... but I ended up just working around this by relabeling my columns with dplyr before funneling them to gt() so that I wouldn't have to do manual formatting of the column headers in markdown or html.

**Comment by rich-iannone** [comment]
Thanks for reporting this. It's a clear bug with `cols_label()` and I've also verified it in recent testing.

**Comment by rich-iannone** [comment]
Should be fixed in `master` now. Please let me know if this is still an issue.

**Comment by daranzolin** [comment]
I think the bug reappears if the column is within a tab_spanner:
```
library(gt)
library(dplyr)
iris %>%
  gt() %>% 
  cols_label(
    Sepal.Length = "sepal_length"
  ) %>% 
  tab_spanner(
    label = "Petal Stuff",
    columns = matches("^Petal")
  ) %>% 
  tab_spanner(
    label = "Sepal Stuff",
    columns = matches("^Sepal")
  ) %>% 
  tab_style(
    style = cell_text(color = "#C99700"), 
    locations = cells_column_labels(columns = everything())
  ) %>% 
  tab_style(
    style = cell_text(color = "#C99700"), 
    locations = cells_column_labels(groups = c("Sepal Stuff", "Petal Stuff"))
  )
```
![gt_cols_label_bug](https://user-images.githubusercontent.com/9537384/67973011-fc853800-fbcc-11e9-8642-08201b43e045.PNG)
