### ISSUE TITLE
Make sure all `cells_*` methods / types are consistent

### ISSUE THREAD

**Issue by schloerke** [rstudio/gt#319]
I **really** like the chart you have on the front.

To be consistent with that....

* `cells_body` vs `cells_data`
  * Referred to as the table body, but also is derived from the data. I'm ok with either
* `cells_group` vs `cells_rowgroup`
  * Chart says `rowgroup`, but less typing is also good.
* `cells_stubhead_label` vs `cells_stubhead`
  * I know there is `cells_column_label`, but that is a location not a value.  (It is not `cells_column_label_label`.)  So my argument is it should be `cells_stubhead`.

First three that I saw.  Just wanting to be consistent or agree to different on purpose.

**Comment by rich-iannone** [comment]
Thanks for giving this some consideration! I'd like to make changes in all three cases, so:

`cells_data` -> `cells_body` (this just feels more correct in terms of a location on the table and perhaps is less ambiguous than data).

`cells_group` -> `cells_rowgroup` (this makes clear what the group refers to).

`cells_stubhead_label` -> `cells_stubhead` (https://github.com/rstudio/gt/pull/276) (for your reasons plus it's much shorter and the location is not entirely about the label—it could have no label).

**Comment by schloerke** [comment]
Correct!  

There may be more. But those are the ones I ran into

**Comment by rich-iannone** [comment]
One renaming (`cells_stubhead_label()` -> `cells_stubhead()`) was performed in https://github.com/rstudio/gt/pull/276. The remaining two now have separate issues (https://github.com/rstudio/gt/issues/321 and https://github.com/rstudio/gt/issues/322), so, closing this issue.
