### ISSUE TITLE
`cell_borders()` appears to be missing call to `cell_style_structure()`

### ISSUE THREAD

**Issue by dtburk** [rstudio/gt#320]
The lack of a call to to `cell_style_structure()` at the end of `cell_borders()` leaves the return value of `cell_borders()` as a list, without special class values attached. This leads to, for example, the following error (the color shows up for me in RStudio viewer, but not here, sorry):

``` r
library(dplyr)
#> Warning: package 'dplyr' was built under R version 3.5.3
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union
library(gt)

# Causes error
exibble %>% 
  select(1:4) %>% 
  gt() %>% 
  tab_style(
    style = cell_borders(
      "top"
    ),
    locations = cells_data(
      rows = char == "honeydew"
    )
  )
#> Error: All provided styles should be generated by stylizing helper functions. Style with index `1` is invalid.

# Works
exibble %>% 
  select(1:4) %>% 
  gt() %>% 
  tab_style(
    style = cell_fill(
      color = "lightgreen"
    ),
    locations = cells_data(
      rows = char == "honeydew"
    )
  )
```

<div id="cjvuvxhmhm" style="overflow-x:auto;overflow-y:auto;width:auto;height:auto;">

<table class="gt_table">

<tr>

<th class="gt_col_heading gt_columns_bottom_border gt_columns_top_border gt_center" rowspan="1" colspan="1">

num

</th>

<th class="gt_col_heading gt_columns_bottom_border gt_columns_top_border gt_left" rowspan="1" colspan="1">

char

</th>

<th class="gt_col_heading gt_columns_bottom_border gt_columns_top_border gt_center" rowspan="1" colspan="1">

fctr

</th>

<th class="gt_col_heading gt_columns_bottom_border gt_columns_top_border gt_left" rowspan="1" colspan="1">

date

</th>

</tr>

<body class="gt_table_body">

<tr>

<td class="gt_row gt_right">

1.111e-01

</td>

<td class="gt_row gt_left">

apricot

</td>

<td class="gt_row gt_center">

one

</td>

<td class="gt_row gt_left">

2015-01-15

</td>

</tr>

<tr>

<td class="gt_row gt_right gt_striped">

2.222e+00

</td>

<td class="gt_row gt_left gt_striped">

banana

</td>

<td class="gt_row gt_center gt_striped">

two

</td>

<td class="gt_row gt_left gt_striped">

2015-02-15

</td>

</tr>

<tr>

<td class="gt_row gt_right">

3.333e+01

</td>

<td class="gt_row gt_left">

coconut

</td>

<td class="gt_row gt_center">

three

</td>

<td class="gt_row gt_left">

2015-03-15

</td>

</tr>

<tr>

<td class="gt_row gt_right gt_striped">

4.444e+02

</td>

<td class="gt_row gt_left gt_striped">

durian

</td>

<td class="gt_row gt_center gt_striped">

four

</td>

<td class="gt_row gt_left gt_striped">

2015-04-15

</td>

</tr>

<tr>

<td class="gt_row gt_right">

5.550e+03

</td>

<td class="gt_row gt_left">

NA

</td>

<td class="gt_row gt_center">

five

</td>

<td class="gt_row gt_left">

2015-05-15

</td>

</tr>

<tr>

<td class="gt_row gt_right gt_striped">

NA

</td>

<td class="gt_row gt_left gt_striped">

fig

</td>

<td class="gt_row gt_center gt_striped">

six

</td>

<td class="gt_row gt_left gt_striped">

2015-06-15

</td>

</tr>

<tr>

<td class="gt_row gt_right">

7.770e+05

</td>

<td class="gt_row gt_left">

grapefruit

</td>

<td class="gt_row gt_center">

seven

</td>

<td class="gt_row gt_left">

NA

</td>

</tr>

<tr>

<td class="gt_row gt_right gt_striped" style="background-color: lightgreen;">

8.880e+06

</td>

<td class="gt_row gt_left gt_striped" style="background-color: lightgreen;">

honeydew

</td>

<td class="gt_row gt_center gt_striped" style="background-color: lightgreen;">

eight

</td>

<td class="gt_row gt_left gt_striped" style="background-color: lightgreen;">

2015-08-15

</td>

</tr>

</body>

</table>

</div>

<sup>Created on 2019-07-15 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by rich-iannone** [comment]
Thanks for reporting this! We will have a bugfix ready for this soon.
