### ISSUE TITLE
Rename helper function `cells_data()` to `cells_body()`

### ISSUE THREAD

**Issue by rich-iannone** [rstudio/gt#321]
As discussed in https://github.com/rstudio/gt/issues/319, this name change will fit better with the table model especially since the term 'data' is somewhat ambiguous (since we can create new data in terms of summary rows).

**Comment by william3031** [comment]
Is this what you're after or is there more to this? I imagine that it would need to be changed in other places too. Where? https://github.com/rstudio/gt/pull/377

**Comment by rich-iannone** [comment]
@william3031 It would need to change everywhere (tests, vignettes, `_pkgdown.yml`, etc.) and the best way to ensure that the name change is performed everywhere is to use a text editor that can do a search and replace globally. Then `devtools::document()` needs to be executed so that the .Rd files get modified.
