### ISSUE TITLE
Installation instructions do not work because `sass` is not available on CRAN

### ISSUE THREAD

**Issue by vincentarelbundock** [rstudio/gt#325]
The `sass` package is no longer available on CRAN. Since `gt` depends on `sass`, the installation instructions using `remotes::install_github('rstudio/gt')` no longer work.

I opened an issue on the `sass` github.

https://github.com/rstudio/sass/issues/22

In the meantime, it might be useful to change the installation instructions in the README to say:

```r
remotes::install_github('rstudio/sass')
remotes::install_github('rstudio/gt')
```

**Comment by rich-iannone** [comment]
Thanks for posting these issues. We will modify a few things while **sass** gets fixed and resubmitted to CRAN.
