### ISSUE TITLE
Consider including caption addition as in `pander`

### ISSUE THREAD

**Issue by r-cheologist** [rstudio/gt#328]
`gt` greatly facilitates the table generation and formatting in my `rmarkdown`/`bookdown` reports. Adding corresponding captions, however, is not straight forward and I haven't yet figured out how to

1. add a caption that is nicely represented in (`pdf`)`LaTeX` output

2. linked to the table object  and

3. integrated into `bookdowns` cross referencing infrastructure.

`pander`as well as `knitr::kable` offer `caption` arguments for this purpose (which may be wrangled into `bookdown`-compatibility in the first case).

I'd appreciate if `gt` would provide something equivalent - like `gt::tab_caption`.

**Comment by billdenney** [comment]
When adding captions, it would be nice if the captions supported the LaTeX feature of short and long captions.  The short caption is what shows up in the list of tables at the top while the long caption is what is used immediately adjacent to the table itself.

The LaTeX to accomplish this is:

```
sprintf("\caption[%s]{%s}", short, long)
```
