### ISSUE TITLE
The `cells_stub()` location helper isn't working

### ISSUE THREAD

**Issue by rich-iannone** [rstudio/gt#339]
The `cells_stub()` location helper no longer applies styles to the stub location. This code produces a table with a stub (left-most column) that is unstyled:

```r
sza %>%
  dplyr::filter(
    latitude == 20 & tst <= "1000") %>%
  dplyr::select(-latitude) %>%
  dplyr::filter(!is.na(sza)) %>%
  tidyr::spread(key = "tst", value = sza) %>%
  gt(rowname_col = "month") %>%
  fmt_missing(
    columns = TRUE,
    missing_text = ""
  ) %>%
  tab_style(
    style = list(
      cell_fill(color = "darkblue"),
      cell_text(color = "white")
    ),
    locations = cells_stub(rows = TRUE)
  )
```

<img width="739" alt="unstyled_stub" src="https://user-images.githubusercontent.com/5612024/62415273-f21ac880-b5f4-11e9-95ae-ecf8ba365392.png">

**Comment by MadhulikaTanuboddi** [comment]
This does not work well on Edge and IE11 (Windows 10). Left most column (month) data is missing on these browsers. Check the attached snapshot.
<img width="1677" alt="Issue_Edge_gt_app_cells_stub" src="https://user-images.githubusercontent.com/5369655/66544445-01cef580-eaed-11e9-97e4-7386abee271f.png">
