### ISSUE TITLE
Not possible to markdown groups' headings

### ISSUE THREAD

**Issue by Pietro-DAmelio** [rstudio/gt#350]
From your example https://gt.rstudio.com/articles/intro-creating-gt-tables.html
I cannot add markdown to group headings,
for example put "country" in **bold**.

Am I doing something wrong?

```r
gt_tbl <- 
    gt_tbl %>% 
    tab_row_group(
        group = "continent",
        rows = 1:6
    ) %>%
    tab_row_group(
        group = md("**country**"),
        rows = c("Australia", "Greenland")
    ) %>%
    tab_row_group(
        group = "subregion",
        rows = c("New Guinea", "Borneo")
    )
```

**Comment by rich-iannone** [comment]
This is not your fault. Currently, row group labels don't formally have key-label pairs so it doesn't work like the column labels (which do have key-label pairs). There is a valid workaround for this particular case though:

```r
  dplyr::tibble(
    name = names(islands),
    size = islands
  ) %>%
  dplyr::arrange(desc(size)) %>%
  dplyr::slice(1:10) %>%
  gt(rowname_col = "name") %>%
  tab_row_group(
    group = "continent",
    rows = 1:6
  ) %>%
  tab_row_group(
    group = "country",
    rows = c("Australia", "Greenland")
  ) %>%
  tab_row_group(
    group = "subregion",
    rows = c("New Guinea", "Borneo")
  ) %>%
  tab_style(
    style = cell_text(weight = "bold"),
    locations = cells_group(groups = "country")
  )
```

**Comment by rich-iannone** [comment]
Our plan is to continue refactoring work and, with that, the `tab_row_group()` function should work with helper functions like `md()` and `html()`.

**Comment by Pietro-DAmelio** [comment]
Thanks, the work around works just fine for the moment!

**Comment by Pietro-DAmelio** [comment]
Further question/comment, is there a way to center the group level label? There is not such and option in `tab_row_group()` and `tab_spanner()` does not work for it either...

**Comment by Ari04T** [comment]
This is not exactly the original question that was asked, but I feel like it's pretty similar. Right now, even with the workaround, is there any way to add an image to the `tab_row_group`? Text transform doesn't work with this type of row since it only takes the `cells_body()`, `cells_stub()`, and `cells_column_labels()` functions.

**Comment by qdread** [comment]
Is there any resolution to this issue? I would like to add special html characters to the row group labels, such as `15&deg;C` which I do not think the workaround will help with.

**Comment by qdread** [comment]
I learned elsewhere that including `process_md = TRUE` as an argument to `gt()` now solves this problem at least for me.
