### ISSUE TITLE
gtsave() does not export colors for R versions 3.5.3 or superior

### ISSUE THREAD

**Issue by Pietro-DAmelio** [rstudio/gt#351]
When exporting, cell colors are visible only in html but not in any other format.
I tried in 4 different laptop and only the one with R version 3.5.1 the colors are visible.
Colors are correctly represented in the viewer window of RStudio but not exported.

A work-around I found is to open the html in Chrome, save as pdf ticking the background colors in the advanced option. 

Session info

```
R version 3.5.3 (2019-03-11)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 17134)

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252   
[3] LC_MONETARY=English_United States.1252 LC_NUMERIC=C                          
[5] LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] gt_0.1.0        reshape2_1.4.3  dplyr_0.8.3     tidybayes_1.1.0 Cairo_1.5-10   
 [6] ggplot2_3.2.1   sjPlot_2.7.0    loo_2.1.0       brms_2.9.0      Rcpp_1.0.2  
```
```r
<insert reprex here>
```

**Comment by rich-iannone** [comment]
Cell colors are currently only implemented in HTML tables (not LaTeX or RTF currently), if that's what you mean. Although I suspect this is an issue entirely with the HTML format. Would you be able to share some labeled screenshots here?

**Comment by Pietro-DAmelio** [comment]
Thank you for your interest. The html works fine. .png and .pdf do not show the colors. To save the html as pdf from chrome I had to enable background color, maybe when webshot captures the image from the html the background is not activated?

**Comment by Pietro-DAmelio** [comment]
![table_tot_fit_nat18](https://user-images.githubusercontent.com/42181672/63031617-8d912080-beb4-11e9-80df-5b5bcad8a4ce.png)

**Comment by rich-iannone** [comment]
Thanks for the quick response. One more thing though, could you provide the code that generated the table? I'd like to test this on my system as well.

**Comment by rich-iannone** [comment]
Or, if the data are sensitive and you can't post that here, could you come up with a similar example table that exhibits the same problem?

**Comment by Pietro-DAmelio** [comment]
data are not yet published :) but I could post them here I think.
But maybe not necessary....
In my 3 machines with R 3.5.3 anything saved with the following format will not have background color.

 `gtsave(gt_tbl,"xx.png")`

**Comment by Pietro-DAmelio** [comment]
webshot is version 0.5.1
tell me if I can add versions of other useful packages

**Comment by rich-iannone** [comment]
Actually that might be enough to go on, thanks. I'll investigate and see where the problem is.

**Comment by xavidp** [comment]
Hi, same issue reproduced in my case (GNU/Linux, 64 bits, R 3.6.x). I add a simple reproducible example so that anyone can have a better look at any debugging attempt, for instance, etc., in case it helps:

```
library(tidyverse)
library(gt)

df <- data.frame(x=rnorm(10), y=rep(0.259,10)) %>% 
  gt() %>%
  data_color(
    columns = vars(x,
                   y),
    colors = scales::col_numeric(
      # palette = "Greens",
      palette = "RdBu",
      domain = range(0,1)
    )
  )

df %>%
    gtsave(
      "df_saved_with_gtsave.png"
    )
```

Image displayed in viewer pane (or within a Rmd chunk, same effect: colors are displayed as expected):
![df_saved_from_rstudio_viewer_pane_by_hand](https://user-images.githubusercontent.com/366309/68857651-8d870380-06e3-11ea-9113-63eb83e54a6e.png)


Image saved to disk with gtsave():
![df_saved_with_gtsave](https://user-images.githubusercontent.com/366309/68857660-924bb780-06e3-11ea-8827-0af9b1c40a90.png)


I tried calling the webshot package (aside of gt), while adding a delay through the webshot package param (upto 10 seconds, just in case) and no difference: no colors included in the webshot. :-( 

Same when attempting to print to pdf the html generated by Rmd knitting, through the firefox or chromium brosers: no colors in those gt tables (whoch display colors as expected in the browser).

**Comment by xavidp** [comment]
Addendum: I confirm that this workaround 

> A work-around I found is to open the html in Chrome, save as pdf ticking the background colors in the advanced option.

only works in simple cases. For instance, in the reprex I just added in the previous comment, it works. However, in the real world scenario (html knitted from longer Rmd document, in which a chunk is producing that colored-gt-table, doesn't work, and html table is kept inside the pdf with no bg colors.

**Comment by jcheng5** [comment]
After investigating with @rich-iannone we think this might be because of #RRGGBBAA color notation being used. We'll try using #RRGGBB when possible and rgba() when required.

**Comment by jfgomezok** [comment]
Hello! Have he same issue!

I might add something:

I can export with colors the 'background', for instance:
`tab_options(
      heading.background.color = "#592D64",
      column_labels.background.color = "#592D64"
      # column_labels.font.weight = 'bold'
    )`

But that is not the case with:
`tab_style(
      style = list(
        cell_fill(color = "#592D64")
      )`


Same color code: one being exported, not the other one.

**Comment by DominiqueMakowski** [comment]
As far as I know, this issue still persists
