### ISSUE TITLE
summary_rows does not work if the number of columns is greater than 18

### ISSUE THREAD

**Issue by MackenzieKolev** [rstudio/gt#353]
While trying to summarize a wide table with gt() and summary_rows(). I kept getting the following error:

**Error: The length of the `x_side` vector must be 1 or the length of `x`.**

After troubleshooting for a while I found that if I make the number of columns <= 18  the summary function would work properly. If the number of columns > 18. the summary_rows() function results in the error above.

**Comment by rich-iannone** [comment]
Thanks for posting this issue. I'm seeing the problem as well.

**Comment by rappster** [comment]
I also get this error when:

- trying to set `rows = gt::matches(<string>) in `gt::fmt_number()`
- trying to set `rows = TRUE` for wide tables with columns that have missing values only. Also tried running `gt::fmt_missing(columns, missing_text = 0)` first to get rid of NAs, but same error

**Comment by rich-iannone** [comment]
@rappster Your errors are the same but the codepath is seemingly different (i.e., doesn't occur through use of `summary_rows()`). I can reproduce your errors though, so, I'm going to move your comments to a new issue.
