### ISSUE TITLE
sass is now back on CRAN; recommend changing DESCRIPTION

### ISSUE THREAD

**Issue by davidkane9** [rstudio/gt#365]
The current DESCRIPTION includes:

Remotes:
    rstudio/sass

I recommend removing it. sass is now back on CRAN, so it is no longer necessary to get it from GitHub. Also, I (at least) get a failure trying to install the current gt if I start that process with no sass installed.

**Comment by rich-iannone** [comment]
Agree about this one. Will change this soon. Thanks!

**Comment by davidkane9** [comment]
I will give this a try right now.

**Comment by davidkane9** [comment]
I submitted a pull request. Apologies if I messed this up! If I did, please just fix it yourself. Thanks for providing this novice with the opportunity!

**Comment by rich-iannone** [comment]
Thanks for the PR @davidkane9 ! Now merged in, so, closing this issue.
