### ISSUE TITLE
cols_merge silently fails when rows contain "NA"  as chars

### ISSUE THREAD

**Issue by JakeHurlbut** [rstudio/gt#367]
There is a bug in `cols_merge` which causes it to ignore the row contents of col_2 when either the rows of col_1 or col_2 contain, specifically, an uppercase NA anywhere in the character string. It only happens in the table rows that meet this criteria, and doesn't apply to the entire table. In the example below merging a row where one col contains "banana" works fine, while "BANANA" triggers this bug.

``` r
library(tidyverse)
library(gt)

test_data = gtcars %>% 
  filter(mfr %in% c('Audi', 'Porsche')) %>% 
  mutate(test = if_else(mfr == 'Audi', 'banana', 'BANANA')) %>% 
  select(mfr, model, test)

test_data
#> # A tibble: 9 x 3
#>   mfr     model       test  
#>   <chr>   <chr>       <chr> 
#> 1 Audi    R8          banana
#> 2 Audi    RS 7        banana
#> 3 Audi    S6          banana
#> 4 Audi    S7          banana
#> 5 Audi    S8          banana
#> 6 Porsche 718 Boxster BANANA
#> 7 Porsche 718 Cayman  BANANA
#> 8 Porsche 911         BANANA
#> 9 Porsche Panamera    BANANA

test_data %>% 
  gt() %>% 
  cols_merge(
    col_1 = vars(model),
    col_2 = vars(test)
  ) 
```

<div id="ypilezhvtp" style="overflow-x:auto;overflow-y:auto;width:auto;height:auto;">

<table class="gt_table">

<tr>

<th class="gt_col_heading gt_columns_bottom_border gt_columns_top_border gt_left" rowspan="1" colspan="1">

mfr

</th>

<th class="gt_col_heading gt_columns_bottom_border gt_columns_top_border gt_left" rowspan="1" colspan="1">

model

</th>

</tr>

<body class="gt_table_body">

<tr>

<td class="gt_row gt_left">

Audi

</td>

<td class="gt_row gt_left">

R8 banana

</td>

</tr>

<tr>

<td class="gt_row gt_left gt_striped">

Audi

</td>

<td class="gt_row gt_left gt_striped">

RS 7 banana

</td>

</tr>

<tr>

<td class="gt_row gt_left">

Audi

</td>

<td class="gt_row gt_left">

S6 banana

</td>

</tr>

<tr>

<td class="gt_row gt_left gt_striped">

Audi

</td>

<td class="gt_row gt_left gt_striped">

S7 banana

</td>

</tr>

<tr>

<td class="gt_row gt_left">

Audi

</td>

<td class="gt_row gt_left">

S8 banana

</td>

</tr>

<tr>

<td class="gt_row gt_left gt_striped">

Porsche

</td>

<td class="gt_row gt_left gt_striped">

718 Boxster

</td>

</tr>

<tr>

<td class="gt_row gt_left">

Porsche

</td>

<td class="gt_row gt_left">

718 Cayman

</td>

</tr>

<tr>

<td class="gt_row gt_left gt_striped">

Porsche

</td>

<td class="gt_row gt_left gt_striped">

911

</td>

</tr>

<tr>

<td class="gt_row gt_left">

Porsche

</td>

<td class="gt_row gt_left">

Panamera

</td>

</tr>

</body>

</table>

</div>

``` r
  
# Flipped arguments to col_1 & col_2
test_data %>% 
  gt() %>% 
  cols_merge(
    col_1 = vars(test), 
    col_2 = vars(model)
  ) 
```

<div id="flyrzrltwp" style="overflow-x:auto;overflow-y:auto;width:auto;height:auto;">

<table class="gt_table">

<tr>

<th class="gt_col_heading gt_columns_bottom_border gt_columns_top_border gt_left" rowspan="1" colspan="1">

mfr

</th>

<th class="gt_col_heading gt_columns_bottom_border gt_columns_top_border gt_left" rowspan="1" colspan="1">

test

</th>

</tr>

<body class="gt_table_body">

<tr>

<td class="gt_row gt_left">

Audi

</td>

<td class="gt_row gt_left">

banana R8

</td>

</tr>

<tr>

<td class="gt_row gt_left gt_striped">

Audi

</td>

<td class="gt_row gt_left gt_striped">

banana RS 7

</td>

</tr>

<tr>

<td class="gt_row gt_left">

Audi

</td>

<td class="gt_row gt_left">

banana S6

</td>

</tr>

<tr>

<td class="gt_row gt_left gt_striped">

Audi

</td>

<td class="gt_row gt_left gt_striped">

banana S7

</td>

</tr>

<tr>

<td class="gt_row gt_left">

Audi

</td>

<td class="gt_row gt_left">

banana S8

</td>

</tr>

<tr>

<td class="gt_row gt_left gt_striped">

Porsche

</td>

<td class="gt_row gt_left gt_striped">

BANANA

</td>

</tr>

<tr>

<td class="gt_row gt_left">

Porsche

</td>

<td class="gt_row gt_left">

BANANA

</td>

</tr>

<tr>

<td class="gt_row gt_left gt_striped">

Porsche

</td>

<td class="gt_row gt_left gt_striped">

BANANA

</td>

</tr>

<tr>

<td class="gt_row gt_left">

Porsche

</td>

<td class="gt_row gt_left">

BANANA

</td>

</tr>

</body>

</table>

</div>

<sup>Created on 2019-09-07 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by rich-iannone** [comment]
Thanks for reporting this! This will be fixed in https://github.com/rstudio/gt/pull/355... I tested out the example with the revised `cols_merge()` and it works.
