### ISSUE TITLE
Have `fmt_markdown()` and `md()` handle LaTeX math formulas

### ISSUE THREAD

**Issue by rich-iannone** [rstudio/gt#375]
The `fmt_markdown()`, `html()`, and `md()`  functions should be able to convert LaTeX math formulas to inline SVGs. This will allow math formulas in table cells and in any other label areas (e.g., column labels, header title, etc.). 

The rendered formula SVGs should entirely consist of paths.

**Comment by maj-biostat** [comment]
Hi 
I have been looking for a way to introduce mathematical notation in the column headers (beyond simple cases such as html("p<sub>y<\sub>"). Is there a way to do this? I have been scouring the net and documentation for a few hours and cannot seem to find any options. For the current use case, all I want to do is the equivalent of $\hat{p}_y$ but I have other more complex scenarios that I need to use as well. Thanks.

**Comment by rich-iannone** [comment]
@maj-biostat we'll have this soon when https://github.com/rstudio/gt/pull/1578 is merged!

**Comment by maj-biostat** [comment]
Hi Rich, thank you  very much for the work you are doing on gt. It's really great. Regards, Mark

**Comment by rich-iannone** [comment]
@maj-biostat Thanks Mark, appreciate that! And please let me know if this new feature (only documented currently in `fmt_markdown()`, but also works in `md()`--- though *not* `html()` like the issue states) falls flat in some areas.
