### ISSUE TITLE
Tab_footnote eliminates cell formatting

### ISSUE THREAD

**Issue by elizabethst** [rstudio/gt#378]
Tab_footnote eliminates formatting.

![gt_tab_footnote](https://user-images.githubusercontent.com/11184119/66241150-430d7280-e6b3-11e9-84c8-e5c1cc02dafc.png)

```r
library(tidyverse)
library(gt)

exibble %>%
  group_by(group) %>%
  gt(rowname_col = "row") %>%
  tab_style(
    style = cell_text(weight = "bold"),
    locations = cells_group(
      groups = c("grp_a", "grp_b")
    )
  ) %>%
  tab_footnote(
    footnote = md("**why isn't grp_a still bold?**"),
    locations = cells_group(c("grp_a"))
  ) 
```

**Comment by rich-iannone** [comment]
Thanks for reporting this @elizabethst . This is indeed still a problem but I hope to address it after https://github.com/rstudio/gt/pull/355 is merged.

**Comment by rich-iannone** [comment]
This is now fixed in the development version of gt. Closing.
