### ISSUE TITLE
Add vertical alignment inside rows for tab_style()

### ISSUE THREAD

**Issue by jthomasmock** [rstudio/gt#380]
Hi team,

An older version of `gt` allowed for passing raw CSS style rules as strings which allowed for vertical alignment within rows of a table. I spoke with Rich about this and he suggested posting it as an Issue.

Problem:
The current version of `gt` disallows the use of CSS rules as strings in `tab_style()` and only accept a subset of options (really, the argument list). This is totally fine as I think there are long-term goals of accomplishing additional styling, but a vertical alignment option in addition to horizontal alignment. Specifically this is useful for tables with large chunks of text, where the less verbose columns end up way down the page. See below for a reprex and a representation of the table.

see [Community](https://community.rstudio.com/t/vertical-alignment-of-gt-cell-contents/23174) for a past thread and attempted work-around that has since been removed.

---

<brief description of the problem>

``` r
library(tidyverse)
library(gt)
library(stringi)


long_text <- stri_rand_lipsum(3) %>%
  str_c(., collapse = "\n")

df <- data.frame(
  index = c("I want this", "at the top", "of each cell"),
  text = long_text
)
df %>% gt()
```

<div id="rpmmrtqfwx" style="overflow-x:auto;overflow-y:auto;width:auto;height:auto;">

<table class="gt_table">

<tr>

<th class="gt_col_heading gt_columns_bottom_border gt_columns_top_border gt_center" rowspan="1" colspan="1">

index

</th>

<th class="gt_col_heading gt_columns_bottom_border gt_columns_top_border gt_center" rowspan="1" colspan="1">

text

</th>

</tr>

<body class="gt_table_body">

<tr>

<td class="gt_row gt_center">

I want this

</td>

<td class="gt_row gt_center">

Lorem ipsum dolor sit amet, nulla vel lectus congue, lacus sed viverra potenti ut. Congue amet, nunc porta porta velit convallis parturient condimentum sit consectetur per etiam habitasse mauris parturient. Orci lorem turpis. Lorem lacus ac per eros finibus vulputate sed non. Iaculis, nec faucibus urna convallis aptent cursus. Eu primis tortor, nec condimentum in rutrum nec mauris, facilisis curae a morbi. Ullamcorper lorem in ac in\! In cursus et suspendisse eros condimentum, tortor fusce ipsum. Consequat, purus hac varius tristique. Tortor blandit donec tincidunt sem ridiculus consectetur, hac. Litora turpis dis est eu ridiculus, nisl, nascetur? Nibh torquent sed risus id libero. Justo scelerisque, ornare diam eu lacinia integer, velit porta ac at. Non, in sem justo habitant. Cursus ligula sed arcu tincidunt in ullamcorper adipiscing interdum, dictumst nibh vel eu sit. Eu ut condimentum integer maximus volutpat amet maecenas.
Accumsan sagittis ipsum augue nunc dapibus libero primis felis augue, ex. Quis netus in consequat. In et tempus tempor leo etiam class ut, taciti. Mattis sed fermentum lorem malesuada risus, pellentesque neque risus. Sociosqu at nec in phasellus vehicula aliquam justo ultrices in inceptos. Id donec dui lectus congue tellus eleifend sed. Nulla, at donec mauris amet nulla ut faucibus. Velit nec pellentesque molestie penatibus sed.
Tellus ac sed adipiscing ut sit lobortis penatibus donec. Porttitor dolor nulla in scelerisque, nec tempor pellentesque purus cubilia sit himenaeos. Convallis ad ut nam sapien odio nunc adipiscing semper\! Tempus mattis taciti neque etiam commodo nisi massa lacus dui egestas. Suscipit risus imperdiet, sit sociis massa tincidunt accumsan massa in inceptos. Eu ac lacus. Pharetra porta diam leo turpis. Eu interdum egestas, ut dolor augue turpis curae netus sed, taciti. In penatibus ultricies odio non nam ac phasellus. In et, tempor mi pretium, sodales volutpat praesent mi.

</td>

</tr>

<tr>

<td class="gt_row gt_center gt_striped">

at the top

</td>

<td class="gt_row gt_center gt_striped">

Lorem ipsum dolor sit amet, nulla vel lectus congue, lacus sed viverra potenti ut. Congue amet, nunc porta porta velit convallis parturient condimentum sit consectetur per etiam habitasse mauris parturient. Orci lorem turpis. Lorem lacus ac per eros finibus vulputate sed non. Iaculis, nec faucibus urna convallis aptent cursus. Eu primis tortor, nec condimentum in rutrum nec mauris, facilisis curae a morbi. Ullamcorper lorem in ac in\! In cursus et suspendisse eros condimentum, tortor fusce ipsum. Consequat, purus hac varius tristique. Tortor blandit donec tincidunt sem ridiculus consectetur, hac. Litora turpis dis est eu ridiculus, nisl, nascetur? Nibh torquent sed risus id libero. Justo scelerisque, ornare diam eu lacinia integer, velit porta ac at. Non, in sem justo habitant. Cursus ligula sed arcu tincidunt in ullamcorper adipiscing interdum, dictumst nibh vel eu sit. Eu ut condimentum integer maximus volutpat amet maecenas.
Accumsan sagittis ipsum augue nunc dapibus libero primis felis augue, ex. Quis netus in consequat. In et tempus tempor leo etiam class ut, taciti. Mattis sed fermentum lorem malesuada risus, pellentesque neque risus. Sociosqu at nec in phasellus vehicula aliquam justo ultrices in inceptos. Id donec dui lectus congue tellus eleifend sed. Nulla, at donec mauris amet nulla ut faucibus. Velit nec pellentesque molestie penatibus sed.
Tellus ac sed adipiscing ut sit lobortis penatibus donec. Porttitor dolor nulla in scelerisque, nec tempor pellentesque purus cubilia sit himenaeos. Convallis ad ut nam sapien odio nunc adipiscing semper\! Tempus mattis taciti neque etiam commodo nisi massa lacus dui egestas. Suscipit risus imperdiet, sit sociis massa tincidunt accumsan massa in inceptos. Eu ac lacus. Pharetra porta diam leo turpis. Eu interdum egestas, ut dolor augue turpis curae netus sed, taciti. In penatibus ultricies odio non nam ac phasellus. In et, tempor mi pretium, sodales volutpat praesent mi.

</td>

</tr>

<tr>

<td class="gt_row gt_center">

of each cell

</td>

<td class="gt_row gt_center">

Lorem ipsum dolor sit amet, nulla vel lectus congue, lacus sed viverra potenti ut. Congue amet, nunc porta porta velit convallis parturient condimentum sit consectetur per etiam habitasse mauris parturient. Orci lorem turpis. Lorem lacus ac per eros finibus vulputate sed non. Iaculis, nec faucibus urna convallis aptent cursus. Eu primis tortor, nec condimentum in rutrum nec mauris, facilisis curae a morbi. Ullamcorper lorem in ac in\! In cursus et suspendisse eros condimentum, tortor fusce ipsum. Consequat, purus hac varius tristique. Tortor blandit donec tincidunt sem ridiculus consectetur, hac. Litora turpis dis est eu ridiculus, nisl, nascetur? Nibh torquent sed risus id libero. Justo scelerisque, ornare diam eu lacinia integer, velit porta ac at. Non, in sem justo habitant. Cursus ligula sed arcu tincidunt in ullamcorper adipiscing interdum, dictumst nibh vel eu sit. Eu ut condimentum integer maximus volutpat amet maecenas.
Accumsan sagittis ipsum augue nunc dapibus libero primis felis augue, ex. Quis netus in consequat. In et tempus tempor leo etiam class ut, taciti. Mattis sed fermentum lorem malesuada risus, pellentesque neque risus. Sociosqu at nec in phasellus vehicula aliquam justo ultrices in inceptos. Id donec dui lectus congue tellus eleifend sed. Nulla, at donec mauris amet nulla ut faucibus. Velit nec pellentesque molestie penatibus sed.
Tellus ac sed adipiscing ut sit lobortis penatibus donec. Porttitor dolor nulla in scelerisque, nec tempor pellentesque purus cubilia sit himenaeos. Convallis ad ut nam sapien odio nunc adipiscing semper\! Tempus mattis taciti neque etiam commodo nisi massa lacus dui egestas. Suscipit risus imperdiet, sit sociis massa tincidunt accumsan massa in inceptos. Eu ac lacus. Pharetra porta diam leo turpis. Eu interdum egestas, ut dolor augue turpis curae netus sed, taciti. In penatibus ultricies odio non nam ac phasellus. In et, tempor mi pretium, sodales volutpat praesent mi.

</td>

</tr>

</body>

</table>

</div>

<sup>Created on 2019-10-11 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by rich-iannone** [comment]
Thanks, Tom! Hope to address this one soon.
