### ISSUE TITLE
Left align of columns works, right align does not

### ISSUE THREAD

**Issue by ixodid198** [rstudio/gt#381]
Using `cols_align` I can left align the columns. When I try to right align, the right side of the column names are not aligned with the right of the data. See image below.

```r
library(gt)

can_world_table <- tibble(
  region = c("Canada", "World"),
  target_year = c(20123456, 3479525000),
  current_year = c(38987654, 7713852000)
)

gt(can_world_table) %>% 
  tab_header(
    title = "Population",
    subtitle = "(in millions)"
  ) %>% 
  cols_label(
    region = "",
    target_year = "1967", 
    current_year = "2019"
  ) %>% 
  fmt_number(
    columns = vars(target_year, current_year),
    decimals = 0, 
    scale_by = 1e-6
  ) %>% 
  cols_align(
    align = "right",
    columns = vars(target_year, current_year)
  )


```
<img width="248" alt="Screen Shot 2019-10-11 at 9 52 44 PM" src="https://user-images.githubusercontent.com/12522241/66693025-50f26300-ec72-11e9-9b77-22cc41d9c758.png">

**Comment by rich-iannone** [comment]
Thanks for posting this issue. This one seems to be fixed in a PR that we hope to merge soon (https://github.com/rstudio/gt/pull/355). I'll make sure this issue auto closes when that PR is merged to master.
