### ISSUE TITLE
Attempting to format cells of an incompatible type leads to an unhelpful error message

### ISSUE THREAD

**Issue by rich-iannone** [rstudio/gt#385]
Using `fmt_number()` on a column that is `character` will result in an unhelpful error message. This should be changed so that the message identifies the problem and states which columns/cells are incompatible.

**Comment by MadhulikaTanuboddi** [comment]
Verify example below when this issue is fixed

```
sza %>%
  filter(latitude == 20) %>%
  filter(!is.na(sza)) %>%
  spread(key = "tst", value = sza) %>%
  gt(rowname_col = "month") %>%
  fmt_number(columns = TRUE, decimals = 2) %>%
  fmt_missing(columns = TRUE, missing_text = "")
```
