### ISSUE TITLE
`cols_merge()` fails to preserve img src of a preceding `text_transform()` that uses `web_image()`

### ISSUE THREAD

**Issue by JakeHurlbut** [rstudio/gt#396]
When using `cols_merge()` (the new re-worked version) to merge two columns **after** a `text_transform()` that uses `web_image()` has been applied to one of the two merging columns, the merged column from `cols_merge()` places the second column inside the src attribute of the img tag in the first column.

Here is the img tag generated by the reprex code below, note the end of the src attribute: `<img src="http://upload.wikimedia.org/wikipedia/commons/thumb/9/92/Audi-Logo_2016.svg/196px-Audi-Logo_2016.svg.png Audi" style="height:30px;">`

``` r
library(tidyverse)
library(gt)

audi = gtcars %>%
  filter(mfr == 'Audi') %>%
  mutate(mfr_logo = "http://upload.wikimedia.org/wikipedia/commons/thumb/9/92/Audi-Logo_2016.svg/196px-Audi-Logo_2016.svg.png") %>%
  select(mfr_logo, mfr, model)


gt_audi = audi %>%
  gt() %>%
  text_transform(
    locations = cells_data(vars(mfr_logo)),
    fn = web_image
  )

gt_audi
```

<div id="gvnoxxajdg" style="overflow-x:auto;overflow-y:auto;width:auto;height:auto;">

<table class="gt_table">

<tr>

<th class="gt_col_heading gt_columns_bottom_border gt_left" rowspan="1" colspan="1">

mfr\_logo

</th>

<th class="gt_col_heading gt_columns_bottom_border gt_left" rowspan="1" colspan="1">

mfr

</th>

<th class="gt_col_heading gt_columns_bottom_border gt_left" rowspan="1" colspan="1">

model

</th>

</tr>

<body class="gt_table_body">

<tr>

<td class="gt_row gt_left">

<img src="http://upload.wikimedia.org/wikipedia/commons/thumb/9/92/Audi-Logo_2016.svg/196px-Audi-Logo_2016.svg.png" style="height:30px;">

</td>

<td class="gt_row gt_left">

Audi

</td>

<td class="gt_row gt_left">

R8

</td>

</tr>

<tr>

<td class="gt_row gt_left gt_striped">

<img src="http://upload.wikimedia.org/wikipedia/commons/thumb/9/92/Audi-Logo_2016.svg/196px-Audi-Logo_2016.svg.png" style="height:30px;">

</td>

<td class="gt_row gt_left gt_striped">

Audi

</td>

<td class="gt_row gt_left gt_striped">

RS 7

</td>

</tr>

<tr>

<td class="gt_row gt_left">

<img src="http://upload.wikimedia.org/wikipedia/commons/thumb/9/92/Audi-Logo_2016.svg/196px-Audi-Logo_2016.svg.png" style="height:30px;">

</td>

<td class="gt_row gt_left">

Audi

</td>

<td class="gt_row gt_left">

S6

</td>

</tr>

<tr>

<td class="gt_row gt_left gt_striped">

<img src="http://upload.wikimedia.org/wikipedia/commons/thumb/9/92/Audi-Logo_2016.svg/196px-Audi-Logo_2016.svg.png" style="height:30px;">

</td>

<td class="gt_row gt_left gt_striped">

Audi

</td>

<td class="gt_row gt_left gt_striped">

S7

</td>

</tr>

<tr>

<td class="gt_row gt_left">

<img src="http://upload.wikimedia.org/wikipedia/commons/thumb/9/92/Audi-Logo_2016.svg/196px-Audi-Logo_2016.svg.png" style="height:30px;">

</td>

<td class="gt_row gt_left">

Audi

</td>

<td class="gt_row gt_left">

S8

</td>

</tr>

</body>

</table>

</div>

``` r

gt_audi_merged = gt_audi %>%
  cols_merge(
    columns = vars(mfr_logo, mfr),
    hide_columns = vars(mfr)
  )

gt_audi_merged
```

<div id="gvnoxxajdg" style="overflow-x:auto;overflow-y:auto;width:auto;height:auto;">

<table class="gt_table">

<tr>

<th class="gt_col_heading gt_columns_bottom_border gt_left" rowspan="1" colspan="1">

mfr\_logo

</th>

<th class="gt_col_heading gt_columns_bottom_border gt_left" rowspan="1" colspan="1">

model

</th>

</tr>

<body class="gt_table_body">

<tr>

<td class="gt_row gt_left">

<img src="http://upload.wikimedia.org/wikipedia/commons/thumb/9/92/Audi-Logo_2016.svg/196px-Audi-Logo_2016.svg.png Audi" style="height:30px;">

</td>

<td class="gt_row gt_left">

R8

</td>

</tr>

<tr>

<td class="gt_row gt_left gt_striped">

<img src="http://upload.wikimedia.org/wikipedia/commons/thumb/9/92/Audi-Logo_2016.svg/196px-Audi-Logo_2016.svg.png Audi" style="height:30px;">

</td>

<td class="gt_row gt_left gt_striped">

RS 7

</td>

</tr>

<tr>

<td class="gt_row gt_left">

<img src="http://upload.wikimedia.org/wikipedia/commons/thumb/9/92/Audi-Logo_2016.svg/196px-Audi-Logo_2016.svg.png Audi" style="height:30px;">

</td>

<td class="gt_row gt_left">

S6

</td>

</tr>

<tr>

<td class="gt_row gt_left gt_striped">

<img src="http://upload.wikimedia.org/wikipedia/commons/thumb/9/92/Audi-Logo_2016.svg/196px-Audi-Logo_2016.svg.png Audi" style="height:30px;">

</td>

<td class="gt_row gt_left gt_striped">

S7

</td>

</tr>

<tr>

<td class="gt_row gt_left">

<img src="http://upload.wikimedia.org/wikipedia/commons/thumb/9/92/Audi-Logo_2016.svg/196px-Audi-Logo_2016.svg.png Audi" style="height:30px;">

</td>

<td class="gt_row gt_left">

S8

</td>

</tr>

</body>

</table>

</div>

<sup>Created on 2019-11-12 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by jcheng5** [comment]
Thanks for the feedback @JakeHurlbut. In this case, the `fmt` function is more appropriate than `text_transform`.

* The `fmt` functions tell gt how to change raw data to HTML. If multiple `fmt_*` directives apply to a single cell, the last one wins.
* The `text_transform` functions tell gt how to take the HTML returned by formatters (and, as you have seen, post-col-merge) and turn it into other HTML. If multiple `text_transform`s apply to a single cell, their effects stack (the output from the first formatter is used as the input to the second formatter).

To me, the `web_image` function is clearly an example of the former (whereas, say, wrapping in `<strong>` would be a clear example of the latter).

```r
gt_audi = audi %>%
  gt() %>%
  fmt(
    columns = vars(mfr_logo),
    fns = function(x) {
      "<strong>hello</strong>"
    }
  )
```

The distinction between formatters and text transform are underdocumented at the moment, we have our eye on it.

**Comment by JakeHurlbut** [comment]
This is good to know, thanks for taking the time to clarify @jcheng5! Feel free to close the issue.

**Comment by rich-iannone** [comment]
Thanks! Closing now.
