### ISSUE TITLE
Error in values[index] (only 0's may be mixed with negative subscripts) when one variable in df contains only zeroes

### ISSUE THREAD

**Issue by xavidp** [rstudio/gt#397]
First of all, let me say congrats for this awseome package gt you are building! :-)

Issue detected: If you have a dataframe more than one variable, and one of them contains only empty values, you end up hitting this error: 

`Error in values[index] : only 0's may be mixed with negative subscripts` 
(using R 3.6.x under GNU/Linux 64 bits, in case it matters)

Reproducible example:

```r
  data.frame(x=rnorm(10), y=rep(0,10)) %>% 
  gt() %>%
  fmt_number(
    columns = vars(x,
                   y),
    decimals = 2,
    suffixing = TRUE
  )
```

FYI, If you attempt to make the similar reprex but only with one  column (y in the previous example), then no error is triggered and the expected result is produced.

```r
  data.frame(y=rep(0,10)) %>% 
  gt() %>%
  fmt_number(
    columns = vars(y),
    decimals = 2,
    suffixing = TRUE
  )
```

**Comment by rich-iannone** [comment]
Thanks so much for catching this bug. The example code helps a lot! It looks like the code path from `suffixing = TRUE` is the problem. We will get this fixed.
