### ISSUE TITLE
Two-way summaries

### ISSUE THREAD

**Issue by mine-cetinkaya-rundel** [rstudio/gt#4]
`base::table()` results in an output that is decidedly not tidy, and not necessarily very attractive either, but it does a good job in suumarising the conditional distribution of one categorical variable over the other, and it’s a nice display for teaching conditional probabilities. It would be nice to think about whether/how to achieve this same goal here (ideally along with margins added too).

**Comment by robyngit** [comment]
`gt()` makes a nice two-way table if you convert the output of `table()` using `base::as.data.frame.matrix()` first. For example:

```
gtcars %>% 
	with(table(drivetrain, bdy_style)) %>% 
	addmargins() %>% 
	as.data.frame.matrix() %>% 
	gt(rownames_to_stub = TRUE)
```
<table class='gt_table'><tr><th class='gt_col_heading gt_left' rowspan='1' colspan='1'></th><th class='gt_col_heading gt_right' rowspan='1' colspan='1'>convertible</th><th class='gt_col_heading gt_right' rowspan='1' colspan='1'>coupe</th><th class='gt_col_heading gt_right' rowspan='1' colspan='1'>hatchback</th><th class='gt_col_heading gt_right' rowspan='1' colspan='1'>sedan</th><th class='gt_col_heading gt_right' rowspan='1' colspan='1'>Sum</th></tr><tbody class='gt_table_body'><tr><td class='gt_row gt_stub gt_left'>awd</td><td class='gt_row gt_right'>0</td><td class='gt_row gt_right'>8</td><td class='gt_row gt_right'>2</td><td class='gt_row gt_right'>3</td><td class='gt_row gt_right'>13</td></tr><tr><td class='gt_row gt_stub gt_left'>rwd</td><td class='gt_row gt_right gt_striped'>5</td><td class='gt_row gt_right gt_striped'>24</td><td class='gt_row gt_right gt_striped'>0</td><td class='gt_row gt_right gt_striped'>5</td><td class='gt_row gt_right gt_striped'>34</td></tr><tr><td class='gt_row gt_stub gt_left'>Sum</td><td class='gt_row gt_right'>5</td><td class='gt_row gt_right'>32</td><td class='gt_row gt_right'>2</td><td class='gt_row gt_right'>8</td><td class='gt_row gt_right'>47</td></tr></tbody></table>

**Comment by rich-iannone** [comment]
Given that it’s now pretty difficult to transform data table within the gt API, I’m going to close this one.
