### ISSUE TITLE
Add a format function to generate fractions from numbers

### ISSUE THREAD

**Issue by rmurrayed** [rstudio/gt#402]
This is one of the best packages in R. Thanks so much for making it!

My idea is to make fractions from numbers. Where if you had 0.5, it becomes 1/2, 2.33 becomes 2 33/100 (or 2 1/3, depending on the accuracy which could be 1, 2, 3 digits in the denominator). You could also specify that the denominator must be of a certain type (1/3s, 1/2s, 1/4s, 1/8s).

**Comment by rich-iannone** [comment]
This could become `fmt_fraction()` and based on these requirements it doesn’t look too difficult. Thanks for the feature request!

**Comment by jordanmllr5** [comment]
The amount of formatters in this package is really impressive and I think this would be a great one. Honestly, if you would just keep adding more formatters it would only increase the value proposition of the whole project!
