### ISSUE TITLE
Allow selection of a font for the table (and maybe specific parts)

### ISSUE THREAD

**Issue by rmurrayed** [rstudio/gt#404]
Right now, there is no choice in the font selection. It would be awesome if we could choose a webfont for the HTML table or at least monospace fonts in certain columns (for numbers).

**Comment by rich-iannone** [comment]
This is partially addressed by using `tab_style()` and `cell_text()` but you are right in that you can’t just choose a font for the entire table. A webfont is not a bad idea for HTML output tables, and I think there could be other options available to make the table more self-contained. 

Thank you for this feature request.

**Comment by kmatosli** [comment]
Rich, it might be end user error on my part but do you have a list of fonts that can be used with the table.  I have attempted to use tab_style and cell_text and neither actually change the font.
