### ISSUE TITLE
Make it easy to insert a Fontawesome icon into a new text element of a table

### ISSUE THREAD

**Issue by scotbader8858** [rstudio/gt#418]
Perhaps this can already be done with the fontawesome package, not sure, but having an easy way to get an icon into a title or footnote or some other location is something that would be very valuable.

**Comment by rich-iannone** [comment]
I have to explore what’s already possible here. It may turn out that it is possible to do but requires a lot of input. 

It would be really nice to have something like a short code that could be present in the text and interpreted as request for an icon.

**Comment by jordanmllr5** [comment]
This would be a really great feature. Maybe have the icons built in to the package as SVG and have a way to put in the SVG through a text keyword. As an example, the following could be interpreted as text (for the title) with a fontawesome icon:

```
exibble %>% 
  gt() %>%
  tab_header(title = "Daily bus timetable {{fas bus}}")
```

With this the title would have the text `Daily bus timetable` plus the right-sized fontawesome icon (https://fontawesome.com/icons/bus?style=solid). I really think having this templating idea with `{{ }}` could be also great for supplying styles to text (bolding specific text, or changing font, font size, etc.). That is going a bit off topic so maybe I'll open a different issue with some ideas there.

**Comment by jordanmllr5** [comment]
I also wanted to add that if you have text in your table that has the templating (as suggested above), that could be formatted with a function called `fmt_text()`. That could take the place of (or be in addition to) `fmt_markdown()`. You could have options to interpret (separately) Markdown text or the templating text (both set to TRUE as a default).

I could imagine this being used to compose text options with dplyr::mutate() and combining into the final interpretable form (probably with `mutate()` again) before entering the gt API. We can then always combine the formatted text elements nicely with `cols_merge()`. Basically, these options would give us a lot of freedom for customizing the look (which I think everyone would appreciate).

Thanks again for this wonderful package! It is truly awesome and has helped me a lot.

**Comment by rich-iannone** [comment]
This is now possible and pretty simple with the {fontawesome} package on CRAN. You can use:

```r
exibble %>% 
    gt() %>%
    tab_header(title = html(glue::glue("Daily bus timetable {fontawesome::fa('bus')}")))
```

or

```r
exibble %>% 
    gt() %>%
    tab_header(title = md(glue::glue("Daily bus timetable {fontawesome::fa('bus')}")))
```

and get the following:

<img width="926" alt="table" src="https://user-images.githubusercontent.com/5612024/116291649-d4937800-a762-11eb-9d14-f92610d26524.png">

**Comment by juka19** [comment]
In case anyone is wondering how to do this with a column (it took me a while to understand), here is short example:

```
tribble(
  ~country, ~glasgow, ~coal, ~oil, ~gas, ~indirect,
  "Australia", T, "Single partial exclusion", "No exclusion", "No exclusion", "No exclusion",
  "Belgium", T,  "Single partial exclusion", "Full exclusion", "Multiple partial exclusions", "Multiple partial exclusions",
  "Canada", T, "Full exclusion", "Multiple partial exclusions", "Multiple partial exclusions", "No exclusion"
)

map_color <- function(x) {
  case_when(
    x == "Single partial exclusion" ~ glue::glue('{fontawesome::fa("circle", prefer_type = "solid", fill = "brown")}'),
    x == "No exclusion" ~ glue::glue('{fontawesome::fa("circle", prefer_type = "solid", fill = "red")}'),
    x == "Multiple partial exclusions" ~ glue::glue('{fontawesome::fa("circle", prefer_type = "solid", fill = "yellow")}'), 
    x == "Full exclusion" ~ glue::glue('{fontawesome::fa("circle", prefer_type = "solid", fill = "green")}')
  )
}

data %>% mutate_at(
  vars(coal:indirect),
  list(
    circle_color = ~map_color(.)
  )
) %>%
  mutate(
    glasgow = case_when(
      glasgow == T ~ glue::glue('{fontawesome::fa("circle-check", prefer_type = "solid")}'),
      glasgow == F ~ glue::glue('{fontawesome::fa("circle-xmark", prefer_type = "regular")}')
    )
  ) %>% 
  gt() %>% 
  fmt_markdown(
    glasgow
    ) %>% 
  cols_label(
    coal_circle_color = md("**Coal**"),
    oil_circle_color = md("**Oil**"),
    gas_circle_color = md("**Gas**"),
    indirect_circle_color = md("**Indirect Financing**"),
    glasgow = md("**Glasgow Signatory**"),
    country = md("")
  ) %>% 
  fmt_markdown(
    coal_circle_color:indirect_circle_color
  ) %>% 
  cols_hide(
    columns = coal:indirect
  )
```
