### ISSUE TITLE
Render gt into a gtable grob

### ISSUE THREAD

**Issue by thomasp85** [rstudio/gt#420]
It would be very nice to put table designs created with gt into figures. For this to be possible gt objects need to be able to be rendered into gtable objects (or another type of grob).

For an example of this functionality (without the gt styling) see `gridExtra::tableGrob()`

**Comment by rich-iannone** [comment]
This is a great feature request, thanks!

**Comment by JohannesNE** [comment]
A workaround until this is implemented is to save the table as PNG and then add this PNG with e.g. {patchwork}. 
(It is probably possible to skip saving to disk, but I'm unsure how). 

Example:
```
tmp <- tempfile(fileext = '.png') #generate path to temp .png file
gtsave(gt, tmp) #save gt table as png
table_png <- png::readPNG(tmp, native = TRUE) # read tmp png file

library(patchwork)
plot_1 + table_png
```
