### ISSUE TITLE
Update README, function reference, and Cloud examples

### ISSUE THREAD

**Issue by rich-iannone** [rstudio/gt#421]
Update README and pkgdown reference section (`_pkdown.yml`). 

For the RStudio Cloud examples, create multiple .Rmd files in a single Cloud project (splitting by family). This will reuse examples from the function documentation.

**Comment by MadhulikaTanuboddi** [comment]
@rich-iannone : https://gt.rstudio.com/index.html. Two requests

#1. Can you provide links to the functions in the svg?
#2. Update the svg file with the all the new functions and correct function names? for ex: tab_stubhead_label is now tab_stubhead.

**Comment by MadhulikaTanuboddi** [comment]
Update needed in this context - https://gt.rstudio.com/reference/summary_rows.html
`grand_summary_rows()` function reference uses the same link above and the example in there does not show how to use this function. Figures also needs to be updated showing grand summary rows
