### ISSUE TITLE
Include self contained examples for every function and helper functions

### ISSUE THREAD

**Issue by MadhulikaTanuboddi** [rstudio/gt#422]
https://gt.rstudio.com/reference/cell_fill.html

for example: cell_fill helper function above does not have an example and expected output.

**Comment by kmatosli** [comment]
When running any of the sample code, I get an error indicating that could not find function: cell_fill and cell_text.

**Comment by rich-iannone** [comment]
@kmatosli try updating gt with `remotes::install_github("rstudio/gt")`.
