### ISSUE TITLE
Feature:  Automatic scrolling of cell content

### ISSUE THREAD

**Issue by charlesatkinson2000** [rstudio/gt#428]
First off, kudos are in order. This is a fantastic R package and, for us, the most significant one since dplyr and ggplot before that. Thanks so much for the beautiful documentation, clear examples, and excellent features. We are planning on integrating gt more and more into our analytical pipelines so keep being awesome!

Anyway onto the ask. I know you’re getting a lot of feature requests but at least put this one under consideration. We want to make mostly non-interactive HTML tables, which are supported really well in gt. However it would be great to have an option for automatic horizontal scrolling of longer text inside of specific table cells. This way, we can have columns that are of fixed-width but occasionally longer strings will still be readable without an ellipsis or user interaction. 

Thanks again! You really hit it out of the park with this package.

**Comment by rich-iannone** [comment]
I know what this is and I have a pretty good idea about how it can be implemented (through CSS keyframes).

In the most successful of these implementations (in my mind, at least), there is a reduction in text alpha on the right side where there would be additional text content. The overflowed content would be paused initially, move to the left to reveal all of the content (with linear easing or in-out easing), and the beginning of the string would appear again on the RHS (separated by a gap) until moving back into the initial position. Pausing (for 4-5 s) and moving would repeat indefinitely. 

If there are multiple overflowed strings we might consider an additional pausing until the longest of those strings is back in the initial position. 

Does this description (which is hard to put in words) correspond to what you were thinking?

**Comment by charlesatkinson2000** [comment]
Yes Rich, this is exactly what I was trying to describe. Thanks for responding to the issue so quickly! Again, really appreciate everything you're doing here.
