### ISSUE TITLE
`tab_style` with `cells_column_labels` not working in the presence of a `tab_spanner`

### ISSUE THREAD

**Issue by fnaufel** [rstudio/gt#429]
I want to produce a table with all column labels set in **bold**. The code below does it:

``` r
library(gt)
library(magrittr)

df <- data.frame(
  fn = c('a', 'b'),
  ln = c('c', 'd'),
  value = c(1, 2)
)

df %>% 
  gt() %>% 
  cols_label(fn = 'First', ln = 'Last') %>% 
  tab_style(
    style = cell_text(weight = 'bold'),
    locations = cells_column_labels(columns = 1:3)
  )
```
![image](https://user-images.githubusercontent.com/1002949/69984941-06c28b00-1519-11ea-9684-59974c72e6e5.png)

But the formatting does not work for labels of columns that are under a spanner, as in the code below:

``` r
library(gt)
library(magrittr)

df <- data.frame(
  fn = c('a', 'b'),
  ln = c('c', 'd'),
  value = c(1, 2)
)

df %>% 
  gt() %>% 
  cols_label(fn = 'First', ln = 'Last') %>% 
  tab_spanner('Name', vars(fn, ln)) %>%
  tab_style(
    style = cell_text(weight = 'bold'),
    locations = cells_column_labels(columns = 1:3)
  )
```
![image](https://user-images.githubusercontent.com/1002949/69984971-19d55b00-1519-11ea-9090-8b5082db67ce.png)

HOWEVER, this only happens when I set the column names via `cols_label`. If the table uses the original column names from the dataframe, the formatting is correctly applied:

``` r
library(gt)
library(magrittr)

df <- data.frame(
  fn = c('a', 'b'),
  ln = c('c', 'd'),
  value = c(1, 2)
)

df %>% 
  gt() %>% 
  # cols_label(fn = 'First', ln = 'Last') %>% 
  tab_spanner('Name', vars(fn, ln)) %>%
  tab_style(
    style = cell_text(weight = 'bold'),
    locations = cells_column_labels(columns = 1:3)
  )
```

![image](https://user-images.githubusercontent.com/1002949/69985396-d4655d80-1519-11ea-9496-610a79fd9747.png)

**Comment by rich-iannone** [comment]
Hi @fnaufel I just tested this on `master` and found that all column labels are in bold. I used your code:

```r
library(gt)

df <- data.frame(
  fn = c('a', 'b'),
  ln = c('c', 'd'),
  value = c(1, 2)
)

df %>% 
  gt() %>% 
  cols_label(fn = 'First', ln = 'Last') %>% 
  tab_spanner('Name', vars(fn, ln)) %>%
  tab_style(
    style = cell_text(weight = 'bold'),
    locations = cells_column_labels(columns = 1:3)
  )
```

And saw this:

<img width="174" alt="column_labels_bold" src="https://user-images.githubusercontent.com/5612024/69986701-f526b680-150b-11ea-896a-629ab50e940a.png">

Could you try once again after updating **gt**? Feel free to close if this solves the issue.

**Comment by fnaufel** [comment]
Hi, @rich-iannone, thanks for the quick response.

I updated the package and it now works. Issue solved. Thanks.
