### ISSUE TITLE
Render Row Names By Default for Data Frames

### ISSUE THREAD

**Issue by DarioS** [rstudio/gt#432]
If the input variable is a data frame, should the default behaviour be to draw the row names? Also, could `rowname_col` accept a special value for data frames, to denote the row names of the data frame, rather than a column within the data frame?

**Comment by rich-iannone** [comment]
Since both data frames and tibbles are in common use, we decided to standardize the behavior of their ingest in the `gt()` function. This means that you first have to create a column that contains the row names for use in the stub.
