### ISSUE TITLE
tab_style() with cells_column_labels() targets wrong column label when `rowname_col` arg supplied 

### ISSUE THREAD

**Issue by viviankhoo** [rstudio/gt#439]
I've illustrated the unusual behavior with three datasets. The `exibble` dataset works as expected but not `mtcars` and `countrypops`.

I called the `columns` arg in `cells_column_labels` three different ways (vars, names, index) and all show the consistent incorrect behaviour - the column label to the right of the intended column label is targeted instead.

```
  library(gt)
  library(tibble)
  
  # exibble: highlight "char"
  exibble %>% 
    head(5) %>% 
    gt(rowname_col = "row") %>% 
    tab_style(
      list(cell_fill(), cell_text(weight = "bold")),
      cells_column_labels(2)
      )
  
  # mtcars: highlight "cyl"
  ## vars
  mtcars %>% 
    head(5) %>% 
    as_tibble(rownames = "model") %>% 
    gt(rowname_col = "model") %>% 
    tab_style(
      list(cell_fill(), cell_text(weight = "bold")),
      cells_column_labels(vars(cyl))
      )
  
  ## names
  mtcars %>% 
    head(5) %>% 
    as_tibble(rownames = "model") %>% 
    gt(rowname_col = "model") %>% 
    tab_style(
      list(cell_fill(), cell_text(weight = "bold")),
      cells_column_labels(c("cyl"))
      )
  
  ## index
  mtcars %>% 
    head(5) %>% 
    as_tibble(rownames = "model") %>% 
    gt(rowname_col = "model") %>% 
    tab_style(
      list(cell_fill(), cell_text(weight = "bold")),
      cells_column_labels(2)
      )
  
  # countrypop: highlight `country_code_3`
  ## var
  gt::countrypops %>% 
    head(5) %>% 
    gt(rowname_col = "country_name") %>% 
    tab_style(
      list(cell_fill(), cell_text(weight = "bold")),
      cells_column_labels(vars(country_code_3))
    )
  
  ## names
  gt::countrypops %>% 
    head(5) %>% 
    gt(rowname_col = "country_name") %>% 
    tab_style(
      list(cell_fill(), cell_text(weight = "bold")),
      cells_column_labels("country_code_3")
    )
  
  ## index
  gt::countrypops %>% 
    head(5) %>% 
    gt(rowname_col = "country_name") %>% 
    tab_style(
      list(cell_fill(), cell_text(weight = "bold")),
      cells_column_labels(2)
    )
```
![image](https://user-images.githubusercontent.com/42796157/70766829-038d9180-1d9a-11ea-9d62-05d3a0de3f75.png)

There is no issue when `rowname_col` arg in `gt` is not supplied.
```r
gt::countrypops %>% 
  head(5) %>% 
  gt() %>% 
  tab_style(
    list(cell_fill(), cell_text(weight = "bold")),
    cells_column_labels("country_code_3")
    )
```
![image](https://user-images.githubusercontent.com/42796157/70766413-a0e7c600-1d98-11ea-8220-ec1b5888a21e.png)

**Comment by viviankhoo** [comment]
#438

**Comment by viviankhoo** [comment]
#438 Probably the same root cause as this issue

**Comment by viviankhoo** [comment]
#438 Possibly related to this issue where the `rowname_col` arg is not supplied explicitly but in use.

**Comment by rich-iannone** [comment]
This is probably related to 'hidden' columns being still included while resolving column indices (the stub column is hidden automatically). Seems isolated to the `cells_column_labels()` function. One question Vivian, do underscore characters always appear like that for you? As `\_` I mean.

**Comment by viviankhoo** [comment]
> This is probably related to 'hidden' columns being still included while resolving column indices (the stub column is hidden automatically). Seems isolated to the cells_column_labels() function. One question Vivian, do underscore characters always appear like that for you? As \_ I mean.

I've never rendered gt in reprex before so I am unsure why it appears like that. Also it is my first time filing an issue but I think there's great potential in this package that I just had to contribute. I hope it helps.

**Comment by rich-iannone** [comment]
Ah, okay! Thought it was another bug we hadn't seen before.

Thanks for contributing by filing the issue! It helps a lot to see these problems that we sometimes don't catch. We will get to fixing this bug and we'll also add some tests (to ensure this exact issue doesn't creep back after it's 'fixed').

And always feel free to file more issues if you do see problems (we appreciate the feedback).
