### ISSUE TITLE
indent in gt row headers 

### ISSUE THREAD

**Issue by haohua** [rstudio/gt#448]
Hi gt team, 

I want to add indentation to my row headers, and also add more than one layers of indentation. 
right now, the indentation of row header is only available if the stubhead or tab_row_group are used. 
is there any way to specify the indent of each row headers?

I was trying to paste space or tab to the text of each row header. However , the rendering process ignore the space/tab of the text. 

Here is some example I want to create with gt. 
![image](https://user-images.githubusercontent.com/5149101/71213487-43141c00-2279-11ea-8eb7-d9d0220b668f.png)

**Comment by rich-iannone** [comment]
I think that there should be more high-level support for this down the road (with a `cols_indent()` function). Today, however, this is possible with `tab_style()` and `cell_text()` (the `indent` option).
