### ISSUE TITLE
Add option to reverse relationship between delimited group levels

### ISSUE THREAD

**Issue by jcheng5** [rstudio/gt#454]
This is for compatibility with `tidyr::pivot_longer`.

(Sorry I lost the example we were working with when we discussed this, I'm just closing open tabs and saw this half started bug report)

**Comment by rich-iannone** [comment]
I do remember this, so, I’ll add in an example here soon. Thanks!

**Comment by rich-iannone** [comment]
Now implemented! (Actually has been for a while now.)
