### ISSUE TITLE
Minimum version for scales package is incorrect

### ISSUE THREAD

**Issue by actuarialvoodoo** [rstudio/gt#456]
I was unable to successfully run R CMD check (`devtools::check()`) due to a failure  of one unit test in the test-data_color.R file (line 36 "the correct color values are obtained when defining a palette"). 

The test fails because the call to `data_color` throws an error which is due to call to `scales::col_factor` having an unused argument (alpha = TRUE). The alpha argument was [added on Aug 18 2018](https://github.com/r-lib/scales/commit/7cd81215ba1f0da3e03418871ffccef7dbc7b523), just after the release of v1.0.0.

Currently the DESCRIPTION file list scales >=1.0.0 as an import. When I updated my local setup to have version 1.1.0 of scales package I no longer have these errors. My proposed fix would be to update the DESCRIPTION file to scales >= 1.1.0. 

``` r
library(dplyr)
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union

test_tbl <- tibble::tibble(x = 1:12)
# Obtain a palette of 12 colors in #RRGGBB format
pal_12 <-
  paletteer::paletteer_d(palette = "rcartocolor::Vivid") %>% as.character() %>%
  gsub("FF$", "", .)

color_fn <- scales::col_factor(pal_12, domain = test_tbl$x)
color_fn <- scales::col_factor(pal_12, domain = test_tbl$x, alpha = TRUE)
#> Error in scales::col_factor(pal_12, domain = test_tbl$x, alpha = TRUE): unused argument (alpha = TRUE)
```

<sup>Created on 2019-12-29 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>```

**Comment by rich-iannone** [comment]
Thank you so much for this issue and for the PR! We will review and merge that in soon.
