### ISSUE TITLE
Allow cols_width to be specified relative to each other

### ISSUE THREAD

**Issue by akgold** [rstudio/gt#460]
Right now, widths in `col_width` must be specified as a number of pixels. I would love to be able to specify column widths relative to each other. For example, I'd love to be able to put in something like
```r
cols_width(gt, vars(double_wide_col) ~ 2, vars(half_wide_col) ~ 0.5, TRUE ~ 1)
``` 
or even having the `TRUE ~ 1` implied, so it'd be 
```r
cols_width(gt, vars(double_wide_col) ~ 2, vars(half_wide_col) ~ 0.5)
```
This would mainly be useful because I don't know the width of my table in px as I'm writing it, but I do know how relatively wide I want my columns.

**Comment by rich-iannone** [comment]
This is a great idea and one that I would use quite a lot! I'd really like to spend some time enhancing the definition of column widths because I feel we are only 20% of the way there toward good usability.
