### ISSUE TITLE
Bug: Detecting a subtitle when none present - fails to knit to latex. 

### ISSUE THREAD

**Issue by annacnev** [rstudio/gt#463]
**Problem Description**
When using ```as_latex``` and knitr in RStudio, gt LaTeX table fails giving the following error:

>! LaTeX Error: There's no line here to end.

**Reproducible Example**
```
library(gt)
library(tidyverse)

summary_single_table <- tribble(~study, ~N, ~Observation,
                                1,      25,     0.555, 
                                2,      55,     0.777,
                                3,     109,     0.355)



gt_tab <- summary_single_table %>% 
          gt(rowname_col = "study") %>%
  tab_header(title = "Table S1: Summary of Clinical Study Data by Study")


gt_tab %>% as_latex()
```

The LaTeX is failing because gt is registering a subtitle that is not actually present. If I do:

```
g <- gt:::build_data(gt_tab, context='latex')
gt:::dt_heading_has_subtitle(data = g)

>>> [1] TRUE

gt:::dt_heading_get(data = g)

>>>$title
[1] "Table S1: Summary of Clinical Study Data by Study"

$subtitle
character(0)
```

The ```dt_heading_has_subtitle``` function is:

```
dt_heading_has_subtitle <- function(data) {

  heading <- dt_heading_get(data = data)

  length(heading) > 0 && !is.null(heading$subtitle)
}
```

If I change this to:

```
dt_heading_has_subtitle <- function(data) {

  heading <- dt_heading_get(data = data)

  length(heading$subtitle) > 0 && !is.null(heading$subtitle)
}
```

It accurately returns ```FALSE```  instead of ```TRUE``` and knitr does not fail to render the LaTeX table. 

Note the ```dt_heading_has_title``` should also probably be changed from:

```
dt_heading_has_title <- function(data) {

  heading <- dt_heading_get(data = data)

  length(heading) > 0 && !is.null(heading$title)
}
```
To:
```
dt_heading_has_title <- function(data) {

  heading <- dt_heading_get(data = data)

  length(heading$title) > 0 && !is.null(heading$title)
}
```

**Comment by jonathan-g** [comment]
I'm running into this bug too. The pull request  #464 looks like a clean solution (a dozen lines of code in two .R files, plus a bunch of changes to generated .Rd files) and it looks like it passes all the tests, but it has been languishing since January.

Is there anything I can do to help move this forward?

**Comment by annacnev** [comment]
@jonathan-g oops, changes to the .Rd files are just from them being generated with a different version of ```roxygen``` and are all related to line spacing -probably should not have committed those in retrospect.. is this still happening on the newest release though?

**Comment by rich-iannone** [comment]
@annacnev I apologize for not responding to you (much, much earlier) about the LaTeX improvements you've been making. I wasn't sure whether the HTML API was stable enough to move ahead with the much-needed fixes on the LaTeX side.

If it's okay, I'd like to create a new issue for discussing LaTeX in terms of a roadmap. That way we could talk about the LaTeX improvements as a whole and also discuss specific PRs. Again, really very sorry about the lack of communication here.

**Comment by annacnev** [comment]
@rich-iannone oh no worries! I saw previous comments on issues where you guy's had said you were trying to stabilize the HTML before you moved on to the LaTeX so I was holding off on making any further LaTeX-related PRs until it seemed like it was being worked on again.

And more than okay- sounds like a good plan!

**Comment by rich-iannone** [comment]
Great! Thanks again for understanding. I’ll start up that issue where some planning/discussion can occur!

**Comment by jonathan-g** [comment]
Thanks for the responses @annacnev and @rich-iannone. Let me know if I can contribute any help.
