### ISSUE TITLE
as_latex creates extra columns in summary_rows 

### ISSUE THREAD

**Issue by tbradley1013** [rstudio/gt#465]
When a `gt` table with `summary_rows` is converted to LaTeX, additional columns are added to the summary rows section causing the alignment to be incorrect. Here is a minimal example (using the example from the `summary_rows` help page with only two columns getting the summary row):

````
---
title: "gt issue"
author: "Tyler Bradley"
date: "1/13/2020"
output:
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(gt)
library(tidyverse)
```

```{r}
sp500 %>%
    dplyr::filter(
        date >= "2015-01-05" &
            date <="2015-01-16"
    ) %>%
    dplyr::arrange(date) %>%
    dplyr::mutate(
        week = paste0(
            "W", strftime(date, format = "%V"))
    ) %>%
    dplyr::select(-adj_close, -volume) %>%
    gt(
        rowname_col = "date",
        groupname_col = "week"
    ) %>%
    summary_rows(
        groups = TRUE,
        columns = vars(open, high, low, close),
        fns = list(
            min = ~min(.),
            max = ~max(.),
            avg = ~mean(.)),
        formatter = fmt_number,
        use_seps = FALSE
    )

```
````

![image](https://user-images.githubusercontent.com/23705496/72260984-f276b100-35e1-11ea-89e0-00a4a565782c.png)

If you render to HTML or just run the code in the console than it is rendered correctly. If you use the `as_latex` function then it returns the LaTeX with the extra spaces. I have found some tables that add two extra columns rather than one as well. 

Any help with this is greatly appreciated!

**Comment by tbradley1013** [comment]
The problem appears to be [here in `create_summary_rows`](https://github.com/rstudio/gt/blob/c82a67d3d0217307a2abf8239ede09bc198513e4/R/utils_render_common.R#L411):
 ```  
 summary_df <-
      list_of_summaries$summary_df_display_list[[group]] %>%
      as.data.frame(stringsAsFactors = FALSE)
```

Running browser() on this lapply loop in that function the output for the group ending row of this chunk of code is:

```
# A tibble: 3 x 7
  rowname date  open      high      low       close     week 
  <chr>   <chr> <chr>     <chr>     <chr>     <chr>     <chr>
1 min     ---   $2005.55$ $2029.61$ $1992.44$ $2002.61$ ---  
2 max     ---   $2063.45$ $2064.43$ $2038.33$ $2062.14$ ---  
3 avg     ---   $2035.24$ $2048.56$ $2016.85$ $2031.21$ --- 
```
These blanks correspond to the groupname and rowname cols in the `gt` object. They should be removed from this table likely and the issue would be resolved. I have found a possible fix and will submit a PR this morning

**Comment by rich-iannone** [comment]
This is now fixed from the recent merging of https://github.com/rstudio/gt/pull/768.
