### ISSUE TITLE
tab_spanner gap width feature

### ISSUE THREAD

**Issue by engineerchange** [rstudio/gt#467]
Thank you for the work put into gt. It's such a joy to use!

I've noted that when using gt tables in presentations, that with wider data, the distinction between one tab spanner and another can be hard to interpret. 

Recommend a feature such as spanner width to change the distance between tab spanners and/or a logical to add a vertical line as a separator.

``` r
library(tidyverse)
library(gt)

packageVersion("tidyverse")
#> [1] '1.3.0'
packageVersion("gt")
#> [1] '0.1.0'

gtcars %>% head(10) %>%
  select(mfr,model,year,bdy_style,hp,hp_rpm,trq,trq_rpm,mpg_c,mpg_h) %>%
  gt() %>%
  tab_spanner(
    label = "Car Model",
    columns = vars(mfr,model,year)
  ) %>%
  tab_spanner(
    label = "Performance",
    columns = vars(bdy_style,hp,hp_rpm,trq,trq_rpm,mpg_c,mpg_h)
  ) %>%
  tab_header("gtcars dataset")
```
<sup>Created on 2020-01-15 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

![image](https://user-images.githubusercontent.com/3580210/72492769-6d131c80-37ec-11ea-8b66-a509fba186cd.png)

Note above that the distinction between where "Car Model" and "Performance" starts/ends is more of an interpretation of the center of both titles, and less the gap width between the tab spanners.

**Comment by rich-iannone** [comment]
Sorry for the late response on this but I totally agree with all the points you made! I'm not really satisfied with the small gap between the horizontal spanner lines, the method with which it is produced, and the lack of customizability. Once I circle back to column label formatting enhancements, I'll be sure to get these feature requests implemented. Thanks!
