### ISSUE TITLE
grand_summary_rows errors on all NA columns

### ISSUE THREAD

**Issue by smingerson** [rstudio/gt#471]
latest from github (GithubSHA1: 883df9ad23e49e7e7ede9ea3cce91940fc59f189)  

My use case is an empty table showing what information will be displayed. The end user will enter info in a Shiny app and then the table will update. My workaround will be to populate the table with 0s. Edit: this also happens with 0. The error happened in the print method, when it is applying the functions to the columns.

```r
library(gt)
grand_summary_rows(gt(data.frame(a = c(1,2), b = NA_real_)), columns = vars(b),
                   fns = list(max = ~max(.)))
#> Error: Column `b` must be length 1 (the number of rows), not 0
```
Created on 2020-01-17 by the reprex package (v0.3.0)

**Comment by rich-iannone** [comment]
Thanks for reporting this and sorry for waiting until now to respond. I'm able to reproduce the error in my environment and I do believe this requires fixing.

**Comment by jkgrain** [comment]
I am running into the same issue.  The following reprex might help trace the problem.  I think it has to do with the mean of a vector that is all NA returns NaN even with na.rm=TRUE.
`
library(dplyr)
library(gt)

x <- c(1:6)
y <- c(6:2, NA)
z <- rep(NA, 6)

df <- tibble(x,y,z)

df <- mutate_if(df, is.logical, as.numeric)

df %>%
  gt() %>%
  grand_summary_rows(
    columns = c(1:3),
    fns = list(
      Avg = ~ mean(., na.rm = T)
    )
  ) 

mean(df$x, na.rm = TRUE)
mean(df$y, na.rm = TRUE)
mean(df$z, na.rm = TRUE)
`

**Comment by jkgrain** [comment]
I was able to trap for the problematic column with this variation on the code:

```
library(dplyr)
library(gt)

x <- c(1:6)
y <- c(6:2, NA)
z <- rep(NA, 6)

df <- tibble(x,y,z)

df %>%
  gt() %>%
  grand_summary_rows(
    columns = c(1:3),
    fns = list(
      Avg = ~ mean(., na.rm = T)
    )
  ) 

df %>%
  gt() %>%
  grand_summary_rows(
    columns = which(sapply(df, class) != "logical"),
    fns = list(
      Avg = ~ mean(., na.rm = T)
    )
  ) 
```
