### ISSUE TITLE
tab_style fails to target all cell_summary rows

### ISSUE THREAD

**Issue by steveputman** [rstudio/gt#472]
Applying `tab_style` to `cells_summary` can result in erratic behavior (in my case, styling some but not all of the summary rows). It seems to pop up more often when there are more groups, but there is some pattern that is eluding me: with 1 row and 1 group, it happens every time. With 2 rows and 1 group, it seems never to happen. With 2 rows and 2 groups, it happens to the first group (if the rows are members of different groups) every time. But 1-row groups don't seem to be the issue--in my use case, all groups have 2 members: summary rows for the first 7 groups style as expected, and the remainder of the summary rows are unformatted (in my case, there are 6 more groups). Easiest example (1 row and 1 group) shown in reprex.

``` r
library(tidyverse)
library(gt)
library(babynames)

numrows <- 1
numgroups <- 1

df <- tibble::tibble(
  name = sample(babynames$name, numrows), 
  value = runif(numrows, 50000, 2000000), 
  group = sample(letters[1:numgroups], numrows, replace = TRUE)
) 

gttbl <- df %>%
  group_by(group) %>%
  arrange(group) %>%
  gt(rowname_col = "name") %>%
  summary_rows(groups = TRUE, columns = vars(value), fns = list("sum")) %>%
  tab_style(style = list(cell_text(style = "italic")),
            locations = cells_summary())

gttbl
```

<div id="gyrclcmsvl" style="overflow-x:auto;overflow-y:auto;width:auto;height:auto;">

<table class="gt_table">

<thead class="gt_col_headings">

<tr>

<th class="gt_col_heading gt_columns_bottom_border gt_left" rowspan="1" colspan="1">

</th>

<th class="gt_col_heading gt_columns_bottom_border gt_right" rowspan="1" colspan="1">

value

</th>

</tr>

</thead>

<tbody class="gt_table_body">

<tr class="gt_group_heading_row">

<td colspan="2" class="gt_group_heading">

a

</td>

</tr>

<tr>

<td class="gt_row gt_left gt_stub">

Elijaha

</td>

<td class="gt_row gt_right">

1865195

</td>

</tr>

<tr>

<td class="gt_row gt_stub gt_right gt_summary_row gt_first_summary_row">

sum

</td>

<td class="gt_row gt_right gt_summary_row gt_first_summary_row">

1,865,194.99

</td>

</tr>

</tbody>

</table>

</div>

<sup>Created on 2020-01-21 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by rich-iannone** [comment]
Thanks for this detailed look. I was able to reproduce all of the scenarios you outlined. This definitely requires a fix.

**Comment by j-krogh** [comment]
I have also had this issue and a similar one when trying to apply text transforms to cells that have been grouped. I suspect the underlying issue is the same.

**Comment by rich-iannone** [comment]
Testing this again, it seems to work now that https://github.com/rstudio/gt/pull/782 has been merged.
