### ISSUE TITLE
rtf example from the repo throws error

### ISSUE THREAD

**Issue by MadhulikaTanuboddi** [rstudio/gt#477]
Run the https://github.com/rstudio/gt/tree/master/tests/gt-examples/04-rtf example

Throws the following error

`Error in if (headings[i] == spanners[i]) { : 
  missing value where TRUE/FALSE needed`

**Comment by rich-iannone** [comment]
These should all work now since https://github.com/rstudio/gt/pull/638 fixes RTF.
