### ISSUE TITLE
Bold cells dont get equally "knitted" in HTML or PDF

### ISSUE THREAD

**Issue by oranwutang** [rstudio/gt#478]
Hi,

If you run:

```{r}
head(trial) %>% 
  gt::gt() %>% 
  gt::tab_style(style = gt::cell_text(weight = 'bold'), locations = gt::cells_body(columns = gt::vars(trt)))
```

In HTML cells in the first column are correctly formatted as **bold**:
![htmlTable2](https://user-images.githubusercontent.com/6965617/72938646-a6f39e00-3d6b-11ea-8a93-4b0edb75a845.png)

...but if you knit to pdf it doesn't:
![pdfTable2](https://user-images.githubusercontent.com/6965617/72938673-ad821580-3d6b-11ea-8553-c89010c69640.png)

Is there a reason for that? gt correctly manages bold formatting in columns headers, tho...

Thanks in advance!

**Comment by Ljupch0** [comment]
I am experiencing the same issue. It seems that gt is currently optimized only for HTML.

**Comment by rich-iannone** [comment]
This is because there is not yet a way to add styling to LaTeX table cells. That will happen in a future release.
