### ISSUE TITLE
feature request: themes for tables

### ISSUE THREAD

**Issue by scotbader8858** [rstudio/gt#485]
Love this package A LOT. Really helpful and I appreciate the work.... I mostly use HTML output tables and I'm really satisfied with the way they present. Something that would, I feel, be really wonderful is having the ability to choose table themes.

I know we can color cells but it would be nicer to have a collection of color themes available to choose from. Is this something that you're thinking of putting into the package?

THANKS!

**Comment by rich-iannone** [comment]
Glad you're finding the package to be useful! Yes, this has been asked for multiple times and there has been some work in this direction. If you want to try it out, there are functions for 'presets' in this branch: https://github.com/rstudio/gt/tree/table-presets. Let me know if you try it out and what you think of all this.

**Comment by jenniferp96** [comment]
I would just like to say that I would love to have table themes available. A little color is important in life (and in gt tables too!). Oh, I really just love this package.

**Comment by rich-iannone** [comment]
This has been done! It’s in this merged PR: https://github.com/rstudio/gt/pull/987
