### ISSUE TITLE
cols_width removes last column when table has rownames

### ISSUE THREAD

**Issue by csoderberg** [rstudio/gt#493]
I really like the package, thanks for developing it! I'm trying to set the width of columns in a table with `col_widths`, but when the table has one column specificied as `rowname_col`, the last column in the table isn't shown. 

**works as expected**
```r
iris %>% 
  gt() %>% 
  cols_width(
    vars(Sepal.Width) ~ px(120),
    vars(Petal.Length) ~ px(120),
    vars(Petal.Width) ~ px(120),
    vars(Species) ~ px(120),
    everything() ~ px(250))
```
![Screenshot 2020-02-19 16 39 14](https://user-images.githubusercontent.com/7332030/74879057-61100280-5336-11ea-8a31-1281db6311bc.png)

**Species column is removed when `Sepal.Length` made into rownames**
```r
iris %>% 
  gt(rowname_col = 'Sepal.Length') %>% 
  cols_width(
    vars(Sepal.Width) ~ px(120),
    vars(Petal.Length) ~ px(120),
    vars(Petal.Width) ~ px(120),
    vars(Species) ~ px(120),
    everything() ~ px(250))
```
![Screenshot 2020-02-19 16 37 56](https://user-images.githubusercontent.com/7332030/74879018-4b024200-5336-11ea-98c9-2aa332bc033e.png)

**Comment by rich-iannone** [comment]
Thanks so much for reporting this. This will get fixed soon!
