### ISSUE TITLE
as_raw_html(inline_css = TRUE) takes a long amount of time for a large table

### ISSUE THREAD

**Issue by ben-laufer** [rstudio/gt#501]
I've noticed that when processing a large table (a few thousands rows and several columns) that the `as_raw_html()` function takes a couple of hours when `(inline_css = TRUE)` but only a minute or two when `inline_css = FALSE`.  I'd like to keep `(inline_css = TRUE)` since that produces a nicer table. However, since I'm using this for a program that requires high resources on our cluster, I'd like to speed up this step as much as possible. As an alternative solution, since we have a lot of resources available for our program that calls to `gt`, is there a way to parallelize the process?  Also, sorry I don't have a reprex to share.

**Comment by rich-iannone** [comment]
There is currently a performance bottleneck in the way we do CSS inlining. This is something we want and need to address soon. Thanks for being patient for the time being.

**Comment by rich-iannone** [comment]
There's no longer a need to use `inline_css = TRUE` with `as_raw_html()` just to preserve styles. With `FALSE` all of the styles now are present in the output (plus it's faster since no inlining is required).
