### ISSUE TITLE
tab_spanner and cols_move_* functions does not work well together

### ISSUE THREAD

**Issue by MadhulikaTanuboddi** [rstudio/gt#506]
I have noticed the following 2 cases: When we use `cols_mov` function with `tab_spanner`, the resulting gt table does not display the spanners and columns as we expect. Specifically, if you try to move a column from a tab_spanner_1 (for ex: group_a) to the **start/end/after** a column that belongs to a tab_spanner_2 (for ex: group_b), it results in an unorganized table

##Case 1: When `cols_move` function moves a column from "spanner-A" after a column from "spanner-B"

Example 1:
```r
library(gt)
mtcars_tbl <-
  gt(mtcars) %>%
  tab_header(
    title = md("The **mtcars** dataset"),
  ) %>%
  tab_spanner(
    label = md("*group_a*"),
    columns = vars(mpg, cyl, disp, hp)
  ) %>%
  tab_spanner(
    label = md("*group_b*"),
    columns = vars(drat, wt, qsec, vs, am, gear, carb)
  ) %>%
  cols_move_to_start(columns = vars(hp)) %>%
  cols_move_to_end(columns = vars(am, gear)) %>%
  #Note that in below cols_mov, we are moving group_a column label after group_b column label
  cols_move(
    columns = vars(mpg), #group_a column
    after = vars(gear))  #group_b column

mtcars_tbl
```
![Example_1_group_b_moved_after_group_a](https://user-images.githubusercontent.com/5369655/77098898-55186e80-69d0-11ea-8871-07ef531b0512.png)

Example 2:
```r
library(gt)
mtcars_tbl <-
  gt(mtcars) %>%
  tab_header(
    title = md("The **mtcars** dataset"),
  ) %>%
  tab_spanner(
    label = md("*group_a*"),
    columns = vars(mpg, cyl, disp, hp)
  ) %>%
  tab_spanner(
    label = md("*group_b*"),
    columns = vars(drat, wt, qsec, vs, am, gear, carb)
  ) %>%
  cols_move_to_start(columns = vars(hp)) %>%
  cols_move_to_end(columns = vars(am, gear)) %>%
  # #Note that in below cols_mov, we are moving group_b column label after group_a column label
  cols_move(
    columns = vars(gear), #group_b column
    after = vars(hp))  #group_a column

mtcars_tbl
```

![Example 2_tab_spanner_cols_mov](https://user-images.githubusercontent.com/5369655/77098736-0f5ba600-69d0-11ea-81ee-8670b98006af.png)

##Case 2: When `cols_move_to_start` and `cols_move_to_end` used with `tab_spanner` , columns are not placed under the respective/correct spanners
```r
library(gt)
mtcars_tbl <-
  gt(mtcars) %>%
  # cols_align(
  #   align = "right",
  #   columns = vars(disp, vs)
  # ) %>%
  tab_spanner(
    label = md("*group_a*"),
    columns = vars(mpg, cyl)
  ) %>%
  tab_spanner(
    label = md("*group_b*"),
    columns = vars(drat, wt, qsec, vs, am, gear, carb)
  ) %>%
  tab_spanner(
    label = md("*group_c*"),
    columns = vars(disp, hp)
  ) %>%
  cols_move_to_end(columns = vars(hp)) %>%
  cols_move_to_start(columns = vars(am, gear)) %>%
  tab_header(
    title = md("The **mtcars** dataset"),
  )
 mtcars_tbl
```
![Case_2_cols_move_to_start_end_results_in_unexpected_table](https://user-images.githubusercontent.com/5369655/77100404-cce79880-69d2-11ea-8bfa-0a62829ac145.png)

**Comment by jcheng5** [comment]
Conceptually, what happens first? Moving or spanning?

**Comment by rich-iannone** [comment]
Moving is first. That happens in the `build_data()` function.

**Comment by jcheng5** [comment]
In effect then, these examples are explicitly asking for discontiguous columns to be spanned? We want to allow that? (Not rhetorical, sincerely asking.)

**Comment by jcheng5** [comment]
And if we do want to allow that--does it mean those columns are gathered together (i.e. moved again), or is it the spanner that splits?

**Comment by rich-iannone** [comment]
I believe we do want to allow it. We already have the option to gather columns. Using `cols_move()` or the other moving functions would precipitate a forced splitting (even if `gather = TRUE` for the `tab_spanner()` call).

**Comment by jcheng5** [comment]
We wouldn't just gather them despite the move?

**Comment by rich-iannone** [comment]
Currently, a use of `cols_move()` takes precedence over the gathering by `tab_spanner()`. Whether that's right design choice is a bit up for debate. I think it makes some sense as we may want to selectively move some of the columns that may have been gathered up under a spanner.

**Comment by rich-iannone** [comment]
But I think it has to be communicated that `cols_move()` or similar are doing this type of column movement override.

**Comment by jcheng5** [comment]
It strikes me as a bit weird that we allow discontiguous spanners at all. If anything, it feels to me like if you want discontiguous spanners with the same label, you should have to make a separate `tab_spanner` call for each segment. Am I missing something? Is this an important scenario?

If not, it seems like it'd be simpler to perform `col_move` first, then have `tab_spanner` gather no matter what.

**Comment by rich-iannone** [comment]
We should perhaps talk about this tomorrow because I do have examples where you need to have repeating, discontiguous spanners (and it's a table format that's widely in use). I have the code for it as well (works better with the fix, btw).

**Comment by katossky** [comment]
Not sur whether here is the best place to comment but I run into a similar problem, let me know if I should open a new issue.

```
iris |> gt() |> cols_move_to_start(columns = ends_with("Width")) |> tab_spanner_delim(".", rev=T)
```

... seems to mix everything up : 

![image](https://github.com/rstudio/gt/assets/13658517/b346906f-4a27-42f9-927f-daa6cf1de0fb)

Doing things in the converse order (less intuitive to me) preserves the correct pairing, but does not merge the spanners :

```
iris |> head() |> gt() |> tab_spanner_delim(".", rev=T) |> cols_move_to_start(columns = ends_with("Width"))
```

![image](https://github.com/rstudio/gt/assets/13658517/e3c860c8-4ebc-4d6d-97fc-81c9aba3984c)
