### ISSUE TITLE
Merging multiple bodies request

### ISSUE THREAD

**Issue by kylebutts** [rstudio/gt#509]
Hi! I was thinking that a lot of the tables that I want to make involve multiple bodies that are appended together. What I'm referring to as the "body" of a table is Table body + Stub stuff + Column Labels:
![image](https://user-images.githubusercontent.com/19961439/77251100-c4859c80-6c22-11ea-9ee0-ce28ed9b56c4.png)

It would be nice to be able to create 2 bodies and append them (perhaps with stub heads labeling them Panel A, Panel B) into a gt object with the title header and footer.

Is this easily implementable currently?

**Comment by rich-iannone** [comment]
This is a very good idea. I also like the idea of appending horizontally as well (i.e., more columns).
