### ISSUE TITLE
Troubleshooting local_image()

### ISSUE THREAD

**Issue by Worville** [rstudio/gt#510]
Hi,

I'm trying to use the local_image() helper to enter a .png file into a table.

If I try and create the path to the local image in my dataframe, then point local_image() to that path, I get an error of 

```"Error in file(con, "rb") : invalid 'description' argument"```

Here's a minimum working (well, failing) example:

```
data <- data.frame(team_id = c(1, 22, 1),
                   stat = c(3, 4, 5)) %>% 
  mutate(logo_loc = str_glue('/path/to/image/{team_id}_logo.png'))

data %>% 
  gt() %>% 
  text_transform(
    locations = cells_body(columns = "logo_loc"), 
    fn = function(x) {local_image(filename =  as.character(x), height = 120)})
```

Any thoughts or advice?

Thanks a lot in advance.

**Comment by primaj** [comment]
I posted a pull request which should fix this! 

Here's a workaround:

`tibble(img_path = rep(test_image(), 5)) %>% 
  gt() %>%
  text_transform(
    locations = cells_body(columns = vars(img_path)),
    fn = function(x) map_chr(x, ~local_image(filename = .x, height=50))
  )`

**Comment by rich-iannone** [comment]
Now fixed in https://github.com/rstudio/gt/pull/803. Sorry @primaj for not accepting your PR, it turns out we had to do a lot of extra work on top of the fix.
