### ISSUE TITLE
Add custom bar and histogram graphics (using ggplot) to table cells

### ISSUE THREAD

**Issue by bronsonpetersa** [rstudio/gt#515]
Hello. Love this package. Thanks for making it Rich! I have a feature request: make it possible to include some bar lines or histograms in table cells. The input data could be in a list column (and I guess it replaces that column, for the rows specified). I could imagine that some data might also come from other columns too.

I suppose ggplot would be the best way to make these plots? If so, can you make a separate function that wraps some common plot types and makes the labels look okay in a table? Sorry, I don't have a good idea in how to implement it but simple wrapper functions might be the best way.

**Comment by rich-iannone** [comment]
This is probably the right approach. I definitely agree that visual elements like these are lacking and not at all easy to place into the table at the current time. Thanks for your suggestions and perspectives here. This is quite valuable input for me!
