### ISSUE TITLE
Need to be able to freeze gt version in install

### ISSUE THREAD

**Issue by bkkkk** [rstudio/gt#523]
Hey, love gt, however we had some issues in our deployments yesterday due to moving from rlang 0.4.5 to 0.3.0.

The deploy was fixed I just wonder if you are planning on creating versioned tags from now so we can freeze the `gt` version in our builds.

Thank you!

**Comment by rich-iannone** [comment]
Now that gt is released to CRAN we now have tagged releases and finally the distinction between a release version and an in-development version. Sorry for the rough ride previously :( but things will be more standardized from now on.

**Comment by bkkkk** [comment]
Just after I posted this I saw that this was published on CRAN. Congratulations!
