### ISSUE TITLE
github_document incompatible?

### ISSUE THREAD

**Issue by msevi** [rstudio/gt#532]
Hello, 
Cool package! 
I was able to reproduce the pizzaplace example code on a html_document markdown, but not on a github_document markdown.

**Comment by rjpat** [comment]
What error are you getting? I did get an error 1033 trying to replicate but after updating my pandoc installation it was resolved

**Comment by msevi** [comment]
I don't get an error. The rendering just looks different.

github_document:
![image](https://user-images.githubusercontent.com/41703347/78894753-a8b03200-7a3b-11ea-87e9-eef0f0e9088e.png)

html_document:
![image](https://user-images.githubusercontent.com/41703347/78894778-b796e480-7a3b-11ea-867c-bf0b89da7850.png)
