### ISSUE TITLE
Suggestion for Latex Output

### ISSUE THREAD

**Issue by shivaway** [rstudio/gt#533]
This for the future Latex  enhanced version.

Please include a raw output for already formatted Latex.  As an engineer I need to generally show the units of a variable.  I generally use the units package and have create a deparseing routine to convert into true latex expressions for tables.  For example

2 gallon/min (as using the units package) would deparse to the following Latex string 
2\frac{gallon}{min}.  I would like to be able to pass this string to any part of the table (as units are everywhere) without reparsing the string.

However, I would also love to not have to worry about parsing if something were written within the latex portion of the code for the most part.  I guess an option to deal with it would be great. This is similar to xtable using the sanitization.text.function to clean up latex.

**Comment by rich-iannone** [comment]
There are now special functions for dealing with measurement units (in the dev version of the package). It works across different table output formats too.
