### ISSUE TITLE
Is it possible to generate PDF document based on 'gt' data processing?

### ISSUE THREAD

**Issue by andirey** [rstudio/gt#534]
It will cool to have the ability to generate PDF documents like using RMarkdown format.
Thanks
Andrii

**Comment by runyoncr** [comment]
Yeah, this would be great. I tried to use gt() in a pdf I was making and got the error of "! LaTeX Error: There's no line here to end."

**Comment by rich-iannone** [comment]
PDF/LaTeX table generation has been fixed up recently (in the dev version of the package). Now, we shouldn't get that error.
