### ISSUE TITLE
Format stub label text, particularly for groups (e.g., allow targeting with fmt_markdown())

### ISSUE THREAD

**Issue by LukasWallrich** [rstudio/gt#538]
It would be great if the text in the stub could be formatted with Markdown, as fmt_markdown() can do elsewhere in the table and md() in the column labels. (Or is that already somehow possible and I am overlooking it.)

**Comment by steveputman** [comment]
You may want to see if the fix implemented in response to #99 addresses your issue.

**Comment by LukasWallrich** [comment]
Thanks, but as I understand it, that does not address formatting the stub text itself?

**Comment by steveputman** [comment]
Does something like this work? (The table doesn't render properly in the reprex, so I've just included it as an image)

``` r
library(tidyverse)
library(gt)

exibble %>%
  group_by(group) %>%
  gt() %>%
  tab_style(
    style = list(cell_text(weight = "bold")),
    locations = cells_row_groups()
  )
```

![Rplot](https://user-images.githubusercontent.com/4965916/79076487-21bfbb80-7cc0-11ea-8524-29d8199cf8d9.png)

**Comment by LukasWallrich** [comment]
Wonderful, thank you! I was stuck looking for something related to stub in the documentation, so did not find `cells_row_groups()`.
