### ISSUE TITLE
Different rendering behaviour in Microsoft Outlook and mobile Email App

### ISSUE THREAD

**Issue by leungi** [rstudio/gt#540]
As per subject; screenshots attached.

#### Mobile (as expected)
![mobile-email](https://user-images.githubusercontent.com/30273868/79021091-42610780-7b40-11ea-8ed0-a0e75254ae57.JPG)

#### Microsoft Outlook (style stripped)
![outlook-email](https://user-images.githubusercontent.com/30273868/79021128-602e6c80-7b40-11ea-90e8-565f6ed34a8a.JPG)

#### Reprex
``` r
library(gt)
#> Warning: package 'gt' was built under R version 3.6.3
library(dplyr)
#> Warning: package 'dplyr' was built under R version 3.6.3
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union

df <- tibble(`Non Risky` = c(9, 12, 21), `Risky` = c(1, 0, 1)) %>%
  mutate(
    Total = `Non Risky` + Risky,
    `At Risk Percentage` = Risky / Total
  )

df %>%
  gt() %>%
  tab_style(
    style = cell_text(
      color = "white"
    ),
    locations = cells_column_labels(
      columns = everything()
    )
  ) %>%
  tab_options(
    row.striping.include_table_body = FALSE,
    column_labels.font.weight = "bold",
    column_labels.background.color = "black"
  ) %>%
  fmt_percent(vars(`At Risk Percentage`), decimals = 1) %>%
  data_color(
    columns = vars(Risky),
    colors = scales::col_bin(
      c("red", "green"),
      bins = 2,
      domain = c(0, 100)
    ),
    alpha = 0.8
  )
```

#### Package version
```r
> packageVersion("gt")
[1] ‘0.2.0.5’
```

<sup>Created on 2020-04-10 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by rich-iannone** [comment]
Try using the `as_raw_html()` function at the end of the `gt()` call before embedding the table into the email message body. The reason that works is because email clients will sometimes strip out CSS rules but if the CSS styles are inlined into the HTML tags, then you'll see tables with all formatting preserved in pretty much all email clients.

You could also expand your reprex a bit to show us how you're generating the email message.

**Comment by leungi** [comment]
@rich-iannone : thanks for prompt reply.

I did try the `as_raw_html()` as well, and the result was slightly better - header column retains CSS styling, but body still got stripped (refer to below).

![image](https://user-images.githubusercontent.com/30273868/79479142-f1cf2b80-7fd1-11ea-82ac-7f1eeadf5079.png)

Email is generated via [mailR](https://github.com/rpremraj/mailR), as follow:

```r
library(mailR)

from <- "from@gmail.com"
to <- "to@gmail.com"
subject <- "Test"

body <- glue::glue("{gt_tbl_as_html}")

send.mail(
    from = from,
    to = to,
    subject = subject,
    body = body,
    encoding = "utf-8",
    smtp =
      list(host.name = <host_name>, port = 25, ssl = FALSE),
    authenticate = FALSE,
    send = TRUE,
    html = TRUE,
    inline = TRUE
  )
```
