### ISSUE TITLE
Including gt in rmarkdown PDF

### ISSUE THREAD

**Issue by bradrg** [rstudio/gt#541]
Is it possible to include a gt object in an rmarkdown document that knits to a PDF?  I get the following error when including the gt code by itself or using as_latex().  What's the proper way to do this?

! LaTeX Error: There's no line here to end.

**Comment by fcadete** [comment]
I'm having the same issue. Any suggestions?

**Comment by rich-iannone** [comment]
Should now be fixed in the development version of the package.
