### ISSUE TITLE
Line breaks in cells need additional CSS in `gt_table` style to display correctly for HTML output

### ISSUE THREAD

**Issue by archerdan** [rstudio/gt#547]
Hello! Another line break issue which I can't seem to find an answer for.

When including \n to break a line within cells these do not accurately display within an html table.

To correctly display line breaks the addition to the table style of: white-space:pre resolves this issue. This could be an optional flag in the gt() function if you didn't think it should be included permanently.

Thanks in advance.

example:

`gtcars %>%
  mutate(hp(rpm) = paste0(hp, "\n", "(", hp_rpm, ")")) %>%
  select(mfr, model, hp(rpm)) %>%
  gt(groupname_col = "mfr")`

produces this table with no line breaks
![egz](https://user-images.githubusercontent.com/54158784/79410957-c65e3800-7ff5-11ea-8e99-4b98507e4580.PNG)

by including white-space:pre in the gt_table css style
![eg2](https://user-images.githubusercontent.com/54158784/79410986-da099e80-7ff5-11ea-81ea-8677e17d5aa0.PNG)

we can now display line breaks correctly
![eg3](https://user-images.githubusercontent.com/54158784/79411011-e7268d80-7ff5-11ea-91ca-27832cf95f27.PNG)

**Comment by rich-iannone** [comment]
Thanks for reporting this (with a potential solution as well).

**Comment by rossellhayes** [comment]
As an intermediate solution, you can get line breaks by including "`<br />`" in a column formatted with `fmt_markdown()`.

**Comment by rich-iannone** [comment]
There’s now a white space option in `cell_text()` where you can set 'pre'.
