### ISSUE TITLE
Typical table 1 in medical science

### ISSUE THREAD

**Issue by zachariae** [rstudio/gt#552]
Thank you for your great efforts to develop a package that provides a general grammer for tables.
I am always looking for new packages to make reproducable "print-ready" tables. Unfortenately most previous attempts do not really fit my needs. In the medical sciences, the typical table 1 (patient characteristics) has one important feature. Here, most of the times, patient groups are in columns and the variables are in the rows (kind of transposed wide format). Moreover, mostly, one cell contains different aggregated information such mean +- standard deviation, counts with percentage in brackets, or median with interquartile range in brackets.
So I would like to have package to build my tables row by row with optional grouping and optional concatination of statistical results. 
Something like the table "Tech giants invade each other's turf". But in google picture search (table 1 patient characteristics) you can find many other examples.
I am not sure, how I would do this with the gt package.

**Comment by 11rchitwood** [comment]
Hello @zachariae! 👋 Have you seen the [gtsummary package](https://github.com/ddsjoberg/gtsummary)? It's built on top of gt and looks just like what you need.

**Comment by zachariae** [comment]
Hello @11rchitwood  ! Thank you very much for the hint. Indeed, I haven't seen this packages before. I will take a closer look at it now. I really seems to do what I was looking for.
