### ISSUE TITLE
Summary rows shouldn't require that the table be presorted by the group variable

### ISSUE THREAD

**Issue by NathanSkene** [rstudio/gt#553]
I attach a data frame. If I run the following code on it, then the summary row is calculated wrong.

```
data = gt(data = costs2 %>% mutate(COSTS=as.numeric(COSTS)), rowname_col = "REF", groupname_col = "LAB" ) %>%
  summary_rows(
    groups = TRUE,
    columns = vars(COSTS),
    fns = list(total = ~sum(., na.rm = TRUE)))
```

If I resort the data as follows then it calculates correctly.

data = gt(data = costs2 %>% mutate(COSTS=as.numeric(COSTS)) %>% dplyr::arrange(LAB), rowname_col = "REF", groupname_col = "LAB" ) %>%
  summary_rows(
    groups = TRUE,
    columns = vars(COSTS),
    fns = list(total = ~sum(., na.rm = TRUE)))
```

This is not very user friendly, expecting people to know to do this. I really recommend changing this, I nearly ditched using the package because of it.

Nice work otherwise!

[costs2.rda.zip](https://github.com/rstudio/gt/files/4497209/costs2.rda.zip)

**Comment by rich-iannone** [comment]
This seems pretty serious and I'd like to explore this a bit more but I can't reproduce the example since I don't have the `costs2` object. Could you provide a minimal, reproducible example? Thanks!

**Comment by steveputman** [comment]
@rich-iannone This is the same issue as #470, and there's a reprex there.

**Comment by rich-iannone** [comment]
@steveputman Thanks! Looking into this now.
