### ISSUE TITLE
we need gtedit

### ISSUE THREAD

**Issue by ramiromagno** [rstudio/gt#555]
There's [ggedit](https://github.com/metrumresearchgroup/ggedit) for ggplot2.

We need something similar for gt. :smirk: let us call it gtedit...

**Comment by rich-iannone** [comment]
I have to agree but it's still a bit too early to make something like this; gt, far along as it is, still has *a lot* of work ahead before the API really stabilizes. Until there are ways to control more of the underlying mechanism, I think that creation of a frontend might not be worth it.

**Comment by ramiromagno** [comment]
Fair enough. :)
