### ISSUE TITLE
Could fmt_percent() have a 'scale_by' argument?

### ISSUE THREAD

**Issue by jdjohn215** [rstudio/gt#559]
I commonly use tables where the percent values are already percents, not proportions. Could we add a `scale_by` argument like the one that already exists in `gt::fmt_number()`?

This would also match the `scale` argument commonly used in ggplot2 legend labels using `scales::percent_format()`.

Thanks for considering!

**Comment by rich-iannone** [comment]
Thanks for the suggestion! Totally agree, and this was a bit of an oversight when designing the function.
