### ISSUE TITLE
Decimal mark alignment

### ISSUE THREAD

**Issue by rich-iannone** [rstudio/gt#560]
Perform alignment on decimal marks in all number-based `fmt_*()` functions. This adds the option `dec_mark_align`, which either takes `TRUE` or `FALSE` (the default).

Originally suggested by @drolejoel in https://github.com/rstudio/gt/issues/535, but moved to this issue since there were multiple requests in that issue.

**Comment by meghannash8** [comment]
Rich, this is a hugely important feature for me and I'm positive others would love to see it become a reality. I'm really excited to see this getting some consideration. IMO this feature would elevate this package to the stratosphere (it's already my favorite package, but still)...

**Comment by jthomasmock** [comment]
Rich - I imagine you could adapt code from `pillar` and their existing robust approach to `tibble` printing. 

``` r
pillar::pillar(c(1.2345, 12.345, 123.45, 1234.5, 12345))
#> <pillar>
#>    <dbl>
#>     1.23
#>    12.3 
#>   123.  
#>  1234.  
#> 12345
```

<sup>Created on 2021-08-30 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

Note that for now, you _can_ use base R + `gt` solution albeit I haven't tested it against edge-cases:

``` r
library(gt)

pad_fn <- function(x, nsmall = 2){
  
  # round and format values as text with specific number of decimals
  round_x <- round(x, digits = nsmall)
  fmt_x <- format(round_x, nsmall = nsmall)
  
  # calc number of trailing zeros
  nbsp_len <- nchar(fmt_x) - nchar(sub("0*$", "", fmt_x))
  
  # create string of non-breaking spaces
  rep_nbsp <- strrep("&nbsp", nbsp_len)
  
  # remove trailing zeros by position
  fmt_out <- substr(fmt_x, 1, nchar(fmt_x) - nbsp_len) 
  
  # add the non-breaking spaces to the formatted values
  filled_out <- paste0(fmt_out, rep_nbsp)
  
  filled_out
  
}

basic_table <- data.frame(x = c(1.2345, 12.345, 123.45, 1234.5, 12345)) %>% 
  gt() %>% 
  fmt(
    fns = function(x){pad_fn(x, nsmall = 4)}
  )

basic_table %>% 
  # default font doesn't respect nbsp as mono-width
  gtsave("table-default-font.png")
```

![](https://i.imgur.com/6KSqiVv.png)

``` r
basic_table %>%
  tab_style(
    # MUST USE A MONO-SPACED FONT
    style = cell_text(font = google_font("Fira Mono")),
    locations = cells_body(columns = x)
  ) %>% 
  gtsave("table-monospace.png")
```

![](https://i.imgur.com/W9Ntz75.png)

<sup>Created on 2021-08-30 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

**Comment by rich-iannone** [comment]
If you replace `"&nbsp;"` with `"\U02007"` (the figure space, see https://en.wikipedia.org/wiki/Whitespace_character) both examples work equally well. There will be edge cases but I think with enough work and testing, decimal alignment could arrive soon to gt. Previously, the biggest blocker was the possible intrusion of footnote marks but those have been made to be set (by default) on the *left* side of numeric figures.
