### ISSUE TITLE
Retain data attributes in `gt()`?

### ISSUE THREAD

**Issue by LukasWallrich** [rstudio/gt#573]
Would it be possible to retain the attributes of the data in the return of gt()? That way, one could create a table with footnotes etc from one data object in one pipe. 

Tracing the gt() function with two extra lines 
` attribs <- attributes(data)` at the start and `attributes(data)$original <- attribs` at the end
allows me to run the following, which I find very helpful:

```
my_fun(x) %>% gt::gt() %>%
  gt::tab_header(attributes(.)$original$title) %>% gt::tab_footnote(footnote = attributes(.)$original$footnote, location = gt::cells_column_labels("indirect"))
```

**Comment by rich-iannone** [comment]
Great idea! I think this should become possible in the future.

**Comment by rich-iannone** [comment]
We now have the `extract_body()` function which should be helpful for your use case.
