### ISSUE TITLE
`cells_column_labels()` and `cells_column_spanners()` should default to selecting all

### ISSUE THREAD

**Issue by kendonB** [rstudio/gt#580]
``` r
library(tidyverse)
library(gt)
# Fails as nothing is passed to the cells_ functions
iris %>%
  slice(1) %>% 
  gt() %>% 
  tab_spanner(label = c("Sepal"),
              columns = matches("Sepal")) %>% 
  tab_spanner(label = c("Petal"),
              columns = matches("Petal")) %>% 
  tab_style(style = cell_text(color = "black", font = "Arial"),
            locations = list(cells_column_labels(),
                             cells_column_spanners()))
#> Error in rlang::eval_tidy(expr = var_expr, data = data_tbl, env = emptyenv()): object '' not found

iris %>%
  slice(1) %>% 
  gt() %>% 
  tab_spanner(label = c("Sepal"),
              columns = matches("Sepal")) %>% 
  tab_spanner(label = c("Petal"),
              columns = matches("Petal")) %>% 
  tab_style(style = cell_text(color = "black", font = "Arial"),
            locations = list(cells_column_labels(everything()),
                             cells_column_spanners(everything())))
```

<div id="hepisktxbf" style="overflow-x:auto;overflow-y:auto;width:auto;height:auto;">

<table class="gt_table">

<thead class="gt_col_headings">

<tr>

<th class="gt_center gt_columns_top_border gt_column_spanner_outer" rowspan="1" colspan="2" style="color: black; font-family: Arial;">

<span class="gt_column_spanner">Sepal</span>

</th>

<th class="gt_center gt_columns_top_border gt_column_spanner_outer" rowspan="1" colspan="2" style="color: black; font-family: Arial;">

<span class="gt_column_spanner">Petal</span>

</th>

<th class="gt_col_heading gt_center gt_columns_bottom_border" rowspan="2" colspan="1" style="color: black; font-family: Arial;">

Species

</th>

</tr>

<tr>

<th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1" style="color: black; font-family: Arial;">

Sepal.Length

</th>

<th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1" style="color: black; font-family: Arial;">

Sepal.Width

</th>

<th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1" style="color: black; font-family: Arial;">

Petal.Length

</th>

<th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1" style="color: black; font-family: Arial;">

Petal.Width

</th>

</tr>

</thead>

<tbody class="gt_table_body">

<tr>

<td class="gt_row gt_right">

5.1

</td>

<td class="gt_row gt_right">

3.5

</td>

<td class="gt_row gt_right">

1.4

</td>

<td class="gt_row gt_right">

0.2

</td>

<td class="gt_row gt_center">

setosa

</td>

</tr>

</tbody>

</table>

</div>

<sup>Created on 2020-05-11 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by rich-iannone** [comment]
Not sure when the change occurred but now these functions have `everything()` for the default option.
