### ISSUE TITLE
explicit groups seem to be required for `cells_summary` when summarizing a full table (i.e. a single group)

### ISSUE THREAD

**Issue by kendonB** [rstudio/gt#581]
I found that I couldn't select summary rows through `cells_summary` when following the example here: https://gt.rstudio.com/reference/cells_summary.html

It seems that the minimal change required to make it fail is to remove the groups in that example. In this example and my real-life one, there is only a single group so it shouldn't matter.

```r
library(tidyverse)
library(gt)
countrypops %>%
  dplyr::filter(
    country_name == "Japan",
    year < 1970) %>%
  dplyr::select(-contains("country")) %>%
  dplyr::mutate(
    decade = paste0(substr(year, 1, 3), "0s")
  ) %>%
  gt(
    rowname_col = "year"
  ) %>%
  summary_rows(
    columns = vars(population),
    fns = list("min", "max"),
    formatter = fmt_number,
    decimals = 0
  ) %>%
  tab_style(
    style = list(
      cell_text(style = "italic"),
      cell_fill(color = "lightblue")
    ),
    locations = cells_summary(
      columns = vars(population),
      rows = 1)
  )
#> Error: All column or row indices given must be present in `data_tbl`.
```
Created on 2020-05-11 by the reprex package (v0.3.0)

**Comment by kendonB** [comment]
Worked out that just using `grand_summary` can work here. That may be the intended method to deal with one big group. However, there should be a useful error message here.

**Comment by rich-iannone** [comment]
Yes, this could be a lot nicer with messaging. We could either just accept `summary_rows()` in the condition that there are no groups or error with a statement that recommends the use of `grand_summary_rows()`.
