### ISSUE TITLE
Set global font options (rather than specifying body, column, header, etc invdividually)

### ISSUE THREAD

**Issue by jthomasmock** [rstudio/gt#585]
After a discussion with @rich-iannone I posted this issue.

`gt` has easy and rich support for custom fonts which I love, but to change fonts across the entire table I believe the only way so far is to do the following (and if you wanted to change things like the title you'd also need to specify further targets):

``` r
library(gt)
suppressPackageStartupMessages(library(dplyr))

ggplot2::mpg %>% 
  head() %>% 
  gt() %>% 
  gt::tab_style(
    style = list(
      cell_text(font = "Fira Mono")
    ),
    locations = list(
      cells_body(gt::everything()),
      cells_column_labels(gt::everything())
  
  ))
```
<sup>Created on 2020-05-15 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

![Screen Shot 2020-05-15 at 10 40 20 AM](https://user-images.githubusercontent.com/29187501/82071851-4979b900-969c-11ea-8876-7aa32566892a.png)

It'd be great if there were options to:
- Set a global/table level font
- Override sections optionally with the above formatting (cell body, columns, title, etc)
- Clearly understand WHERE fonts are allowed to be imported from IE:
  - System Installed fonts
  - Imported web fonts
  - Integration w/ font packages (`extrafont`, `systemfonts`, `gridtext`, etc)

Some ideas about supporting/loading fonts via:
- `systemfonts`
- `thematic`
- `gridtext`

Tagging @apreshill for her interest as well.

**Comment by zrodriguez89** [comment]
On a related note, I have seen similar requests regarding setting other stylistic changes to a table. For example, if I want to easily change all of the borders to black instead of the default gray.
