### ISSUE TITLE
Unable to apply font to source_notes

### ISSUE THREAD

**Issue by Torvaney** [rstudio/gt#587]
As far as I can tell, there is no `locations` helper function to select cells or text in the source notes. This means that we are unable to apply certain styles to source notes.

We can apply styling to the source notes through `tab_options`; however this is much more limited than `tab_style` and does not include the ability to set a specific font.

**Comment by rich-iannone** [comment]
Agreed that there should be location helper functions for the source notes *and* for the footnotes. Thanks for reporting as this was a major oversight.

**Comment by Torvaney** [comment]
No problem! Thanks for developing such a nice package!

**Comment by rich-iannone** [comment]
I didn't link this issue but a recent PR (https://github.com/rstudio/gt/pull/737) added the `cells_source_notes()` (and `cells_footnotes()`) functions. So those locations can now be styled.
