### ISSUE TITLE
Table margin bottom too small in RNotebook

### ISSUE THREAD

**Issue by MokeEire** [rstudio/gt#590]
The bottom margin between a `gt()` table in an RNotebook chunk (with no specified chunk options) and markdown text which follows it is too small.  

```r
mtcars %>% 
  rownames_to_column() %>% 
  mutate(hp_per_us_ton = hp/(2*wt)) %>% 
  arrange(-hp_per_us_ton) %>% 
  select(rowname, mpg, hp, wt, hp_per_us_ton) %>% 
  head(10) %>% 
  gt()
```

Looks like this:

![rmarkdown issue](https://user-images.githubusercontent.com/19700454/82392321-6c87ce00-99f8-11ea-8c31-95cd1cdd2d2c.PNG)

**Comment by rich-iannone** [comment]
I was reminded of this recently and I think it definitely does not look good at all. Also, occurs in RMarkdown documents (and probably in other contexts too).

**Comment by MokeEire** [comment]
The following addition to a CSS file solved it for me:

```
.gt_table {
    margin-bottom: 20px;
    margin-top: 20px;
}
```

**Comment by qdread** [comment]
The CSS solution was helpful for me also in the context of `print()`ing a large number of gt tables in a loop within a code chunk, to put padding between them.
