### ISSUE TITLE
Custom CSS classes

### ISSUE THREAD

**Issue by awgymer** [rstudio/gt#595]
I may be missing something but I can't find anyway within the package to add a custom CSS class to a table (or cell etc)? There may be a good reason this isn't supported but I can't see it myself and it's a little frustrating.

**Comment by rich-iannone** [comment]
I agree that this is frustrating. This is something that's being addressed now and it's been taking some time to make this feature intuitive to use. Thanks for your patience on this one.

**Comment by meghannash8** [comment]
I'm really excited for this feature. Thanks for working on it!
