### ISSUE TITLE
Unable to change font of the column spanner if it has footnote

### ISSUE THREAD

**Issue by kulbhushanchand** [rstudio/gt#597]
Since column spanner with footnotes (or with markdown) cannot have IDs, they are overlooked by helper function and thus styling them is not possible.
```
tab_style(
    style = list(
      cell_text(font = "Stencil")
    ),
    locations = list(
      cells_column_spanners(spanners = "Commands")
 ))
```
In the code above the, column spanner has already a footnote attached. Thus the above styling does not works on that particular column. Even `everything()` selector also overlooks this column.

1. A journal asks for particular font in my paper and I am stuck at this point. Any ideas or workaround?  

2. Is there any way to change the default font of gt table to something else? This can be a good workaround for now

**Edit**: Just came to my notice, there is a pull request https://github.com/rstudio/gt/pull/591 for the same. Keeping this issue open to get any valuable feedback or workaround.

**Comment by rich-iannone** [comment]
Sorry about this problem. That PR will partially address this but I do want to fix the underlying bug. Thanks for reporting!

**Comment by luis-zapata-b** [comment]
Hi! I have the same problem. It was solved?

**Comment by rich-iannone** [comment]
@luis-zapata-b This should be fixed once https://github.com/rstudio/gt/pull/665 is merged.
