### ISSUE TITLE
Changing the font for the table

### ISSUE THREAD

**Issue by bronsonpetersa** [rstudio/gt#598]
I wasn't able to find a way to change the font for the entire table. Seems like a pretty important thing but it doesn't look like its possible. Looking into the code it appears that fonts are hardcoded in, which is a strange choice. 

Any chance you might make this possible?

**Comment by rich-iannone** [comment]
It just so happens that we are trying to get this feature implemented. The PR is https://github.com/rstudio/gt/pull/591 and it's pretty far along. Thanks for submitting this issue.
