### ISSUE TITLE
Cannot add summary rows without calling grand total summary row as well

### ISSUE THREAD

**Issue by schaubst** [rstudio/gt#602]
Hello all,

I have a table with subgroups, and would like to add summary rows for those subgroups. However, the summary rows are not added to the table unless I also add a call for a grand total summary row. Is there a way to only have the summary rows, but without having a grand total summary row?

R version: 4.0.0
gt version: 0.2.1

A reprex is added below. Any tipps are greatly appreciated, thank you all!

Steffen
(First time poster, and R noob, so please be gentle!  :o))

```r
library(tidyverse)
library(gt)

# Create a tibble with some fake data
tib <- tibble(x = 1:5,
                 y = 2:6,
                 z = 3:7)

# Make tibble into gt table
gt_tib <- tib %>%
  gt()

# Form a subgroup of first 3 rows
gt_tib <- gt_tib %>%
  tab_row_group(group = "my_subgroup",
                rows = 1:3)

# Here, I want to create a summary row of my subgroup
# However, the summary row is not added after this call.
# It is only added if I also add a call for a grand total summary row (below)
gt_tib <- gt_tib %>%
  summary_rows(groups = TRUE, 
               columns = vars(x, y, z),
               fns = "sum")
gt_tib

# Add grand total summary row.
# Now, both the summary row and grand total summary row are added
gt_tib <- gt_tib %>%
  grand_summary_rows(columns = vars(x, y, z),
                     fns = "sum")
gt_tib

# I would like to know if it is possible to have the subgroup summary rows
# without adding the grand totals.
```

**Comment by rich-iannone** [comment]
This is a definite bug. You're building a table with groups and no stub. The `grand_summary_rows()` codepath results in a stub being created for summary labels, but, the `summary_rows()` codepath doesn't do that.

Thanks for reporting!

**Comment by jcheng5** [comment]
Another symptom of the same underlying bug: if you add rownames, then summary_rows works even without grand_summary_rows.

Doesn't work:

```r
gt(exibble, groupname_col = "group") %>%
  summary_rows(columns = "num", fns = list(mean = ~mean(., na.rm = TRUE)), groups = "grp_a")
```

Works:

```r
gt(exibble, rowname_col = "row", groupname_col = "group") %>%
  summary_rows(columns = "num", fns = list(mean = ~mean(., na.rm = TRUE)), groups = "grp_a")
```
