### ISSUE TITLE
Get CSS from gt table when using `as_raw_html()`

### ISSUE THREAD

**Issue by rachelupton** [rstudio/gt#604]
Wonderful package, thanks for making this!

When using `as_raw_html()` with inline = FALSE, I don't get the table CSS with that string. It's just the table itself. Any reason for this? I would like to see what CSS gets produced without having to dig into the browser's dev tools.

**Comment by rich-iannone** [comment]
Thanks for posting this issue. It looks like this is a mistake on our side. We should definitely be including that. Additionally, there should be an option in `as_raw_html()` to create the table inside of a complete HTML document.

**Comment by rich-iannone** [comment]
This was fixed in https://github.com/rstudio/gt/pull/718. Thanks again for this issue!
