### ISSUE TITLE
Function reference card

### ISSUE THREAD

**Issue by rachelupton** [rstudio/gt#605]
Awhile back you had a function reference graphic on the README. It's not there any more but I think it was a handy bit of documentation, and I did refer to it often. Could you bring that back?

By the way, the documentation for this package is the best I ever seen for an R package. It just makes using gt so easy, thank you for all your efforts in making this package so incredible.

**Comment by meghannash8** [comment]
Fully support the bringing back of that graphic in the README. Also agree with the above that this package has great docs.

**Comment by rich-iannone** [comment]
Sorry about removing it. It was done to lower the size of the tarball when submitting the package to CRAN. However I can put it back (and improve it!) while also finding an alternate solution for file size issues during releases.

**Comment by rich-iannone** [comment]
We'll probably instead work on a cheatsheet. The package has many more functions than it did in 2020 so this sort of graphic now risks overwhelming the user.
