### ISSUE TITLE
Add the `fmt_partsper()` function

### ISSUE THREAD

**Issue by janekbennett** [rstudio/gt#608]
There is a fmt_percent formatting function in gt but, in the same spirit, it would be lovely to have a an additional general function that does parts-per notation (eg. ppm, ppb, ppt, ppmV, per mille and per ten thousand, to name a few). These types of units are pretty common in the sciences and so this function would definitely get a lot of use from the scientific community.

**Comment by rich-iannone** [comment]
Thanks for posting the issue, it's a great feature request. I used to use this type of notation and I'm sure many would appreciate support for this. 

I also like the function name you proposed. I think `ppm`, `ppb`, etc. should be part of `fmt_partsper()`. For per mille and per ten thousand, that might separate go into a `fmt_per()` function. For the first, we can go from `ppm` to `ppmV` by way of the `pattern` argument.
