### ISSUE TITLE
A formatter that creates a button

### ISSUE THREAD

**Issue by meghannash8** [rstudio/gt#609]
It would be a great feature addition to have some text in a column transformed to a  button (this is a HTML only feature) that could be clickable and might have a link. 

The only difficulty design-wise is getting the text and the link together in the cell before using this formatter (maybe the links could be in a different column?)

**Comment by rich-iannone** [comment]
This could perhaps operate internally with `text_transform()`. If it's just URLs then it's pretty straightforward. But if the button text is expected to be different for each row, then we have much more to conside. This is similar to the UI problem for plots, where data could be in multiple columns or in a single list column.
