### ISSUE TITLE
tidyselect-based improvements

### ISSUE THREAD

**Issue by jthomasmock** [rstudio/gt#611]
---

When trying to apply some type of adjustment to multiple columns, I would typically want to do:
`col_1:col_n`, this fails w/ `vars()`, which forces the user to move to naming every column. This is fine for small tables, but could be a bad UX for many col names.

`reprex`

``` r
library(gt)

# Fails 
gtcars %>%
  head() %>% 
  gt() %>% 
  tab_spanner(
    label = "Gas Mileage",
    columns = vars(
      mpg_c:mpg_h
    )
  )
#> Error: Can't convert a call to a string


# works
gtcars %>%
  head() %>% 
  gt() %>% 
  tab_spanner(
    label = "Gas Mileage",
    columns = vars(
      mpg_c, mpg_h
    )
  )
```

<div id="bzzepvfyai" style="overflow-x:auto;overflow-y:auto;width:auto;height:auto;">

<table class="gt_table">

<thead class="gt_col_headings">

<tr>

<th class="gt_col_heading gt_center gt_columns_bottom_border" rowspan="2" colspan="1">

mfr

</th>

<th class="gt_col_heading gt_center gt_columns_bottom_border" rowspan="2" colspan="1">

model

</th>

<th class="gt_col_heading gt_center gt_columns_bottom_border" rowspan="2" colspan="1">

year

</th>

<th class="gt_col_heading gt_center gt_columns_bottom_border" rowspan="2" colspan="1">

trim

</th>

<th class="gt_col_heading gt_center gt_columns_bottom_border" rowspan="2" colspan="1">

bdy\_style

</th>

<th class="gt_col_heading gt_center gt_columns_bottom_border" rowspan="2" colspan="1">

hp

</th>

<th class="gt_col_heading gt_center gt_columns_bottom_border" rowspan="2" colspan="1">

hp\_rpm

</th>

<th class="gt_col_heading gt_center gt_columns_bottom_border" rowspan="2" colspan="1">

trq

</th>

<th class="gt_col_heading gt_center gt_columns_bottom_border" rowspan="2" colspan="1">

trq\_rpm

</th>

<th class="gt_center gt_columns_top_border gt_column_spanner_outer" rowspan="1" colspan="2">

<span class="gt_column_spanner">Gas Mileage</span>

</th>

<th class="gt_col_heading gt_center gt_columns_bottom_border" rowspan="2" colspan="1">

drivetrain

</th>

<th class="gt_col_heading gt_center gt_columns_bottom_border" rowspan="2" colspan="1">

trsmn

</th>

<th class="gt_col_heading gt_center gt_columns_bottom_border" rowspan="2" colspan="1">

ctry\_origin

</th>

<th class="gt_col_heading gt_center gt_columns_bottom_border" rowspan="2" colspan="1">

msrp

</th>

</tr>

<tr>

<th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1">

mpg\_c

</th>

<th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1">

mpg\_h

</th>

</tr>

</thead>

<tbody class="gt_table_body">

<tr>

<td class="gt_row gt_left">

Ford

</td>

<td class="gt_row gt_left">

GT

</td>

<td class="gt_row gt_right">

2017

</td>

<td class="gt_row gt_left">

Base Coupe

</td>

<td class="gt_row gt_left">

coupe

</td>

<td class="gt_row gt_right">

647

</td>

<td class="gt_row gt_right">

6250

</td>

<td class="gt_row gt_right">

550

</td>

<td class="gt_row gt_right">

5900

</td>

<td class="gt_row gt_right">

11

</td>

<td class="gt_row gt_right">

18

</td>

<td class="gt_row gt_left">

rwd

</td>

<td class="gt_row gt_left">

7a

</td>

<td class="gt_row gt_left">

United States

</td>

<td class="gt_row gt_right">

447000

</td>

</tr>

<tr>

<td class="gt_row gt_left">

Ferrari

</td>

<td class="gt_row gt_left">

458 Speciale

</td>

<td class="gt_row gt_right">

2015

</td>

<td class="gt_row gt_left">

Base Coupe

</td>

<td class="gt_row gt_left">

coupe

</td>

<td class="gt_row gt_right">

597

</td>

<td class="gt_row gt_right">

9000

</td>

<td class="gt_row gt_right">

398

</td>

<td class="gt_row gt_right">

6000

</td>

<td class="gt_row gt_right">

13

</td>

<td class="gt_row gt_right">

17

</td>

<td class="gt_row gt_left">

rwd

</td>

<td class="gt_row gt_left">

7a

</td>

<td class="gt_row gt_left">

Italy

</td>

<td class="gt_row gt_right">

291744

</td>

</tr>

<tr>

<td class="gt_row gt_left">

Ferrari

</td>

<td class="gt_row gt_left">

458 Spider

</td>

<td class="gt_row gt_right">

2015

</td>

<td class="gt_row gt_left">

Base

</td>

<td class="gt_row gt_left">

convertible

</td>

<td class="gt_row gt_right">

562

</td>

<td class="gt_row gt_right">

9000

</td>

<td class="gt_row gt_right">

398

</td>

<td class="gt_row gt_right">

6000

</td>

<td class="gt_row gt_right">

13

</td>

<td class="gt_row gt_right">

17

</td>

<td class="gt_row gt_left">

rwd

</td>

<td class="gt_row gt_left">

7a

</td>

<td class="gt_row gt_left">

Italy

</td>

<td class="gt_row gt_right">

263553

</td>

</tr>

<tr>

<td class="gt_row gt_left">

Ferrari

</td>

<td class="gt_row gt_left">

458 Italia

</td>

<td class="gt_row gt_right">

2014

</td>

<td class="gt_row gt_left">

Base Coupe

</td>

<td class="gt_row gt_left">

coupe

</td>

<td class="gt_row gt_right">

562

</td>

<td class="gt_row gt_right">

9000

</td>

<td class="gt_row gt_right">

398

</td>

<td class="gt_row gt_right">

6000

</td>

<td class="gt_row gt_right">

13

</td>

<td class="gt_row gt_right">

17

</td>

<td class="gt_row gt_left">

rwd

</td>

<td class="gt_row gt_left">

7a

</td>

<td class="gt_row gt_left">

Italy

</td>

<td class="gt_row gt_right">

233509

</td>

</tr>

<tr>

<td class="gt_row gt_left">

Ferrari

</td>

<td class="gt_row gt_left">

488 GTB

</td>

<td class="gt_row gt_right">

2016

</td>

<td class="gt_row gt_left">

Base Coupe

</td>

<td class="gt_row gt_left">

coupe

</td>

<td class="gt_row gt_right">

661

</td>

<td class="gt_row gt_right">

8000

</td>

<td class="gt_row gt_right">

561

</td>

<td class="gt_row gt_right">

3000

</td>

<td class="gt_row gt_right">

15

</td>

<td class="gt_row gt_right">

22

</td>

<td class="gt_row gt_left">

rwd

</td>

<td class="gt_row gt_left">

7a

</td>

<td class="gt_row gt_left">

Italy

</td>

<td class="gt_row gt_right">

245400

</td>

</tr>

<tr>

<td class="gt_row gt_left">

Ferrari

</td>

<td class="gt_row gt_left">

California

</td>

<td class="gt_row gt_right">

2015

</td>

<td class="gt_row gt_left">

Base Convertible

</td>

<td class="gt_row gt_left">

convertible

</td>

<td class="gt_row gt_right">

553

</td>

<td class="gt_row gt_right">

7500

</td>

<td class="gt_row gt_right">

557

</td>

<td class="gt_row gt_right">

4750

</td>

<td class="gt_row gt_right">

16

</td>

<td class="gt_row gt_right">

23

</td>

<td class="gt_row gt_left">

rwd

</td>

<td class="gt_row gt_left">

7a

</td>

<td class="gt_row gt_left">

Italy

</td>

<td class="gt_row gt_right">

198973

</td>

</tr>

</tbody>

</table>

</div>

<sup>Created on 2020-06-17 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by meersel** [comment]
Please add tidy_select option when selecting column names :

Example: 
columns = vars(ends_with("old"))

**Comment by rich-iannone** [comment]
This is pretty overdue. Definitely need to overhaul tidyselect support, thanks!

**Comment by rich-iannone** [comment]
Given the tidyselect improvements we made in a recent PR, @jthomasmock 's example code now works!

The revised code (sans `vars()`) is:

```r
gtcars %>%
  head() %>% 
  gt() %>% 
  tab_spanner(
    label = "Gas Mileage",
    columns = mpg_c:mpg_h
  )
```

The tables looks like this:

<img width="1370" alt="table" src="https://user-images.githubusercontent.com/5612024/116264721-88d3d500-a748-11eb-93e8-2fa8cbe0f485.png">

![woohoo-gif-26](https://user-images.githubusercontent.com/5612024/116264977-b882dd00-a748-11eb-9f0e-9e78342ec248.gif)
