### ISSUE TITLE
Strange footer behavior in GT tables in loops with RMarkdown

### ISSUE THREAD

**Issue by jcanistrum** [rstudio/gt#614]
In the example below, the same GT table displays the footnote differently when inside and outside of a loop.
![Screen Shot 2020-06-29 at 09 52 35](https://user-images.githubusercontent.com/914946/86013582-b0a5bf80-b9f5-11ea-8e69-277a4edbb997.png)
![Screen Shot 2020-06-29 at 09 52 43](https://user-images.githubusercontent.com/914946/86013587-b1d6ec80-b9f5-11ea-8f1a-8d04fb7cc738.png)

---
title: "Report"

output:
  html_document: default

---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

```{r, include=FALSE}
#bibliotecas usadas
library(tidyverse)
library(gt)
```

```{r gt1, echo=FALSE}

   head(mtcars) %>% gt() %>% tab_footnote("footnote blah blah", locations=cells_title())
```
\  
\  
```{r gtfor, echo = FALSE, warning=FALSE, message= FALSE, results='asis'}
for( i in 1:3)
{
  cat("\n### Some Header H3\n")
  cat("blah blah blah blah blah blahblah blah blah blah blah blah blah blah blahblah blah blahblah blah blahblah blah blahblah blah blahblah blah blah.\n\n")
  
  print(
      head(mtcars) %>% gt() %>% tab_footnote("footnote blah blah", locations=cells_title())
  )
  
}
   
```

**Comment by ddsjoberg** [comment]
I came to report the same issue.  Here's another example of the formatting issue for the footnotes when printed within a loop: https://rpubs.com/ddsjoberg/688904

![image](https://user-images.githubusercontent.com/26774684/98618117-7961ec00-22ce-11eb-95c3-88e375c2dce9.png)

Thank you! 🍁

**Comment by rich-iannone** [comment]
With the latest version of gt, this doesn't work at all. I don't think we'll support this usage because fixing it will probably increase the risk of other problems.
