### ISSUE TITLE
fmt_number with columns = vars(where(is.numeric)) gives an error

### ISSUE THREAD

**Issue by iago-pssjd** [rstudio/gt#618]
Hi!,

I would expect using the selection helper `where` would work but:
```r
library(tidyselect)
library(dplyr)
library(gt)

countrypops %>%
  dplyr::select(country_code_3, year, population) %>%
  dplyr::filter(
    country_code_3 %in% c(
      "CHN", "IND", "USA", "PAK", "IDN")
  ) %>%
  dplyr::filter(year > 1975 & year %% 5 == 0) %>%
  tidyr::spread(year, population) %>%
  dplyr::arrange(desc(`2015`)) %>%
  gt(rowname_col = "country_code_3") %>%
  fmt_number(
    columns = vars(where(is.numeric)),
    decimals = 2,
    suffixing = TRUE
  )
Error: Can't convert a call to a string
Run `rlang::last_error()` to see where the error occurred.
```

I also tried removing `vars`, `where` and both, even I didn't expect that these tries would work. I have all packages up to date and use R 3.6.3.

Thank you!

**Comment by rich-iannone** [comment]
Work on https://github.com/rstudio/gt/issues/611 would solve this. Basically, we need to get current with tidyselect. Thanks for posting this issue.

**Comment by rich-iannone** [comment]
This now works in the dev version of the package! Your example needs to drop `vars()` and here it is in revised form

```r
library(gt)
library(tidyverse)

countrypops %>%
  dplyr::select(country_code_3, year, population) %>%
  dplyr::filter(
    country_code_3 %in% c(
      "CHN", "IND", "USA", "PAK", "IDN")
  ) %>%
  dplyr::filter(year > 1975 & year %% 5 == 0) %>%
  tidyr::spread(year, population) %>%
  dplyr::arrange(desc(`2015`)) %>%
  gt(rowname_col = "country_code_3") %>%
  fmt_number(
    columns = where(is.numeric),
    decimals = 2,
    suffixing = TRUE
  )
```

and here is the table:

<img width="913" alt="table" src="https://user-images.githubusercontent.com/5612024/116331095-06293500-a79d-11eb-9787-612c51e96560.png">

It works now because of changes made in https://github.com/rstudio/gt/pull/718.

cc @jthomasmock
