### ISSUE TITLE
Markdown within cols_label not working

### ISSUE THREAD

**Issue by johnkparsons** [rstudio/gt#620]
Markdown formatting within the cols_label function is not working. Markdown formatting works with other functions, such as tab_spanner, so I think it's an issue with the cols_label function itself.

```r
gt(iris) %>% 
  cols_label(Sepal.Length = md("*Sepal Length*")) %>% 
  tab_spanner(label = md("*Sepals*"), columns = 1:2)
```

**Comment by johnkparsons** [comment]
<img width="356" alt="Annotation 2020-07-09 094649" src="https://user-images.githubusercontent.com/51463310/87067602-287ba300-c1c9-11ea-82f1-c423749b049c.png">

**Comment by rich-iannone** [comment]
This is looking okay on my end. Could you update **gt** with `install.packages("gt")` and try again?

**Comment by johnkparsons** [comment]
Updating gt alone didn't help, but updating tidyverse as well solved the issue. Thanks!
