### ISSUE TITLE
save as RTF file with rowname_col specified

### ISSUE THREAD

**Issue by CamBullen** [rstudio/gt#622]
When trying to save a gt object as an RTF file, I'm running into an issue if rowname_col is specified. I'm getting the error message "Error in row_splits[[i]] : subscript out of bounds".

I don't understand why the below code would lead to this error, but its very possible this is something I don't understand rather than an issue with gt.

```r
df <- tibble(x = c("A", "B", "B", "C"),
             y = c("1", "2", "2", "8"),
             z = c("Low", "Low", "High", "Low"))

# as_rtf() throws error "Error in row_splits[[i]] : subscript out of bounds"
df %>%
  gt(rowname_col = "x") %>%
  as_rtf()

#same error when using gtsave()
df %>%
  gt(rowname_col = "x") %>%
  gtsave("test.rtf")
```

**Comment by rich-iannone** [comment]
Sorry about this. A major effort the last few months has gotten RTF output support in much better shape (https://github.com/rstudio/gt/pull/638). With the most recent changes to the dev version of gt, this is now fixed (tested myself and it's good now).
