### ISSUE TITLE
select negate/except/exclude columns

### ISSUE THREAD

**Issue by klin333** [rstudio/gt#624]
For fmt_.* functions, is it possible to specify all columns except a few to-be-specified columns? In other words, a negate selection capability?

For example in dplyr, you can do things like select(-col_a) or select(-contains('abc')). Is it possible to do this type of 'negated' column selection in gt fmt_.* functions? This would be useful if we want to apply formatting to all columns except a few columns that we wish to exclude. 

Thanks

**Comment by Zedseayou** [comment]
Seconded! I'd compare to the tidyr pivot_ functions that allow the use of just c() instead of vars, as well. Is changing the select interface on the roadmap for gt?

**Comment by rich-iannone** [comment]
Thanks for feature requests, these are all good things that gt should have. We need to do some general work in updating tidyselect support so this is part of that (and was planned for awhile back).

**Comment by rich-iannone** [comment]
This now works in the dev version of the package thanks to the work done in https://github.com/rstudio/gt/pull/718.

Here's an example:

```r
library(gt)
library(tidyverse)

countrypops %>%
  dplyr::select(country_code_3, year, population) %>%
  dplyr::filter(
    country_code_3 %in% c(
      "CHN", "IND", "USA", "PAK", "IDN")
  ) %>%
  dplyr::filter(year > 1975 & year %% 5 == 0) %>%
  tidyr::spread(year, population) %>%
  dplyr::arrange(desc(`2015`)) %>%
  gt(rowname_col = "country_code_3") %>%
  fmt_number(
    columns = -c(`1980`, `2000`),
    decimals = 2,
    suffixing = TRUE
  )
```

Which produces this table (where the `1980` and `2000` columns aren't formatted):

<img width="959" alt="table" src="https://user-images.githubusercontent.com/5612024/116331926-c400f300-a79e-11eb-91d6-4fb19a420315.png">
