### ISSUE TITLE
`tab_spanner_delim` with `gather = TRUE` not working

### ISSUE THREAD

**Issue by pdeffebach** [rstudio/gt#626]
Here is an MWE

```
r$> df = tibble(A_X = c(1), B_X = c(2), A_Y = c(3), B_Y = c(4))                                          

r$> gt(df) %>% tab_spanner_delim(delim = "_", gather = TRUE) 
```
Gives me this:

![Screenshot from 2020-07-22 12-32-54](https://user-images.githubusercontent.com/23196228/88202952-938c9700-cc17-11ea-8366-9bb32733078a.png)

From the docstring, we `gather = TRUE` should re-arrange the columns. 

On version 0.2.1

**Comment by rich-iannone** [comment]
Thank you for reporting this bug (which is pretty serious) and providing the MWE. This is highly prioritized so it'll be handled soon.
