### ISSUE TITLE
Outdated currency symbol for "PEN" in the fmt_currency() function

### ISSUE THREAD

**Issue by andresrcs** [rstudio/gt#636]
---

The current currency symbol showed for "PEN" is `S/.` and it should be `S/` this changed a couple of years ago.

``` r
library(gt)
data.frame(
    Currency = 1
    ) %>% 
    gt() %>% 
    fmt_currency(
        columns = vars(Currency),
        currency = "PEN"
    )
```

**Comment by rich-iannone** [comment]
Thanks very much for letting me know. I hope to change this fairly quickly!
