### ISSUE TITLE
gt + distill rendering

### ISSUE THREAD

**Issue by jthomasmock** [rstudio/gt#643]
---
The `distill` RMarkdown format appears to override portions of `gt` tables. This leads to double "plotting" of header borders, and adds row dividers even if they've been excluded via `tab_options()`.

This also appears to occur with [`kableExtra`](https://github.com/haozhu233/kableExtra/issues/279) and further documented [here](https://haozhu233.github.io/kableExtra/using_kableExtra_in_radix.html).

My assumption is that there is a `boostrap` or `CSS` conflict. If it's more appropriate to reference this in the `distill` repo let me know!

```r
library(gt)

mtcars %>% 
  head() %>% 
  gt() %>% 
  tab_spanner(
    2:5,
    label = "Spanner"
  ) %>% 
  tab_options(
    table_body.hlines.color = "white",
    column_labels.border.bottom.width = px(3),
    column_labels.border.bottom.color = "black",
    table.border.top.color = "white",
    table.border.top.width = px(3),
    table.border.bottom.color = "black",
    table.border.bottom.width = px(3)
  )
```

### V1 - as seen from console

![Screen Shot 2020-09-09 at 4 55 42 PM](https://user-images.githubusercontent.com/29187501/92659101-5bbbda80-f2bd-11ea-84f4-6cd3888c6e20.png)

### V2 - as seen in `distill`

Notice the gray lines behind the spanner and for h-lines.

![Screen Shot 2020-09-09 at 4 55 30 PM](https://user-images.githubusercontent.com/29187501/92659103-5ced0780-f2bd-11ea-9971-8abac1799dbe.png)

**Comment by apreshill** [comment]
Out of curiosity, does this work?

```
exibble %>%
  dplyr::select(num, currency) %>%
  gt(id = "one") %>%
  fmt_currency(
    columns = vars(currency),
    currency = "HKD"
  ) %>%
  fmt_scientific(
    columns = vars(num)
  ) %>%
  opt_css(
    css = "
    #one .gt_table {
      background-color: skyblue;
    }
    #one .gt_row {
      padding: 20px 30px;
    }
    #one .gt_col_heading {
      text-align: center !important;
    }
    "
  )
```

**Comment by jthomasmock** [comment]
It does, but the grey divider lines are still there.

![Screen Shot 2020-09-11 at 8 15 48 PM](https://user-images.githubusercontent.com/29187501/92983869-a2e7ce00-f46b-11ea-9be5-060d5754be01.png)

**Comment by jthomasmock** [comment]
This was corrected in Distill, thanks!
