### ISSUE TITLE
gt() spitting out link not found

### ISSUE THREAD

**Issue by piercefa** [rstudio/gt#647]
<My problem consists of using gt() to create the most basic first pass table, but I am only receiving a "not found" link
>

```r
<fruit <- c("SB: Strawberry", "PH: Peach", "BB: Blueberry", "AP: Apple", "WM: Watermelon")
floral <- c("RS: Rose", "LA: Lavender", "IR: Iris", "JM: Jasmine", "HS: Honeysuckle")
df <- data.frame(fruit, floral)
columns <- c("Fruit", "Floral")
table <- gt(df)>
```
output is the following:

/session/viewhtml4a741915534/index.html?viewer_pane=1&capabilities=1&host=http%3A%2F%2F127.0.0.1%3A18187 not found

I am using R 4.0.0

**Comment by rich-iannone** [comment]
Using similar statements I was able to create a basic table:

``` r
fruit <- c("SB: Strawberry", "PH: Peach", "BB: Blueberry", "AP: Apple", "WM: Watermelon")
floral <- c("RS: Rose", "LA: Lavender", "IR: Iris", "JM: Jasmine", "HS: Honeysuckle")
df <- data.frame(fruit, floral)
gt(df)
```

<img width="798" alt="gt_table_example" src="https://user-images.githubusercontent.com/5612024/95237447-39db4800-07d6-11eb-9fea-a0667b6d8e92.png">

**Comment by piercefa** [comment]
Thank you so much, I appreciate it. I think the lack of table was more due to a lack of consistency between R studio and R versions. Thank you again!

**Comment by rich-iannone** [comment]
You're welcome, and, enjoy!
