### ISSUE TITLE
`cols_merge_n_pct()` for N (%) format

### ISSUE THREAD

**Issue by thomas-neitmann** [rstudio/gt#651]
In the pharmaceutical industry, one of the most commonly used formats in tables is `N (%)` to display the absolute number of patients and percentage of patients relative to the population of interest, e.g. `123 (85.6%)`. It would be great to have a utility `cols_merge_n_pct()` function for that.

**Comment by lcougnaud** [comment]
It could also be interesting to have an option in this function to include only the counts in case of 'zero counts', a.k.a '0' instead of '0 (0%)'

**Comment by rich-iannone** [comment]
This is a very reasonable feature request and really the usefulness of having `cols_merge_*()` variants is to handle exceptions and. I can work the zero counts option into it as well. Thanks!

**Comment by thomas-neitmann** [comment]
The zero option would be great indeed. I'd be happy to try to take this on myself @rich-iannone. I guess looking at the other `cols_merge_*()` should get me enough inspiration to get started. Please let me know if that's fine with you 🙂

**Comment by rich-iannone** [comment]
Thomas! We'd love your contribution.

**Comment by thomas-neitmann** [comment]
Awesome, looking forward to contributing 😁👍

**Comment by jcheng5** [comment]
(Notes from in-person discussion with @rich-iannone)

`cols_merge*` could be more like `fmt` in the sense of being extensible and based on functions being registered with the render pipeline; as opposed to their current implementation, which has the `cols_merge*` functions register *values* that are recognized by the render pipeline. The disadvantage of this is that the set of values recognized by the render pipeline are necessarily a closed set.

For this release I don't mind if we implement `cols_merge_n_pct()` as a one-off though, given its usefulness and our desire to go to CRAN soon.
