### ISSUE TITLE
Noted Issues from R/pharma workshop

### ISSUE THREAD

**Issue by bellafengkite** [rstudio/gt#653]
1) Would really want footnote needs to be in the footnote. 
2) "Page 1 of total" is needed.
3) Example template (for Gilead/Kite ;)) wrapper function would be great.
More to follow...

**Comment by drolejoel** [comment]
4. you mentioned need to add n_sigfig to format_number

**Comment by rich-iannone** [comment]
`n_sigfig` was added to format number in https://github.com/rstudio/gt/issues/535 (thanks for that, by the way). It needs to be added to `fmt_scientific()` and `fmt_percent()`.

**Comment by drolejoel** [comment]
Yeah, I'm still learning my way around Gt. TY.  
Great workshop yesterday  :-)
