### ISSUE TITLE
Hazem Abd Elkader

### ISSUE THREAD

**Issue by ha82zem** [rstudio/gt#654]
Hi 

I am start using gt package to create tables for my report. I developed a very nice table that I can save in html, pdf, png but struggle to export rtf fine due to the error below

Error in if (headings[i] == spanners[i]) { : 
  missing value where TRUE/FALSE needed
In addition: Warning message:
In spanners[is.na(spanners)] <- headings_vars[is.na(spanners)] :
  number of items to replace is not a multiple of replacement length

Here is a copy of my code:

tab1 <- PCQI_table %>% gt()
tab1
tab1 <- PCQI_table %>% 
  gt(rowname_col = "Value", 
     groupname_col = "Variable") %>%
  tab_spanner(
    label = "Had surgery",
    columns = vars(
      "Number of those who had surgery", "% of those who had surgery")
  ) %>%
  cols_label("Number of those who had surgery" = "N",
             "% of those who had surgery" = "%")  %>%
  cols_align(
    align = "center",
    columns = vars("Men with prostate cancer","Number of those who had surgery", "% of those who had surgery")
  ) %>%
  tab_spanner(
    label = "Had radiation",
    columns = vars(
      "Number of those who had radiation", "% of those who had radiation")
  ) %>%
  cols_label("Number of those who had radiation" = "N",
             "% of those who had radiation" = "%")  %>%
  cols_align(
    align = "center",
    columns = vars("Men with prostate cancer","Number of those who had radiation", "% of those who had radiation")
  ) %>%
  tab_header(
    title = md("Proportion of men diagnosed with prostate cancer who had surgey / radiation"),
    subtitle = md("between 2016 and 2018")
  ) %>%
  tab_source_note(
    source_note = "Source(s): New Zealand Cancer Registry (NZCR), National Minimum Dataset (hospital events) & Radiation Oncology Collection"
  ) %>%
  tab_footnote(
    footnote = "Exclude men registered with prostate cancer from death certificates only.",
    locations = cells_column_labels(
      columns = vars("Men with prostate cancer")) 
  ) %>%
  tab_options(
    table.width = pct(100)
  )

tab1

gtsave(tab1, "Equitable treatment DHB_SERV.html")
gtsave(tab1, "Equitable treatment DHB_SERV.rtf")

I would appreciate if you could help me with fixing this.

Regards
Hazem

**Comment by rich-iannone** [comment]
Hazem,

I don't have your `PCQI_table` to reproduce this error. However, I think that this error can be avoided by using the updated RTF support in gt. This is presently only available in the development version of the package so you need to install that with

``` r
devtools::install_github("rstudio/gt")
```

If you try this again, I think it should provide the RTF without error. For now, I'm going to close this issue but if you do have an RTF output error after updating, please file one more issue.
