### ISSUE TITLE
Issue with rendering % with as_raw_html in Email

### ISSUE THREAD

**Issue by tanyanchongDA** [rstudio/gt#657]
Hi,

I am trying to render % sign in HTML so it can be passed into mailR. However, it seems to be showing "&percnt;" rather than %. I have some simple example below to show.

```
trial <- tibble(trial = c(0.1,0.2,0.3))

gt_html <- trial %>%
  gt() %>%
  fmt_percent(
    columns = vars(trial)
  ) %>%
  as_raw_html(.)

from <- 
to <- 
subject <- paste("Trial Report on ", Sys.Date())
send.mail(from,to,subject,gt_html, encoding = "utf-8",
          smtp = list(
            host.name = "",
            port = ,
            user.name =,
            passwd = ),
            tls = TRUE
          ), authenticate = TRUE, send=TRUE, html=TRUE)
```

I got this instead though. I remembered it used to render properly about 6 months ago. Is there anything I have missed there?

![image](https://user-images.githubusercontent.com/71107943/95735199-196c2b80-0cb7-11eb-8c97-e51deffc9a77.png)

Thank you so much in advance!

**Comment by davidwales** [comment]
Related to #686

**Comment by Thyrisis** [comment]
I just had this issue too with an email body generated using as_raw_html() in which the % is not correctly rendered back from the escaped "& percnt;" (excluding whitespace) - is there any update on when this might be resolved please?

**Comment by rich-iannone** [comment]
I tried this out and I confirmed that my Gmail email didn't work (Mac mail.app was fine). Here's what I did:

```r
library(gt)
library(blastula)

# Create table, write to inlined HTML
gt_html <-
  gt(dplyr::tibble(a = c(0.1, 0.2, 0.3), b = c(34, 67, 23))) %>%
  fmt_percent(columns = a) %>%
  fmt_scientific(columns = b) %>%
  as_raw_html()

# Compose email message
email <-
  blastula::compose_email(body = blastula::md(glue::glue(
    "Hey, I've got a table here:
  
  {gt_html}
  
  Enjoy
  "
  )))

# Check email in Viewer
email

# Send email
blastula::smtp_send(
  email = email,
  subject = "Test email with table included",
  from = "rich@rstudio.com",
  to = "riannone@me.com",
  credentials = creds_envvar(
    user = "*****",
    pass = "*****",
    host = "mail.smtp2go.com",
    port = 465,
    use_ssl = TRUE
  )
)
```

Here's a screenshot from Gmail:

<img width="818" alt="email_existing_gt" src="https://user-images.githubusercontent.com/5612024/151906631-7d8c6de6-7ca6-4fe2-9aa2-4808478cd877.png">

😟

With the changed gt code (`&percnt;` -> `%`) I get this:

<img width="819" alt="email_try_2" src="https://user-images.githubusercontent.com/5612024/151906731-2c2febce-b059-466b-a1c6-915c82e25893.png">

There's a PR in the works to fix this: https://github.com/rstudio/gt/pull/871

Thanks for reporting!
