### ISSUE TITLE
Use plotmath with gt

### ISSUE THREAD

**Issue by py9mrg** [rstudio/gt#659]
Hello,

I feel like I'm missing a really obvious way of doing this, but is it possible to use plotmath with gt? I've tried a few things such a

```
library(tidyverse)
library(gt)
data <- tibble(a = c(1, 2), b = c("expression(y^2)", "expression(z^2)"))
data %>%
gt() %>%
fmt(
    columns = vars(b),
    fns = function(x) parse(text = x)
)
```

and then tried various different functions in fns, `bquote(x)`, `eval(x)`, `eval(parse(text = x))` (which works well in the `labs` function of `ggplot2`), but nothing I've tried seems to work.

**Comment by rich-iannone** [comment]
It’s not possible to use polymath with gt.
