### ISSUE TITLE
`google_font()` does not seem to work when passed as a list into `tab_style()` 

### ISSUE THREAD

**Issue by kaustavSen** [rstudio/gt#661]
When passing `google_font()` as a list into `tab_style()`, it does not seem to work, i.e. the font face does not change. 

```r
library(gt)

mtcars %>%
  head() %>% 
  gt() %>% 
  tab_style(
    style = list(
      cell_text(font = google_font("Fira Code")),
      cell_fill(color = "#F5F3F1")
    ),
    locations = cells_body(everything())
  )
```
![image](https://user-images.githubusercontent.com/16508583/96361694-84998000-1145-11eb-8a90-ba8177847504.png)

However, if I pass it as two separate calls to `tab_style()` and **not** as a `list()`:

* one for changing the font-face
* second for updating the background color of the cells

then it works:

```r
mtcars %>%
  head() %>% 
  gt() %>% 
  # First call to change font-face
  tab_style(
    style = cell_text(font = google_font("Fira Code")),  # without list()
    locations = cells_body(everything())
  ) %>% 
  # Second call to update background color
  tab_style(
    style = cell_fill(color = "#F5F3F1"),  # without list()
    locations = cells_body(everything())
  )
```
![image](https://user-images.githubusercontent.com/16508583/96361757-05f11280-1146-11eb-9f75-bbe765424136.png)

**Comment by rich-iannone** [comment]
Ran into this myself recently and it’s no good. I hope to fix this soon.
