### ISSUE TITLE
Cant apply bold to row_group that has a footnote

### ISSUE THREAD

**Issue by luis-zapata-b** [rstudio/gt#671]
I cant apply bold to a rop_group that has a footnote. Some help please?

exibble %>%
  dplyr::select(num, currency,group) %>%
  gt(rowname_col = "num",
     groupname_col = "group")%>%

tab_footnote(
  footnote = "testing footnotes",
  cells_row_groups(groups = "grp_a")
) %>% 
  tab_style(
    style = cell_text(weight = "bold"),
    locations = cells_row_groups()
  )

**Comment by rich-iannone** [comment]
Try this:

```r
exibble %>%
  dplyr::select(num, currency,group) %>%
  gt(rowname_col = "num",
     groupname_col = "group",
     id = "table"
  ) %>%
  tab_footnote(
    footnote = "testing footnotes",
    cells_row_groups(groups = "grp_a")
  ) %>%
  tab_style(
    style = cell_text(weight = "bold"),
    locations = cells_row_groups()
  ) %>% opt_css(
    css = "
    #table .gt_group_heading {
      font-weight: bold;
    }
    "
  )
```

**Comment by luis-zapata-b** [comment]
Hi. I tried it on my dataset, and it hasn't any effect. Also, in others dataset it doesn't work neither (i couldn't apply bold):

mtcars %>% 
  select(disp,hp,drat,wt,gear) %>% 
  mutate(gear = ifelse(gear==4,"test1",
                       ifelse(gear==3,
                              "test2","test3"))) %>% 
  gt(rowname_col = "hp",
     groupname_col = "gear") %>% 
  tab_footnote(
    footnote = "test1",
    cells_row_groups(groups = "test1")
  )%>% 
  tab_footnote(
    footnote = "test2",
    cells_row_groups(groups = "test2")
  ) %>% 
  tab_footnote(
    footnote = "test3",
    cells_row_groups(groups = "test3")
  )%>% 
  opt_css(
    css = "
    #table .gt_group_heading {
      font-weight: bold;
    }
    "
  )

**Comment by rich-iannone** [comment]
That code is slightly incorrect, it should be:

``` r
mtcars %>%
  select(disp,hp,drat,wt,gear) %>%
  mutate(gear = ifelse(gear==4,"test1",
                       ifelse(gear==3,
                              "test2","test3"))) %>%
  gt(rowname_col = "hp",
     groupname_col = "gear",
     id = "table") %>%
  tab_footnote(
    footnote = "test1",
    cells_row_groups(groups = "test1")
  )%>%
  tab_footnote(
    footnote = "test2",
    cells_row_groups(groups = "test2")
  ) %>%
  tab_footnote(
    footnote = "test3",
    cells_row_groups(groups = "test3")
  )%>%
  opt_css(
    css = "
#table .gt_group_heading {
font-weight: bold;
}
"
  )
```
