### ISSUE TITLE
`gtsave()` to RTF file issue when used in an Rmd file

### ISSUE THREAD

**Issue by twu13** [rstudio/gt#674]
If I run the code below in RStudio the resulting .rtf file is created and can be viewed by TextEdit just fine:

```
library(gt)
gtsave(gt(mtcars), "test.rtf")
```

However if I put it into an Rmd file and knit to HTML, the .rtf file that is outputted is the same but contains in addition some strange tags (!!!!!RAW-KNITR-CONTENT and RAW-KNITR-CONTENT!!!!!)  that cause the file to be unreadable by TextEdit and other errors. These seem like they are placed by `knitr` but I can’t tell if it’s a bug or if I’m using the function incorrectly on my end?

**Comment by twu13** [comment]
Does anyone have any suggestions for this issue? It's still happening for me. As an example, if I knit the very simple code below from an Rmd file to either PDF or HTML the `test.rtf` file contains the strange tags as I described before and cannot be opened:

``` 
---
title: "test"
output: html_document
---

```{r setup, include=FALSE}
library(gt)
gtsave(gt(mtcars), "test.rtf")
```

**Comment by jpattee** [comment]
Looks like this is a continued issue - unfortunately renders the package near-unusable with my workflow. Any solutions?

**Comment by twu13** [comment]
@jpattee I have a manual workaround where I read the file in and strip out those strange tags...

```
temp <- readr::read_file("file.rtf"))
temp_fixed <- stringr::str_replace_all(temp, "RAW-KNITR-CONTENT!!!!!|!!!!!RAW-KNITR-CONTENT", "")
writeLines(temp_fixed, "fixed_file.rtf")
```

Hopefully this issue can be fixed!

**Comment by rich-iannone** [comment]
Fixed by https://github.com/rstudio/gt/pull/1153.
