### ISSUE TITLE
[accessibility] Add scope="col" attribute to first and second column headers.

### ISSUE THREAD

**Issue by jooyoungseo** [rstudio/gt#680]
For all the column headers denoted with `<th>` tag, we need to add `scope = "col"` attribute to explicitly make a semantic binding for accessibility improvements.

Please take care of this issue after resolving #679 so that only column headers are denoted with `<th scope = "col" ...>` tag excepting `title` and `subtitle`.

Relevant issue (#678) talks about row headers, which have to be denoted with `<th scope = "row" ...>`.

**Comment by jooyoungseo** [comment]
This also applies to `gt::tab_stubhead()`. Stub head also has to include `scope = "col"` attribute.

**Comment by rich-iannone** [comment]
Because https://github.com/rstudio/gt/pull/978 is now merged, this issue can be closed.
