### ISSUE TITLE
Need for cells_footnote()?

### ISSUE THREAD

**Issue by courtiol** [rstudio/gt#684]
It would be great to have a location helper for targeting the footnote (apologies if it exists).

If that is technically possible, it would make it easier to change aspects of the footnote.
For now, as far as I understand, `tab_options()` let you change the font size (`footnotes.font.size`) but nothing else about the text.

The location helper would avoid the multiplication of arguments in `tab_options()` and it would also avoid HTML.

Example (using HTML as workaround):
``` r
library(gt)

set.seed(1)
tb <- data.frame(x = sample(1:10))

tb %>%
  gt() %>%
  tab_style(style = cell_borders(color = "red"),
            locations = cells_body(columns = vars(x), rows = which.min(tb$x))) %>%
   tab_footnote(footnote = md("<p style=color:red>smallest value</p>"),
                locations = cells_body(columns = vars(x), rows = which.min(tb$x))) %>%
  tab_options(footnotes.marks = "standard")
```
![image](https://user-images.githubusercontent.com/7499666/99191940-5329c980-2770-11eb-9d3b-5f295aee6fcd.png)

**Comment by rich-iannone** [comment]
Excellent idea. Thank you for suggesting this. I think `cells_source_note()` is also required.

**Comment by francisbarton** [comment]
Came here to ask how to use `tab_style` could be used to target a `tab_source_note` text. Seems like the idea of a `cells_source_note()` helper is what's needed. Yes please... consider this my `+1`

**Comment by rich-iannone** [comment]
@courtiol @francisbarton Sorry I didn't include this issue in the recent PR but these new functions were added in https://github.com/rstudio/gt/pull/737.
