### ISSUE TITLE
Feature request: have option of using literal "%" instead of "&percnt;".

### ISSUE THREAD

**Issue by travis-leith** [rstudio/gt#686]
I am using R Markdown to generate an HTML file which includes some tables from gt. Some of the tables include numbers formatted as a percentage. When I load the HTML into an Outlook email, "&percnt;" does not get rendered as "%". Would be nice if I had the option of getting gt to use a literal "%" instead of "&percnt;".

**Comment by joeroe** [comment]
Is there any reason to escape % at all? It's not listed here: https://www.w3.org/International/questions/qa-escapes#use

**Comment by travis-leith** [comment]
Just re-reading my original question, for some of those '%' characters, I had intended to display the escape sequence. However, on my Firefox browser at least, they get re-rendered as '%' characters.
So for the avoidance of doubt, I would like to prevent "& p e r c n t ;" (less the white space) to be output, instead of just a '%' character.

**Comment by davidwales** [comment]
I also get this when using R Markdown with Shiny:

![image](https://user-images.githubusercontent.com/55477181/119085953-09d07480-ba48-11eb-80f1-3661ba2f82cd.png)

**Comment by davidwales** [comment]
> 
> 
> Is there any reason to escape % at all? It's not listed here: https://www.w3.org/International/questions/qa-escapes#use

`%` is the comment symbol in LaTeX, but it probably only makes sense to escape it for LaTeX output.

**Comment by davidwales** [comment]
I think this is the relevant line of code:

https://github.com/rstudio/gt/blob/405f63b8b7c880495f9eeb634647af607bfa5b4a/R/utils_formatters.R#L427

**Comment by davidwales** [comment]
When I download the HTML from my Shiny app, it's actually showing `&amp;percnt;`. This explains why the escape code is not being automatically translated back into a percentage symbol in Shiny. Presumably Shiny has it's own HTML escaping function, which is converting the `&` to `&amp;`, which breaks the escaped percentage symbol.

**Comment by rich-iannone** [comment]
Sorry for the delay on this. Was able to reproduce this issue in the emailing scenario. Check out the response in https://github.com/rstudio/gt/issues/657. Fix is on the way!
