### ISSUE TITLE
HTML/Markdown in group heading rows is not processed

### ISSUE THREAD

**Issue by abielr** [rstudio/gt#694]
Currently HTML or Markdown stored in a column that is then defined as the row group (groupname_col) is not rendered properly (the characters are escaped). This appears to occur in `dt_stub_df.R::dt_stub_df_init()` at the following stage, which converts the column to plain text even if the `gt::html` or `gt::md` functions were used.

    row_group_labels <-
      apply(
        data_tbl[, groupname_col],
        MARGIN = 1,
        paste, collapse = row_group.sep
      )

Would like to request that users be able to pass HTML/MD into the row group.

**Comment by rich-iannone** [comment]
This seems quite reasonable. While it’s not yet possible, I think the way this ought to be done is to allow formatters (`fmt_markdown()` in this case) to transform columns that are used for group row labels and stub labels.
