### ISSUE TITLE
Spacer Rows

### ISSUE THREAD

**Issue by peterparkerspicklepatch** [rstudio/gt#698]
It's often the case that we need to visually separate different groups of information for readability. Adding a spacer row/column should been be easy to implement and achieve this.

Columnwise:
![image](https://user-images.githubusercontent.com/10812302/101341977-2c981380-3882-11eb-87f7-ce3189704161.png)

Rowwise:
![image](https://user-images.githubusercontent.com/10812302/101341962-25710580-3882-11eb-9816-c7f1cbddf742.png)

**Comment by alex-lauer** [comment]
Amazing! I would definitely love to see that for optional spacing between groups.
