### ISSUE TITLE
Feature Request: Unhide columns

### ISSUE THREAD

**Issue by ddsjoberg** [rstudio/gt#700]
Hello Rich! In gtsummary, we auto-hide some columns. Sometimes users convert the gtsummary objects to gt and need to unhide these columns. Can we get a `cols_unhide()` companion to `cols_hide()`?

ヽ(ຈل͜ຈ)ﾉ︵ ┻━┻🍁

**Comment by ddsjoberg** [comment]
Just realized this is related to https://github.com/rstudio/gt/issues/26

**Comment by rich-iannone** [comment]
This will be prioritized for the upcoming release. Thanks!

**Comment by ddsjoberg** [comment]
Thank you!! 😍
