### ISSUE TITLE
Feature request: Use of variables in cols_label for left hand side of assignment

### ISSUE THREAD

**Issue by ScoobyQ** [rstudio/gt#702]
Say I had the following as  a working column rename:

```r
cols_label(`Org Name` = 'AMBULANCE SERVICE')
```

And instead I want 'Org Name' to be passed in as a variable  and be interpreted as the actual column,

```r
var  <- 'Org Name'
cols_label( var = 'AMBULANCE SERVICE')
```
Currently, variations using {{}}, !!, vals etc seem to yield

> Error in stop_if_not_gt(data = data) :  argument "data" is missing, with no default

OR

>  All column names provided must exist in the input `data` table.

Can the use of variables to represent columns on left hand side of assignment be supported in cols_label?

**Comment by kerem-a** [comment]
I am struggling with the same problem (I think). Did you find any workaround to this problem?

**Comment by rich-iannone** [comment]
This is now possible (actually, it was possible awhile back but I didn't close this issue). The following now works:

```r
towny |>
  dplyr::select(
    name, ends_with("2001"), ends_with("2006"), matches("2001_2006")
  ) |>
  dplyr::filter(population_2001 > 100000) |>
  dplyr::arrange(desc(pop_change_2001_2006_pct)) |>
  dplyr::slice_head(n = 10) |>
  gt() |>
  fmt_integer() |>
  fmt_percent(columns = matches("change"), decimals = 1) |>
  tab_spanner(label = "Population", columns = starts_with("population")) |>
  tab_spanner(label = "Density", columns = starts_with("density")) |>
  cols_label(
    ends_with("01") ~ "2001",
    ends_with("06") ~ "2006",
    matches("change") ~ md("Population Change,<br>2001 to 2006")
  ) |>
  cols_width(everything() ~ px(120))
```
