### ISSUE TITLE
Unused argument id in tab_spanner

### ISSUE THREAD

**Issue by kulbhushanchand** [rstudio/gt#704]
gt ver. - 0.2.2
R studio ver. - 1.3.1093 

When using this reproducible example from gt documentation for [cell_column_spanner](https://gt.rstudio.com/reference/cells_column_spanners.html), the error is - 

> Error in tab_spanner(., label = "dates and times", id = "dt", columns = vars(date,  : 
  unused argument (id = "dt")

Not able to find what am I doing wrong?

```r
# Use `exibble` to create a gt table; add a
# spanner column label over three column
# labels and then use `tab_style()` to make
# the spanner label text bold

library(dplyr)
library(gt)
tab_1 <-
  exibble %>%
  dplyr::select(-fctr, -currency, -group) %>%
  gt(rowname_col = "row") %>%
  tab_spanner(
    label = "dates and times",
    id = "dt",
    columns = vars(date, time, datetime)
  ) %>%
  tab_style(
    style = cell_text(weight = "bold"),
    locations = cells_column_spanners(spanners = "dt")
  )
```

**Comment by rich-iannone** [comment]
Currently, the `id` argument of that function is only in the development version of `gt`. If you look at the internal documentation for the function in your installation, you’ll find that it’s not there. It will definitely be there in the next release of gt though.

**Comment by kulbhushanchand** [comment]
@rich-iannone  Thanks for the confirmation. 
The doubt arises because, the [documentation ](https://gt.rstudio.com/reference/cells_column_spanners.html) is providing example for gt ver 0.2.2. I think it must me updated there too, else someone else may file the same issue. 
And looking forward to next release :)
