### ISSUE TITLE
Formatting error using `fmt()` when formatted value has a `>` and is printed in a loop

### ISSUE THREAD

**Issue by ddsjoberg** [rstudio/gt#707]
Hello, hello!

I am printing a gt table in a loop in an R markdown document. I have a numeric column that I am formatting with `fmt()`.  The formatted value in the example should be ">0.9", but the greater than symbol is being stripped and extra spacing is added to the cell.  

Here is an example https://rpubs.com/ddsjoberg/715283
Thank you! 🍁 
![image](https://user-images.githubusercontent.com/26774684/105096404-02d32e80-5a75-11eb-8062-41e82e753492.png)

cc @leejasme

**Comment by fh-mthomson** [comment]
Hello! Are there any updates on this issue? It's blocking my team's adoption of `gtsummary`, since if any categorical levels contain a `>`, then they will similarly not render correctly. cc: @fh-clau

**Comment by rich-iannone** [comment]
@ddsjoberg It seems like you're inadvertently creating a `<blockquote>` by using the unescaped `>` character when converting from markdown text to HTML. Try using `&gt;` instead (i.e., replace `>` with `&gt;` beforehand). Here are some examples of the difference using `commonmark::markdown_to_html()`:

```r
> commonmark::markdown_html("> hey")
[1] "<blockquote>\n<p>hey</p>\n</blockquote>\n"

> commonmark::markdown_html("&gt; hey")
[1] "<p>&gt; hey</p>\n"
```

You may want to try htmltools::htmlEscape() to make this easy. Example:

```r
> htmltools::htmlEscape("> < &")
[1] "&gt; &lt; &amp;"
```

**Comment by ddsjoberg** [comment]
Thank you @rich-iannone for the suggestion! So, this will work for HTML output, but wouldn't work for RTF (or the upcoming PDF), right?

**Comment by rich-iannone** [comment]
Sorry for the great amount of time between responses :(

I'd now recommend using the Unicode character (`"\U0003E"`) instead of the HTML entity. That should work well across output formats. I've been doing quite a few internal changes where HTML entities were replaced with Unicode `code-point` representations and so far, so good!
