### ISSUE TITLE
tbl summary two grouping variables

### ISSUE THREAD

**Issue by shanie-landen** [rstudio/gt#708]
I am trying to make a tbl summary with gt summary and am struggling to find a way to split up my data as I need it to be.

I have 3 cohorts, each containing males/females. I want the cohorts split, and then further split by sex, and then for the numbers to show how many individuals were healthy and what their ages are- for each sex- for each cohort. Here is what I **want** (I did it separately and copy pasted them on top of each other):
![image](https://user-images.githubusercontent.com/77825780/105455635-ee42a080-5cd7-11eb-96bb-626d456a8e4d.png)

(I have marked out the cohort names, but ideally just need them at the top, don't need it twice.)

Here is the closest I can get:
![image](https://user-images.githubusercontent.com/77825780/105456135-be47cd00-5cd8-11eb-8f94-790ea67647e3.png)

And this is my code:
```
table2 <-
  tbl_summary(
    all_des,
    by = Study, # split table by group
    label = list(Age ~ "Age (years)",Sex~"Sex"),
    statistic = list(all_continuous() ~ "{mean} ({sd})"),
    missing = "no" # don't list missing data separately
  ) %>%
  #add_n() %>% # add column with total number of non-missing observations
  #add_p() %>% # test for a difference between groups
  modify_header(label = "") %>% # update the column header
  bold_labels()
```

**Comment by ddsjoberg** [comment]
Hi @shanie-landen !

I think you meant to post this question to https://github.com/ddsjoberg/gtsummary FYI. For questions about how to use the gtsummary package, it's best to post on stackoverflow.com, use the gtsummary tag, and I will be notified of your post.

For your question, you'll want to utilize the `tbl_stack()` function.  See example below:

```r
library(gtsummary)
library(dplyr)

# Drug A
tbl_a <-
  trial %>%
  filter(trt == "Drug A") %>%
  select(age, grade, stage) %>%
  tbl_summary(by = stage) %>%
  modify_header(all_stat_cols() ~ "**{level}**")

# Drug B
tbl_b <-
  trial %>%
  filter(trt == "Drug B") %>%
  select(age, grade, stage) %>%
  tbl_summary(by = stage) %>%
  modify_header(all_stat_cols() ~ "**{level}**")

tbl_stack(list(tbl_a, tbl_b), group_header = c("Drug A", "Drug B"))
```
![image](https://user-images.githubusercontent.com/26774684/106365977-fc5f7500-6306-11eb-9db3-08e96be77b86.png)

**Comment by shanie-landen** [comment]
Hi Daniel

Thanks so much for replying and for your solution! Will post on stack
overflow next time.

Best
Shanie
