### ISSUE TITLE
Warning message: The `.dots` argument of `group_by()` is deprecated as of dplyr 1.0.0.

### ISSUE THREAD

**Issue by ddsjoberg** [rstudio/gt#709]
Hello, hello! 🍁 

It seems that something in the gt print function is throwing a warning that the  `.dots` argument of `group_by()` is deprecated as of dplyr 1.0.0. I have put together a small example that result in the warning. Hope it helps. 🌱 

``` r
library(gt)
packageVersion("gt")
#> [1] '0.2.2'
packageVersion("dplyr")
#> [1] '1.0.3'

tbl <-
  head(countrypops) %>%
  gt() %>%
  tab_style(
    style = cell_text(indent = px(10), align = "left"), 
    locations = cells_body(columns = vars(country_name), 
                           rows = !is.na(country_name))
  )

print(tbl)
#> Warning: The `.dots` argument of `group_by()` is deprecated as of dplyr 1.0.0.
#> This warning is displayed once every 8 hours.
#> Call `lifecycle::last_warnings()` to see where this warning was generated.
```

<sup>Created on 2021-01-26 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by rich-iannone** [comment]
Yes, I'm noticing a lot of this recently. Will need to fix this ASAP.

**Comment by sanjmeh** [comment]
The error still comes every 8 hours. 
Any news of its fixing? Thanks.

**Comment by rich-iannone** [comment]
@sanjmeh update the gt package and I think this problem will go away
