### ISSUE TITLE
Padding between columns

### ISSUE THREAD

**Issue by ymer** [rstudio/gt#711]
I would often like to increase the padding / spacing between columns. However, I cannot find a good way to do this.

tab_options has data_row.padding, but no column padding.

I can set cols_width, but if I don't know the length of the longest content, I risk breaking up the line.

**Comment by rich-iannone** [comment]
Do you mean internal padding in the cell? Also, do you intend to output in HTML? If both of those are true, you can use `tab_style()`, target the cells that need left/right padding, and use CSS rules (`padding-left` and `padding-right`).

**Comment by sactyr** [comment]
What's the best way to do this please? I am trying to increase top and bottom padding in column labels, but can't get it to work. The default seems to 5px and 6px however there is no options under tab_options for column_labels (i.e. column_labels.padding). The other thing is using tab_style I am assuming padding will come under cell_borders but I could be wrong.
```
tab_style(
      style = list(
        cell_borders(
          sides = c("top", "bottom")
          ,'padding-top' = px(10)
          ,'padding-bottom' = px(10)
        )
      )
      ,locations = list(
        cells_column_labels(everything())
      )
    )
```

**Comment by rich-iannone** [comment]
@sactyr Sorry I didn't respond sooner, with `tab_style()` you can use arbitrary CSS rules. So this will work

```r
library(gt)

exibble %>%
  gt() %>%
  tab_style(
    style = "padding-top:12px;padding-bottom:12px;",
    locations = cells_column_labels()
  )
```

to give you this:

<img width="955" alt="table" src="https://user-images.githubusercontent.com/5612024/116302597-60130600-a76f-11eb-88b9-52f8f1056749.png">

**Comment by ymer** [comment]
I am interested in having some more space between all the columns in all the tables I make.

If I put
```
tab_style(
        style = "padding-right:80px",
        locations = cells_column_labels()
        )
```

This works if none of the colums are very wide. But if one of the colums are not that wide, it doesn't get much padding. Also the other columns get more padding if they are less wide.
