### ISSUE TITLE
tidyselect `where` doesn't work in columns arguments

### ISSUE THREAD

**Issue by jcheng5** [rstudio/gt#716]
`tidyselect::eval_select` makes `where` available, but isn't suitable for `resolve_data_val_idx` because its return value MUST be a valid index into the data, and sometimes ours are rows. `tidyselect::with_vars` doesn't care about the return value (which is good) but doesn't know about the data frame.

(Idea: use `eval_select` but have it return `NULL` after doing a superassign)

**Comment by jcheng5** [comment]
This turns out to be harder than expected. We do several kinds of resolving today, across several different resolving functions:

* Resolve columns, return names
* Resolve columns, return indices
* Resolve rows, return names
* Resolve rows, return indices

(Returning names vs indices can be ignored for right now)

## Resolving columns

* Want to be able to let users use tidyselect's `where()`. As far as we can tell, this currently requires `eval_select`.
* Want to be able to let user-provided expr evaluate to `NULL`, numeric, character, logical, or quosure (`vars()`). Currently, `eval_select` errors if you return logical or quosure.
* Of course, need to be able to access variables in lexical scope of any quosures. (I only mention this because one prototype of ours involved replacing the environment of the user-provided expr.)

## Resolving rows

* Want to have the data frame columns present as a data mask, so you can do something like `rows = currency > 100` on `exibble`, for example.
* Do NOT necessarily need access to `where()`--I'm not sure what you'd use it for.
* Want to be able to let user-provided expr evaluate to the same things above.
* As I said in the original comment, the return values are not going to correspond with columns but rather rows, so `eval_select` is not going to like that either.

**Comment by jcheng5** [comment]
Options for resolving columns:

1. Migrate to tidyselect semantics. This will break backwards compatibility in terms of logical and quosures being returned. Maybe we can help provide migration strategies for a time (i.e. trying tidyselect and if that fails then falling back to the old way, with a deprecation warning if the latter succeeds).
2. Try to hack our way through extending `tidyselect::eval_select` to work for columns by effectively supporting logical and quosure results.
3. See if we can get changes into tidyselect to implement logical/quosure support.
4. Implement the semantics we want ourselves.

For rows, I think we just need to use `rlang::eval_tidy` and that's it.

I'll talk to Hadley about this on Friday.

**Comment by jcheng5** [comment]
Talked to Hadley, the clear conclusion was to go with 1: migrate to tidyselect semantics, with shims implemented by inspecting the AST. I learned two new facts that heavily weighted towards this conclusion:

1. The `vars()` function was never intended to be used this way, it's supposed to be bare column names. This is why the implementation for this in gt is so funky.
2. Although logical selectors for columns are supported, they've never actually been documented. Not to say that we should just drop support, but, I don't feel bad about deprecating with a message. (I also could not come up with a reason to use logicals besides `TRUE`, and `everything()` is a fine equivalent.)

Notes from our meeting, in code form.

```r
library(gt)

# These are unchanged by moving to tidyselect
gt(exibble) %>% cols_hide(columns = 1)
gt(exibble) %>% cols_hide(columns = "currency")
gt(exibble) %>% cols_hide(columns = starts_with("n"))

# These will break or change by moving to tidyselect; implement shims
gt(exibble) %>% cols_hide(columns = NULL) # backwards semantics
gt(exibble) %>% cols_hide(columns = TRUE) # not supported by tidyselect, not documented by gt
gt(exibble) %>% cols_hide(columns = vars(fctr, datetime)) # mistake

# These do not work with gt today, but will start working with tidyselect
gt(exibble) %>% cols_hide(columns = where(is.numeric))
gt(exibble) %>% cols_hide(columns = fctr)
gt(exibble) %>% cols_hide(columns = everything())

# Works in gt and tidyselect, but tidyselect gives a warning asking you to do it differently
x <- c("fctr", "datetime")
gt(exibble) %>% cols_hide(columns = x)

# This works in gt but doesn't with tidyselect, and can't be shimmed using just the AST
x <- vars(fctr, datetime)
gt(exibble) %>% cols_hide(columns = x)
```

Hadley also confirmed that rows just need to use `rlang::eval_tidy`.

**Comment by jcheng5** [comment]
In process, we are also rationalizing the various code paths that resolve rows, row groups, summary rows, spanner ids. The semantics for all of these is different than column selection, and more closely match `dplyr::filter()`, with a couple of differences, some for convenience and some for backwards compatibility:

1. logical and numeric results are interpreted identically in `filter` and `gt`
2. Unlike `filter`, some tidyselect select helpers are supported in `gt`; they operate against row names (which dplyr pretends don't exist), group names, spanner ids, etc.
3. `NULL` is not supported by `filter`. In the past it has meant `TRUE` in `gt`. In the future, we will continue to interpret it as `TRUE` but discourage this usage with a warning. In the far future perhaps we would error as well, who knows.

**Comment by rich-iannone** [comment]
Fixed by https://github.com/rstudio/gt/pull/718.
