### ISSUE TITLE
Rowname_col cell footnotes not appearing

### ISSUE THREAD

**Issue by CarlssonLeo** [rstudio/gt#722]
Second issue published, so please come with suggestions for how to improve my issue writing :) 

While playing around, I tried to make a footnote on one of the rownames in the rowname cols, but failed and failed. When dropping the `"rowname_col"` argument it then works. I've googled and tried to find an answer, but has so far not found anything on whether this is expected behaviour or a bug. 

If it's expected behaviour, I believe it should change, since it's not unreasonable to want to add footnotes to an entire row, and not wanting that footnote to be on every cell in that row.

PS. I've deleted some of the HTML that did not render correctly in the reprex, for ease of readability. If that's needed, just tell me and I'll add it back :) 

---
``` r
library(tidyverse)
library(gt)

prognos_v10 <- tibble::tribble(
        ~`year_month`, ~numbers,
        "2021 May",    506000,
        "2021 June",    618000,
        "2021 Juli",  2900000
)

prognos_v10 %>% 
        gt(rowname_col = "year_month") %>% 
        fmt_number(vars(numbers), 
                   use_seps = TRUE, 
                   decimals = 0, 
                   suffixing = TRUE) %>%   
        tab_footnote(footnote = "2021 Juli has a footnote",
                     locations = cells_body(columns = vars(year_month),
                                            rows = year_month == "2021 Juli"))
```

<div id="nqchepmbir" style="overflow-x:auto;overflow-y:auto;width:auto;height:auto;"><table class="gt_table">
  
  <thead class="gt_col_headings">
    <tr>
      <th class="gt_col_heading gt_columns_bottom_border gt_left" rowspan="1" colspan="1"></th>
      <th class="gt_col_heading gt_columns_bottom_border gt_right" rowspan="1" colspan="1">numbers</th>
    </tr>
  </thead>
  <tbody class="gt_table_body">
    <tr><td class="gt_row gt_left gt_stub">2021 May</td>
<td class="gt_row gt_right">506K</td></tr>
    <tr><td class="gt_row gt_left gt_stub">2021 June</td>
<td class="gt_row gt_right">618K</td></tr>
    <tr><td class="gt_row gt_left gt_stub">2021 Juli</td>
<td class="gt_row gt_right">3M</td></tr>
  </tbody>
  

<div id="vitmpchkfh" style="overflow-x:auto;overflow-y:auto;width:auto;height:auto;"><table class="gt_table">
  
  ```r
prognos_v10 %>% 
        gt() %>% 
        fmt_number(vars(numbers), 
                   use_seps = TRUE, 
                   decimals = 0, 
                   suffixing = TRUE) %>%   
        tab_footnote(footnote = "2021 Juli has a footnote",
                     locations = cells_body(columns = vars(year_month),
                                            rows = year_month == "2021 Juli"))
```
  <thead class="gt_col_headings">
    <tr>
      <th class="gt_col_heading gt_columns_bottom_border gt_left" rowspan="1" colspan="1">year_month</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_right" rowspan="1" colspan="1">numbers</th>
    </tr>
  </thead>
  <tbody class="gt_table_body">
    <tr><td class="gt_row gt_left">2021 May</td>
<td class="gt_row gt_right">506K</td></tr>
    <tr><td class="gt_row gt_left">2021 June</td>
<td class="gt_row gt_right">618K</td></tr>
    <tr><td class="gt_row gt_left">2021 Juli<sup class="gt_footnote_marks">1</sup></td>
<td class="gt_row gt_right">3M</td></tr>
  </tbody>
  
  <tfoot>
    <tr class="gt_footnotes">
      <td colspan="2">
        <p class="gt_footnote">
          <sup class="gt_footnote_marks">
            <em>1</em>
          </sup>
           
          2021 Juli has a footnote
  </tfoot>
</table></div>

<sup>Created on 2021-03-13 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>

**Comment by rich-iannone** [comment]
You were pretty close! The key to making this work is to use the `cells_stub()` location helper function. Here's the modified code:

```r
library(tidyverse)
library(gt)

prognos_v10 <- tibble::tribble(
  ~`year_month`, ~numbers,
  "2021 May",    506000,
  "2021 June",    618000,
  "2021 Juli",  2900000
)

prognos_v10 %>% 
  gt(rowname_col = "year_month") %>% 
  fmt_number(
    vars(numbers), 
    use_seps = TRUE, 
    decimals = 0, 
    suffixing = TRUE
  ) %>%   
  tab_footnote(
    footnote = "2021 Juli has a footnote",
    locations = cells_stub(
      rows = year_month == "2021 Juli"
    )
  )
```

And here's the table:

<img width="660" alt="table" src="https://user-images.githubusercontent.com/5612024/116164137-30102800-a6c7-11eb-89ba-b94f4a964a88.png">
