### ISSUE TITLE
Enhancement - Ability to embed shiny inputs within gt tables

### ISSUE THREAD

**Issue by sactyr** [rstudio/gt#723]
---

Would it be possible to embed shiny inputs (actionButton, selectInput, checkbox etc) within gt tables? Currently the only way this can be done is by using datatables and javascript as per the links below:

https://thatdatatho.com/adding-action-buttons-in-rows-of-dt-data-table-in-r-shiny/
https://antoineguillot.wordpress.com/2017/03/01/three-r-shiny-tricks-to-make-your-shiny-app-shines-33-buttons-to-delete-edit-and-compare-datatable-rows/
https://community.rstudio.com/t/how-to-use-shiny-action-button-in-datatable-through-shiny-module/39998/2

Use cases/benefits - this will allow shiny users to select rows in the table by using checkboxes, or to categorise rows of data by using selectInputs, or by using actionButtons one can delete that row or using textInput to add comments to particular row of data. This will open up a whole new world in shiny/table interactivity.

---

**Comment by JPerGo** [comment]
Hello @sactyr , currently with the `gt::html()` function and some creativity I could achieve this same functionality from shiny. 
Here is a small reprex of my code:

      library(shiny)
      library(gt)
      library(tidyverse)
      
      # Define sample data
      iris_tibble <- 
        iris %>% 
        group_by(Species) %>% 
        slice(1:3) %>% 
        as_tibble() %>% 
        ungroup()
      
      ui <- 
        fluidPage(
          gt_output("iris_example"),
          verbatimTextOutput("checkbox"),
          verbatimTextOutput("select"),
          verbatimTextOutput("text")
        )
      
      checkbox_gt <- function(value, inputid,...){
        as.character(
          shiny::checkboxInput(
            inputId = paste0(value,inputid),
            ...
          )
        ) %>% 
          gt::html()
      }
      
      selectinput_gt <- function(value, inputid,...){
        as.character(
          shiny::selectInput(
            paste0(value,inputid),
            ...
          )
        ) %>% 
          gt::html()
      }
      
      textinput_gt <- function(value, inputid, ...){
        as.character(
          shiny::textInput(
            paste0(value,inputid),
            ...
          )
        ) %>% 
          gt::html()
      }
      
      
      server <- 
        function(input, output, session){
          
          output$iris_example <- render_gt(
            iris_tibble %>% 
              rownames_to_column() %>% 
              rowwise() %>% 
              mutate(
                rowname = as.numeric(rowname),
                checkbox_column = map(rowname, .f = ~checkbox_gt(.x, "_checkbox",label = paste("My cb label", .x))),
                selectinput_column = map(rowname,.f = ~selectinput_gt(.x, "_selectinput", label = paste("My select label", .x),choices = c("Yes","No"), selected = "Yes")),
                textinput_column = map(rowname, .f = ~textinput_gt(.x,"_textinput", label = paste("My text label", .x)))
              ) %>% 
              group_by(Species) %>% 
              gt()
          )
          
          output$checkbox <- renderText({
            map_chr(
              .x = 1:nrow(iris_tibble),
              .f = ~input[[paste0(.x,"_checkbox")]]
            )
          })
          
          output$select <- renderText({
            map_chr(
              .x = 1:nrow(iris_tibble),
              .f = ~input[[paste0(.x,"_selectinput")]]
            )
          })
          
          output$text <- renderText({
            map_chr(
              .x = 1:nrow(iris_tibble),
              .f = ~input[[paste0(.x,"_textinput")]]
            )
          })
          
        }
      
      
      shinyApp(ui,server)

At the bottom of the app you can find the values from the shiny inputs of the table.

Hope this helps! :)

**Comment by sactyr** [comment]
Thanks @JPerGo this is awesome, I have just tested this and it works great!

**Comment by Nova-Scotia** [comment]
Getting lots of errors and warnings when I run that example - I reduced the code to just include the text boxes, and am getting some errors. Would love to get this working!

```
library(shiny)
library(gt)
library(tidyverse)

# Define sample data
iris_tibble <- 
  iris %>% 
  group_by(Species) %>% 
  slice(1:3) %>% 
  as_tibble() %>% 
  ungroup()

ui <- 
  fluidPage(
    gt_output("iris_example"),
    verbatimTextOutput("checkbox")
  )

checkbox_gt <- function(value, inputid,...){
  as.character(
    shiny::checkboxInput(
      inputId = paste0(value,inputid),
      ...
    )
  ) %>% 
    gt::html()
}


server <- 
  function(input, output, session){
    
    output$iris_example <- render_gt(
      iris_tibble %>% 
        rownames_to_column() %>% 
        rowwise() %>% 
        mutate(
          rowname = as.numeric(rowname),
          checkbox_column = map(rowname, .f = ~checkbox_gt(.x, "_checkbox",label = paste("My cb label", .x))))
         %>% 
        group_by(Species) %>% 
        gt()
    )
    
    output$checkbox <- renderText({
      map_chr(
        .x = 1:nrow(iris_tibble),
        .f = ~input[[paste0(.x,"_checkbox")]]
      )
    })
    
    
  }


shinyApp(ui,server)

```

Errors and warnings
```
Listening on http://...
Warning: Error in map_chr: ℹ In index: 1.
Caused by error:
! Result must be length 1, not 0.
  113: <Anonymous>
  112: signalCondition
  111: signal_abort
  110: rlang::abort
  109: cli::cli_abort
  108: h
  107: .handleSimpleError
  106: call_with_cleanup
  103: map_
  102: map_chr
  101: renderText [C:\Users\NewtonEr\OneDrive - Government of Ontario\Documents\LargeMammal\MooseProject\gt_shiny_select_test/app.R#46]
  100: func
   87: renderFunc
   86: output$checkbox
    1: runApp
Input to asJSON(keep_vec_names=TRUE) is a named vector. In a future version of jsonlite, this option will not be supported, and named vectors will be translated into arrays instead of objects. If you want JSON object output, please use a named list instead. See ?toJSON.
Warning: Automatic coercion from logical to character was deprecated in purrr 1.0.0.
ℹ Please use an explicit call to `as.character()` within `map_chr()` instead.
Call `lifecycle::last_lifecycle_warnings()` to see where this warning was generated.
```
