### ISSUE TITLE
Add pandoc as an engine of `fmt_markdown()`

### ISSUE THREAD

**Issue by atusy** [rstudio/gt#725]
Currently, `fmt_markdown` internally uses **commonmark** package for conversion of markdown texts.
I would like to suggest pandoc as an optional engine.
In this way, we can use Pandoc's Markdown which is consistent with R Markdown.
This will allow wider variety of inline formatting such as superscript and subscript, and also allow complex features like citations.

Just to give a hint to implement citations, `ftExtra::colformat_md` for flextable internally reads `rmarkdown::metadata` to fetch bibliographies (https://github.com/atusy/ftExtra/blob/master/R/md2ast.R#L8), and then output citation keys as a part of YAML meta data block so to invisibly make sure citations appear in the reference (https://github.com/atusy/ftExtra/blob/master/R/knit-print.R#L20-L24).

**Comment by maia-sh** [comment]
+1 for this feature. In the meanwhile, is there any existing workaround to add a citation (of the format `@mycitationkey`) to a `gt` table?

**Comment by LukasWallrich** [comment]
Until this is implemented, it would be great to document the limitations (or available MD features) in `?md` - it took me a while to understand why `~sub~script` worked in RMarkdown until I moved it into a table.
