### ISSUE TITLE
Soft deprecation for `columns = vars(...)` ?

### ISSUE THREAD

**Issue by ddsjoberg** [rstudio/gt#730]
Hello hello!

I installed the dev version of gt, and ran a gtsummary table. I am now seeing multiple deprecation messages about `columns = vars(...)` when I create a gtsummary table.

Can this be changed to a soft deprecation, like `lifecycle::deprecate_soft()` which warns only if the deprecated function is called from the global environment, or update so the note is only posted once per session (like in `lifecycle::deprecate_warn()`)?  I'll update gtsummary soon, I promise!

Thanks @rich-iannone ! 🍁 

```r
> library(gtsummary)
> tbl_summary(trial)

Warning messages:
1: `columns = vars(...)` is deprecated since gt 0.2.3:
* please use `columns = c(...)` instead 
2: `columns = vars(...)` is deprecated since gt 0.2.3:
* please use `columns = c(...)` instead 
3: `columns = vars(...)` is deprecated since gt 0.2.3:
* please use `columns = c(...)` instead 
4: `columns = vars(...)` is deprecated since gt 0.2.3:
* please use `columns = c(...)` instead 
5: `columns = vars(...)` is deprecated since gt 0.2.3:
* please use `columns = c(...)` instead 
```

**Comment by rich-iannone** [comment]
We decided against using {lifecycle} for the time being. However, if you want to avoid this in your package, the always safe thing to do (and works with the on-CRAN {gt}, dev {gt}, and future releases of {gt}) is to use column names in double quotes. Not great for interactive use but actually ideal when programming with {gt} (i.e., making complex functions with {gt}).

The {gt} package does this in https://github.com/rstudio/gt/blob/master/R/info_tables.R , and I have another package that uses {gt} to generate tables and the same style is used.

**Comment by ddsjoberg** [comment]
Great! I thought the `vars()` syntax was required! This is the perfect solution
