### ISSUE TITLE
Bold style bug in HTML output

### ISSUE THREAD

**Issue by ddsjoberg** [rstudio/gt#731]
Hello hello!

When I use `tab_style()` to bold a column that is followed by a `tab_style()` for vertical alignment, the bold is ignored in the output. Example below

Thanks! 🍁  

``` r
library(gt)
packageVersion("gt")
#> [1] '0.2.2'

gt_tbl <-
  head(gt::sp500) %>%
  gt::gt() %>%
  gt::tab_style(
    style = "vertical-align:top",
    locations = gt::cells_body(columns = any_of("date"))) %>%
  gt::tab_style(
    style = gt::cell_text(weight = "bold"),
    locations = gt::cells_body(columns = gt::vars(date), 
                               rows = c(1L, 3L))
  )
#> Warning: `columns = vars(...)` is deprecated since gt 0.2.3:
#> * please use `columns = c(...)` instead
```

![image](https://user-images.githubusercontent.com/26774684/112729882-d8826f00-8f04-11eb-8d76-5f5ad8fbcfe1.png)

<sup>Created on 2021-03-27 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>

**Comment by ddsjoberg** [comment]
I was looking into this further, I think the bug is with the vertical alignment, not the bold weight.

In this example the vertical alignment breaks the thick border line, which should extend through the date column.

``` r
library(gt)
#> Warning: package 'gt' was built under R version 4.0.4
packageVersion("gt")
#> [1] '0.2.2'

tbl <-
  head(gt::sp500) %>%
  gt::gt() %>%
  gt::tab_style(style = "vertical-align:top", 
                locations = gt::cells_body(columns = vars(date))) %>%
  gt::tab_style(
    style = gt::cell_borders(sides = "top",
                             color = "#D3D3D3", 
                             weight = gt::px(10)), 
    locations = gt::cells_body(rows = 3)
  )
```
![image](https://user-images.githubusercontent.com/26774684/112772619-c76a5880-8fff-11eb-9ee4-0ea577936001.png)

<sup>Created on 2021-03-28 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>

**Comment by rich-iannone** [comment]
If you adjust your example such that the CSS style rule is terminated with a `;`, then it works! Here's the working example:

```r
head(gt::sp500) %>%
  gt::gt() %>%
  gt::tab_style(style = "vertical-align:top;", 
                locations = gt::cells_body(columns = vars(date))) %>%
  gt::tab_style(
    style = gt::cell_borders(
      sides = "top",
      color = "#D3D3D3", 
      weight = gt::px(10)
    ), 
    locations = gt::cells_body(rows = 3)
  )
```

Likewise, flipping the order of `tab_style()` statements makes it work. The reason is that the style rules are pasted together and the manual input of `"vertical-align:top"` results in no delimiter between rules (and malformed rule text, in the end).

@jcheng5 Is there something we could/should do here?
