### ISSUE TITLE
Documentation issue:  c() is used instead of vars() in example on https://gt.rstudio.com/reference/tab_spanner.html

### ISSUE THREAD

**Issue by dewoller** [rstudio/gt#733]
In the example on page https://gt.rstudio.com/reference/tab_spanner.html, c( )is used instead of vars(), as in the example in the cols_label documentation.  vars() works, c() doesn't. 

```r

  gtcars %>%
  dplyr::select(
    -mfr, -trim, bdy_style, drivetrain,
    -drivetrain, -trsmn, -ctry_origin
  ) %>%
  dplyr::slice(1:8) %>%
  gt(rowname_col = "model") %>%
  tab_spanner(
    label = "performance",
    columns = c(
      hp, hp_rpm, trq, trq_rpm,
      mpg_c, mpg_h)
  )
```

```r

  gtcars %>%
  dplyr::select(
    -mfr, -trim, bdy_style, drivetrain,
    -drivetrain, -trsmn, -ctry_origin
  ) %>%
  dplyr::slice(1:8) %>%
  gt(rowname_col = "model") %>%
  tab_spanner(
    label = "performance",
    columns = vars(
      hp, hp_rpm, trq, trq_rpm,
      mpg_c, mpg_h)
  )
```

**Comment by py9mrg** [comment]
I'm finding the same thing with lots of the documentation - presume there's been a tidy eval related change in the package. FOr example:

```
tab_1 <-
  gtcars %>%
  dplyr::filter(ctry_origin == "United Kingdom") %>%
  dplyr::select(mfr, model, year, hp) %>%
  gt() %>%
  tab_footnote(
    footnote = "Highest horsepower.",
    locations = cells_body(
      columns = hp,
      rows = hp == max(hp))
  ) %>%
  opt_footnote_marks(marks = c("*", "+"))
```

Gives an error that `hp` is not found, whereas replacing the `columns = hp` with any of the following will work:


```
      columns = vars(hp),
      columns = "hp",
      columns = c("hp"),

```

**Comment by rich-iannone** [comment]
The documentation on the pkgdown site (and the README) reflects the dev version of the package. It's a little unfortunate it is this way but things should be in sync when v0.3 is released to CRAN. In the meantime, either update to the dev version using `devtools::install_github("rstudio/gt")` or refer to the documentation in the package (e.g., `?fmt_number()`).
