### ISSUE TITLE
Setting `column_labels.border.bottom.width` with width of `px(1)` not working

### ISSUE THREAD

**Issue by ajjitn** [rstudio/gt#739]
I'm working on creating a `gt` theme for our organization (thanks for this great package!) and would like to adjust the width of `column_labels.border.bottm.width`argument inside `tab_options`. I am able to do this when I set the value of that argument to any value above `px(1.5)`. However in the case where I set `column_labels.border.bottm.witdth = px(1)` or any number below `px(1.5)`, there seems to be no effect.

So for example, this code
```
library(tidyverse)
library(gt)
cars %>% 
  slice(1:5) %>% 
  gt() %>% 
  tab_options(
    column_labels.border.bottom.color = "red",
    column_labels.border.bottom.width = px(3),
  )  
```
generates the following image as expected:

<img width="136" alt="Screen Shot 2021-04-15 at 5 43 11 PM" src="https://user-images.githubusercontent.com/34085716/114942237-3c1c0000-9e12-11eb-8ec4-09a1a412084b.png">

But changing to `px(1)`

```
cars %>% 
  slice(1:5) %>% 
  gt() %>% 
  tab_options(
    column_labels.border.bottom.color = "red",
    column_labels.border.bottom.width = px(1),
  )  
```
generates the following (incorrect looking) table:

<img width="136" alt="Screen Shot 2021-04-15 at 5 55 04 PM" src="https://user-images.githubusercontent.com/34085716/114943274-bdc05d80-9e13-11eb-91cb-3edc470e0177.png">

What is causing this, is it another border type that we also need to override/hide? Or are values below `px(1.5)` not allowed?

**Comment by ajjitn** [comment]
I've done some more digging into the default CSS and looks like the following CSS classes have conflicting/overlapping borders for the red strip in the pictures above. They are:

```
..gt_table_body {
   ...
    border-top-style: solid;
    border-top-width: 2px;
    border-top-color: #D3D3D3;
   ...
}

.gt_col_headings {
    ...
    border-bottom-style: solid;
    border-bottom-width: 2px;
    border-bottom-color: #D3D3D3;
    ...
}

.gt_row {
    ...
    border-top-style: solid;
    border-top-width: 1px;
    border-top-color: #D3D3D3;
    ...
    }

```

And it looks like when we set `column_labels.border.bottom.width = px(1)`, the borders from the other css classes win out.
So a workaround to get a `column_labels.border.bottom.width` of 1 px, is to manually set the width of the other borders to 0. Using `gt` functions, we can do this with


```
cars %>% 
  slice(1:5) %>% 
  gt() %>% 
  tab_options(
    table_body.border.top.width = px(0),
    column_labels.border.bottom.width = px(1),
    column_labels.border.bottom.color = "red"
  ) %>% 
  tab_style(
    style = 
      cell_borders(
        sides = c("top"),
        weight = px(0)
      ),
    locations = 
      cells_body(
        columns =  c(speed, dist)
      )
  )
```

which produces

<img width="128" alt="Screen Shot 2021-04-21 at 6 47 02 PM" src="https://user-images.githubusercontent.com/34085716/115630432-fc518e80-a2d1-11eb-9380-5680aa02af61.png">

This works if you're fine with no cell borders in the interior of the table.

**Comment by ajjitn** [comment]
The process of debugging this made me realize how helpful it could be to have a visual graphic of what each of the various border options available in `tab_options` corresponds to in a gt table (perhaps using the same graphic that lays out parts of a gt table: https://gt.rstudio.com/). I'm happy to take a first stab at creating something like this as I've been playing around with gt borders for a while now if that's helpful!

**Comment by rich-iannone** [comment]
Sorry for the extremely long time in getting to respond here :(

Yes, this surprised me as well a long time ago during testing with borders. Bigger borders tend to 'win' when they are shared and this went against my assumption that later defined borders would paint over top previously defined ones. I thought about making the behavior work in the more obvious way but I found it to be a pretty difficult problem (fighting HTML, in a sense).

I do think extra documentation that clearly explains the rules would be useful here! Will close this issue since it seems that the question was self-answered, but I'll always look at PRs that provide useful docs. :)
