### ISSUE TITLE
pct() function to modify cols width doesn't work

### ISSUE THREAD

**Issue by SCasanova** [rstudio/gt#741]
When setting the width of the columns with cols_width, it reacts normally to pixel inputs but when using the pct function it defaults to 100 and won't adjust to new values

---

<brief description of the problem>

```r
<insert reprex here>
```

**Comment by rich-iannone** [comment]
You should try out this exhaustive set of examples with `cols_width()`: https://github.com/rstudio/gt/blob/master/tests/gt-examples/01-html-script/html-17-table_width_specifications.R. It'll give you a better feel for how `pct()`, `px()`, etc. can be used to size columns.
