### ISSUE TITLE
tab_spanner_delim() with gather = T still not working

### ISSUE THREAD

**Issue by martinschlund** [rstudio/gt#745]
---

Hello, 
I have encountered a bug in tab_spanner_delim as it does not group together the variables as expected, though gather is set to TRUE. I see a closed issue on the same problem in fall 2020 but the problem seems to persist. I believe I run the latest version of gt in R for windows 3.6.1: 

```r
<#this works as expected: 
iris %>%
  dplyr::group_by(Species) %>%
  dplyr::slice(1:4) %>%
  gt() %>%
  tab_spanner_delim(delim = ".")

#this does not: 
testtib <- tibble(a.1 = 1:3, b.2 = 1:3, a.2 = 1:3, b.1 = 1:3)

testtib %>% gt() %>% 
  tab_spanner_delim(delim = '.', gather = T)
```
Best regards, 

Martin

**Comment by rich-iannone** [comment]
Hi @martinschlund , I just confirmed this works in the development version of the package. You can test it out by first installing gt from GitHub with `devtools::install_github("rstudio/gt")`.
