### ISSUE TITLE
GT table not applying style to all summary rows

### ISSUE THREAD

**Issue by jat255** [rstudio/gt#752]
I'm having some trouble styling a table using `gt` related to summary rows. I've confirmed that this happens on both v0.2.2 and the latest `master` (which has some changes related to cell locators). The issue is that the `cells_summary()` locator (and the `cells_stub_summary()` in the latest `master` for some reason doesn't apply to the first group summary. Here's a simplified example from my use case that strips out everything else to just show the answer:

```r
tibble(
  div_num=c("630", "641", "643", "643", "646", "647"), 
  group_num=c("01","02","09","10","05","02"), 
  count=as.integer(c(1,1,1,1,8,2))
) %>% 
  group_by(div_num) %>% 
  gt(rowname_col = 'group_num') %>% 
  summary_rows(
    groups = TRUE,
    columns = vars(count),
    fns = list(`Division total: `="sum"),
    formatter = fmt_number,
    decimals = 0
  ) %>% tab_style(
    style = list(
      cell_text(
        weight = "bold",
        size = px(12)
      ),
      cell_fill("red")
    ),
    locations = cells_summary()
  ) 
```

![image](https://user-images.githubusercontent.com/1278301/116829412-2e2fe400-ab61-11eb-9743-65a289dc5d88.png)

Any ideas on why this might be happening?

**Comment by rich-iannone** [comment]
I could reproduce this, and it's a definite bug. Not sure why this is happening but we'll get to the bottom of this soon. Thanks for reporting!
