### ISSUE TITLE
Problem with R 4.1.0

### ISSUE THREAD

**Issue by jcpb1971** [rstudio/gt#766]
Dear all,

not sure if this is a gt bug or something different.

I have updated to R 4.1.0 and gt version 0.3. The following very simple code works

```{r}
library(gt)
gt(exibble, rowname_col = "row", groupname_col = "group")
```

As expected. However if I try to run this in rmarkdown 

```
---
output:
  pdf_document: default
  html_document: default
---
```

```{r}
library(gt)
gt(exibble, rowname_col = "row", groupname_col = "group")
``` 

it generates an error if knitted to pdf; if knitted to html it works.

Funny enough the following code

```
---
output:
  pdf_document: default
  html_document: default
---
```
```{r}
library(gt)
gt(exibble, rowname_col = "row")
``` 

can be knitted (both to pdf and html). Any ideas?

Regards

**Comment by jcpb1971** [comment]
Btw, with version 0.2.2 of gt (and R 4.1.0) it works

**Comment by rich-iannone** [comment]
This was fixed with https://github.com/rstudio/gt/pull/768. If you update to the latest dev version of gt, this should work now.
