### ISSUE TITLE
Summary rows not rendering properly while saving as RTF file

### ISSUE THREAD

**Issue by galactose310** [rstudio/gt#769]
Dear all,

I faced an issue trying to export as RTF file. Here is the code to reproduce the issue :
```r
tbl <- ratio %>% # tibble with cols: id, res_plasma, res_peritoine, temps, 
	mutate(ratio = ratio * 100) %>%
	pivot_wider(names_from = temps, values_from = c(res_plasma, res_peritoine, ratio)) %>%
	gt::gt(rowname_col = "id") %>%
	gt::tab_stubhead(label = "Patient") %>%
	gt::tab_spanner(
		label = "Taux résiduel à H12",
		columns = matches("_H12")
	) %>%
	gt::tab_spanner(
		label = "Taux résiduel à H24",
		columns = matches("_H24")
	) %>%
	gt::tab_spanner(
		label = "Taux résiduel à H72",
		columns = matches("_H72")
	) %>%
	gt::cols_label(...) %>%
	gt::summary_rows(
		fns = list(
			"Moyenne" = ~mean(., na.rm = TRUE),
			"Ecart-type" = ~sd(., na.rm = TRUE)
		),
		columns = c(
			res_plasma_H12, res_peritoine_H12, ratio_H12,
			res_plasma_H24, res_peritoine_H24, ratio_H24,
			res_plasma_H72, res_peritoine_H72, ratio_H72)
	)
tbl %>% gt::gtsave(filename = "tbl.rtf")
tbl
```

This works fine to display the right table as a plot.

Yet when I open the RTF file, lines generated by summary_rows() are wrong, like this :
![image](https://user-images.githubusercontent.com/20073561/119241650-5014f900-bb58-11eb-92a1-b9dd37f27f25.png)

The first columns shows "-" as if there was no data... And all results are shifted on the right so that the 2nd "Moyenne" should be the first, and the last does not appear at all.

I tried with CRAN version (0.3.0) and dev version (installed today).

Any idea to correct this ?

**Comment by rich-iannone** [comment]
This looks like an issue on our end (thanks for reporting it!). We will fix this as soon as we can.

**Comment by rich-iannone** [comment]
I've tried to generate an MRE and came up with this:

```r
library(gt)
library(tidyverse)

tbl <- 
  tibble(
    a = 1:5,
    b = 1:5 * 100,
    c = 1:5 * 2,
    d = 1:5,
    e = 1:5 * 100,
    f = 1:5 * 2,
    id = as.character(1:5)
  ) %>%
  gt::gt(rowname_col = "id") %>%
  gt::tab_stubhead(label = "stubhead") %>%
  gt::tab_spanner(
    label = "one",
    columns = c(a, b, c)
  ) %>%
  gt::tab_spanner(
    label = "two",
    columns = c(d, e, f)
  ) %>%
  gt::summary_rows(
    fns = list(
      "mean" = ~ mean(., na.rm = TRUE),
      "stdev" = ~ sd(., na.rm = TRUE)
    ),
    columns = c(a, b, c, d, e, f)
  )

tbl %>% gt::gtsave(filename = "tbl.rtf")
```

The thing is, the RTF table looked okay when opening it in Word:

<img width="1342" alt="tbl_rtf_word" src="https://user-images.githubusercontent.com/5612024/120386146-462c8c00-c2f6-11eb-8d8b-1ef32b825106.png">

Would you be able to either (1) provide all of your code, or, (2) attempt to produce a more minimal example (again, with complete code) that produces the same bug?
