### ISSUE TITLE
Inability to control cell padding within Table Header and Column Labels

### ISSUE THREAD

**Issue by samtrippy** [rstudio/gt#770]
The gt package allows for a few cell padding parameters to be passed within tab_options(). For example, _data_row.padding_ and _footnotes.padding_. However, there are no parameters available to control the Table Header or Column Labels parts of the gt Table.

**reprex with massive cell padding for demonstration:**
```r
gt_tbl <- gt(data = mtcars) %>% 
  tab_header(
     title = "mtcars dataset") %>% 
  tab_options(data_row.padding = px(35))

gt_tbl
```

**Comment by rich-iannone** [comment]
Thanks for the feature idea. I definitely agree that is something that is missing and would also be really useful!
