### ISSUE TITLE
Export internal RTF Rendering Functions

### ISSUE THREAD

**Issue by elimillera** [rstudio/gt#778]
We are looking to add support for gt tables in [pharmaRTF ](https://github.com/atorus-research/pharmaRTF) and we have a good idea about how this would work. This would rely on several functions in gt that are currently internal. Could these functions be exported in a future release?

These are the functions we are currently using to render the RTFs from gt objects
```
'gt:::build_data' 'gt:::create_body_component_rtf'
     'gt:::create_columns_component_rtf' 'gt:::rtf_file'
     'gt:::rtf_fonttbl'
```

**Comment by rich-iannone** [comment]
In personal communication it was agreed that the best strategy was to copy the needed functions since exporting them in gt wasn’t likely to happen. Closing.
