### ISSUE TITLE
Feature request: gt_print or print table in Rstudio when using gtsave()

### ISSUE THREAD

**Issue by oyvindbso** [rstudio/gt#781]
I think it would be very nice if gtsave() could have an option for printing the table in rstudio at the same time as saving the file or better if there was a code for printing the gt-table inside a longer pipe. 

I use gt() a lot for tables and my code usually looks something like:
```
mytable %>%
 gt() %>% 
  fmt_percent(columns=c(2,4,6),decimals =0) %>% 
gtsave("myfile.rtf")
```

What I would like was it was possible to print directly from i.e. gtsave("myfile",print=TRUE) or if a gt_print() that could be inserted into a longer pipe. This last option would look something like this:

```
mytable %>%
 gt() %>% 
  fmt_percent(columns=c(2,4,6),decimals =0) %>% 
  gt_print()%>%
  tab_row_group()%>% 
  tab_spanner() %>% 
gtsave("myfile.rtf")
```
Then I could check if my code worked well before the adding of the next elements.

**Comment by rich-iannone** [comment]
If you run the above statements sans the `gtsave()` part, you should be seeing the HTML table in the Viewer.

Is that what you’re asking for (and currently missing)?

**Comment by rich-iannone** [comment]
Noticed that you probably mean LaTeX and RTF files. There’s currently no good way to display rendered output in those output formats in the Viewer.
