### ISSUE TITLE
`as_latex()` broken when using `rowname_col`

### ISSUE THREAD

**Issue by burgerga** [rstudio/gt#786]
Similar to #622 also the `as_latex()` is broken when using `rowname_col`:

``` r
library(gt)
gtcars %>% gt(rowname_col = "model") %>% as_latex()
#> Error in row_splits[[x]]: subscript out of bounds
```

<sup>Created on 2021-06-02 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

**Comment by rich-iannone** [comment]
This has been fixed in https://github.com/rstudio/gt/pull/768. Could you update gt to the latest development version and try once more?

**Comment by burgerga** [comment]
Yes, completely solved! Thanks for your fast reply
