### ISSUE TITLE
Feature request: wrap column names

### ISSUE THREAD

**Issue by IsadoraBM** [rstudio/gt#799]
Related to [issue #181](https://github.com/rstudio/gt/issues/181), can gt wrap column names when they are long? I have tried renaming the variable using \n but of course it prints as string so `Very long name of a variable` prints as `Very long name \nof a variable`

**Comment by rich-iannone** [comment]
To make this work, you have to use `cols_label()` to specify styling of a label. These two options should work:

```r
library(gt)
library(tidyverse)

dplyr::tibble(var_1 = 1:3) %>%
  gt() %>%
  cols_label(var_1 = html("Very long name<br>of a variable"))

dplyr::tibble(var_1 = 1:3) %>%
  gt() %>%
  cols_label(var_1 = md("Very long name<br />of a variable"))
```

<img width="673" alt="gt_line_break_column_label" src="https://user-images.githubusercontent.com/5612024/121911260-9dbaf680-ccfd-11eb-8f70-2c7a3d23356d.png">
