### ISSUE TITLE
`fmt_scientific()` errors when processing an NA cell

### ISSUE THREAD

**Issue by rich-iannone** [rstudio/gt#80]
This will result in an error since the column contains `NA` values:

```r
exibble %>%
  gt(
    rowname_col = "row",
    groupname_col = "group"
  ) %>%
  fmt_scientific(
    columns = vars(num),
    rows = c(5, 7, 8)
  )
```

**Comment by krlmlr** [comment]
Note that this example doesn't err for me with 54e4dfb:

``` r
library(gt)
exibble %>%
  gt(
    rowname_col = "row",
    groupname_col = "group"
  ) %>%
  fmt_scientific(
    columns = vars(num),
    rows = c(5, 7, 8)
  )
```



<style>html {
  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Helvetica Neue', 'Fira Sans', 'Droid Sans', Arial, sans-serif;
}

#yuidcmrksh .gt_table {
  display: table;
  border-collapse: collapse;
  margin-left: auto;
  margin-right: auto;
  color: #000000;
  font-size: 16px;
  background-color: #FFFFFF;
  /* table.background.color */
  width: auto;
  /* table.width */
  border-top-style: solid;
  /* table.border.top.style */
  border-top-width: 2px;
  /* table.border.top.width */
  border-top-color: #A8A8A8;
  /* table.border.top.color */
}

#yuidcmrksh .gt_heading {
  background-color: #FFFFFF;
  /* heading.background.color */
  border-bottom-color: #FFFFFF;
}

#yuidcmrksh .gt_title {
  color: #000000;
  font-size: 125%;
  /* heading.title.font.size */
  padding-top: 4px;
  /* heading.top.padding */
  padding-bottom: 1px;
  border-bottom-color: #FFFFFF;
  border-bottom-width: 0;
}

#yuidcmrksh .gt_subtitle {
  color: #000000;
  font-size: 85%;
  /* heading.subtitle.font.size */
  padding-top: 1px;
  padding-bottom: 4px;
  /* heading.bottom.padding */
  border-top-color: #FFFFFF;
  border-top-width: 0;
}

#yuidcmrksh .gt_bottom_border {
  border-bottom-style: solid;
  /* heading.border.bottom.style */
  border-bottom-width: 2px;
  /* heading.border.bottom.width */
  border-bottom-color: #A8A8A8;
  /* heading.border.bottom.color */
}

#yuidcmrksh .gt_column_spanner {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #A8A8A8;
  padding-top: 4px;
  padding-bottom: 4px;
}

#yuidcmrksh .gt_col_heading {
  color: #000000;
  background-color: #FFFFFF;
  /* column_labels.background.color */
  font-size: 16px;
  /* column_labels.font.size */
  font-weight: initial;
  /* column_labels.font.weight */
  vertical-align: middle;
  padding: 10px;
  margin: 10px;
}

#yuidcmrksh .gt_sep_right {
  border-right: 5px solid #FFFFFF;
}

#yuidcmrksh .gt_group_heading {
  padding: 8px;
  color: #000000;
  background-color: #FFFFFF;
  /* stub_group.background.color */
  font-size: 16px;
  /* stub_group.font.size */
  font-weight: initial;
  /* stub_group.font.weight */
  border-top-style: solid;
  /* stub_group.border.top.style */
  border-top-width: 2px;
  /* stub_group.border.top.width */
  border-top-color: #A8A8A8;
  /* stub_group.border.top.color */
  border-bottom-style: solid;
  /* stub_group.border.bottom.style */
  border-bottom-width: 2px;
  /* stub_group.border.bottom.width */
  border-bottom-color: #A8A8A8;
  /* stub_group.border.bottom.color */
  vertical-align: middle;
}

#yuidcmrksh .gt_empty_group_heading {
  padding: 0.5px;
  color: #000000;
  background-color: #FFFFFF;
  /* stub_group.background.color */
  font-size: 16px;
  /* stub_group.font.size */
  font-weight: initial;
  /* stub_group.font.weight */
  border-top-style: solid;
  /* stub_group.border.top.style */
  border-top-width: 2px;
  /* stub_group.border.top.width */
  border-top-color: #A8A8A8;
  /* stub_group.border.top.color */
  border-bottom-style: solid;
  /* stub_group.border.bottom.style */
  border-bottom-width: 2px;
  /* stub_group.border.bottom.width */
  border-bottom-color: #A8A8A8;
  /* stub_group.border.bottom.color */
  vertical-align: middle;
}

#yuidcmrksh .gt_striped {
  background-color: #f2f2f2;
}

#yuidcmrksh .gt_row {
  padding: 10px;
  /* row.padding */
  margin: 10px;
  vertical-align: middle;
}

#yuidcmrksh .gt_stub {
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #A8A8A8;
  padding-left: 12px;
}

#yuidcmrksh .gt_stub.gt_row {
  background-color: #FFFFFF;
}

#yuidcmrksh .gt_summary_row {
  background-color: #FFFFFF;
  /* summary_row.background.color */
  padding: 6px;
  /* summary_row.padding */
  text-transform: inherit;
  /* summary_row.text_transform */
}

#yuidcmrksh .gt_first_summary_row {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #A8A8A8;
}

#yuidcmrksh .gt_table_body {
  border-top-style: solid;
  /* field.border.top.style */
  border-top-width: 2px;
  /* field.border.top.width */
  border-top-color: #A8A8A8;
  /* field.border.top.color */
  border-bottom-style: solid;
  /* field.border.bottom.style */
  border-bottom-width: 2px;
  /* field.border.bottom.width */
  border-bottom-color: #A8A8A8;
  /* field.border.bottom.color */
}

#yuidcmrksh .gt_footnote {
  font-size: 90%;
  /* footnote.font.size */
  padding: 4px;
  /* footnote.padding */
}

#yuidcmrksh .gt_sourcenote {
  font-size: 90%;
  /* sourcenote.font.size */
  padding: 4px;
  /* sourcenote.padding */
}

#yuidcmrksh .gt_center {
  text-align: center;
}

#yuidcmrksh .gt_left {
  text-align: left;
}

#yuidcmrksh .gt_right {
  text-align: right;
  font-variant-numeric: tabular-nums;
}

#yuidcmrksh .gt_font_normal {
  font-weight: normal;
}

#yuidcmrksh .gt_font_bold {
  font-weight: bold;
}

#yuidcmrksh .gt_font_italic {
  font-style: italic;
}

#yuidcmrksh .gt_super {
  font-size: 65%;
}

#yuidcmrksh .gt_footnote_glyph {
  font-style: italic;
  font-size: 65%;
}
</style>

<div id="yuidcmrksh" style="overflow-x:auto;">



<table class="gt_table">

<tr>

<th class="gt_col_heading gt_left" rowspan="1" colspan="1">

</th>

<th class="gt_col_heading gt_right" rowspan="1" colspan="1">

num

</th>

<th class="gt_col_heading gt_left" rowspan="1" colspan="1">

char

</th>

<th class="gt_col_heading gt_center" rowspan="1" colspan="1">

fctr

</th>

<th class="gt_col_heading gt_left" rowspan="1" colspan="1">

date

</th>

<th class="gt_col_heading gt_left" rowspan="1" colspan="1">

time

</th>

<th class="gt_col_heading gt_left" rowspan="1" colspan="1">

datetime

</th>

<th class="gt_col_heading gt_right" rowspan="1" colspan="1">

currency

</th>

</tr>

<tbody class="gt_table_body">

<tr class="gt_group_heading_row">

<td colspan="8" class="gt_group_heading">

grp\_a

</td>

</tr>

<tr>

<td class="gt_row gt_stub gt_left">

row\_1

</td>

<td class="gt_row gt_right">

0.1111

</td>

<td class="gt_row gt_left">

apricot

</td>

<td class="gt_row gt_center">

one

</td>

<td class="gt_row gt_left">

2015-01-15

</td>

<td class="gt_row gt_left">

13:35

</td>

<td class="gt_row gt_left">

2018-01-01 02:22

</td>

<td class="gt_row gt_right">

49.950

</td>

</tr>

<tr>

<td class="gt_row gt_stub gt_left">

row\_2

</td>

<td class="gt_row gt_right gt_striped">

2.2220

</td>

<td class="gt_row gt_left gt_striped">

banana

</td>

<td class="gt_row gt_center gt_striped">

two

</td>

<td class="gt_row gt_left gt_striped">

2015-02-15

</td>

<td class="gt_row gt_left gt_striped">

14:40

</td>

<td class="gt_row gt_left gt_striped">

2018-02-02 14:33

</td>

<td class="gt_row gt_right gt_striped">

17.950

</td>

</tr>

<tr>

<td class="gt_row gt_stub gt_left">

row\_3

</td>

<td class="gt_row gt_right">

33.3300

</td>

<td class="gt_row gt_left">

coconut

</td>

<td class="gt_row gt_center">

three

</td>

<td class="gt_row gt_left">

2015-03-15

</td>

<td class="gt_row gt_left">

15:45

</td>

<td class="gt_row gt_left">

2018-03-03 03:44

</td>

<td class="gt_row gt_right">

1.390

</td>

</tr>

<tr>

<td class="gt_row gt_stub gt_left">

row\_4

</td>

<td class="gt_row gt_right gt_striped">

444.4000

</td>

<td class="gt_row gt_left gt_striped">

durian

</td>

<td class="gt_row gt_center gt_striped">

four

</td>

<td class="gt_row gt_left gt_striped">

2015-04-15

</td>

<td class="gt_row gt_left gt_striped">

16:50

</td>

<td class="gt_row gt_left gt_striped">

2018-04-04 15:55

</td>

<td class="gt_row gt_right gt_striped">

65100.000

</td>

</tr>

<tr class="gt_group_heading_row">

<td colspan="8" class="gt_group_heading">

grp\_b

</td>

</tr>

<tr>

<td class="gt_row gt_stub gt_left">

row\_5

</td>

<td class="gt_row gt_right">

5.55 × 10<sup class='gt_super'>3</sup>

</td>

<td class="gt_row gt_left">

NA

</td>

<td class="gt_row gt_center">

five

</td>

<td class="gt_row gt_left">

2015-05-15

</td>

<td class="gt_row gt_left">

17:55

</td>

<td class="gt_row gt_left">

2018-05-05 04:00

</td>

<td class="gt_row gt_right">

1325.810

</td>

</tr>

<tr>

<td class="gt_row gt_stub gt_left">

row\_6

</td>

<td class="gt_row gt_right gt_striped">

NA

</td>

<td class="gt_row gt_left gt_striped">

fig

</td>

<td class="gt_row gt_center gt_striped">

six

</td>

<td class="gt_row gt_left gt_striped">

2015-06-15

</td>

<td class="gt_row gt_left gt_striped">

NA

</td>

<td class="gt_row gt_left gt_striped">

2018-06-06 16:11

</td>

<td class="gt_row gt_right gt_striped">

13.255

</td>

</tr>

<tr>

<td class="gt_row gt_stub gt_left">

row\_7

</td>

<td class="gt_row gt_right">

7.77 × 10<sup class='gt_super'>5</sup>

</td>

<td class="gt_row gt_left">

grapefruit

</td>

<td class="gt_row gt_center">

seven

</td>

<td class="gt_row gt_left">

NA

</td>

<td class="gt_row gt_left">

19:10

</td>

<td class="gt_row gt_left">

2018-07-07 05:22

</td>

<td class="gt_row gt_right">

NA

</td>

</tr>

<tr>

<td class="gt_row gt_stub gt_left">

row\_8

</td>

<td class="gt_row gt_right gt_striped">

8.88 × 10<sup class='gt_super'>6</sup>

</td>

<td class="gt_row gt_left gt_striped">

honeydew

</td>

<td class="gt_row gt_center gt_striped">

eight

</td>

<td class="gt_row gt_left gt_striped">

2015-08-15

</td>

<td class="gt_row gt_left gt_striped">

20:20

</td>

<td class="gt_row gt_left gt_striped">

NA

</td>

<td class="gt_row gt_right gt_striped">

0.440

</td>

</tr>

</tbody>

</table>



</div>



<sup>Created on 2019-01-01 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by rich-iannone** [comment]
@krlmlr my apologies, the example provided was actually the workaround to the issue. The correct statements that result in an error are:

```r
exibble %>%
  gt(
    rowname_col = "row",
    groupname_col = "group"
  ) %>%
  fmt_scientific(
    columns = vars(num)
  )
```

...using the entire vector of values from `exibble$num` where there is an NA value (that `fmt_scientific()` didn't handle).

The related PR is now merged in, so this problem will no longer occur.
