### ISSUE TITLE
`tab_style()` fails to target all cell_summary rows with `row_group_order()`

### ISSUE THREAD

**Issue by adietster** [rstudio/gt#812]
Try using ``tab_style`` to ``cells_summary`` with ``row_group_order`` in my case will result in missing the style (or unformatted). It happens everytime. I am using latest version of gt from github.

``` r
library(dplyr)
library(tidyverse)
library(gt)
library(babynames)

numrows <- 6
numgroups <- 2

df <- tibble::tibble(
  name = sample(babynames$name, numrows), 
  value = runif(numrows, 50000, 2000000), 
  group = sample(letters[1:numgroups], numrows, replace = TRUE)
) 

gttbl <- df %>%
  group_by(group) %>%
  arrange(group) %>%
  gt(rowname_col = "name") %>%
  row_group_order(groups = c("b", "a")) %>%
  summary_rows(groups = TRUE, columns = c(value), fns = list("sum")) %>%
  tab_style(style = list(cell_text(style = "italic", weight="bold")),
            locations = cells_summary())
gttbl
```

<img width="224" alt="Screen Shot 2021-07-05 at 16 34 10" src="https://user-images.githubusercontent.com/2858597/124450681-ddca4200-ddae-11eb-8d5c-5c653969fdc9.png">

<img width="212" alt="Screen Shot 2021-07-05 at 16 32 49" src="https://user-images.githubusercontent.com/2858597/124450523-b7a4a200-ddae-11eb-92b4-71f4d1af883f.png">

<sup>Created on 2021-07-05 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

**Comment by rich-iannone** [comment]
Thank you for reporting this bug. It's high priority so will be the next thing that's worked on.
