### ISSUE TITLE
Missing values not supported in `summary_rows()`?

### ISSUE THREAD

**Issue by eutwt** [rstudio/gt#827]
It looks like a summary row value can't be missing, even though missing values are displayed correctly (without error or warning) as part of a normal column. Is this known/expected?

``` r
library(gt)

example <- gt(data.frame(a = c(1, NA, 3)))

summary_rows(example, columns = a, fns = list(~ sum(.)))
#> Error: Problem with `mutate()` column `a`.
#> ℹ `a = (function (x) ...`.
#> ℹ `a` must be size 1, not 0.
```

<sup>Created on 2021-08-19 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by rich-iannone** [comment]
This is definitely not something I'm happy with and I do think it's a bug. Workaround is to use `summary_rows(example, columns = a, fns = list(~ sum(., na.rm = TRUE)))` but it's not ideal. Thanks for reporting this.
