### ISSUE TITLE
Update help for fmt_number

### ISSUE THREAD

**Issue by nmarantz** [rstudio/gt#831]
The help file for `fmt_number` does not reflect the fact the upgrades in pull #718. The section on the **columns** argument should be updated.

**Comment by rich-iannone** [comment]
Thanks for reporting @nmarantz ! We indeed need to get the documentation updated here.

**Comment by rich-iannone** [comment]
The pkgdown documentation has now been updated. Closing.

**Comment by francisbarton** [comment]
I can't see anything in the current documentation [online](https://gt.rstudio.com/reference/fmt_number.html) or in my locally installed package help files (gt version 0.6.0) that reflects the ability to use `where(is.numeric)` for example within `fmt_number()`.
