### ISSUE TITLE
Mean Comparison Table

### ISSUE THREAD

**Issue by BB1464** [rstudio/gt#846]
Good afternoon all, Please find below an example of analysis in which I performed in R using for loop, but I want to ask how can I extract the means using any package to form a table so that someone else can follow my analysis. Thank you and best regard.

library(agricolae) # For mean comparison
library(tidyverse) 

####   Let me fit a model using a for loop  ###
for (i in 5) {
  print(paste('-----',names(npk[i]),'-----')) # To display group names
  model<-lm(npk[,i]~block+N*P*K,data=npk)
  print(anova(model))
  print=(HSD.test(model,'N',console=TRUE))
  print(HSD.test(model,'P',console=TRUE))
  print(HSD.test(model,'K',console = TRUE))
  print(result$groups)
}

**Comment by rich-iannone** [comment]
This is pretty general and probably has less to do with `gt` and more to do with generating a data frame. I'm going to close this now but let me know if you solve this and need to tabulate the results with `gt`!
