### ISSUE TITLE
"transparent" for color is no longer accepted

### ISSUE THREAD

**Issue by kylebutts** [rstudio/gt#856]
Hi -- I think an update removed the ability to use "transparent" as a color. Is this a bug or an intended change?

``` r
gt::gt(mtcars) |> 
    gt::tab_options(
        table.border.top.color = "transparent"
    )
#> Error: Problem with `mutate()` column `value`.
#> ℹ `value = { ... }`.
#> x An invalid color name was used (`"transparent"`):
#>  * Only R/X11 color names and CSS 3.0 color names can be used
```

<sup>Created on 2021-11-29 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by rich-iannone** [comment]
It was something that was considered but was put off til later because of `transparent` handling across output formats. However, I do think it should be implemented.
