### ISSUE TITLE
Question: How to adjust column widths/font size to see everything?

### ISSUE THREAD

**Issue by pabuta88** [rstudio/gt#861]
First of all, thank you very much for all your effort - I absolutely love the gt package!

I have a gt table that I want to look at either on my desktop browser or on my mobile phone. Unfortunately, some of the columns are cut when I open the page on my mobile phone. I tried different combinations in cols_width following your R script here https://github.com/rstudio/gt/blob/master/tests/gt-examples/01-html-script/html-17-table_width_specifications.R. However, I don't manage to create a table that allows me to see everything, independent on the size of the browser window. Is there any way I can implement this - maybe by automatically adjusting the font size in a way that contents fit in?

**Comment by rich-iannone** [comment]
@pabuta88 Could you share some screenshots and a bit more info on what could be made better? There are a variety of approaches that can be taken to improve tables on mobile (and still make them presentable for wider displays). However, not all of that is implemented at this time. But, I'd like to find specific areas where we could begin improving this.
