### ISSUE TITLE
How to set background colors for the cells of multiple columns based on string contents

### ISSUE THREAD

**Issue by ahbon123** [rstudio/gt#863]
Hello, say I have a small dataset as follows:

```
library(gt)
library(tidyverse)

id <- c(1,2,3,4,5)
res1 <- c("true", "true", "false", "true", "false")
res2 <- c("false", NA, NA, "true", "true")
df <- data.frame(id, res1, res2)

df %>% 
  gt()
```

For columns `res1 ` and `res2`, let's say if value content are `true`s, I'll need to highlight that cell with red background color, if `false`s, highlight with green color, for other cases, keep their colors as original.

Is it possible to achieve that using gt package?

**Comment by rich-iannone** [comment]
We need an easier way to set basic style attributes based on values. I think a new function for this should be the way to do it. The `sub_values()` function provides a nice (and forgiving) way to target values so I believe the new function ought to be modeled on that.

**Comment by ahbon123** [comment]
Thank you very much, I believe this function will have lots of application scenarios.

**Comment by jthomasmock** [comment]
Tagging on to this, there are a few requests I've seen on Twitter and `gtExtras` re: color the background of column 1 based on column 2. Right now, `data_color()` only operates on the current column, `text_transform()` only works on the current column (although this can be "abused"), and to properly color the background of a column you end up needing to use `tab_style()` multiple times.

I have a prototype that works like below:

```r
set.seed(37)
base_tab <- head(mtcars) |>
  dplyr::slice_sample(n = 6) |>
  dplyr::arrange(desc(mpg)) |>
  gt::gt()

base_tab |>
  gt_color_by_col(mpg, cyl, domain = range(gtExtras::gt_index(base_tab, mpg)))
```

![image](https://user-images.githubusercontent.com/29187501/200356656-b363a793-c869-47e3-912b-4c4a69ac8da1.png)

Essentially it loops through the column, values, and rows to apply a `tab_style()` with the minimal snippets of code below:

```r
fn_data_clr_by_col <- function(gt_object, col2, value, row_id, color_add){

  gt_object |>
    tab_style(
      style = list(
        cell_fill(color = color_add),
        cell_text(color = gt:::ideal_fgnd_color(color_add))
      ),
      locations = cells_body({{ col2 }}, rows = row_id)
    )

}
```

```r
for (i in 1:length(full_vals)){
    gt_object <- fn_data_clr_by_col(gt_object, {{ col2 }}, full_vals[i], i, color_add[i])
  }
  return(gt_object)
```

Full code:

<details><summary>Full Code</summary>

```r


fn_data_clr_by_col <- function(gt_object, col2, value, row_id, color_add){

  gt_object |>
    tab_style(
      style = list(
        cell_fill(color = color_add),
        cell_text(color = gt:::ideal_fgnd_color(color_add))
      ),
      locations = cells_body({{ col2 }}, rows = row_id)
    )

}

gt_color_by_col <- function(
    gt_object, col1, col2, ..., domain = NULL, direction = 1, type = "continuous",
    palette = c("#af8dc3", "#e7d4e8", "#f7f7f7", "#d9f0d3", "#7fbf7b")){

  stopifnot("Table must be of class 'gt_tbl'" = "gt_tbl" %in% class(gt_object))

  full_vals <- gtExtras::gt_index(gt_object = gt_object, {{ col1 }})

  rng_vals <- range(full_vals, na.rm = TRUE)

  if(is.null(domain)){

    domain <- rng_vals
    warning(
      "Domain not specified, defaulting to observed range within each specified column.",
      call. = FALSE
    )
  }

  color_add <- scales::col_numeric(
    palette = if(grepl(x = palette[1], pattern = "::")){
      paletteer::paletteer_d(
        palette = palette,
        direction = direction,
        type = pal_type
      ) %>% as.character()
    } else {
      if(direction == -1){
        rev(palette)
      } else {
        palette
      }
    },
    ...,
    domain = domain
  )(full_vals)

  for (i in 1:length(full_vals)){
    gt_object <- fn_data_clr_by_col(gt_object, {{ col2 }}, full_vals[i], i, color_add[i])
  }
  return(gt_object)
}

```

</details>

**Comment by rich-iannone** [comment]
@jthomasmock if it doesn't already exist could we transfer you comments/idea to a new issue? There's some great stuff there and it's such a common problem that I don't want to lose track of this.

**Comment by jthomasmock** [comment]
> If it doesn't already exist could you transfer your comments/ideas to a new issue? There's some great stuff there and it's such a common problem that I don't want to lose track of this.

Done! I've moved it to: https://github.com/rstudio/gt/issues/1119 with some of the public requests I've seen
