### ISSUE TITLE
An empty table (i.e., has >0 columns but 0 rows) should be valid input to `gt()`

### ISSUE THREAD

**Issue by rich-iannone** [rstudio/gt#87]
During internal testing, @tareefk found that if we use table data with 0 rows but some columns defined, we get an error (and it's not informative). Here's an example:

```r
sp500[0, ] %>% gt()
```
```
 Error in value[[jvseq[[jjj]]]] : subscript out of bounds 
```

This should be instead be considered valid input and yield a rendered table with no rows (perhaps showing text in the output that states there are no rows). Perhaps a console message (or warning) should be issued that states that the input table has no rows.

Further to this, a data frame or tibble that is 0 x 0 will cause an error when passed to `gt()`:

```r
dplyr::tibble() %>% gt()
```
```
Error in mutate_impl(.data, dots) : 
  Column `colnum_final` must be length 0 (the number of rows) or one, not 2 
```

This should either stop with an informative error message or render an empty view.

**Comment by shrektan** [comment]
Adding an _invisible_ row (all `''`) automatically if the table is empty may be a simple solution...  

This feature is very important to the shiny users because the data source is dynamic. At present, we have to handle it manually. Error-prone and tedious...
