### ISSUE TITLE
HTML table bug for `tab_spanner()` via `as_raw_html()`

### ISSUE THREAD

**Issue by Thyrisis** [rstudio/gt#878]
Hi,

I've found a minor but annoying bug in the way gt() will produce html output for email via as_raw_html() when using the tab_spanner() function. It's even more noticeable with opt_table_lines() in use.

It appears to be that the column spanning values produced by tab_spanner() are not lined in the same was as the cells of the table can be - hence why this is more visible when using opt_table_lines().

Default behaviour is demonstrated by this code:

```
exibble |>
	select(char, num, currency) |>
	gt() |>
		tab_spanner(label = "Numbers"
					, columns = c(num, currency))
```

![image](https://user-images.githubusercontent.com/8824008/152521927-b74b7fba-f1ab-4491-89bd-9910eec8ad2a.png)
You can see that the spanner value of "Numbers" is underlined and appears consistent with other lines.

When adding opt_table_lines() this also looks OK though there is a little clue that it's not the same as the other lines in the small gap at the start of the line:

```
exibble |>
	select(char, num, currency) |>
	gt() |>
		tab_spanner(label = "Numbers"
					, columns = c(num, currency)) |>
		opt_table_lines()
```

![image](https://user-images.githubusercontent.com/8824008/152522006-debba3ce-c665-4612-922b-6f60d2df2865.png)
However, it's when this is sent via email that the issue become really noticeable:

```
with_lines <- exibble |>
	select(char, num, currency) |>
	gt() |>
		tab_spanner(label = "Numbers"
					, columns = c(num, currency)) |>
		opt_table_lines() |>
		as_raw_html()

with_lines <- paste0("<html>", with_lines, "</html>")

send.mail(from = "example@from.com",
		  to = "example@to.com",
		  subject = "HTML line tab_spanner bug example",
		  body = with_lines,
		  html = TRUE,
		  smtp = list(host.name = "<my server>", port = 25),
		  send = TRUE)
```

![image](https://user-images.githubusercontent.com/8824008/152522135-9d5f3508-a9dd-4437-9086-ffd0f2ed341f.png)

As you can see, there is no line at all under the column spanner - I believe there should be one for the opt_table_lines() to work as expected.

These examples were produced using gt version 0.3.1 on R 4.1.2

**Comment by rich-iannone** [comment]
The `as_raw_html()` function has been improved to address this exact situation.
