### ISSUE TITLE
Build column labels and spanners from rows present in the data

### ISSUE THREAD

**Issue by turbanisch** [rstudio/gt#892]
Regression table output (e.g., from the `modelsummary` package) often contains rows that I would like to build column labels and spanners from. 

In this example, I would like to build a column spanner based on `dep_var` and column labels combining `sample` and the model number: 
```r
library(tidyverse)
library(gt)

df <- tibble::tribble(
         ~rownames, ~model_1,     ~model_2,      ~model_3,
         "dep_var",      "x",          "y",           "y",
          "sample",   "full", "low income", "high income",
        "estimate",  "0.614",      "0.409",       "0.231",
  "standard_error",  "0.149",      "0.318",       "0.181"
  )
```

The desired output can be achieved by manually assigning both column labels and spanners:
```r
df %>%
  gt() %>% 
  cols_label(rownames = "",
             model_1 = html("full<br>model_1"),
             model_2 = html("low income<br>model_2"),
             model_3 = html("high income<br>model_3")) %>% 
  tab_spanner(label = "x", columns = 2) %>% 
  tab_spanner(label = "y", columns = 3:4)
```
<img width="400" alt="image" src="https://user-images.githubusercontent.com/51969412/153769599-b7055387-98da-4596-8cc4-c30797ff6b45.png">

But of course it would be superb if this type of redundant work could be avoided. My best try given the current functionality involves splitting the table into two (one for model info, one for the actual table body) before converting it to a `GT` object and then passing the model info as a list to `cols_label()`. Note that in the example above I would still have to remove the now-redundant rows from the body, but there seems to be no equivalent to `cols_hide()` for rows.

My desired workflow in pseudo code looks like:
```r
df %>% 
  gt() %>% 
  col_labs_from_rows("{sample}<br>{rownames}") %>% 
  tab_spanner_from_row(rows = (rownames == "dep_var"))
```

The function `tab_spanner_delim()` that is already implemented goes into that direction but requires some pre-processing (appending the column names). Of course being able to just assign multiple rows as the column headers (as in LaTeX) would do the trick as well. But it seems that this would go against `GT`'s design philosophy?

**Comment by rich-iannone** [comment]
After some thought on this, I don't think we can reasonably support this feature. Mixing text with numbers in the columns means that numeric values cannot be formatted. That limitation alone would indicate that this approach is not a workable one.

**Comment by turbanisch** [comment]
Thanks for looking into it!
