### ISSUE TITLE
Option to add summary row labels into existing column when using row groups

### ISSUE THREAD

**Issue by jdbarillas** [rstudio/gt#913]
## Prework

- [x] Read and abide by **gt**'s [code of conduct](https://www.contributor-covenant.org/version/2/0/code_of_conduct/) and [contributing guidelines](https://github.com/rstudio/gt/blob/master/.github/CONTRIBUTING.md).
- [x] Search for duplicates among the [existing issues](https://github.com/rstudio/gt/issues) (both open and closed).

## Proposal

It would be helpful if we could dictate whether a new column is created when a summary row is added when there are row groups present, and to which column the label is added. 

For example, I'm trying to get to this: 
<img width="421" alt="image" src="https://user-images.githubusercontent.com/11413447/158444122-44116322-cf83-494a-883e-5586dcdb3ec8.png">

With gt, I'm currently here:
<img width="421" alt="image" src="https://user-images.githubusercontent.com/11413447/158444007-5823f268-abd6-48f7-a188-995cf99ce27c.png">

There's a lot of space being taken by the added column when there's space in the column adjacent for the label to go into.

**Comment by rich-iannone** [comment]
Sorry I missed this earlier. To get to your target appearance you need to put the ‘benefits’ column into the stub with `rowname_col` in `gt()`.
