### ISSUE TITLE
Add support for side-by-side regression tables?

### ISSUE THREAD

**Issue by andrewheiss** [rstudio/gt#92]
This is a phenomenal package and I'm a huge fan of the API for creating tables.

At least two other packages provide support for side-by-side regression tables ([**stargazer**](https://cran.r-project.org/web/packages/stargazer/index.html) and [**huxtable**](https://github.com/hughjonesd/huxtable)), but both have limitations: **stargazer** only supports HTML and TeX and doesn't play well with knitr, and **huxtable** supports HTML and TeX with minimal Word support, since it creates Markdown tables that don't support column spans or other fancier table features.

I wonder if it would be possible to provide support for regression tables similar to **stargazer** and **huxtable** tables, given that the format fits well in the gt API paradigm.

``` r
library(tidyverse)
library(gt)
library(huxtable)

model1 <- lm(mpg_c ~ hp, data = gtcars)
model2 <- lm(mpg_c ~ hp + trq, data = gtcars)
model3 <- lm(mpg_c ~ hp + trq + year, data = gtcars)

huxreg(model1, model2, model3)
```

```
─────────────────────────────────────────────────────────────
                    (1)            (2)             (3)       
              ───────────────────────────────────────────────
  (Intercept)     23.932 ***     22.422 ***   -1275.504      
                  (1.540)        (1.777)      (1174.083)     
  hp              -0.017 ***     -0.024 ***      -0.021 ***  
                  (0.003)        (0.005)         (0.006)     
  trq                             0.012           0.008      
                                 (0.007)         (0.008)     
  year                                            0.644      
                                                 (0.582)     
              ───────────────────────────────────────────────
  N               46             46              46          
  R2               0.431          0.463           0.479      
  logLik        -108.446       -107.086        -106.426      
  AIC            222.892        222.172         222.853      
─────────────────────────────────────────────────────────────
  *** p < 0.001; ** p < 0.01; * p < 0.05.                    

Column names: names, model1, model2, model3
```

Right now there's a way to fake it very uglyly by extracting coefficients and model details using functions from **broom** (which **huxtable** does behind the scenes too), but it'd be cool if there was a less clunky way to make side-by-side regression tables with **gt**:

```r
library(broom)
library(glue)

models_combined <- tibble(model = list(model1, model2, model3)) %>% 
  mutate(coefs = model %>% map(tidy),
         details = model %>% map(glance),
         model_number = 1:n())

model_coefs <- models_combined %>% 
  unnest(coefs) %>% 
  mutate(value = as.character(glue("{round(estimate, 2)} ({round(std.error, 2)})"))) %>% 
  select(model_number, term, value) %>% 
  spread(model_number, value)

model_details <- models_combined %>% 
  unnest(details) %>% 
  mutate(N = model %>% map_dbl(nobs),
         R2 = round(adj.r.squared, 2),
         AIC = round(AIC, 2)) %>% 
  select(model_number, N, R2, AIC) %>% 
  gather(term, value, -model_number) %>% 
  spread(model_number, value) %>% 
  mutate_at(vars(-term), as.character)

ugly_blank_row <- tibble(term = NA, `1` = NA, `2` = NA, `3` = NA)

bind_rows(model_coefs,ugly_blank_row,  model_details) %>% 
  gt() %>% 
  tab_header(title = "Side-by-side regression table")
```

<div id="gefoycaxtg">

<table class='gt_table'>

<thead>

<tr>

<th class="gt_heading gt_title gt_font_normal gt_center" colspan="4">

Side-by-side regression table

</th>

</tr>

<tr>

<th class="gt_heading gt_subtitle gt_font_normal gt_center gt_bottom_border" colspan="4">

</th>

</tr>

<tr>

<th class="gt_col_heading gt_left" rowspan="1" colspan="1">

term

</th>

<th class="gt_col_heading gt_left" rowspan="1" colspan="1">

1

</th>

<th class="gt_col_heading gt_left" rowspan="1" colspan="1">

2

</th>

<th class="gt_col_heading gt_left" rowspan="1" colspan="1">

3

</th>

</tr>

<tbody class="gt_table_body gt_striped">

<tr>

<td class="gt_row gt_left">

(Intercept)

</td>

<td class="gt_row gt_left">

23.93 (1.54)

</td>

<td class="gt_row gt_left">

22.42 (1.78)

</td>

<td class="gt_row gt_left">

\-1275.5 (1174.08)

</td>

</tr>

<tr>

<td class="gt_row gt_left">

hp

</td>

<td class="gt_row gt_left">

\-0.02 (0)

</td>

<td class="gt_row gt_left">

\-0.02 (0.01)

</td>

<td class="gt_row gt_left">

\-0.02 (0.01)

</td>

</tr>

<tr>

<td class="gt_row gt_left">

trq

</td>

<td class="gt_row gt_left">

NA

</td>

<td class="gt_row gt_left">

0.01 (0.01)

</td>

<td class="gt_row gt_left">

0.01 (0.01)

</td>

</tr>

<tr>

<td class="gt_row gt_left">

year

</td>

<td class="gt_row gt_left">

NA

</td>

<td class="gt_row gt_left">

NA

</td>

<td class="gt_row gt_left">

0.64 (0.58)

</td>

</tr>

<tr>

<td class="gt_row gt_left">

NA

</td>

<td class="gt_row gt_left">

NA

</td>

<td class="gt_row gt_left">

NA

</td>

<td class="gt_row gt_left">

NA

</td>

</tr>

<tr>

<td class="gt_row gt_left">

AIC

</td>

<td class="gt_row gt_left">

222.89

</td>

<td class="gt_row gt_left">

222.17

</td>

<td class="gt_row gt_left">

222.85

</td>

</tr>

<tr>

<td class="gt_row gt_left">

N

</td>

<td class="gt_row gt_left">

46

</td>

<td class="gt_row gt_left">

46

</td>

<td class="gt_row gt_left">

46

</td>

</tr>

<tr>

<td class="gt_row gt_left">

R2

</td>

<td class="gt_row gt_left">

0.42

</td>

<td class="gt_row gt_left">

0.44

</td>

<td class="gt_row gt_left">

0.44

</td>

</tr>

</tbody>

</table>

</div>

**Comment by rich-iannone** [comment]
Yeah! This has got to be possible presently. I'll experiment with this today. I'm also wondering whether it'd be a good idea to support a collection of standardized table types like this within **gt**.

**Comment by andrewheiss** [comment]
I experimented a little with it yesterday, but got stuck :). 

The tricky part about this is that regression models are all different and it's difficult to support every contingency. **stargazer** hard codes the logic for every possible model, but that takes time and it doesn't support things made by Stan, for instance. **huxtable** is amazing because it doesn't hard code anything and instead relies on **broom**. If `broom::tidy()` and `broom::glance()` can work with a model, `huxreg()` can show it (which also allows developers of modeling packages to create their own S3 `tidy.*` and `glance.*` methods to get support for `huxreg()`).

Because **huxtable** has robust support for selectively pulling model details out and displaying them in a table, I tried different ways of feeding its output to `gt()` so that `huxreg()` could keep doing all the heavy lifting and `gt()` could handle the display, but I couldn't find a good way to do it.

**Comment by JosiahParry** [comment]
@andrewheiss your work around is extremely helpful.

**Comment by andrewheiss** [comment]
Whoa, @vincentarelbundock has created a gt-based solution for this! https://github.com/vincentarelbundock/gtsummary

**Comment by vincentarelbundock** [comment]
@andrewheiss How did you find out about this?!?

Yeah, I just worked on it over the weekend. It's not quite feature-complete yet, but almost. And it works quite nicely on my machine.

I'd be really grateful if anyone could take a look and tell me how it works on their end. Any suggestion will be most welcome.

If there's interest, I plan to invest some actual effort into this thing. The way the table just pops-out nicely in RStudio's Viewer was a real eye opener for me :)

**Comment by andrewheiss** [comment]
Ha, the benefits of the GitHub activity stream thing. It said you'd made a new repo  :)

I'll check it out and throw some different models at it. 

Thanks for this!

**Comment by rich-iannone** [comment]
@vincentarelbundock Questions are definitely okay, no need to apologize for them! 

Right now, I don't have a solution for suppressing (or even transforming) the row group labels. Could you file an issue and provide a code example (with screenshot)? Then I could see what I could do about that.

**Comment by rich-iannone** [comment]
Going to close this since {modelsummary} and {gtsummary} both have this handled!
