### ISSUE TITLE
[accessibility] Assign `id`s to summary row heads (`<th>`) and apply as `headers` to `<td>`s

### ISSUE THREAD

**Issue by batpigandme** [rstudio/gt#926]
Expansion of https://github.com/rstudio/gt/issues/678 as it applies to, e.g. summary lines (as in the examples in the [creating-summary-lines vignette](https://gt.rstudio.com/articles/creating-summary-lines.html) where you're creating groupwise summary lines). 

These will constitute tables with multi-level headings, and need the `<th>`s with each scope (`col`, `row`, `colgroup`, `rowgroup`) to have `id`s that are applied to the individual `<td>` cells.

The examples in the [W3C WAI Tables with Multi-Level Headers](https://www.w3.org/WAI/tutorials/tables/multi-level/) (particularly Example 2) match nicely with the structure you have for the groupwise summary lines (see [full code for Complete “Table with three headers related to each data cell” Example](https://www.w3.org/WAI/tutorials/tables/examples/threeheaders/)). 

Wanted to file this now, since it might be useful for the `<th>` elements to get ids by default, so that they can be applied to individual cells for multi-level-header tables, and [tables with irregular headers](https://www.w3.org/WAI/tutorials/tables/irregular/).

**Edit** Sorry about filing as bug rather than enhancement! 😳  I can't change it after the fact.

**Comment by rich-iannone** [comment]
Thanks for filing the issue and providing lots of detail! This and the small collection of other accessibility issues will be worked on for the `v0.6.0` release.
