### ISSUE TITLE
Allow word wrap for columns with underscores

### ISSUE THREAD

**Issue by engineerchange** [rstudio/gt#939]
## Prework

- [x] Read and abide by **gt**'s [code of conduct](https://www.contributor-covenant.org/version/2/0/code_of_conduct/) and [contributing guidelines](https://github.com/rstudio/gt/blob/master/.github/CONTRIBUTING.md).
- [x] Search for duplicates among the [existing issues](https://github.com/rstudio/gt/issues) (both open and closed).

## Proposal

Allow word wrap to work similarly with columns that use underscores as it does with columns that use dashes. See how both work with columns of unreasonable long names:

Word wrap working with dash separated column name:
```
tribble(~"column-1-wishmaker-haymaker-windowwasher",
       ~'column-2-wishmaker-haymaker-windowwasher',
       ~'column-3-wishmaker-haymaker-windowwasher',
       ~'column-4-wishmaker-haymaker-windowwasher',
       ~'column-5-wishmaker-haymaker-windowwasher',
       ~'column-6-wishmaker-haymaker-windowwasher',
       ~'column-7-wishmaker-haymaker-windowwasher',
       ~'column-8-wishmaker-haymaker-windowwasher',
       ~'column-9-wishmaker-haymaker-windowwasher',
       ~'column-10-wishmaker-haymaker-windowwasher',
       ~'column-11-wishmaker-haymaker-windowwasher',
       ~'column-12-wishmaker-haymaker-windowwasher',
       1,2,3,4,5,6,7,8,9,10,11,12) %>%
  gt()
```
![image](https://user-images.githubusercontent.com/3580210/166565489-68e205e5-d587-42d8-8f15-555dcca1742d.png)

Word wrap not working with underscore separated column name:

```
tribble(~"column_1_wishmaker_haymaker_windowwasher",
        ~'column_2_wishmaker_haymaker_windowwasher',
        ~'column_3_wishmaker_haymaker_windowwasher',
        ~'column_4_wishmaker_haymaker_windowwasher',
        ~'column_5_wishmaker_haymaker_windowwasher',
        ~'column_6_wishmaker_haymaker_windowwasher',
        ~'column_7_wishmaker_haymaker_windowwasher',
        ~'column_8_wishmaker_haymaker_windowwasher',
        ~'column_9_wishmaker_haymaker_windowwasher',
        ~'column_10_wishmaker_haymaker_windowwasher',
        ~'column_11_wishmaker_haymaker_windowwasher',
        ~'column_12_wishmaker_haymaker_windowwasher',
        1,2,3,4,5,6,7,8,9,10,11,12) %>%
  gt()
```

![image](https://user-images.githubusercontent.com/3580210/166565566-29c79768-fc36-4e06-b244-e51f2cf2847a.png)

The only current quasi-workaround is using cols_width() to "trim" down a column name, which seems a bit "hacky" and doesn't exactly meet this need.

```
tribble(~"column_1_wishmaker_haymaker_windowwasher",
        ~'column_2_wishmaker_haymaker_windowwasher',
        ~'column_3_wishmaker_haymaker_windowwasher',
        ~'column_4_wishmaker_haymaker_windowwasher',
        ~'column_5_wishmaker_haymaker_windowwasher',
        ~'column_6_wishmaker_haymaker_windowwasher',
        ~'column_7_wishmaker_haymaker_windowwasher',
        ~'column_8_wishmaker_haymaker_windowwasher',
        ~'column_9_wishmaker_haymaker_windowwasher',
        ~'column_10_wishmaker_haymaker_windowwasher',
        ~'column_11_wishmaker_haymaker_windowwasher',
        ~'column_12_wishmaker_haymaker_windowwasher',
        1,2,3,4,5,6,7,8,9,10,11,12) %>%
  gt() %>% cols_width(everything()~px(150))
```
![image](https://user-images.githubusercontent.com/3580210/166565884-de068acc-6a73-4e07-abc4-ee5cb6ba6f9b.png)

**Comment by rich-iannone** [comment]
I don’t think this is possible because these are browser rules that aren’t easy to circumvent. One workaround is to insert a space after every `-` using `cols_label_with()` and `gsub()`.
