### ISSUE TITLE
Multiple column input to aggregate functions in summary rows

### ISSUE THREAD

**Issue by alofting** [rstudio/gt#952]
Aggregation functions only allows input from the column for which the summary value is for. Typical use case shown below where a volume weighted close price uses both close and volume as inputs to the aggregation function. 

``` r
 suppressPackageStartupMessages(library(dplyr))
 library(gt)

 sp500 %>%
 slice_head(n = 22) %>%
 select(date, close, volume) %>%
 gt() %>%
 summary_rows('close', groups = NULL, fns = list('Average close' = ~ mean(.))) %>%
 summary_rows('close', groups = NULL, fns = list('Average volume weighted close' = ~ sum(. * volume) / sum(volume)))
#> Error in `summarise()`:
#> ! Problem while computing `close = (function (x) ...`.
#> ℹ The error occurred in group 1: ::group_id:: = "::GRAND_SUMMARY".
#> Caused by error in `fn()`:
#> ! object 'volume' not found
```
<sup>Created on 2022-05-26 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

[Another example at stackoverflow with ratios](https://stackoverflow.com/questions/62541285/r-gt-summary-rows-ratio-total-row)

I have cloned the project and changed 'dt_summary.r' to allow access to all columns to get the desired ouput as shown below. I have some missgivings about doing summaries inside gt and then extracting them. I would have prefered to separate data, including summaries, and format completely. Anyways, I can make a pull request for the summary change if desired.

``` r
 suppressPackageStartupMessages(library(dplyr))
 library(gt_aggr)

 sp500 %>%
 slice_head(n = 22) %>%
 select(date, close, volume) %>%
 gt() %>%
 summary_rows('close', groups = NULL, fns = list('Average close' = ~ mean(.))) %>%
 summary_rows('close', groups = NULL, fns = list('Average volume weighted close' = ~ sum(. * volume) / sum(volume)))
```
<sup>Created on 2022-05-26 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

<!DOCTYPE html>
<html>
<body>
<div id="zkjmqivhos" style="overflow-x:auto;overflow-y:auto;width:auto;height:auto;">
<table class="gt_table">
  
  <thead class="gt_col_headings">
    <tr>
      <th class="gt_col_heading gt_columns_bottom_border gt_left" rowspan="1" colspan="1"></th>
      <th class="gt_col_heading gt_columns_bottom_border gt_left" rowspan="1" colspan="1">date</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_right" rowspan="1" colspan="1">close</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_right" rowspan="1" colspan="1">volume</th>
    </tr>
  </thead>
  <tbody class="gt_table_body">
    <tr><td class="gt_row gt_right gt_stub"></td>
<td class="gt_row gt_left">2015-12-31</td>
<td class="gt_row gt_right">2043.94</td>
<td class="gt_row gt_right">2655330000</td></tr>
    <tr><td class="gt_row gt_right gt_stub"></td>
<td class="gt_row gt_left">2015-12-30</td>
<td class="gt_row gt_right">2063.36</td>
<td class="gt_row gt_right">2367430000</td></tr>
    <tr><td class="gt_row gt_right gt_stub"></td>
<td class="gt_row gt_left">2015-12-29</td>
<td class="gt_row gt_right">2078.36</td>
<td class="gt_row gt_right">2542000000</td></tr>
    <tr><td class="gt_row gt_right gt_stub"></td>
<td class="gt_row gt_left">2015-12-28</td>
<td class="gt_row gt_right">2056.50</td>
<td class="gt_row gt_right">2492510000</td></tr>
    <tr><td class="gt_row gt_right gt_stub"></td>
<td class="gt_row gt_left">2015-12-24</td>
<td class="gt_row gt_right">2060.99</td>
<td class="gt_row gt_right">1411860000</td></tr>
    <tr><td class="gt_row gt_right gt_stub"></td>
<td class="gt_row gt_left">2015-12-23</td>
<td class="gt_row gt_right">2064.29</td>
<td class="gt_row gt_right">3484090000</td></tr>
    <tr><td class="gt_row gt_right gt_stub"></td>
<td class="gt_row gt_left">2015-12-22</td>
<td class="gt_row gt_right">2038.97</td>
<td class="gt_row gt_right">3520860000</td></tr>
    <tr><td class="gt_row gt_right gt_stub"></td>
<td class="gt_row gt_left">2015-12-21</td>
<td class="gt_row gt_right">2021.15</td>
<td class="gt_row gt_right">3760280000</td></tr>
    <tr><td class="gt_row gt_right gt_stub"></td>
<td class="gt_row gt_left">2015-12-18</td>
<td class="gt_row gt_right">2005.55</td>
<td class="gt_row gt_right">6683070000</td></tr>
    <tr><td class="gt_row gt_right gt_stub"></td>
<td class="gt_row gt_left">2015-12-17</td>
<td class="gt_row gt_right">2041.89</td>
<td class="gt_row gt_right">4327390000</td></tr>
    <tr><td class="gt_row gt_right gt_stub"></td>
<td class="gt_row gt_left">2015-12-16</td>
<td class="gt_row gt_right">2073.07</td>
<td class="gt_row gt_right">4635450000</td></tr>
    <tr><td class="gt_row gt_right gt_stub"></td>
<td class="gt_row gt_left">2015-12-15</td>
<td class="gt_row gt_right">2043.41</td>
<td class="gt_row gt_right">4353540000</td></tr>
    <tr><td class="gt_row gt_right gt_stub"></td>
<td class="gt_row gt_left">2015-12-14</td>
<td class="gt_row gt_right">2021.94</td>
<td class="gt_row gt_right">4612440000</td></tr>
    <tr><td class="gt_row gt_right gt_stub"></td>
<td class="gt_row gt_left">2015-12-11</td>
<td class="gt_row gt_right">2012.37</td>
<td class="gt_row gt_right">4301060000</td></tr>
    <tr><td class="gt_row gt_right gt_stub"></td>
<td class="gt_row gt_left">2015-12-10</td>
<td class="gt_row gt_right">2052.23</td>
<td class="gt_row gt_right">3715150000</td></tr>
    <tr><td class="gt_row gt_right gt_stub"></td>
<td class="gt_row gt_left">2015-12-09</td>
<td class="gt_row gt_right">2047.62</td>
<td class="gt_row gt_right">4385250000</td></tr>
    <tr><td class="gt_row gt_right gt_stub"></td>
<td class="gt_row gt_left">2015-12-08</td>
<td class="gt_row gt_right">2063.59</td>
<td class="gt_row gt_right">4173570000</td></tr>
    <tr><td class="gt_row gt_right gt_stub"></td>
<td class="gt_row gt_left">2015-12-07</td>
<td class="gt_row gt_right">2077.07</td>
<td class="gt_row gt_right">4043820000</td></tr>
    <tr><td class="gt_row gt_right gt_stub"></td>
<td class="gt_row gt_left">2015-12-04</td>
<td class="gt_row gt_right">2091.69</td>
<td class="gt_row gt_right">4214910000</td></tr>
    <tr><td class="gt_row gt_right gt_stub"></td>
<td class="gt_row gt_left">2015-12-03</td>
<td class="gt_row gt_right">2049.62</td>
<td class="gt_row gt_right">4306490000</td></tr>
    <tr><td class="gt_row gt_right gt_stub"></td>
<td class="gt_row gt_left">2015-12-02</td>
<td class="gt_row gt_right">2079.51</td>
<td class="gt_row gt_right">3950640000</td></tr>
    <tr><td class="gt_row gt_right gt_stub"></td>
<td class="gt_row gt_left">2015-12-01</td>
<td class="gt_row gt_right">2102.63</td>
<td class="gt_row gt_right">3712120000</td></tr>
    <tr><td class="gt_row gt_right gt_stub gt_grand_summary_row gt_first_grand_summary_row">Average close</td>
<td class="gt_row gt_left gt_grand_summary_row gt_first_grand_summary_row">&mdash;</td>
<td class="gt_row gt_right gt_grand_summary_row gt_first_grand_summary_row">2,054.08</td>
<td class="gt_row gt_right gt_grand_summary_row gt_first_grand_summary_row">&mdash;</td></tr>
    <tr><td class="gt_row gt_right gt_stub gt_grand_summary_row gt_last_summary_row">Average volume weighted close</td>
<td class="gt_row gt_left gt_grand_summary_row gt_last_summary_row">&mdash;</td>
<td class="gt_row gt_right gt_grand_summary_row gt_last_summary_row">2,051.51</td>
<td class="gt_row gt_right gt_grand_summary_row gt_last_summary_row">&mdash;</td></tr>
  </tbody>
  
  
</table>
</div>

</body>
</html>

**Comment by rich-iannone** [comment]
Thank you for this very detailed issue and it would be really great to solve this generally. Would you mind sharing your modified code?

**Comment by alofting** [comment]
Hi, I have shared my changes in a pull request. I am a bit of a noob with git - please have patience with me.
