### ISSUE TITLE
Support for PDF output

### ISSUE THREAD

**Issue by kvittingseerup** [rstudio/gt#96]
I would like to requires the option of outputting tables in PDF format. That would be really useful for anything that needs to be put into print (where vector graphics is needed)

**Comment by rich-iannone** [comment]
Excellent idea! Will try to get this going in the coming weeks. I'm also thinking that there should be a broad range of output graphic formats (both raster and vector-based).

**Comment by baptiste** [comment]
FWIW gridExtra has a `grid.table()` function, which can be displayed using standard graphics devices. It's quite limited in terms of formatting; the only benefit that I can see would be in mixing content on a graphic, e.g. a table as an inset in a plot, etc. 
I haven't looked at the code for `gt` but in theory it would be possible to translate its table description into several sub-tables, each rendered as an individual tableGrob, and combine them together.

https://cran.r-project.org/web/packages/gridExtra/vignettes/tableGrob.html
