### ISSUE TITLE
gt_plot_bullet with different colors

### ISSUE THREAD

**Issue by IvoVillanueva** [rstudio/gt#989]
Hello
I would for example in the image below, I would like to be able to change the colors of the bars according to the color of the team
thank you very mucho

**Comment by IvoVillanueva** [comment]
![gtquintetos](https://user-images.githubusercontent.com/56939175/179392259-aec0304f-2567-4acc-a07e-1381f90fdd97.png)

**Comment by rich-iannone** [comment]
This is a feature request for {gtExtras} really. Could you file this issue at https://github.com/jthomasmock/gtExtras/issues please? Closing this here.
