### ISSUE TITLE
Using stub data for conditional styling

### ISSUE THREAD

**Issue by steveputman** [rstudio/gt#99]
Is it possible to use the stub data in tab_style? For example, I'm using a "year" column (renamed to rowname for purposes of gt) and want to bold all rows where the year is 201x, but it looks like that column gets thrown out of the available data in the course of building the pretty table.

```
tab %>%
  rename(rowname = year) %>%
  gt() %>%
    tab_style(
      style = cells_styles(
        text_weight = "bold"),
      locations = cells_data(
        rows = ???? == 2019)
    )
```

**Comment by rich-iannone** [comment]
Right now, it's not possible unfortunately. I'd like to change this so that stub data is accessible for conditional formatting like this.

A small but not insignificant challenge is what to call the stub column (`0`, `stub`, `rowname`?).

**Comment by steveputman** [comment]
Thanks--for now, faking it by duplicating the stub column before piping into `gt()`, conditioning the formatting on the duplicated column, and then hiding that column (though it obviously leaves the actual stub itself unformatted). 

(And for what it's worth, when I was in the crossing-my-fingers phase before I read the code,, I tried `rowname` and `stub` but not `0`!)

Very exciting package -- thanks.

**Comment by rich-iannone** [comment]
In an upcoming PR, this will work:

```r
exibble %>%
  gt(rowname_col = "row") %>%
  fmt_number(columns = vars(num), rows = row %in% c("row_1", "row_2"))
```

<img width="1019" alt="issue_99" src="https://user-images.githubusercontent.com/5612024/64876609-76f9f880-d61d-11e9-808d-e729a7957bed.png">
